--- Test run on 2016/04/12 08:45:13 ---
Converting "/home/travis/build/lrascao/mnesia2/." to "/home/travis/build/lrascao/mnesia2" and re-inserting with add_patha/1


Common Test v1.11 starting (cwd is /home/travis/build/lrascao/mnesia2)


Common Test: Running make in test directories...
Recompile: mnesia2_extra_light_SUITE
Recompile: ts_install_cth
ts_install_cth.erl:247: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
Recompile: mt
Recompile: mnesia2_trans_access_test
Recompile: mnesia2_tpcb
Recompile: mnesia2_test_lib
Recompile: mnesia2_schema_recovery_test
mnesia2_schema_recovery_test.erl:261: Warning: variable 'Bad' is unused
Recompile: mnesia2_registry_test
Recompile: mnesia2_recovery_test
mnesia2_recovery_test.erl:1571: Warning: variable 'Config' is unused
Recompile: mnesia2_qlc_test
Recompile: mnesia2_nice_coverage_test
Recompile: mnesia2_meter
Recompile: mnesia2_measure_test
Recompile: mnesia2_majority_test
Recompile: mnesia2_isolation_test
Recompile: mnesia2_install_test
Recompile: mnesia2_inconsistent_database_test
Recompile: mnesia2_frag_test
Recompile: mnesia2_frag_hash_test
Recompile: mnesia2_examples_test
Recompile: mnesia2_evil_coverage_test
Recompile: mnesia2_evil_backup
Recompile: mnesia2_durability_test
Recompile: mnesia2_dirty_access_test
Recompile: mnesia2_dbn_meters
Recompile: mnesia2_cost
Recompile: mnesia2_consistency_test
Recompile: mnesia2_config_test
Recompile: mnesia2_config_event
Recompile: mnesia2_config_backup
Recompile: mnesia2_atomicity_test

CWD set to: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14.2016-04-12_08.45.13"

TEST INFO: 1 test(s), 52 case(s) in 1 suite(s)

Cover compiling 'mnesia2' (32 files) - this may take some time... done

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: Starting test, 52 test cases

----------------------------------------------------
2016-04-12 08:45:35.779
starting test group: extra_light


----------------------------------------------------
2016-04-12 08:45:35.805
starting test group: install


----------------------------------------------------
2016-04-12 08:45:35.884
starting test case: silly_durability

08:45:35.977 [info] Application lager started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:35.977 [info] Application poolgirl started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:36.001 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.495.0>
08:45:36.004 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:36.014 [info] Application mnesia2 exited with reason: stopped
08:45:36.035 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.563.0>
08:45:36.038 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'

----------------------------------------------------
2016-04-12 08:45:36.046
ending test case: silly_durability


----------------------------------------------------
2016-04-12 08:45:36.071
starting test case: silly_move

08:45:36.469 [error] CRASH REPORT Process <0.554.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:36.608 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.673.0>
08:45:36.827 [info] Application lager started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:36.828 [info] Application poolgirl started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:36.879 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.100.0>
08:45:37.371 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec

----------------------------------------------------
2016-04-12 08:45:37.521
ending test case: silly_move


----------------------------------------------------
2016-04-12 08:45:37.548
starting test case: silly_upgrade

08:45:37.549 [error] gen_server <0.156.0> terminated with reason: killed
08:45:37.550 [error] gen_server <0.730.0> terminated with reason: killed
08:45:37.550 [error] CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:45:37.550 [error] CRASH REPORT Process <0.730.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:45:37.550 [error] CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:37.550 [info] Application mnesia2 exited with reason: killed
08:45:37.550 [error] CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:37.551 [info] Application mnesia2 exited with reason: killed
08:45:37.598 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.800.0>
08:45:37.627 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.216.0>
08:45:37.631 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:37.904 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:38.091 [info] Application mnesia2 exited with reason: stopped
08:45:38.100 [error] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'...

08:45:38.100 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.798.0> exit with reason killed in context child_terminated
08:45:38.100 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.798.0> exit with reason reached_max_restart_intensity in context shutdown
08:45:38.102 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.795.0> exit with reason shutdown in context child_terminated
08:45:38.103 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.795.0> exit with reason reached_max_restart_intensity in context shutdown
08:45:38.103 [info] Application mnesia2 exited with reason: shutdown
08:45:38.142 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.929.0>
08:45:38.144 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:38.150 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.370.0>
08:45:38.155 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:38.190 [info] Application mnesia2 exited with reason: stopped
08:45:38.192 [info] Application mnesia2 exited with reason: stopped
08:45:38.243 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1029.0>
08:45:38.254 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.461.0>

----------------------------------------------------
2016-04-12 08:45:38.771
ending test case: silly_upgrade


----------------------------------------------------
2016-04-12 08:45:38.850
ending test group: install


----------------------------------------------------
2016-04-12 08:45:38.876
starting test group: nice


----------------------------------------------------
2016-04-12 08:45:38.955
starting test case: nice

08:45:39.004 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
08:45:39.005 [warning] lager_error_logger_h dropped 21 messages in the last second that exceeded the limit of 50 messages/sec
08:45:39.026 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1152.0>
08:45:39.028 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.550.0>
08:45:39.037 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:39.331 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:39.448 [info] Application mnesia2 exited with reason: stopped
08:45:39.461 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1265.0>

----------------------------------------------------
2016-04-12 08:45:39.660
ending test case: nice


----------------------------------------------------
2016-04-12 08:45:39.754
ending test group: nice


----------------------------------------------------
2016-04-12 08:45:39.780
starting test group: qlc


----------------------------------------------------
2016-04-12 08:45:39.882
starting test case: dirty_nice_ram_copies

08:45:39.885 [error] CRASH REPORT Process <0.541.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:39.885 [info] Application mnesia2 exited with reason: killed
08:45:39.941 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1497.0>
08:45:39.944 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.765.0>
08:45:40.245 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
08:45:40.246 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'

----------------------------------------------------
2016-04-12 08:45:40.344
ending test case: dirty_nice_ram_copies


----------------------------------------------------
2016-04-12 08:45:40.371
starting test case: dirty_nice_disc_copies

08:45:40.373 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
08:45:40.374 [error] CRASH REPORT Process <0.1488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:40.374 [info] Application mnesia2 exited with reason: killed
08:45:40.373 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.779.0> exit with reason killed in context child_terminated
08:45:40.373 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.779.0> exit with reason reached_max_restart_intensity in context shutdown
08:45:40.374 [error] gen_server mnesia2_monitor terminated with reason: killed
08:45:40.374 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:45:40.374 [error] gen_server mnesia2_recover terminated with reason: killed
08:45:40.374 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:45:40.374 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.760.0> exit with reason killed in context child_terminated
08:45:40.374 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.760.0> exit with reason reached_max_restart_intensity in context shutdown
08:45:40.374 [error] gen_server mnesia2_subscr terminated with reason: {aborted,{node_not_running,'d1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'}} in mnesia2:abort/1 line 313
08:45:40.374 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: {aborted,{node_not_running,'d1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'}} in gen_server:terminate/7 line 814
08:45:40.375 [info] Application mnesia2 exited with reason: shutdown
08:45:40.456 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1612.0>
08:45:40.462 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.865.0>

----------------------------------------------------
2016-04-12 08:45:40.534
ending test case: dirty_nice_disc_copies


----------------------------------------------------
2016-04-12 08:45:40.560
starting test case: dirty_nice_disc_only_copies

08:45:40.637 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1728.0>
08:45:40.643 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.966.0>

----------------------------------------------------
2016-04-12 08:45:40.754
ending test case: dirty_nice_disc_only_copies


----------------------------------------------------
2016-04-12 08:45:40.833
starting test case: trans_nice_ram_copies

08:45:41.114 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
08:45:41.114 [warning] lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
08:45:41.153 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1854.0>
08:45:41.156 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1072.0>
08:45:41.158 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:41.458 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'

----------------------------------------------------
2016-04-12 08:45:41.558
ending test case: trans_nice_ram_copies


----------------------------------------------------
2016-04-12 08:45:41.601
starting test case: trans_nice_disc_copies

08:45:41.604 [error] CRASH REPORT Process <0.1845.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:41.604 [info] Application mnesia2 exited with reason: killed
08:45:41.604 [error] gen_server <0.1127.0> terminated with reason: killed
08:45:41.604 [error] CRASH REPORT Process <0.1127.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:45:41.604 [error] CRASH REPORT Process <0.1063.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:41.604 [info] Application mnesia2 exited with reason: killed
08:45:41.655 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1986.0>
08:45:41.672 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1172.0>

----------------------------------------------------
2016-04-12 08:45:41.783
ending test case: trans_nice_disc_copies


----------------------------------------------------
2016-04-12 08:45:41.817
starting test case: trans_nice_disc_only_copies

08:45:41.885 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2119.0>
08:45:41.889 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1273.0>

----------------------------------------------------
2016-04-12 08:45:42.407
ending test case: trans_nice_disc_only_copies


----------------------------------------------------
2016-04-12 08:45:42.463
starting test case: atomic_eval

08:45:42.465 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
08:45:42.466 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
08:45:42.465 [error] gen_server <0.2175.0> terminated with reason: killed
08:45:42.466 [error] gen_server <0.1327.0> terminated with reason: killed
08:45:42.465 [error] CRASH REPORT Process <0.2175.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:45:42.466 [error] CRASH REPORT Process <0.1327.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:45:42.466 [error] CRASH REPORT Process <0.2110.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:42.466 [info] Application mnesia2 exited with reason: killed
08:45:42.466 [error] CRASH REPORT Process <0.1264.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:42.467 [info] Application mnesia2 exited with reason: killed
08:45:42.524 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2259.0>
08:45:42.527 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:42.544 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1379.0>
08:45:42.547 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'

----------------------------------------------------
2016-04-12 08:45:43.259
ending test case: atomic_eval


----------------------------------------------------
2016-04-12 08:45:43.336
starting test case: frag

08:45:43.339 [error] gen_server <0.2315.0> terminated with reason: killed
08:45:43.338 [error] gen_server <0.1433.0> terminated with reason: killed
08:45:43.339 [error] CRASH REPORT Process <0.2315.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:45:43.338 [error] CRASH REPORT Process <0.1433.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:45:43.340 [error] CRASH REPORT Process <0.2250.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:43.340 [info] Application mnesia2 exited with reason: killed
08:45:43.338 [error] CRASH REPORT Process <0.1370.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:43.338 [info] Application mnesia2 exited with reason: killed
08:45:43.399 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2390.0>
08:45:43.403 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1466.0>
08:45:43.406 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:43.705 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'

----------------------------------------------------
2016-04-12 08:45:43.815
ending test case: frag


----------------------------------------------------
2016-04-12 08:45:43.841
starting test case: info

08:45:43.842 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1461.0> exit with reason killed in context child_terminated
08:45:43.844 [error] CRASH REPORT Process <0.2381.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:43.844 [info] Application mnesia2 exited with reason: killed
08:45:43.843 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1461.0> exit with reason reached_max_restart_intensity in context shutdown
08:45:43.843 [error] Mnesia2('d1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.1463.0>,killed}

08:45:43.843 [error] gen_server mnesia2_monitor terminated with reason: killed
08:45:43.907 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2524.0>
08:45:43.941 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1580.0>

----------------------------------------------------
2016-04-12 08:45:44.052
ending test case: info


----------------------------------------------------
2016-04-12 08:45:44.078
starting test case: mnesia2_down

08:45:44.080 [warning] lager_error_logger_h dropped 11 messages in the last second that exceeded the limit of 50 messages/sec
08:45:44.081 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
08:45:44.081 [error] gen_server <0.2580.0> terminated with reason: killed
08:45:44.080 [error] gen_server <0.1633.0> terminated with reason: killed
08:45:44.081 [error] CRASH REPORT Process <0.2580.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:45:44.080 [error] CRASH REPORT Process <0.1633.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:45:44.081 [error] CRASH REPORT Process <0.2515.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:44.081 [info] Application mnesia2 exited with reason: killed
08:45:44.081 [error] CRASH REPORT Process <0.1570.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:44.081 [info] Application mnesia2 exited with reason: killed
08:45:44.149 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2647.0>
08:45:44.151 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:44.154 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1666.0>
08:45:44.157 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
---> Participant transactions <--- 
---> Coordinator transactions <---
Tid: 10 (owned by <0.2724.0>) 
08:45:44.228 [error] gen_server <0.1718.0> terminated with reason: killed
08:45:44.228 [error] CRASH REPORT Process <0.1718.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826

----------------------------------------------------
2016-04-12 08:45:44.280
ending test case: mnesia2_down


----------------------------------------------------
2016-04-12 08:45:44.359
ending test group: qlc


----------------------------------------------------
2016-04-12 08:45:44.384
starting test group: registry


----------------------------------------------------
2016-04-12 08:45:44.462
starting test case: good_dump

08:45:44.464 [error] CRASH REPORT Process <0.2638.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:44.464 [info] Application mnesia2 exited with reason: killed
08:45:44.509 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2775.0>

----------------------------------------------------
2016-04-12 08:45:44.540
ending test case: good_dump


----------------------------------------------------
2016-04-12 08:45:44.566
starting test case: bad_dump

08:45:44.606 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2869.0>

----------------------------------------------------
2016-04-12 08:45:44.615
ending test case: bad_dump


----------------------------------------------------
2016-04-12 08:45:44.696
ending test group: registry


----------------------------------------------------
2016-04-12 08:45:44.722
starting test group: config


----------------------------------------------------
2016-04-12 08:45:44.801
starting test case: access_module

08:45:45.842 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2979.0>
08:45:45.845 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:47.038 [error] CRASH REPORT Process <0.2970.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:47.038 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:45:48.062
ending test case: access_module


----------------------------------------------------
2016-04-12 08:45:48.107
starting test case: auto_repair

08:45:49.150 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3085.0>
08:45:49.152 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:49.153 [info] Application mnesia2 exited with reason: stopped
08:45:49.155 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3133.0>
08:45:49.159 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3181.0>

----------------------------------------------------
2016-04-12 08:45:50.175
ending test case: auto_repair


----------------------------------------------------
2016-04-12 08:45:50.201
starting test case: backup_module

08:45:51.246 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3253.0>
08:45:51.248 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:51.263 [error] CRASH REPORT Process <0.3244.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:45:51.263 [info] Application mnesia2 exited with reason: killed
08:45:53.304 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3336.0>
08:45:53.307 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:45:53.316 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

08:45:53.317 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14.2016-04-12_08.45.13/Mnesia2.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14/LATEST.LOG"] -> badarg

08:45:53.318 [error] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

08:45:53.318 [error] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

08:45:53.318 [error] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

08:45:53.318 [error] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

08:45:53.318 [error] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

08:45:53.318 [error] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

08:45:53.318 [error] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

08:45:53.318 [error] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}}} ({error,{already_started,<0.3412.0>}})


----------------------------------------------------
2016-04-12 08:45:54.341
ending test case: backup_module


----------------------------------------------------
2016-04-12 08:45:54.366
starting test case: debug

08:45:55.395 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
08:45:55.396 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_monitor starting: <0.3459.0>

08:45:55.396 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Mnesia2 debug level set to verbose
08:45:55.398 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3463.0>
08:45:55.402 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_subscr starting: <0.3460.0>

08:45:55.402 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_locker starting: <0.3461.0>

08:45:55.402 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_recover starting: <0.3462.0>

08:45:55.402 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm starting: <0.3463.0>

08:45:55.402 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Schema initiated from: default

08:45:55.403 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_controller starting: <0.3466.0>

08:45:55.403 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_late_loader starting: <0.3467.0>

08:45:55.403 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Intend to load tables: []

08:45:55.403 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_1 starting: <0.3469.0>

08:45:55.403 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_2 starting: <0.3470.0>

08:45:55.404 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_3 starting: <0.3471.0>

08:45:55.404 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_4 starting: <0.3472.0>

08:45:55.404 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_5 starting: <0.3473.0>

08:45:55.405 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_6 starting: <0.3474.0>

08:45:55.405 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_7 starting: <0.3475.0>

08:45:55.405 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm_8 starting: <0.3476.0>

08:45:57.424 [warning] lager_error_logger_h dropped 49 messages in the last second that exceeded the limit of 50 messages/sec
08:45:57.424 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_monitor starting: <0.3540.0>

08:45:57.424 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Version: "1.0.0"

08:45:57.424 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env access_module: mnesia2

08:45:57.424 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env auto_repair: true

08:45:57.425 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env backup_module: mnesia2_backup

08:45:57.425 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env debug: debug

08:45:57.425 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14.2016-04-12_08.45.13/Mnesia2.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14"

08:45:57.427 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3544.0>
08:45:59.452 [warning] lager_error_logger_h dropped 30 messages in the last second that exceeded the limit of 50 messages/sec
08:45:59.452 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_monitor starting: <0.3621.0>

08:45:59.452 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Version: "1.0.0"

08:45:59.453 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env access_module: mnesia2

08:45:59.453 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env auto_repair: true

08:45:59.453 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env backup_module: mnesia2_backup

08:45:59.454 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env debug: trace

08:45:59.454 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3625.0>
08:45:59.455 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14.2016-04-12_08.45.13/Mnesia2.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14"

08:45:59.455 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_disc_copies_at_startup: true

08:45:59.456 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_log_load_regulation: false

08:45:59.456 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_log_time_threshold: 180000

08:46:01.481 [warning] lager_error_logger_h dropped 27 messages in the last second that exceeded the limit of 50 messages/sec
08:46:01.481 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_monitor starting: <0.3701.0>

08:46:01.481 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Version: "1.0.0"

08:46:01.481 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env access_module: mnesia2

08:46:01.482 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env auto_repair: true

08:46:01.482 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env backup_module: mnesia2_backup

08:46:01.482 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env debug: debug

08:46:01.482 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14.2016-04-12_08.45.13/Mnesia2.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14"

08:46:01.482 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_disc_copies_at_startup: true

08:46:01.482 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_log_load_regulation: false

08:46:01.482 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_log_time_threshold: 180000

08:46:01.482 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_log_update_in_place: true

08:46:01.483 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dump_log_write_threshold: 1000

08:46:01.483 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env event_module: mnesia2_event

08:46:01.483 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env extra_db_nodes: []

08:46:01.483 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env ignore_fallback_at_startup: false

08:46:01.483 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env fallback_error_function: {mnesia2,lkill}

08:46:01.483 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env max_wait_for_decision: infinity

08:46:01.483 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env schema_location: opt_disc

08:46:01.483 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env core_dir: false

08:46:01.484 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env pid_sort_order: false

08:46:01.484 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env no_table_loaders: 2

08:46:01.484 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env dc_dump_limit: 4

08:46:01.484 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env send_compressed: 0

08:46:01.485 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env send_max_packets: 20

08:46:01.485 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env send_max_transfer_size: 7500

08:46:01.485 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env async_dirty_buffer_size: 524288

08:46:01.486 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env async_dirty_max_buffer_file_size: 100000000

08:46:01.486 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env async_dirty_tx_backlog_threshold: 200000

08:46:01.486 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env async_dirty_buffer_min_runtime: 10000

08:46:01.486 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Env async_dirty_buffer_drained_cutoff: 5

08:46:01.486 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Mnesia2 debug level set to debug
08:46:01.487 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_subscr starting: <0.3702.0>

08:46:01.487 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_locker starting: <0.3703.0>

08:46:01.487 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_recover starting: <0.3704.0>

08:46:01.487 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_tm starting: <0.3705.0>

08:46:01.488 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Schema initiated from: default

08:46:01.488 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3705.0>
08:46:01.488 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
08:46:01.489 [info] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): mnesia2_controller starting: <0.3708.0>

08:46:03.513 [warning] lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
08:46:03.514 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3761.0>
08:46:03.517 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'

----------------------------------------------------
2016-04-12 08:46:05.522
ending test case: debug


----------------------------------------------------
2016-04-12 08:46:05.547
starting test case: dir

08:46:03.517 [error] CRASH REPORT Process <0.3752.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:46:03.517 [info] Application mnesia2 exited with reason: killed
08:46:06.577 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3825.0>
08:46:06.580 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:46:06.580 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3820.0> exit with reason killed in context child_terminated
08:46:06.581 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3820.0> exit with reason reached_max_restart_intensity in context shutdown
08:46:06.581 [error] gen_server mnesia2_monitor terminated with reason: killed
08:46:06.581 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:46:06.581 [error] CRASH REPORT Process <0.3816.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:46:06.581 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:46:07.615
ending test case: dir


----------------------------------------------------
2016-04-12 08:46:07.655
starting test case: dump_log_load_regulation

08:46:07.685 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3896.0>
08:46:07.687 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:46:07.692 [info] Application mnesia2 exited with reason: stopped
08:46:07.700 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3957.0>
08:46:14.620 [warning] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

08:46:22.780 [error] CRASH REPORT Process <0.3948.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:46:22.780 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:46:23.802
ending test case: dump_log_load_regulation


----------------------------------------------------
2016-04-12 08:46:23.866
starting test case: dump_log_time_threshold

08:46:24.911 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4487.0>
08:46:24.914 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:46:30.924 [error] CRASH REPORT Process <0.4478.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:46:30.924 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:46:31.960
ending test case: dump_log_time_threshold


----------------------------------------------------
2016-04-12 08:46:31.986
starting test case: dump_log_write_threshold

08:46:33.053 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4587.0>
08:46:33.056 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:46:34.085 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:46:35.098
ending test case: dump_log_write_threshold


----------------------------------------------------
2016-04-12 08:46:35.162
starting test case: dump_log_update_in_place

08:46:36.278 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4703.0>
08:46:36.280 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:46:36.292 [error] CRASH REPORT Process <0.4694.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:46:36.292 [info] Application mnesia2 exited with reason: killed
08:46:38.352 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4770.0>
08:46:38.355 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:46:38.383 [error] CRASH REPORT Process <0.4761.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:46:38.383 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:46:39.406
ending test case: dump_log_update_in_place


----------------------------------------------------
2016-04-12 08:46:39.434
starting test case: event_module

08:46:40.524 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4862.0>
08:46:40.527 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:46:40.532 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1793.0>
08:46:40.541 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'}}
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'}}
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'}}
08:46:41.543 [error] gen_server <0.1845.0> terminated with reason: killed
08:46:41.543 [error] CRASH REPORT Process <0.1845.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:46:41.544 [error] CRASH REPORT Process <0.1784.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:46:41.544 [info] Application mnesia2 exited with reason: killed
08:46:44.215 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1861.0>
08:46:44.220 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'}}
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'}}
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'}}
08:46:45.224 [error] gen_server <0.4925.0> terminated with reason: killed
08:46:45.224 [error] CRASH REPORT Process <0.4925.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:46:45.224 [error] CRASH REPORT Process <0.4853.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:46:45.225 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:46:46.257
ending test case: event_module


----------------------------------------------------
2016-04-12 08:46:46.286
starting test case: inconsistent_database

08:46:46.289 [error] CRASH REPORT Process <0.1852.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:46:46.289 [info] Application mnesia2 exited with reason: killed
08:46:47.528 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4968.0>
08:46:47.531 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1942.0>
08:46:47.542 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:46:47.835 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:46:47.836 [error] CRASH REPORT Process <0.4959.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:46:47.837 [info] Application mnesia2 exited with reason: killed
08:46:47.838 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1957.0> exit with reason killed in context child_terminated
08:46:47.838 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1957.0> exit with reason reached_max_restart_intensity in context shutdown
08:46:47.839 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.1959.0> exit with reason killed in context shutdown_error
08:46:47.840 [error] gen_server <0.1997.0> terminated with reason: killed
08:46:47.840 [error] CRASH REPORT Process <0.1997.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:46:47.840 [error] CRASH REPORT Process <0.1933.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:46:47.841 [info] Application mnesia2 exited with reason: killed
08:46:47.888 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5044.0>
08:46:52.069 [info] Application mnesia2 exited with reason: stopped
08:46:52.158 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2019.0>
08:46:52.160 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:46:52.167 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5168.0>
08:46:52.171 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:07.312 [info] Application mnesia2 exited with reason: stopped
08:47:07.332 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:47:08.355
ending test case: inconsistent_database


----------------------------------------------------
2016-04-12 08:47:08.385
starting test case: max_wait_for_decision


----------------------------------------------------
2016-04-12 08:47:08.387
ending test case: max_wait_for_decision


----------------------------------------------------
2016-04-12 08:47:08.416
starting test case: send_compressed

08:47:08.482 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5299.0>
08:47:08.486 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:08.490 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2141.0>
08:47:08.495 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:08.553 [error] gen_server <0.2195.0> terminated with reason: killed
08:47:08.553 [error] CRASH REPORT Process <0.2195.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:08.554 [error] CRASH REPORT Process <0.2132.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:08.554 [info] Application mnesia2 exited with reason: killed
08:47:08.575 [error] CRASH REPORT Process <0.5290.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:08.575 [info] Application mnesia2 exited with reason: killed
08:47:08.609 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5387.0>
08:47:10.050 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2229.0>
08:47:10.060 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:10.613 [warning] lager_error_logger_h dropped 27 messages in the last second that exceeded the limit of 50 messages/sec
08:47:10.613 [error] gen_server <0.5458.0> terminated with reason: killed
08:47:10.613 [error] CRASH REPORT Process <0.5458.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:10.615 [error] CRASH REPORT Process <0.5378.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:10.615 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:47:11.636
ending test case: send_compressed


----------------------------------------------------
2016-04-12 08:47:11.663
starting test case: app_test


----------------------------------------------------
2016-04-12 08:47:11.685
ending test case: app_test


----------------------------------------------------
2016-04-12 08:47:11.743
starting test case: start_one_disc_full_then_one_disc_less

08:47:11.747 [error] CRASH REPORT Process <0.2220.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:11.748 [info] Application mnesia2 exited with reason: killed
08:47:16.424 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5510.0>
08:47:16.426 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:16.515 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2332.0>
08:47:16.534 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:16.565 [error] CRASH REPORT Process <0.2323.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:16.566 [error] gen_server <0.5574.0> terminated with reason: killed
08:47:16.565 [info] Application mnesia2 exited with reason: killed
08:47:16.566 [error] CRASH REPORT Process <0.5574.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:16.567 [error] CRASH REPORT Process <0.5501.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:16.567 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:47:17.589
ending test case: start_one_disc_full_then_one_disc_less


----------------------------------------------------
2016-04-12 08:47:17.632
starting test case: start_first_one_disc_less_then_one_disc_full

08:47:18.698 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5621.0>
08:47:18.702 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:18.708 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2407.0>
08:47:18.716 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:18.720 [error] gen_server <0.2418.0> terminated with reason: killed
08:47:18.720 [error] gen_server <0.5685.0> terminated with reason: killed
08:47:18.720 [error] CRASH REPORT Process <0.2418.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:18.720 [error] CRASH REPORT Process <0.5685.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:18.720 [error] CRASH REPORT Process <0.2398.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:18.720 [info] Application mnesia2 exited with reason: killed
08:47:18.722 [error] CRASH REPORT Process <0.5612.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:18.722 [info] Application mnesia2 exited with reason: killed
08:47:20.747 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2466.0>
08:47:20.749 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:20.787 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5701.0>
08:47:20.798 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:20.833 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.5718.0> exit with reason killed in context child_terminated
08:47:20.833 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.5718.0> exit with reason reached_max_restart_intensity in context shutdown
08:47:20.836 [error] gen_server <0.5743.0> terminated with reason: killed
08:47:20.836 [error] CRASH REPORT Process <0.5743.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:20.837 [error] CRASH REPORT Process <0.5692.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:20.837 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:47:21.859
ending test case: start_first_one_disc_less_then_one_disc_full


----------------------------------------------------
2016-04-12 08:47:21.904
starting test case: start_first_one_disc_less_then_two_more_disc_less

08:47:22.307 [error] CRASH REPORT Process <0.2457.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:22.307 [info] Application mnesia2 exited with reason: killed
08:47:23.392 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5826.0>
08:47:23.395 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:23.400 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2553.0>
08:47:23.406 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:23.707 [info] Application lager started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:23.708 [info] Application poolgirl started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:23.743 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.100.0>
08:47:23.767 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:23.830 [error] gen_server <0.5871.0> terminated with reason: killed
08:47:23.832 [error] gen_server <0.2604.0> terminated with reason: killed
08:47:23.830 [error] CRASH REPORT Process <0.5871.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:23.832 [error] CRASH REPORT Process <0.2604.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:23.832 [error] gen_server <0.2565.0> terminated with reason: killed
08:47:23.830 [error] gen_server <0.5880.0> terminated with reason: killed
08:47:23.832 [error] CRASH REPORT Process <0.2565.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:23.831 [error] CRASH REPORT Process <0.5880.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:23.833 [error] CRASH REPORT Process <0.2544.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:23.833 [info] Application mnesia2 exited with reason: killed
08:47:23.831 [error] CRASH REPORT Process <0.5817.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:23.831 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:47:24.865
ending test case: start_first_one_disc_less_then_two_more_disc_less


----------------------------------------------------
2016-04-12 08:47:24.897
starting test case: schema_location_and_extra_db_nodes_combinations

08:47:25.976 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5921.0>
08:47:25.979 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:25.986 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2634.0>
08:47:25.994 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:26.015 [error] gen_server mnesia2_monitor terminated with reason: killed
08:47:26.011 [error] gen_server <0.2645.0> terminated with reason: killed
08:47:26.015 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:26.011 [error] CRASH REPORT Process <0.2645.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:26.015 [error] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.5918.0>,killed}

08:47:26.012 [error] CRASH REPORT Process <0.2625.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:26.015 [error] CRASH REPORT Process mnesia2_event with 0 neighbours exited with reason: killed in gen_event:terminate_server/4 line 315
08:47:26.012 [info] Application mnesia2 exited with reason: killed
08:47:26.017 [error] CRASH REPORT Process <0.5912.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:26.018 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:47:27.036
ending test case: schema_location_and_extra_db_nodes_combinations


----------------------------------------------------
2016-04-12 08:47:27.067
starting test case: table_load_to_disc_less_nodes

08:47:28.116 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6015.0>
08:47:28.119 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:28.136 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2704.0>
08:47:28.142 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:28.152 [error] CRASH REPORT Process <0.6006.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:28.153 [info] Application mnesia2 exited with reason: killed
08:47:28.152 [error] CRASH REPORT Process <0.2695.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:28.153 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:47:29.179
ending test case: table_load_to_disc_less_nodes


----------------------------------------------------
2016-04-12 08:47:29.209
starting test case: schema_merge

08:47:30.297 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6101.0>
08:47:30.300 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:30.324 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2780.0>
08:47:30.332 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:30.355 [error] CRASH REPORT Process <0.2770.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:30.355 [info] Application mnesia2 exited with reason: killed
08:47:31.396 [error] CRASH REPORT Process <0.6092.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:31.396 [info] Application mnesia2 exited with reason: killed
08:47:33.441 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2849.0>
08:47:33.443 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:38.467 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6179.0>
08:47:38.478 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:38.493 [error] gen_server <0.2916.0> terminated with reason: killed
08:47:38.504 [error] gen_server <0.6218.0> terminated with reason: killed
08:47:38.494 [error] CRASH REPORT Process <0.2916.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:38.504 [error] CRASH REPORT Process <0.6218.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:38.494 [error] CRASH REPORT Process <0.2840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:38.494 [info] Application mnesia2 exited with reason: killed
08:47:38.506 [error] CRASH REPORT Process <0.6170.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:38.506 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:47:39.529
ending test case: schema_merge


----------------------------------------------------
2016-04-12 08:47:39.586
starting test case: dynamic_basic

08:47:39.658 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
08:47:39.702 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6289.0>
08:47:39.705 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:39.712 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2948.0>
08:47:39.726 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:39.773 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.190.0>
08:47:39.779 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:39.846 [error] gen_server <0.3011.0> terminated with reason: killed
08:47:39.846 [error] CRASH REPORT Process <0.3011.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:39.846 [error] gen_server <0.2987.0> terminated with reason: killed
08:47:39.846 [error] CRASH REPORT Process <0.2987.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:39.847 [error] CRASH REPORT Process <0.2939.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:39.847 [info] Application mnesia2 exited with reason: killed
08:47:39.877 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3039.0>
08:47:39.927 [error] gen_server <0.6353.0> terminated with reason: killed
08:47:39.927 [error] CRASH REPORT Process <0.6353.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:39.928 [error] gen_server <0.6392.0> terminated with reason: killed
08:47:39.928 [error] CRASH REPORT Process <0.6392.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:39.929 [error] CRASH REPORT Process <0.6280.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:39.929 [info] Application mnesia2 exited with reason: killed
08:47:39.950 [error] CRASH REPORT Process <0.181.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:39.950 [info] Application mnesia2 exited with reason: killed
08:47:40.021 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3134.0>
08:47:40.025 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:40.059 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6411.0>
08:47:40.064 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.294.0>
08:47:40.088 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:40.366 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:40.891 [error] gen_server <0.368.0> terminated with reason: killed
08:47:40.891 [error] CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:40.891 [error] gen_server <0.356.0> terminated with reason: killed
08:47:40.892 [error] CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:40.894 [error] CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:40.894 [info] Application mnesia2 exited with reason: killed
08:47:40.925 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.392.0>
08:47:43.036 [error] gen_server <0.6512.0> terminated with reason: killed
08:47:43.037 [error] CRASH REPORT Process <0.6512.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:43.037 [error] gen_server <0.6481.0> terminated with reason: killed
08:47:43.037 [error] CRASH REPORT Process <0.6481.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:43.057 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3149.0> exit with reason killed in context child_terminated
08:47:43.037 [error] CRASH REPORT Process <0.6402.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:43.037 [info] Application mnesia2 exited with reason: killed
08:47:43.057 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3149.0> exit with reason reached_max_restart_intensity in context shutdown
08:47:43.058 [error] gen_server <0.3226.0> terminated with reason: killed
08:47:43.058 [error] CRASH REPORT Process <0.3226.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:43.085 [info] Application mnesia2 exited with reason: stopped
08:47:43.058 [error] CRASH REPORT Process <0.3125.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:43.058 [info] Application mnesia2 exited with reason: killed
08:47:43.136 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.498.0>
08:47:43.137 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:43.170 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6529.0>
08:47:43.172 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3247.0>
08:47:43.201 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:43.479 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:44.007 [error] gen_server <0.571.0> terminated with reason: killed
08:47:44.007 [error] CRASH REPORT Process <0.571.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:44.008 [error] gen_server <0.565.0> terminated with reason: killed
08:47:44.008 [error] CRASH REPORT Process <0.565.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:44.008 [error] CRASH REPORT Process <0.489.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:44.009 [info] Application mnesia2 exited with reason: killed
08:47:44.040 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.596.0>
08:47:44.042 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:44.160 [error] gen_server <0.6617.0> terminated with reason: killed
08:47:44.160 [error] CRASH REPORT Process <0.6617.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:44.164 [error] CRASH REPORT Process <0.6520.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:44.164 [info] Application mnesia2 exited with reason: killed
08:47:44.180 [error] gen_server <0.3335.0> terminated with reason: killed
08:47:44.208 [info] Application mnesia2 exited with reason: stopped
08:47:44.180 [error] CRASH REPORT Process <0.3335.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:44.181 [error] CRASH REPORT Process <0.3238.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:44.181 [info] Application mnesia2 exited with reason: killed
08:47:44.232 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.697.0>
08:47:44.313 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6641.0>
08:47:44.318 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3356.0>
08:47:44.337 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:44.623 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:45.164 [error] CRASH REPORT Process <0.3347.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:45.164 [info] Application mnesia2 exited with reason: killed
08:47:45.210 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3452.0>
08:47:45.228 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:45.248 [error] gen_server <0.3478.0> terminated with reason: killed
08:47:45.248 [error] CRASH REPORT Process <0.3478.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:45.248 [error] gen_server <0.3465.0> terminated with reason: killed
08:47:45.248 [error] CRASH REPORT Process <0.3465.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:45.249 [error] gen_server <0.3508.0> terminated with reason: killed
08:47:45.249 [error] CRASH REPORT Process <0.3508.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:45.249 [error] CRASH REPORT Process <0.3443.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:45.249 [info] Application mnesia2 exited with reason: killed
08:47:46.276 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3530.0>
08:47:46.309 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'

----------------------------------------------------
2016-04-12 08:47:46.339
ending test case: dynamic_basic


----------------------------------------------------
2016-04-12 08:47:46.370
starting test case: dynamic_ext

08:47:46.377 [error] gen_server <0.3543.0> terminated with reason: killed
08:47:46.376 [error] gen_server <0.6754.0> terminated with reason: killed
08:47:46.379 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.712.0> exit with reason killed in context child_terminated
08:47:46.376 [error] CRASH REPORT Process <0.6754.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:46.377 [error] CRASH REPORT Process <0.3543.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:46.380 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.712.0> exit with reason reached_max_restart_intensity in context shutdown
08:47:46.377 [error] CRASH REPORT Process <0.6632.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:46.377 [info] Application mnesia2 exited with reason: killed
08:47:46.379 [error] CRASH REPORT Process <0.3521.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:46.379 [info] Application mnesia2 exited with reason: killed
08:47:46.380 [error] gen_server <0.820.0> terminated with reason: killed
08:47:46.380 [error] CRASH REPORT Process <0.820.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:46.380 [error] gen_server <0.812.0> terminated with reason: killed
08:47:46.468 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6787.0>
08:47:46.472 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3608.0>
08:47:46.380 [error] CRASH REPORT Process <0.812.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:46.380 [error] gen_server <0.771.0> terminated with reason: killed
08:47:46.380 [error] CRASH REPORT Process <0.771.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:46.381 [error] CRASH REPORT Process <0.688.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:46.381 [info] Application mnesia2 exited with reason: killed
08:47:46.777 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:46.893 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3704.0>
08:47:46.993 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3794.0>
08:47:47.017 [warning] lager_error_logger_h dropped 24 messages in the last second that exceeded the limit of 50 messages/sec
08:47:47.017 [error] gen_server <0.3856.0> terminated with reason: killed
08:47:47.017 [error] CRASH REPORT Process <0.3856.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:47.018 [error] CRASH REPORT Process <0.3785.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:47.018 [info] Application mnesia2 exited with reason: killed
08:47:47.060 [info] Application mnesia2 exited with reason: stopped
08:47:47.074 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3894.0>
08:47:47.076 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:47.622 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6901.0>
08:47:47.661 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:47.707 [info] Application mnesia2 exited with reason: stopped
08:47:47.708 [error] gen_server <0.3949.0> terminated with reason: killed
08:47:47.708 [error] CRASH REPORT Process <0.3949.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:48.039 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6984.0>
08:47:48.043 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:48.554 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.3976.0>
08:47:48.587 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'

----------------------------------------------------
2016-04-12 08:47:48.602
ending test case: dynamic_ext


----------------------------------------------------
2016-04-12 08:47:48.648
starting test case: dynamic_bad

08:47:48.653 [error] gen_server <0.4024.0> terminated with reason: killed
08:47:48.652 [error] gen_server <0.7048.0> terminated with reason: killed
08:47:48.652 [error] CRASH REPORT Process <0.7048.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:48.653 [error] CRASH REPORT Process <0.4024.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:48.655 [error] CRASH REPORT Process <0.6975.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:48.655 [info] Application mnesia2 exited with reason: killed
08:47:48.654 [error] CRASH REPORT Process <0.3967.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:48.654 [info] Application mnesia2 exited with reason: killed
08:47:48.736 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7085.0>
08:47:48.743 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4068.0>
08:47:48.744 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.848.0>
08:47:48.763 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:49.045 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:50.303 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
08:47:50.302 [error] gen_server <0.7149.0> terminated with reason: killed
08:47:50.300 [error] gen_server <0.903.0> terminated with reason: killed
08:47:50.303 [error] gen_server <0.4131.0> terminated with reason: killed
08:47:50.302 [error] CRASH REPORT Process <0.7149.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:50.300 [error] CRASH REPORT Process <0.903.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:50.301 [error] CRASH REPORT Process <0.839.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:50.301 [info] Application mnesia2 exited with reason: killed
08:47:50.331 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.951.0>
08:47:50.333 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:50.302 [error] CRASH REPORT Process <0.7076.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:50.302 [info] Application mnesia2 exited with reason: killed
08:47:50.304 [error] CRASH REPORT Process <0.4131.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:50.304 [error] CRASH REPORT Process <0.4059.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:50.304 [info] Application mnesia2 exited with reason: killed
08:47:50.329 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4161.0>
08:47:50.330 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:50.390 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7197.0>
08:47:50.415 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:47:50.427 [error] gen_server <0.1000.0> terminated with reason: killed
08:47:50.427 [error] CRASH REPORT Process <0.1000.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:50.428 [error] gen_server <0.4216.0> terminated with reason: killed
08:47:50.427 [error] gen_server <0.1009.0> terminated with reason: killed
08:47:50.440 [error] gen_server <0.7264.0> terminated with reason: killed
08:47:50.428 [error] CRASH REPORT Process <0.4216.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:50.427 [error] CRASH REPORT Process <0.1009.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:50.440 [error] CRASH REPORT Process <0.7264.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:50.467 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4239.0>
08:47:50.428 [error] gen_server <0.995.0> terminated with reason: killed
08:47:50.440 [error] gen_server <0.7259.0> terminated with reason: killed
08:47:50.428 [error] CRASH REPORT Process <0.995.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:50.429 [error] CRASH REPORT Process <0.942.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:50.441 [error] CRASH REPORT Process <0.7259.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:47:50.429 [info] Application mnesia2 exited with reason: killed
08:47:50.468 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1028.0>
08:47:50.441 [error] CRASH REPORT Process <0.7188.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:47:50.442 [info] Application mnesia2 exited with reason: killed
08:47:50.528 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7289.0>
08:47:50.537 [error] Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** ERROR ** (core dumped to file: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14.2016-04-12_08.45.13/Mnesia2Core.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14_1460_450870_536736")
 ** FATAL ** Failed to merge schema: Bad cookie in table definition tab1: 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14' = {cstruct,tab1,set,['d1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14','d1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'],['test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'],[],0,read_write,false,[],[],false,tab1,[key,val],[],[],[],{{1460450870282104696,-576460752303402878,1},'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'},{{2,0},[]}}, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14' = {cstruct,tab1,set,['d1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'],[],[],0,read_write,false,[],[],false,tab1,[key,val],[],[],[],{{1460450870476728941,-576460752303421247,1},'d1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'},{{2,0},[]}}



----------------------------------------------------
2016-04-12 08:48:00.540
ending test case: dynamic_bad

08:48:00.538 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
08:48:00.538 [error] gen_server mnesia2_monitor terminated with reason: killed
08:48:00.538 [error] gen_server mnesia2_recover terminated with reason: killed
08:48:00.538 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:48:00.538 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
08:48:00.538 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:48:00.538 [error] gen_server mnesia2_subscr terminated with reason: killed
08:48:00.538 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:48:00.538 [error] CRASH REPORT Process <0.7280.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
08:48:00.539 [info] Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
08:48:00.539 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826

----------------------------------------------------
2016-04-12 08:48:00.661
starting test case: unknown_config

08:48:00.664 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
08:48:00.664 [error] gen_server <0.1077.0> terminated with reason: killed
08:48:00.664 [error] gen_server <0.4283.0> terminated with reason: killed
08:48:00.664 [error] CRASH REPORT Process <0.1077.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:48:00.664 [error] CRASH REPORT Process <0.4283.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:48:00.665 [error] CRASH REPORT Process <0.4230.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:48:00.665 [info] Application mnesia2 exited with reason: killed
08:48:00.664 [error] gen_server <0.1072.0> terminated with reason: killed
08:48:00.665 [error] CRASH REPORT Process <0.1072.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
08:48:00.665 [error] CRASH REPORT Process <0.1019.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
08:48:00.665 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-12 08:48:02.733
ending test case: unknown_config


----------------------------------------------------
2016-04-12 08:48:02.859
ending test group: config


----------------------------------------------------
2016-04-12 08:48:02.888
starting test group: examples


----------------------------------------------------
2016-04-12 08:48:03.004
starting test case: bup


----------------------------------------------------
2016-04-12 08:48:03.050
ending test case: bup


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error detected: error
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: *** FAILED test case 41 of 52 ***

----------------------------------------------------
2016-04-12 08:48:03.085
starting test case: company


----------------------------------------------------
2016-04-12 08:48:03.087
ending test case: company


----------------------------------------------------
2016-04-12 08:48:03.119
starting test case: meter

08:48:03.195 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7398.0>
08:48:03.198 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:08.969 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:48:08.975
ending test case: meter


----------------------------------------------------
2016-04-12 08:48:09.033
starting test case: replica_test

08:48:09.127 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7534.0>
08:48:09.128 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4330.0>
08:48:09.131 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1124.0>
08:48:09.166 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:09.190 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:09.435 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:15.866 [info] Application mnesia2 exited with reason: stopped
08:48:15.864 [info] Application mnesia2 exited with reason: stopped
08:48:15.898 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:48:15.898
ending test case: replica_test


----------------------------------------------------
2016-04-12 08:48:15.928
starting test case: sticky_replica_test

08:48:16.021 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7664.0>
08:48:16.025 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:16.031 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1239.0>
08:48:16.044 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4446.0>
08:48:16.067 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:16.348 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:22.488 [info] Application mnesia2 exited with reason: stopped
08:48:22.490 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:48:22.505
ending test case: sticky_replica_test

08:48:22.505 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:48:22.535
starting test case: dist_test

08:48:22.656 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7793.0>
08:48:22.659 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:22.675 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4562.0>
08:48:22.683 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.1354.0>
08:48:22.693 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:22.707 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:47.145 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:48:47.171
ending test case: dist_test

08:48:47.171 [info] Application mnesia2 exited with reason: stopped
08:48:47.166 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:48:47.230
starting test case: conflict_test

08:48:47.722 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.8932.0>
08:48:47.726 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:47.738 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2477.0>
08:48:47.755 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:47.761 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5688.0>
08:48:47.766 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:54.154 [info] Application mnesia2 exited with reason: stopped
08:48:54.168 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:48:54.172
ending test case: conflict_test

08:48:54.172 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:48:54.214
starting test case: frag_test

08:48:54.305 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.9071.0>
08:48:54.308 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:54.318 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5810.0>
08:48:54.322 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.2601.0>
08:48:54.348 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:48:54.624 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:49:01.188 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:49:01.198
ending test case: frag_test

08:49:01.197 [info] Application mnesia2 exited with reason: stopped
08:49:01.198 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:49:01.233
starting test case: frag2_test

08:49:01.333 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.10551.0>
08:49:01.336 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.7282.0>
08:49:01.368 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.4071.0>
08:49:01.388 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:49:01.643 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:49:01.673 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:49:08.012 [info] Application mnesia2 exited with reason: stopped
08:49:08.014 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:49:08.030
ending test case: frag2_test

08:49:08.029 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:49:08.084
starting test case: remote_test

08:49:08.182 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.10856.0>
08:49:08.201 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.5905.0>
08:49:08.205 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.8279.0>
08:49:08.219 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:49:08.502 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:49:08.509 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:49:14.679 [info] Application mnesia2 exited with reason: stopped
08:49:14.684 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:49:14.688
ending test case: remote_test

08:49:14.688 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:49:14.743
starting test case: remote_frag2_test

08:49:14.840 [info] starting mnesia2_tm, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.8394.0>
08:49:14.842 [info] Application mnesia2 started on node 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:49:14.846 [info] starting mnesia2_tm, 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.10986.0>
08:49:14.852 [info] Application mnesia2 started on node 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:49:14.868 [info] starting mnesia2_tm, 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14', <0.6703.0>
08:49:14.875 [info] Application mnesia2 started on node 'd1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'
08:49:21.159 [info] Application mnesia2 exited with reason: stopped
08:49:21.166 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:49:21.169
ending test case: remote_frag2_test

08:49:21.168 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-12 08:49:21.324
ending test group: examples


----------------------------------------------------
2016-04-12 08:49:21.353
ending test group: extra_light


----------------------------------------------------
2016-04-12 08:49:21.382
starting test case: clean_up_suite


----------------------------------------------------
2016-04-12 08:49:21.403
ending test case: clean_up_suite

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: TEST COMPLETE, 51 ok, 1 failed of 52 test cases

Cover analysing... done

Updating /home/travis/build/lrascao/mnesia2/logs/index.html... done
Updating /home/travis/build/lrascao/mnesia2/logs/all_runs.html... done

