--- Test run on 2016/04/10 22:49:06 ---
Converting "/home/travis/build/lrascao/mnesia2/." to "/home/travis/build/lrascao/mnesia2" and re-inserting with add_patha/1


Common Test v1.8.1 starting (cwd is /home/travis/build/lrascao/mnesia2)


Common Test: Running make in test directories...
Recompile: mnesia2_extra_light_SUITE
Recompile: ts_install_cth
Recompile: mt
Recompile: mnesia2_trans_access_test
Recompile: mnesia2_tpcb
Recompile: mnesia2_test_lib
Recompile: mnesia2_schema_recovery_test
mnesia2_schema_recovery_test.erl:261: Warning: variable 'Bad' is unused
Recompile: mnesia2_registry_test
Recompile: mnesia2_recovery_test
mnesia2_recovery_test.erl:1571: Warning: variable 'Config' is unused
Recompile: mnesia2_qlc_test
Recompile: mnesia2_nice_coverage_test
Recompile: mnesia2_meter
Recompile: mnesia2_measure_test
Recompile: mnesia2_majority_test
Recompile: mnesia2_isolation_test
Recompile: mnesia2_install_test
Recompile: mnesia2_inconsistent_database_test
Recompile: mnesia2_frag_test
Recompile: mnesia2_frag_hash_test
Recompile: mnesia2_examples_test
Recompile: mnesia2_evil_coverage_test
Recompile: mnesia2_evil_backup
Recompile: mnesia2_durability_test
Recompile: mnesia2_dirty_access_test
Recompile: mnesia2_dbn_meters
Recompile: mnesia2_cost
Recompile: mnesia2_consistency_test
Recompile: mnesia2_config_test
Recompile: mnesia2_config_event
Recompile: mnesia2_config_backup
Recompile: mnesia2_atomicity_test

CWD set to: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2.2016-04-10_22.49.07"

TEST INFO: 1 test(s), 52 case(s) in 1 suite(s)

Cover compiling 'mnesia2' (32 files) - this may take some time... done

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: Starting test, 52 test cases

----------------------------------------------------
2016-04-10 22:49:31.642
starting test group: extra_light


----------------------------------------------------
2016-04-10 22:49:31.682
starting test group: install


----------------------------------------------------
2016-04-10 22:49:31.761
starting test case: silly_durability

22:49:31.840 [info] Application lager started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:31.840 [info] Application poolgirl started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:31.865 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.494.0>
22:49:31.887 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.562.0>

----------------------------------------------------
2016-04-10 22:49:31.892
ending test case: silly_durability


----------------------------------------------------
2016-04-10 22:49:31.917
starting test case: silly_move

22:49:32.278 [error] CRASH REPORT Process <0.553.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:32.278 [info] Application mnesia2 exited with reason: killed
22:49:32.372 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.672.0>
22:49:32.375 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:32.590 [info] Application lager started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:32.590 [info] Application poolgirl started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:32.642 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.99.0>

----------------------------------------------------
2016-04-10 22:49:32.800
ending test case: silly_move


----------------------------------------------------
2016-04-10 22:49:32.826
starting test case: silly_upgrade

22:49:32.828 [error] gen_server <0.729.0> terminated with reason: killed
22:49:32.828 [error] CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:49:32.828 [error] CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:32.929 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.799.0>
22:49:32.935 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.216.0>
22:49:33.178 [warning] lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
22:49:33.178 [info] Application mnesia2 exited with reason: stopped
22:49:33.180 [warning] lager_error_logger_h dropped 13 messages in the last second that exceeded the limit of 50 messages/sec
22:49:33.180 [error] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'...

22:49:33.180 [error] Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.797.0> exit with reason killed in context child_terminated
22:49:33.180 [error] Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.797.0> exit with reason reached_max_restart_intensity in context shutdown
22:49:33.182 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason shutdown in context child_terminated
22:49:33.182 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason reached_max_restart_intensity in context shutdown
22:49:33.184 [info] Application mnesia2 exited with reason: shutdown
22:49:33.207 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.927.0>
22:49:33.209 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:33.214 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.368.0>
22:49:33.218 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:33.275 [info] Application mnesia2 exited with reason: stopped
22:49:33.288 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1027.0>
22:49:33.293 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.458.0>

----------------------------------------------------
2016-04-10 22:49:33.819
ending test case: silly_upgrade


----------------------------------------------------
2016-04-10 22:49:33.901
ending test group: install


----------------------------------------------------
2016-04-10 22:49:33.927
starting test group: nice


----------------------------------------------------
2016-04-10 22:49:34.006
starting test case: nice

22:49:34.008 [warning] lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
22:49:34.008 [error] gen_server <0.514.0> terminated with reason: killed
22:49:34.011 [error] CRASH REPORT Process <0.1018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:34.011 [info] Application mnesia2 exited with reason: killed
22:49:34.008 [error] CRASH REPORT Process <0.514.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:49:34.008 [error] CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:34.008 [info] Application mnesia2 exited with reason: killed
22:49:34.075 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1150.0>
22:49:34.078 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.547.0>
22:49:34.085 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:34.379 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:34.497 [info] Application mnesia2 exited with reason: stopped
22:49:34.528 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1263.0>

----------------------------------------------------
2016-04-10 22:49:34.702
ending test case: nice


----------------------------------------------------
2016-04-10 22:49:34.784
ending test group: nice


----------------------------------------------------
2016-04-10 22:49:34.811
starting test group: qlc


----------------------------------------------------
2016-04-10 22:49:34.920
starting test case: dirty_nice_ram_copies

22:49:34.921 [error] gen_server <0.663.0> terminated with reason: killed
22:49:34.921 [error] CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:49:34.988 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1495.0>
22:49:34.993 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.762.0>

----------------------------------------------------
2016-04-10 22:49:35.103
ending test case: dirty_nice_ram_copies


----------------------------------------------------
2016-04-10 22:49:35.129
starting test case: dirty_nice_disc_copies

22:49:35.132 [error] CRASH REPORT Process <0.1486.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:35.132 [info] Application mnesia2 exited with reason: killed
22:49:35.132 [error] CRASH REPORT Process <0.753.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:35.132 [info] Application mnesia2 exited with reason: killed
22:49:35.190 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1609.0>
22:49:35.194 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.861.0>
22:49:35.197 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:35.495 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'

----------------------------------------------------
2016-04-10 22:49:35.586
ending test case: dirty_nice_disc_copies


----------------------------------------------------
2016-04-10 22:49:35.613
starting test case: dirty_nice_disc_only_copies

22:49:35.616 [error] CRASH REPORT Process <0.1600.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:35.616 [info] Application mnesia2 exited with reason: killed
22:49:35.615 [error] gen_server <0.916.0> terminated with reason: killed
22:49:35.615 [error] CRASH REPORT Process <0.916.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:49:35.615 [error] CRASH REPORT Process <0.852.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:35.615 [info] Application mnesia2 exited with reason: killed
22:49:35.677 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1726.0>
22:49:35.682 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.963.0>

----------------------------------------------------
2016-04-10 22:49:35.804
ending test case: dirty_nice_disc_only_copies


----------------------------------------------------
2016-04-10 22:49:35.895
starting test case: trans_nice_ram_copies

22:49:36.007 [warning] lager_error_logger_h dropped 20 messages in the last second that exceeded the limit of 50 messages/sec
22:49:36.007 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
22:49:36.025 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1852.0>
22:49:36.027 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:36.033 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1069.0>
22:49:36.047 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'

----------------------------------------------------
2016-04-10 22:49:36.174
ending test case: trans_nice_ram_copies


----------------------------------------------------
2016-04-10 22:49:36.200
starting test case: trans_nice_disc_copies

22:49:36.204 [error] gen_server <0.1908.0> terminated with reason: killed
22:49:36.202 [error] gen_server <0.1121.0> terminated with reason: killed
22:49:36.204 [error] CRASH REPORT Process <0.1908.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:49:36.202 [error] CRASH REPORT Process <0.1121.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:49:36.205 [error] CRASH REPORT Process <0.1843.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:36.205 [info] Application mnesia2 exited with reason: killed
22:49:36.203 [error] CRASH REPORT Process <0.1060.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:36.203 [info] Application mnesia2 exited with reason: killed
22:49:36.278 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1983.0>
22:49:36.281 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1168.0>

----------------------------------------------------
2016-04-10 22:49:36.402
ending test case: trans_nice_disc_copies


----------------------------------------------------
2016-04-10 22:49:36.428
starting test case: trans_nice_disc_only_copies

22:49:36.501 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2116.0>
22:49:36.507 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1269.0>

----------------------------------------------------
2016-04-10 22:49:36.661
ending test case: trans_nice_disc_only_copies


----------------------------------------------------
2016-04-10 22:49:36.712
starting test case: atomic_eval

22:49:36.787 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2256.0>
22:49:36.791 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1375.0>

----------------------------------------------------
2016-04-10 22:49:36.913
ending test case: atomic_eval


----------------------------------------------------
2016-04-10 22:49:36.992
starting test case: frag

22:49:37.030 [warning] lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
22:49:37.031 [warning] lager_error_logger_h dropped 23 messages in the last second that exceeded the limit of 50 messages/sec
22:49:37.074 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2387.0>
22:49:37.077 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1462.0>
22:49:37.081 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:37.379 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'

----------------------------------------------------
2016-04-10 22:49:37.499
ending test case: frag


----------------------------------------------------
2016-04-10 22:49:37.525
starting test case: info

22:49:37.528 [error] CRASH REPORT Process <0.2378.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:37.528 [info] Application mnesia2 exited with reason: killed
22:49:37.526 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1476.0> exit with reason killed in context child_terminated
22:49:37.527 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1476.0> exit with reason reached_max_restart_intensity in context shutdown
22:49:37.527 [error] gen_server mnesia2_subscr terminated with reason: killed
22:49:37.527 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:49:37.527 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1457.0> exit with reason killed in context child_terminated
22:49:37.528 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1457.0> exit with reason reached_max_restart_intensity in context shutdown
22:49:37.598 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2521.0>
22:49:37.603 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1575.0>

----------------------------------------------------
2016-04-10 22:49:37.717
ending test case: info


----------------------------------------------------
2016-04-10 22:49:37.743
starting test case: mnesia2_down

22:49:37.789 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2644.0>
22:49:37.807 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1662.0>
---> Participant transactions <--- 
---> Coordinator transactions <---
Tid: 10 (owned by <0.2721.0>) 

----------------------------------------------------
2016-04-10 22:49:37.901
ending test case: mnesia2_down


----------------------------------------------------
2016-04-10 22:49:37.982
ending test group: qlc


----------------------------------------------------
2016-04-10 22:49:38.007
starting test group: registry


----------------------------------------------------
2016-04-10 22:49:38.087
starting test case: good_dump

22:49:38.089 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:49:38.089 [error] gen_server mnesia2_monitor terminated with reason: killed
22:49:38.089 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:49:38.089 [error] gen_server mnesia2_recover terminated with reason: killed
22:49:38.089 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:49:38.089 [error] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.2641.0>,killed}

22:49:38.090 [error] CRASH REPORT Process mnesia2_event with 0 neighbours exited with reason: killed in gen_event:terminate_server/4 line 304
22:49:38.090 [error] CRASH REPORT Process <0.2635.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:38.090 [info] Application mnesia2 exited with reason: killed
22:49:38.117 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2772.0>

----------------------------------------------------
2016-04-10 22:49:38.128
ending test case: good_dump


----------------------------------------------------
2016-04-10 22:49:38.153
starting test case: bad_dump

22:49:38.196 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2866.0>

----------------------------------------------------
2016-04-10 22:49:38.205
ending test case: bad_dump


----------------------------------------------------
2016-04-10 22:49:38.284
ending test group: registry


----------------------------------------------------
2016-04-10 22:49:38.310
starting test group: config


----------------------------------------------------
2016-04-10 22:49:38.390
starting test case: access_module

22:49:39.441 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
22:49:39.450 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2976.0>
22:49:39.454 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:40.668 [error] CRASH REPORT Process <0.2967.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:40.668 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:49:41.691
ending test case: access_module


----------------------------------------------------
2016-04-10 22:49:41.717
starting test case: auto_repair

22:49:42.747 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3082.0>
22:49:42.749 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:42.751 [info] Application mnesia2 exited with reason: stopped
22:49:42.752 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3130.0>
22:49:42.771 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3178.0>

----------------------------------------------------
2016-04-10 22:49:43.788
ending test case: auto_repair


----------------------------------------------------
2016-04-10 22:49:43.814
starting test case: backup_module

22:49:45.241 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
22:49:45.247 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3250.0>
22:49:45.249 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:45.261 [error] CRASH REPORT Process <0.3241.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:45.261 [info] Application mnesia2 exited with reason: killed
22:49:47.310 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3333.0>
22:49:47.314 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:47.319 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

22:49:47.319 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2.2016-04-10_22.49.07/Mnesia2.test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2/LATEST.LOG"] -> badarg

22:49:47.320 [error] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

22:49:47.320 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_19 terminated: shutdown

22:49:47.321 [error] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

22:49:47.321 [error] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

22:49:47.321 [error] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

22:49:47.321 [error] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

22:49:47.321 [error] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

22:49:47.321 [error] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3409.0>}})


----------------------------------------------------
2016-04-10 22:49:48.344
ending test case: backup_module


----------------------------------------------------
2016-04-10 22:49:48.382
starting test case: debug

22:49:49.410 [warning] lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
22:49:49.410 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_monitor starting: <0.3443.0>

22:49:49.411 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Mnesia2 debug level set to verbose
22:49:49.411 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_subscr starting: <0.3444.0>

22:49:49.411 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_locker starting: <0.3445.0>

22:49:49.411 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_recover starting: <0.3446.0>

22:49:49.412 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm starting: <0.3447.0>

22:49:49.412 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Schema initiated from: default

22:49:49.412 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3447.0>
22:49:49.412 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_controller starting: <0.3450.0>

22:49:49.413 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_late_loader starting: <0.3451.0>

22:49:49.413 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Intend to load tables: []

22:49:49.414 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_1 starting: <0.3453.0>

22:49:49.414 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_2 starting: <0.3454.0>

22:49:49.414 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_3 starting: <0.3455.0>

22:49:49.414 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_4 starting: <0.3456.0>

22:49:49.414 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_5 starting: <0.3457.0>

22:49:49.415 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_6 starting: <0.3458.0>

22:49:49.415 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_7 starting: <0.3459.0>

22:49:49.415 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_8 starting: <0.3460.0>

22:49:49.415 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_9 starting: <0.3461.0>

22:49:49.415 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm_10 starting: <0.3462.0>

22:49:51.439 [warning] lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
22:49:51.439 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_monitor starting: <0.3493.0>

22:49:51.440 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Version: "1.0.0"

22:49:51.440 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env access_module: mnesia2

22:49:51.440 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env auto_repair: true

22:49:51.440 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env backup_module: mnesia2_backup

22:49:51.440 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env debug: debug

22:49:51.440 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2.2016-04-10_22.49.07/Mnesia2.test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2"

22:49:51.440 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_disc_copies_at_startup: true

22:49:51.441 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_load_regulation: false

22:49:51.441 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_time_threshold: 180000

22:49:51.441 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_update_in_place: true

22:49:51.441 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_write_threshold: 1000

22:49:51.441 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env event_module: mnesia2_event

22:49:51.441 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env extra_db_nodes: []

22:49:51.441 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env ignore_fallback_at_startup: false

22:49:51.441 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env fallback_error_function: {mnesia2,lkill}

22:49:51.441 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env max_wait_for_decision: infinity

22:49:51.442 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env schema_location: opt_disc

22:49:51.442 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env core_dir: false

22:49:51.442 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env pid_sort_order: false

22:49:51.442 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env no_table_loaders: 2

22:49:51.442 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dc_dump_limit: 4

22:49:51.442 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env send_compressed: 0

22:49:51.442 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env send_max_packets: 20

22:49:51.442 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env send_max_transfer_size: 7500

22:49:51.444 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env async_dirty_buffer_size: 524288

22:49:51.444 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env async_dirty_max_buffer_file_size: 100000000

22:49:51.444 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env async_dirty_tx_backlog_threshold: 200000

22:49:51.445 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env async_dirty_buffer_min_runtime: 10000

22:49:51.445 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env async_dirty_buffer_drained_cutoff: 5

22:49:51.445 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3497.0>
22:49:51.446 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Mnesia2 debug level set to debug
22:49:51.446 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_subscr starting: <0.3494.0>

22:49:51.446 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_locker starting: <0.3495.0>

22:49:51.446 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_recover starting: <0.3496.0>

22:49:51.447 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_tm starting: <0.3497.0>

22:49:51.447 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Schema initiated from: default

22:49:53.474 [warning] lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
22:49:53.474 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_monitor starting: <0.3546.0>

22:49:53.474 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Version: "1.0.0"

22:49:53.474 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env access_module: mnesia2

22:49:53.476 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3550.0>
22:49:53.478 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:53.480 [error] CRASH REPORT Process <0.3541.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:53.480 [info] Application mnesia2 exited with reason: killed
22:49:55.501 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): mnesia2_monitor starting: <0.3595.0>

22:49:55.502 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Version: "1.0.0"

22:49:55.502 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env access_module: mnesia2

22:49:55.502 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env auto_repair: true

22:49:55.502 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env backup_module: mnesia2_backup

22:49:55.503 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env debug: debug

22:49:55.503 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2.2016-04-10_22.49.07/Mnesia2.test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2"

22:49:55.503 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3599.0>
22:49:55.503 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_disc_copies_at_startup: true

22:49:55.504 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_load_regulation: false

22:49:55.504 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_time_threshold: 180000

22:49:55.504 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_update_in_place: true

22:49:55.504 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env dump_log_write_threshold: 1000

22:49:55.505 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env event_module: mnesia2_event

22:49:55.505 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env extra_db_nodes: []

22:49:55.505 [info] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): Env ignore_fallback_at_startup: false

22:49:57.529 [warning] lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
22:49:57.531 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3655.0>
22:49:57.533 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:57.534 [error] CRASH REPORT Process <0.3646.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:57.534 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:49:58.559
ending test case: debug


----------------------------------------------------
2016-04-10 22:49:58.585
starting test case: dir

22:49:59.627 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3719.0>
22:49:59.629 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:49:59.630 [error] CRASH REPORT Process <0.3710.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:49:59.630 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:50:00.664
ending test case: dir


----------------------------------------------------
2016-04-10 22:50:00.706
starting test case: dump_log_load_regulation

22:50:00.731 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3790.0>
22:50:00.733 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:50:00.736 [info] Application mnesia2 exited with reason: stopped
22:50:00.742 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3851.0>
22:50:10.660 [error] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:50:11.873 [error] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:50:12.410 [error] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:50:15.792 [error] Mnesia2('test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:50:15.916 [error] CRASH REPORT Process <0.3842.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:50:15.916 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:50:16.939
ending test case: dump_log_load_regulation


----------------------------------------------------
2016-04-10 22:50:16.991
starting test case: dump_log_time_threshold

22:50:18.042 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4446.0>
22:50:18.044 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:50:24.051 [error] CRASH REPORT Process <0.4437.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:50:24.051 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:50:25.074
ending test case: dump_log_time_threshold


----------------------------------------------------
2016-04-10 22:50:25.100
starting test case: dump_log_write_threshold

22:50:26.140 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4546.0>
22:50:26.142 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:50:27.158 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:50:28.171
ending test case: dump_log_write_threshold


----------------------------------------------------
2016-04-10 22:50:28.237
starting test case: dump_log_update_in_place

22:50:29.280 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4662.0>
22:50:29.283 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:50:29.290 [error] CRASH REPORT Process <0.4653.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:50:29.290 [info] Application mnesia2 exited with reason: killed
22:50:31.407 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4729.0>
22:50:31.410 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:50:31.446 [error] CRASH REPORT Process <0.4720.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:50:31.446 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:50:32.469
ending test case: dump_log_update_in_place


----------------------------------------------------
2016-04-10 22:50:32.497
starting test case: event_module

22:50:33.548 [warning] lager_error_logger_h dropped 13 messages in the last second that exceeded the limit of 50 messages/sec
22:50:33.567 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4821.0>
22:50:33.570 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1789.0>
22:50:33.582 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:50:33.872 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'}}
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'}}
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'}}
22:50:34.873 [error] gen_server <0.1842.0> terminated with reason: killed
22:50:34.873 [error] CRASH REPORT Process <0.1842.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:50:34.874 [error] CRASH REPORT Process <0.1780.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:50:34.874 [info] Application mnesia2 exited with reason: killed
22:50:36.931 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1858.0>
22:50:36.935 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'}}
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'}}
22:50:37.937 [error] gen_server <0.4885.0> terminated with reason: killed
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'}}
22:50:37.937 [error] CRASH REPORT Process <0.4885.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:50:37.937 [error] CRASH REPORT Process <0.4812.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:50:37.938 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:50:38.960
ending test case: event_module


----------------------------------------------------
2016-04-10 22:50:38.987
starting test case: inconsistent_database

22:50:38.990 [error] CRASH REPORT Process <0.1849.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:50:38.990 [info] Application mnesia2 exited with reason: killed
22:50:40.681 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4928.0>
22:50:40.684 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:50:40.687 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1939.0>
22:50:40.690 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:50:40.694 [error] gen_server <0.1985.0> terminated with reason: killed
22:50:40.692 [error] CRASH REPORT Process <0.4919.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:50:40.693 [info] Application mnesia2 exited with reason: killed
22:50:40.694 [error] CRASH REPORT Process <0.1985.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:50:40.694 [error] CRASH REPORT Process <0.1930.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:50:40.694 [info] Application mnesia2 exited with reason: killed
22:50:40.838 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5008.0>
22:50:45.043 [info] Application mnesia2 exited with reason: stopped
22:50:45.075 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2014.0>
22:50:45.077 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:50:45.084 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5132.0>
22:50:45.089 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:50:56.050 [info] Application mnesia2 exited with reason: stopped
22:50:56.057 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:50:57.088
ending test case: inconsistent_database


----------------------------------------------------
2016-04-10 22:50:57.116
starting test case: max_wait_for_decision


----------------------------------------------------
2016-04-10 22:50:57.116
ending test case: max_wait_for_decision


----------------------------------------------------
2016-04-10 22:50:57.142
starting test case: send_compressed

22:50:57.183 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5263.0>
22:50:57.185 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:50:57.193 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2136.0>
22:50:57.197 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:50:57.244 [error] gen_server <0.2180.0> terminated with reason: killed
22:50:57.244 [error] CRASH REPORT Process <0.2180.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:50:57.244 [error] CRASH REPORT Process <0.2127.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:50:57.245 [info] Application mnesia2 exited with reason: killed
22:50:57.266 [error] CRASH REPORT Process <0.5254.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:50:57.266 [info] Application mnesia2 exited with reason: killed
22:50:57.301 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5351.0>
22:50:57.536 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2224.0>

----------------------------------------------------
2016-04-10 22:50:58.991
ending test case: send_compressed


----------------------------------------------------
2016-04-10 22:50:59.019
starting test case: app_test


----------------------------------------------------
2016-04-10 22:50:59.026
ending test case: app_test


----------------------------------------------------
2016-04-10 22:50:59.083
starting test case: start_one_disc_full_then_one_disc_less

22:50:59.086 [error] CRASH REPORT Process <0.2215.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:50:59.086 [info] Application mnesia2 exited with reason: killed
22:51:00.141 [warning] lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
22:51:00.146 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5474.0>
22:51:00.148 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:00.159 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2327.0>
22:51:00.165 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:00.189 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5469.0> exit with reason killed in context child_terminated
22:51:00.189 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5469.0> exit with reason reached_max_restart_intensity in context shutdown
22:51:00.189 [error] gen_server mnesia2_recover terminated with reason: killed
22:51:00.189 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:00.188 [error] gen_server <0.2339.0> terminated with reason: killed
22:51:00.189 [error] CRASH REPORT Process <0.5465.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:00.189 [info] Application mnesia2 exited with reason: killed
22:51:00.188 [error] CRASH REPORT Process <0.2339.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:00.188 [error] CRASH REPORT Process <0.2318.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:00.188 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:01.212
ending test case: start_one_disc_full_then_one_disc_less


----------------------------------------------------
2016-04-10 22:51:01.239
starting test case: start_first_one_disc_less_then_one_disc_full

22:51:02.285 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5585.0>
22:51:02.286 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:02.291 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2402.0>
22:51:02.304 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:02.308 [error] gen_server <0.5649.0> terminated with reason: killed
22:51:02.308 [error] gen_server <0.2414.0> terminated with reason: killed
22:51:02.308 [error] CRASH REPORT Process <0.5649.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:02.308 [error] CRASH REPORT Process <0.2414.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:02.308 [error] CRASH REPORT Process <0.5576.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:02.308 [info] Application mnesia2 exited with reason: killed
22:51:02.308 [error] CRASH REPORT Process <0.2393.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:02.308 [info] Application mnesia2 exited with reason: killed
22:51:04.334 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2461.0>
22:51:04.335 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:04.495 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5665.0>
22:51:04.507 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:04.547 [error] gen_server <0.5700.0> terminated with reason: killed
22:51:04.547 [error] CRASH REPORT Process <0.5700.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:04.547 [error] CRASH REPORT Process <0.5656.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:04.547 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:05.570
ending test case: start_first_one_disc_less_then_one_disc_full


----------------------------------------------------
2016-04-10 22:51:05.597
starting test case: start_first_one_disc_less_then_two_more_disc_less

22:51:05.969 [error] CRASH REPORT Process <0.2452.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:05.969 [info] Application mnesia2 exited with reason: killed
22:51:07.064 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5790.0>
22:51:07.067 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:07.071 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2550.0>
22:51:07.077 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:07.420 [info] Application lager started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:07.421 [info] Application poolgirl started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:07.475 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.101.0>
22:51:07.506 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:07.553 [error] gen_server <0.2601.0> terminated with reason: killed
22:51:07.550 [error] gen_server <0.5843.0> terminated with reason: killed
22:51:07.553 [error] CRASH REPORT Process <0.2601.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:07.551 [error] CRASH REPORT Process <0.5843.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:07.553 [error] gen_server <0.2592.0> terminated with reason: killed
22:51:07.552 [error] CRASH REPORT Process <0.5781.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:07.552 [info] Application mnesia2 exited with reason: killed
22:51:07.553 [error] CRASH REPORT Process <0.2592.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:07.556 [error] CRASH REPORT Process <0.2541.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:07.556 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:08.590
ending test case: start_first_one_disc_less_then_two_more_disc_less


----------------------------------------------------
2016-04-10 22:51:08.618
starting test case: schema_location_and_extra_db_nodes_combinations

22:51:09.740 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5885.0>
22:51:09.742 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:10.240 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2631.0>
22:51:10.247 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:10.251 [error] gen_server <0.2643.0> terminated with reason: killed
22:51:10.254 [error] gen_server <0.5949.0> terminated with reason: killed
22:51:10.251 [error] CRASH REPORT Process <0.2643.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:10.255 [error] CRASH REPORT Process <0.5949.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:10.252 [error] CRASH REPORT Process <0.2622.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:10.252 [info] Application mnesia2 exited with reason: killed
22:51:10.256 [error] CRASH REPORT Process <0.5876.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:10.256 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:11.284
ending test case: schema_location_and_extra_db_nodes_combinations


----------------------------------------------------
2016-04-10 22:51:11.312
starting test case: table_load_to_disc_less_nodes

22:51:12.346 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5979.0>
22:51:12.348 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:12.350 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2701.0>
22:51:12.354 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:12.374 [error] CRASH REPORT Process <0.2692.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:12.375 [info] Application mnesia2 exited with reason: killed
22:51:12.375 [error] gen_server <0.6023.0> terminated with reason: killed
22:51:12.375 [error] CRASH REPORT Process <0.6023.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:12.375 [error] CRASH REPORT Process <0.5970.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:12.375 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:13.400
ending test case: table_load_to_disc_less_nodes


----------------------------------------------------
2016-04-10 22:51:13.442
starting test case: schema_merge

22:51:14.547 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6065.0>
22:51:14.550 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:14.582 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2776.0>
22:51:14.585 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:14.589 [error] gen_server <0.2830.0> terminated with reason: killed
22:51:14.589 [error] CRASH REPORT Process <0.2830.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:14.589 [error] CRASH REPORT Process <0.2767.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:14.589 [info] Application mnesia2 exited with reason: killed
22:51:15.616 [error] CRASH REPORT Process <0.6056.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:15.616 [info] Application mnesia2 exited with reason: killed
22:51:17.648 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2846.0>
22:51:17.649 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:22.692 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6143.0>
22:51:22.701 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:22.708 [error] gen_server <0.6204.0> terminated with reason: killed
22:51:22.708 [error] CRASH REPORT Process <0.6204.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:22.706 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2859.0> exit with reason killed in context child_terminated
22:51:22.708 [error] CRASH REPORT Process <0.6134.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:22.708 [info] Application mnesia2 exited with reason: killed
22:51:22.706 [error] Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2859.0> exit with reason reached_max_restart_intensity in context shutdown
22:51:22.706 [error] gen_server <0.2913.0> terminated with reason: killed
22:51:22.707 [error] CRASH REPORT Process <0.2913.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:22.707 [error] CRASH REPORT Process <0.2837.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:22.707 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:23.733
ending test case: schema_merge


----------------------------------------------------
2016-04-10 22:51:23.787
starting test case: dynamic_basic

22:51:23.855 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:51:23.883 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6253.0>
22:51:23.885 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:23.898 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2945.0>
22:51:23.901 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:23.907 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.191.0>
22:51:23.912 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:23.981 [error] gen_server <0.2997.0> terminated with reason: killed
22:51:23.981 [error] CRASH REPORT Process <0.2997.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:23.982 [error] gen_server <0.3008.0> terminated with reason: killed
22:51:23.982 [error] CRASH REPORT Process <0.3008.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:23.982 [error] CRASH REPORT Process <0.2936.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:23.982 [info] Application mnesia2 exited with reason: killed
22:51:24.009 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3036.0>
22:51:24.037 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:24.060 [error] CRASH REPORT Process <0.6244.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:24.060 [info] Application mnesia2 exited with reason: killed
22:51:24.080 [error] gen_server <0.274.0> terminated with reason: killed
22:51:24.080 [error] CRASH REPORT Process <0.274.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:24.081 [error] CRASH REPORT Process <0.182.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:24.081 [info] Application mnesia2 exited with reason: killed
22:51:24.108 [info] Application mnesia2 exited with reason: stopped
22:51:24.121 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3131.0>
22:51:24.164 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6375.0>
22:51:24.167 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.295.0>
22:51:24.183 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:24.469 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:24.989 [error] gen_server <0.367.0> terminated with reason: killed
22:51:24.989 [error] CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:24.989 [error] gen_server <0.356.0> terminated with reason: killed
22:51:24.989 [error] CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:25.015 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.391.0>
22:51:25.017 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:27.082 [error] gen_server <0.6473.0> terminated with reason: killed
22:51:27.082 [error] CRASH REPORT Process <0.6473.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:27.083 [error] gen_server <0.6443.0> terminated with reason: killed
22:51:27.083 [error] CRASH REPORT Process <0.6443.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:27.084 [error] CRASH REPORT Process <0.6366.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:27.084 [info] Application mnesia2 exited with reason: killed
22:51:27.103 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:51:27.103 [error] gen_server <0.3224.0> terminated with reason: killed
22:51:27.104 [error] CRASH REPORT Process <0.3224.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:27.104 [error] CRASH REPORT Process <0.3122.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:27.104 [info] Application mnesia2 exited with reason: killed
22:51:27.127 [info] Application mnesia2 exited with reason: stopped
22:51:27.160 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.497.0>
22:51:27.161 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:27.184 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6492.0>
22:51:27.185 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3245.0>
22:51:27.192 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:27.199 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:27.706 [error] CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:27.706 [info] Application mnesia2 exited with reason: killed
22:51:27.741 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.595.0>
22:51:27.815 [error] gen_server <0.6580.0> terminated with reason: killed
22:51:27.815 [error] CRASH REPORT Process <0.6580.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:27.815 [error] gen_server <0.6585.0> terminated with reason: killed
22:51:27.816 [error] CRASH REPORT Process <0.6585.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:27.816 [error] gen_server <0.6566.0> terminated with reason: killed
22:51:27.816 [error] CRASH REPORT Process <0.6566.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:27.816 [error] CRASH REPORT Process <0.6483.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:27.816 [info] Application mnesia2 exited with reason: killed
22:51:27.828 [error] gen_server <0.3333.0> terminated with reason: killed
22:51:27.828 [error] CRASH REPORT Process <0.3333.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:27.865 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.696.0>
22:51:27.895 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6604.0>
22:51:27.896 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3354.0>
22:51:28.201 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:28.725 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
22:51:28.725 [error] gen_server <0.3425.0> terminated with reason: killed
22:51:28.725 [error] CRASH REPORT Process <0.3425.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:28.725 [error] gen_server <0.3410.0> terminated with reason: killed
22:51:28.725 [error] CRASH REPORT Process <0.3410.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:28.725 [error] CRASH REPORT Process <0.3345.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:28.725 [info] Application mnesia2 exited with reason: killed
22:51:28.769 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3451.0>
22:51:28.777 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:29.842 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
22:51:29.845 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3529.0>
22:51:29.855 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'

----------------------------------------------------
2016-04-10 22:51:29.862
ending test case: dynamic_basic


----------------------------------------------------
2016-04-10 22:51:29.904
starting test case: dynamic_ext

22:51:29.907 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:51:29.907 [error] gen_server <0.3543.0> terminated with reason: killed
22:51:29.907 [error] CRASH REPORT Process <0.3543.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:29.907 [error] gen_server <0.819.0> terminated with reason: killed
22:51:29.909 [error] gen_server <0.6716.0> terminated with reason: killed
22:51:29.908 [error] CRASH REPORT Process <0.3520.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:29.908 [info] Application mnesia2 exited with reason: killed
22:51:29.909 [error] CRASH REPORT Process <0.6716.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:29.907 [error] CRASH REPORT Process <0.819.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:29.907 [error] gen_server <0.809.0> terminated with reason: killed
22:51:29.912 [error] gen_server <0.6667.0> terminated with reason: killed
22:51:29.907 [error] CRASH REPORT Process <0.809.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:29.912 [error] CRASH REPORT Process <0.6667.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:29.907 [error] gen_server <0.768.0> terminated with reason: killed
22:51:29.913 [error] CRASH REPORT Process <0.6595.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:29.913 [info] Application mnesia2 exited with reason: killed
22:51:29.907 [error] CRASH REPORT Process <0.768.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:29.908 [error] CRASH REPORT Process <0.687.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:29.908 [info] Application mnesia2 exited with reason: killed
22:51:29.983 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6749.0>
22:51:29.986 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:30.003 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3607.0>
22:51:30.007 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:30.053 [error] CRASH REPORT Process <0.3598.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:30.053 [info] Application mnesia2 exited with reason: killed
22:51:30.080 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3702.0>
22:51:30.155 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3792.0>
22:51:30.217 [info] Application mnesia2 exited with reason: stopped
22:51:30.219 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3892.0>
22:51:30.733 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6862.0>
22:51:30.748 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:30.776 [info] Application mnesia2 exited with reason: stopped
22:51:30.813 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6945.0>
22:51:31.316 [warning] lager_error_logger_h dropped 42 messages in the last second that exceeded the limit of 50 messages/sec
22:51:31.318 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.3974.0>
22:51:31.332 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'

----------------------------------------------------
2016-04-10 22:51:31.351
ending test case: dynamic_ext


----------------------------------------------------
2016-04-10 22:51:31.377
starting test case: dynamic_bad

22:51:31.380 [error] gen_server <0.7010.0> terminated with reason: killed
22:51:31.382 [error] CRASH REPORT Process <0.3965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:31.382 [info] Application mnesia2 exited with reason: killed
22:51:31.380 [error] CRASH REPORT Process <0.7010.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:31.380 [error] CRASH REPORT Process <0.6936.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:31.380 [info] Application mnesia2 exited with reason: killed
22:51:31.459 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7046.0>
22:51:31.461 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:31.466 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.846.0>
22:51:31.468 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4066.0>
22:51:31.770 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:31.843 [error] gen_server <0.7109.0> terminated with reason: killed
22:51:31.842 [error] gen_server <0.908.0> terminated with reason: killed
22:51:31.844 [error] CRASH REPORT Process <0.7109.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:31.842 [error] CRASH REPORT Process <0.908.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:31.843 [error] gen_server <0.903.0> terminated with reason: killed
22:51:31.843 [error] CRASH REPORT Process <0.903.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:31.843 [error] CRASH REPORT Process <0.837.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:31.843 [info] Application mnesia2 exited with reason: killed
22:51:31.869 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4158.0>
22:51:31.867 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.951.0>
22:51:31.894 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7157.0>
22:51:31.943 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1029.0>
22:51:31.944 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4237.0>
22:51:31.964 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7249.0>

----------------------------------------------------
2016-04-10 22:51:41.985
ending test case: dynamic_bad

22:51:41.984 [warning] lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
22:51:41.984 [error] Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
22:51:41.984 [error] gen_server mnesia2_monitor terminated with reason: killed
22:51:41.984 [error] gen_server mnesia2_recover terminated with reason: killed
22:51:41.984 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:41.984 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
22:51:41.984 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:41.984 [error] gen_server mnesia2_subscr terminated with reason: killed
22:51:41.984 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:41.984 [error] CRASH REPORT Process <0.7240.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
22:51:41.985 [info] Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
22:51:41.985 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746

----------------------------------------------------
2016-04-10 22:51:42.067
starting test case: unknown_config

22:51:42.069 [warning] lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
22:51:42.070 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:51:42.069 [error] gen_server <0.4281.0> terminated with reason: killed
22:51:42.070 [error] gen_server <0.1078.0> terminated with reason: killed
22:51:42.070 [error] CRASH REPORT Process <0.4281.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:42.070 [error] CRASH REPORT Process <0.1078.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:42.070 [error] CRASH REPORT Process <0.4228.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:42.070 [info] Application mnesia2 exited with reason: killed
22:51:42.070 [error] gen_server <0.1073.0> terminated with reason: killed
22:51:42.070 [error] CRASH REPORT Process <0.1073.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
22:51:42.070 [error] CRASH REPORT Process <0.1020.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
22:51:42.070 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:51:44.138
ending test case: unknown_config


----------------------------------------------------
2016-04-10 22:51:44.218
ending test group: config


----------------------------------------------------
2016-04-10 22:51:44.244
starting test group: examples


----------------------------------------------------
2016-04-10 22:51:44.336
starting test case: bup


----------------------------------------------------
2016-04-10 22:51:44.361
ending test case: bup


- - - - - - - - - - - - - - - - - - - - - - - - - -
Error detected: error
- - - - - - - - - - - - - - - - - - - - - - - - - -

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: *** FAILED test case 41 of 52 ***

----------------------------------------------------
2016-04-10 22:51:44.390
starting test case: company


----------------------------------------------------
2016-04-10 22:51:44.391
ending test case: company


----------------------------------------------------
2016-04-10 22:51:44.417
starting test case: meter

22:51:44.459 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7358.0>
22:51:44.462 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:48.748 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:51:48.765
ending test case: meter


----------------------------------------------------
2016-04-10 22:51:48.817
starting test case: replica_test

22:51:48.917 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7494.0>
22:51:48.920 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:48.931 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4328.0>
22:51:48.931 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1125.0>
22:51:48.937 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:48.943 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:55.208 [info] Application mnesia2 exited with reason: stopped
22:51:55.209 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:51:55.227
ending test case: replica_test

22:51:55.226 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:51:55.254
starting test case: sticky_replica_test

22:51:55.350 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7623.0>
22:51:55.353 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:55.359 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4444.0>
22:51:55.360 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1240.0>
22:51:55.372 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:51:55.663 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:01.765 [info] Application mnesia2 exited with reason: stopped
22:52:01.765 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:01.782
ending test case: sticky_replica_test

22:52:01.770 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:01.813
starting test case: dist_test

22:52:01.884 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7752.0>
22:52:01.894 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.1353.0>
22:52:01.900 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4560.0>
22:52:01.905 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:01.911 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:02.189 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:18.789 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:18.806
ending test case: dist_test

22:52:18.791 [info] Application mnesia2 exited with reason: stopped
22:52:18.792 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:18.833
starting test case: conflict_test

22:52:18.918 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.8892.0>
22:52:18.920 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:18.924 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5682.0>
22:52:18.924 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2479.0>
22:52:18.930 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:18.944 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:25.297 [info] Application mnesia2 exited with reason: stopped
22:52:25.302 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:25.304
ending test case: conflict_test

22:52:25.303 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:25.356
starting test case: frag_test

22:52:25.443 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.9030.0>
22:52:25.447 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.2603.0>
22:52:25.463 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.5807.0>
22:52:25.468 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:25.748 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:25.751 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:32.070 [info] Application mnesia2 exited with reason: stopped
22:52:32.076 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:32.078
ending test case: frag_test

22:52:32.078 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:32.105
starting test case: frag2_test

22:52:32.219 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.10511.0>
22:52:32.222 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:32.225 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.4076.0>
22:52:32.228 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.7277.0>
22:52:32.236 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:32.529 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:38.767 [info] Application mnesia2 exited with reason: stopped
22:52:38.781 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:38.801
ending test case: frag2_test

22:52:38.800 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:38.828
starting test case: remote_test

22:52:38.924 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.10952.0>
22:52:38.927 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:38.932 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6124.0>
22:52:38.933 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.8351.0>
22:52:38.945 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:39.007 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:45.216 [info] Application mnesia2 exited with reason: stopped
22:52:45.217 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:45.232
ending test case: remote_test

22:52:45.232 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:45.259
starting test case: remote_frag2_test

22:52:45.336 [info] starting mnesia2_tm, 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.11081.0>
22:52:45.337 [info] starting mnesia2_tm, 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.8467.0>
22:52:45.340 [info] Application mnesia2 started on node 'test4620@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:45.358 [info] starting mnesia2_tm, 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2', <0.6916.0>
22:52:45.362 [info] Application mnesia2 started on node 'd1131514o1131462n1131462@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:45.663 [info] Application mnesia2 started on node 'd1131508o1131500n1131500@testing-worker-linux-docker-bf2e3346-3362-linux-2'
22:52:51.844 [info] Application mnesia2 exited with reason: stopped
22:52:51.845 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:51.845
ending test case: remote_frag2_test

22:52:51.845 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:52:51.989
ending test group: examples


----------------------------------------------------
2016-04-10 22:52:52.016
ending test group: extra_light


----------------------------------------------------
2016-04-10 22:52:52.042
starting test case: clean_up_suite


----------------------------------------------------
2016-04-10 22:52:52.060
ending test case: clean_up_suite

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: TEST COMPLETE, 51 ok, 1 failed of 52 test cases

Cover analysing... done

Updating /home/travis/build/lrascao/mnesia2/logs/index.html... done
Updating /home/travis/build/lrascao/mnesia2/logs/all_runs.html... done

