2016-04-10 22:39:16.252 [error] <0.155.0> gen_server <0.155.0> terminated with reason: killed
2016-04-10 22:39:16.253 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:16.252 [error] <0.155.0> CRASH REPORT Process <0.155.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:16.253 [error] <0.90.0> CRASH REPORT Process <0.90.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:16.473 [error] <0.792.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9'...

2016-04-10 22:39:16.475 [error] <0.793.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.796.0> exit with reason killed in context child_terminated
2016-04-10 22:39:16.475 [error] <0.793.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.796.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:17.877 [error] <0.516.0> gen_server <0.516.0> terminated with reason: killed
2016-04-10 22:39:17.878 [error] <0.1019.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1021.0> exit with reason killed in context child_terminated
2016-04-10 22:39:17.877 [error] <0.516.0> CRASH REPORT Process <0.516.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:17.878 [error] <0.1019.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.1021.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:17.877 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:17.879 [error] <0.1017.0> CRASH REPORT Process <0.1017.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:18.787 [error] <0.664.0> gen_server <0.664.0> terminated with reason: killed
2016-04-10 22:39:18.787 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:18.787 [error] <0.538.0> CRASH REPORT Process <0.538.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:18.960 [error] <0.754.0> CRASH REPORT Process <0.754.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:19.148 [error] <0.853.0> CRASH REPORT Process <0.853.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:19.148 [error] <0.1664.0> gen_server <0.1664.0> terminated with reason: killed
2016-04-10 22:39:19.148 [error] <0.1664.0> CRASH REPORT Process <0.1664.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:19.149 [error] <0.1599.0> CRASH REPORT Process <0.1599.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:20.468 [error] <0.1324.0> gen_server <0.1324.0> terminated with reason: killed
2016-04-10 22:39:20.471 [error] <0.2105.0> CRASH REPORT Process <0.2105.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:20.468 [error] <0.1324.0> CRASH REPORT Process <0.1324.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:20.469 [error] <0.1260.0> CRASH REPORT Process <0.1260.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:20.745 [error] <0.1425.0> gen_server <0.1425.0> terminated with reason: killed
2016-04-10 22:39:20.745 [error] <0.1425.0> CRASH REPORT Process <0.1425.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:21.200 [error] <0.1627.0> gen_server <0.1627.0> terminated with reason: killed
2016-04-10 22:39:21.202 [error] <0.2572.0> gen_server <0.2572.0> terminated with reason: killed
2016-04-10 22:39:21.200 [error] <0.1627.0> CRASH REPORT Process <0.1627.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:21.202 [error] <0.2572.0> CRASH REPORT Process <0.2572.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:39:21.200 [error] <0.1566.0> CRASH REPORT Process <0.1566.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:21.203 [error] <0.2509.0> CRASH REPORT Process <0.2509.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:24.079 [error] <0.2964.0> CRASH REPORT Process <0.2964.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:28.289 [error] <0.3242.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3258.0> exit with reason killed in context child_terminated
2016-04-10 22:39:28.290 [error] <0.3242.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3258.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:39:28.290 [error] <0.3238.0> CRASH REPORT Process <0.3238.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:30.340 [error] <0.3384.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:39:30.340 [error] <0.3386.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:39:30.341 [error] <0.3385.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:39:30.341 [error] <0.3388.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:39:30.341 [error] <0.3390.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:39:30.341 [error] <0.3389.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:39:40.572 [error] <0.3665.0> CRASH REPORT Process <0.3665.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:42.670 [error] <0.3729.0> CRASH REPORT Process <0.3729.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:39:54.291 [error] <0.3864.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:39:58.837 [error] <0.3861.0> CRASH REPORT Process <0.3861.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:07.002 [error] <0.4482.0> CRASH REPORT Process <0.4482.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:12.225 [error] <0.4698.0> CRASH REPORT Process <0.4698.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:14.387 [error] <0.4765.0> CRASH REPORT Process <0.4765.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:17.518 [error] <0.1841.0> gen_server <0.1841.0> terminated with reason: killed
2016-04-10 22:40:17.519 [error] <0.1841.0> CRASH REPORT Process <0.1841.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:17.519 [error] <0.1780.0> CRASH REPORT Process <0.1780.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:21.140 [error] <0.4929.0> gen_server <0.4929.0> terminated with reason: killed
2016-04-10 22:40:21.140 [error] <0.4929.0> CRASH REPORT Process <0.4929.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:21.141 [error] <0.4857.0> CRASH REPORT Process <0.4857.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:22.192 [error] <0.1848.0> CRASH REPORT Process <0.1848.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:23.317 [error] <0.4963.0> CRASH REPORT Process <0.4963.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:23.317 [error] <0.1929.0> CRASH REPORT Process <0.1929.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:38.546 [error] emulator Error in process <0.2198.0> on node 'd686222o686218n686218@testing-worker-linux-docker-c74eb140-3365-linux-9' with exit value: {badarg,[{erlang,unlink,[undefined],[]},{mnesia2_tm,commit_participant,6,[{file,"src/mnesia2_tm.erl"},{line,1873}]}]}


2016-04-10 22:40:38.546 [error] <0.2121.0> CRASH REPORT Process <0.2121.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:38.567 [error] <0.5293.0> CRASH REPORT Process <0.5293.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:39.209 [error] <0.5461.0> gen_server <0.5461.0> terminated with reason: killed
2016-04-10 22:40:39.210 [error] <0.5461.0> CRASH REPORT Process <0.5461.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:39.210 [error] <0.5381.0> CRASH REPORT Process <0.5381.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:40.331 [error] <0.2209.0> CRASH REPORT Process <0.2209.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:41.430 [error] <0.2341.0> gen_server <0.2341.0> terminated with reason: killed
2016-04-10 22:40:41.432 [error] <0.5577.0> gen_server <0.5577.0> terminated with reason: killed
2016-04-10 22:40:41.430 [error] <0.2341.0> CRASH REPORT Process <0.2341.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:41.432 [error] <0.5577.0> CRASH REPORT Process <0.5577.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:41.431 [error] <0.2312.0> CRASH REPORT Process <0.2312.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:41.433 [error] <0.5504.0> CRASH REPORT Process <0.5504.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:43.539 [error] <0.5688.0> gen_server <0.5688.0> terminated with reason: killed
2016-04-10 22:40:43.539 [error] <0.5688.0> CRASH REPORT Process <0.5688.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:43.540 [error] <0.5615.0> CRASH REPORT Process <0.5615.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:43.539 [error] <0.2387.0> CRASH REPORT Process <0.2387.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:45.604 [error] <0.5763.0> gen_server <0.5763.0> terminated with reason: killed
2016-04-10 22:40:45.604 [error] <0.5763.0> CRASH REPORT Process <0.5763.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:45.604 [error] <0.5695.0> CRASH REPORT Process <0.5695.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:47.053 [error] <0.2446.0> CRASH REPORT Process <0.2446.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:48.466 [error] <0.5823.0> Mnesia2('test7510@testing-worker-linux-docker-c74eb140-3365-linux-9'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.5826.0>,killed}

2016-04-10 22:40:48.465 [error] <0.2595.0> gen_server <0.2595.0> terminated with reason: killed
2016-04-10 22:40:48.466 [error] <0.5822.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5824.0> exit with reason killed in context child_terminated
2016-04-10 22:40:48.465 [error] <0.2595.0> CRASH REPORT Process <0.2595.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:48.466 [error] <0.2585.0> gen_server <0.2585.0> terminated with reason: killed
2016-04-10 22:40:48.466 [error] <0.5822.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5824.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:40:48.466 [error] <0.5825.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:40:48.466 [error] <0.5828.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:40:48.466 [error] <0.5828.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:48.466 [error] <0.2585.0> CRASH REPORT Process <0.2585.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:48.466 [error] <0.2535.0> CRASH REPORT Process <0.2535.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:50.619 [error] <0.5988.0> gen_server <0.5988.0> terminated with reason: killed
2016-04-10 22:40:50.619 [error] <0.2617.0> CRASH REPORT Process <0.2617.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:50.619 [error] <0.5988.0> CRASH REPORT Process <0.5988.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:50.621 [error] <0.5915.0> CRASH REPORT Process <0.5915.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:52.717 [error] <0.6009.0> CRASH REPORT Process <0.6009.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:52.716 [error] <0.2708.0> gen_server <0.2708.0> terminated with reason: killed
2016-04-10 22:40:52.717 [error] <0.2708.0> CRASH REPORT Process <0.2708.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:52.717 [error] <0.2687.0> CRASH REPORT Process <0.2687.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:54.845 [error] <0.2820.0> gen_server <0.2820.0> terminated with reason: killed
2016-04-10 22:40:54.846 [error] <0.2820.0> CRASH REPORT Process <0.2820.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:40:54.846 [error] <0.2762.0> CRASH REPORT Process <0.2762.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:40:55.878 [error] <0.6095.0> CRASH REPORT Process <0.6095.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:03.010 [error] <0.6245.0> gen_server <0.6245.0> terminated with reason: killed
2016-04-10 22:41:03.012 [error] <0.2908.0> gen_server <0.2908.0> terminated with reason: killed
2016-04-10 22:41:03.010 [error] <0.6245.0> CRASH REPORT Process <0.6245.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:03.012 [error] <0.2908.0> CRASH REPORT Process <0.2908.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:03.010 [error] <0.6173.0> CRASH REPORT Process <0.6173.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:03.012 [error] <0.2832.0> CRASH REPORT Process <0.2832.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:04.551 [error] <0.2999.0> gen_server <0.2999.0> terminated with reason: killed
2016-04-10 22:41:04.551 [error] <0.2999.0> CRASH REPORT Process <0.2999.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:04.552 [error] <0.3004.0> gen_server <0.3004.0> terminated with reason: killed
2016-04-10 22:41:04.552 [error] <0.3004.0> CRASH REPORT Process <0.3004.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:04.552 [error] <0.2931.0> CRASH REPORT Process <0.2931.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:05.091 [error] <0.6379.0> gen_server <0.6379.0> terminated with reason: killed
2016-04-10 22:41:05.091 [error] <0.6379.0> CRASH REPORT Process <0.6379.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:05.091 [error] <0.6349.0> gen_server <0.6349.0> terminated with reason: killed
2016-04-10 22:41:05.092 [error] <0.6349.0> CRASH REPORT Process <0.6349.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:05.092 [error] <0.6395.0> gen_server <0.6395.0> terminated with reason: killed
2016-04-10 22:41:05.092 [error] <0.6395.0> CRASH REPORT Process <0.6395.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:05.092 [error] <0.6283.0> CRASH REPORT Process <0.6283.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:05.113 [error] <0.182.0> CRASH REPORT Process <0.182.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:06.011 [error] <0.371.0> gen_server <0.371.0> terminated with reason: killed
2016-04-10 22:41:06.011 [error] <0.371.0> CRASH REPORT Process <0.371.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:06.011 [error] <0.361.0> gen_server <0.361.0> terminated with reason: killed
2016-04-10 22:41:06.012 [error] <0.361.0> CRASH REPORT Process <0.361.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:06.013 [error] <0.287.0> CRASH REPORT Process <0.287.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:08.120 [error] <0.6510.0> gen_server <0.6510.0> terminated with reason: killed
2016-04-10 22:41:08.120 [error] <0.6510.0> CRASH REPORT Process <0.6510.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.120 [error] <0.6480.0> gen_server <0.6480.0> terminated with reason: killed
2016-04-10 22:41:08.120 [error] <0.6480.0> CRASH REPORT Process <0.6480.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.120 [error] <0.6405.0> CRASH REPORT Process <0.6405.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:08.142 [error] <0.3219.0> gen_server <0.3219.0> terminated with reason: killed
2016-04-10 22:41:08.142 [error] <0.3219.0> CRASH REPORT Process <0.3219.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.142 [error] <0.3118.0> CRASH REPORT Process <0.3118.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:08.762 [error] <0.575.0> gen_server <0.575.0> terminated with reason: killed
2016-04-10 22:41:08.762 [error] <0.575.0> CRASH REPORT Process <0.575.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.762 [error] <0.567.0> gen_server <0.567.0> terminated with reason: killed
2016-04-10 22:41:08.762 [error] <0.567.0> CRASH REPORT Process <0.567.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.762 [error] <0.492.0> CRASH REPORT Process <0.492.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:08.855 [error] <0.6620.0> gen_server <0.6620.0> terminated with reason: killed
2016-04-10 22:41:08.855 [error] <0.6620.0> CRASH REPORT Process <0.6620.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.856 [error] <0.6615.0> gen_server <0.6615.0> terminated with reason: killed
2016-04-10 22:41:08.856 [error] <0.6615.0> CRASH REPORT Process <0.6615.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.856 [error] <0.6567.0> gen_server <0.6567.0> terminated with reason: killed
2016-04-10 22:41:08.856 [error] <0.6567.0> CRASH REPORT Process <0.6567.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:08.856 [error] <0.6520.0> CRASH REPORT Process <0.6520.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:08.876 [error] <0.3327.0> gen_server <0.3327.0> terminated with reason: killed
2016-04-10 22:41:08.876 [error] <0.3327.0> CRASH REPORT Process <0.3327.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:09.753 [error] <0.3415.0> gen_server <0.3415.0> terminated with reason: killed
2016-04-10 22:41:09.753 [error] <0.3422.0> gen_server <0.3422.0> terminated with reason: killed
2016-04-10 22:41:09.753 [error] <0.3415.0> CRASH REPORT Process <0.3415.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:09.753 [error] <0.3422.0> CRASH REPORT Process <0.3422.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:09.753 [error] <0.3339.0> CRASH REPORT Process <0.3339.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:10.931 [error] <0.3515.0> CRASH REPORT Process <0.3515.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:10.931 [error] <0.6628.0> CRASH REPORT Process <0.6628.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:10.932 [error] <0.697.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.717.0> exit with reason killed in context child_terminated
2016-04-10 22:41:10.932 [error] <0.697.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.717.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:10.933 [error] <0.697.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.719.0> exit with reason killed in context shutdown_error
2016-04-10 22:41:10.933 [error] <0.695.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.697.0> exit with reason killed in context child_terminated
2016-04-10 22:41:10.933 [error] <0.695.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.697.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:10.933 [error] <0.698.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:41:10.933 [error] <0.699.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:41:10.933 [error] <0.699.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:10.934 [error] <0.698.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:11.051 [error] <0.3652.0> gen_server <0.3652.0> terminated with reason: killed
2016-04-10 22:41:11.051 [error] <0.3652.0> CRASH REPORT Process <0.3652.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:11.051 [error] <0.3593.0> CRASH REPORT Process <0.3593.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:12.482 [error] <0.7043.0> gen_server <0.7043.0> terminated with reason: killed
2016-04-10 22:41:12.483 [error] <0.7043.0> CRASH REPORT Process <0.7043.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:12.482 [error] <0.3964.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3971.0> exit with reason killed in context child_terminated
2016-04-10 22:41:12.483 [error] <0.6969.0> CRASH REPORT Process <0.6969.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:12.483 [error] <0.3964.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3971.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:12.486 [error] <0.3966.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:41:12.486 [error] <0.3966.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:12.486 [error] <0.3965.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:41:12.486 [error] <0.3965.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:12.948 [error] <0.7142.0> gen_server <0.7142.0> terminated with reason: killed
2016-04-10 22:41:12.948 [error] <0.848.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.868.0> exit with reason killed in context child_terminated
2016-04-10 22:41:12.948 [error] <0.7142.0> CRASH REPORT Process <0.7142.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:12.948 [error] <0.848.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.868.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:12.949 [error] <0.846.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.848.0> exit with reason shutdown in context child_terminated
2016-04-10 22:41:12.949 [error] <0.846.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.848.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:41:13.026 [error] <0.1007.0> gen_server <0.1007.0> terminated with reason: killed
2016-04-10 22:41:13.026 [error] <0.4144.0> CRASH REPORT Process <0.4144.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:13.026 [error] <0.1007.0> CRASH REPORT Process <0.1007.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:13.030 [error] <0.7181.0> CRASH REPORT Process <0.7181.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:13.026 [error] <0.1017.0> gen_server <0.1017.0> terminated with reason: killed
2016-04-10 22:41:13.027 [error] <0.1017.0> CRASH REPORT Process <0.1017.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:13.027 [error] <0.1002.0> gen_server <0.1002.0> terminated with reason: killed
2016-04-10 22:41:13.027 [error] <0.1002.0> CRASH REPORT Process <0.1002.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:13.027 [error] <0.949.0> CRASH REPORT Process <0.949.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:23.105 [error] <0.7275.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 22:41:23.105 [error] <0.7278.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:41:23.105 [error] <0.7281.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:41:23.105 [error] <0.7281.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:23.105 [error] <0.7301.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:41:23.105 [error] <0.7301.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:23.105 [error] <0.7279.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:41:23.105 [error] <0.7279.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:23.105 [error] <0.7273.0> CRASH REPORT Process <0.7273.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-10 22:41:23.106 [error] <0.7278.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:23.205 [error] <0.1027.0> CRASH REPORT Process <0.1027.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:41:23.205 [error] <0.4274.0> gen_server <0.4274.0> terminated with reason: killed
2016-04-10 22:41:23.205 [error] <0.4274.0> CRASH REPORT Process <0.4274.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-10 22:41:23.206 [error] <0.4221.0> CRASH REPORT Process <0.4221.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
