2016-04-12 08:45:36.469 [error] <0.554.0> CRASH REPORT Process <0.554.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:37.549 [error] <0.156.0> gen_server <0.156.0> terminated with reason: killed
2016-04-12 08:45:37.550 [error] <0.730.0> gen_server <0.730.0> terminated with reason: killed
2016-04-12 08:45:37.550 [error] <0.156.0> CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:37.550 [error] <0.730.0> CRASH REPORT Process <0.730.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:37.550 [error] <0.91.0> CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:37.550 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:38.100 [error] <0.794.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'...

2016-04-12 08:45:38.100 [error] <0.795.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.798.0> exit with reason killed in context child_terminated
2016-04-12 08:45:38.100 [error] <0.795.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.798.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:38.102 [error] <0.793.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.795.0> exit with reason shutdown in context child_terminated
2016-04-12 08:45:38.103 [error] <0.793.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.795.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:39.885 [error] <0.541.0> CRASH REPORT Process <0.541.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:40.374 [error] <0.1488.0> CRASH REPORT Process <0.1488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:40.373 [error] <0.760.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.779.0> exit with reason killed in context child_terminated
2016-04-12 08:45:40.373 [error] <0.760.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.779.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:40.374 [error] <0.761.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:45:40.374 [error] <0.761.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:40.374 [error] <0.764.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:45:40.374 [error] <0.764.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:40.374 [error] <0.758.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.760.0> exit with reason killed in context child_terminated
2016-04-12 08:45:40.374 [error] <0.758.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.760.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:40.374 [error] <0.762.0> gen_server mnesia2_subscr terminated with reason: {aborted,{node_not_running,'d1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'}} in mnesia2:abort/1 line 313
2016-04-12 08:45:40.374 [error] <0.762.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: {aborted,{node_not_running,'d1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'}} in gen_server:terminate/7 line 814
2016-04-12 08:45:41.604 [error] <0.1845.0> CRASH REPORT Process <0.1845.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:41.604 [error] <0.1127.0> gen_server <0.1127.0> terminated with reason: killed
2016-04-12 08:45:41.604 [error] <0.1127.0> CRASH REPORT Process <0.1127.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:41.604 [error] <0.1063.0> CRASH REPORT Process <0.1063.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:42.465 [error] <0.2175.0> gen_server <0.2175.0> terminated with reason: killed
2016-04-12 08:45:42.466 [error] <0.1327.0> gen_server <0.1327.0> terminated with reason: killed
2016-04-12 08:45:42.465 [error] <0.2175.0> CRASH REPORT Process <0.2175.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:42.466 [error] <0.1327.0> CRASH REPORT Process <0.1327.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:42.466 [error] <0.2110.0> CRASH REPORT Process <0.2110.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:42.466 [error] <0.1264.0> CRASH REPORT Process <0.1264.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:43.339 [error] <0.2315.0> gen_server <0.2315.0> terminated with reason: killed
2016-04-12 08:45:43.338 [error] <0.1433.0> gen_server <0.1433.0> terminated with reason: killed
2016-04-12 08:45:43.339 [error] <0.2315.0> CRASH REPORT Process <0.2315.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:43.338 [error] <0.1433.0> CRASH REPORT Process <0.1433.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:43.340 [error] <0.2250.0> CRASH REPORT Process <0.2250.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:43.338 [error] <0.1370.0> CRASH REPORT Process <0.1370.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:43.842 [error] <0.1459.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1461.0> exit with reason killed in context child_terminated
2016-04-12 08:45:43.844 [error] <0.2381.0> CRASH REPORT Process <0.2381.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:43.843 [error] <0.1459.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1461.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:43.843 [error] <0.1460.0> Mnesia2('d1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.1463.0>,killed}

2016-04-12 08:45:43.843 [error] <0.1462.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:45:44.080 [error] <0.1633.0> gen_server <0.1633.0> terminated with reason: killed
2016-04-12 08:45:44.081 [error] <0.2580.0> gen_server <0.2580.0> terminated with reason: killed
2016-04-12 08:45:44.081 [error] <0.2580.0> CRASH REPORT Process <0.2580.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:44.080 [error] <0.1633.0> CRASH REPORT Process <0.1633.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:44.081 [error] <0.2515.0> CRASH REPORT Process <0.2515.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:44.081 [error] <0.1570.0> CRASH REPORT Process <0.1570.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:44.228 [error] <0.1718.0> gen_server <0.1718.0> terminated with reason: killed
2016-04-12 08:45:44.228 [error] <0.1718.0> CRASH REPORT Process <0.1718.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:44.464 [error] <0.2638.0> CRASH REPORT Process <0.2638.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:47.038 [error] <0.2970.0> CRASH REPORT Process <0.2970.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:51.263 [error] <0.3244.0> CRASH REPORT Process <0.3244.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:53.318 [error] <0.3369.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3383.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3390.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3388.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_24,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3392.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3394.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3393.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_28,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:45:53.318 [error] <0.3397.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

2016-04-12 08:46:03.517 [error] <0.3752.0> CRASH REPORT Process <0.3752.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:06.580 [error] <0.3818.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3820.0> exit with reason killed in context child_terminated
2016-04-12 08:46:06.581 [error] <0.3818.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3820.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:46:06.581 [error] <0.3821.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:46:06.581 [error] <0.3821.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:46:06.581 [error] <0.3816.0> CRASH REPORT Process <0.3816.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:22.780 [error] <0.3948.0> CRASH REPORT Process <0.3948.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:30.924 [error] <0.4478.0> CRASH REPORT Process <0.4478.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:36.292 [error] <0.4694.0> CRASH REPORT Process <0.4694.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:38.383 [error] <0.4761.0> CRASH REPORT Process <0.4761.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:41.543 [error] <0.1845.0> gen_server <0.1845.0> terminated with reason: killed
2016-04-12 08:46:41.543 [error] <0.1845.0> CRASH REPORT Process <0.1845.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:46:41.544 [error] <0.1784.0> CRASH REPORT Process <0.1784.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:45.224 [error] <0.4925.0> gen_server <0.4925.0> terminated with reason: killed
2016-04-12 08:46:45.224 [error] <0.4925.0> CRASH REPORT Process <0.4925.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:46:45.224 [error] <0.4853.0> CRASH REPORT Process <0.4853.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:46.289 [error] <0.1852.0> CRASH REPORT Process <0.1852.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:47.836 [error] <0.4959.0> CRASH REPORT Process <0.4959.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:47.838 [error] <0.1937.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1957.0> exit with reason killed in context child_terminated
2016-04-12 08:46:47.838 [error] <0.1937.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1957.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:46:47.839 [error] <0.1937.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.1959.0> exit with reason killed in context shutdown_error
2016-04-12 08:46:47.840 [error] <0.1997.0> gen_server <0.1997.0> terminated with reason: killed
2016-04-12 08:46:47.840 [error] <0.1997.0> CRASH REPORT Process <0.1997.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:46:47.840 [error] <0.1933.0> CRASH REPORT Process <0.1933.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:08.553 [error] <0.2195.0> gen_server <0.2195.0> terminated with reason: killed
2016-04-12 08:47:08.553 [error] <0.2195.0> CRASH REPORT Process <0.2195.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:08.554 [error] <0.2132.0> CRASH REPORT Process <0.2132.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:08.575 [error] <0.5290.0> CRASH REPORT Process <0.5290.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:10.613 [error] <0.5458.0> gen_server <0.5458.0> terminated with reason: killed
2016-04-12 08:47:10.613 [error] <0.5458.0> CRASH REPORT Process <0.5458.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:10.615 [error] <0.5378.0> CRASH REPORT Process <0.5378.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:11.747 [error] <0.2220.0> CRASH REPORT Process <0.2220.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:16.566 [error] <0.5574.0> gen_server <0.5574.0> terminated with reason: killed
2016-04-12 08:47:16.565 [error] <0.2323.0> CRASH REPORT Process <0.2323.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:16.566 [error] <0.5574.0> CRASH REPORT Process <0.5574.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:16.567 [error] <0.5501.0> CRASH REPORT Process <0.5501.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:18.720 [error] <0.2418.0> gen_server <0.2418.0> terminated with reason: killed
2016-04-12 08:47:18.720 [error] <0.5685.0> gen_server <0.5685.0> terminated with reason: killed
2016-04-12 08:47:18.720 [error] <0.2418.0> CRASH REPORT Process <0.2418.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:18.720 [error] <0.5685.0> CRASH REPORT Process <0.5685.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:18.720 [error] <0.2398.0> CRASH REPORT Process <0.2398.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:18.722 [error] <0.5612.0> CRASH REPORT Process <0.5612.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:20.833 [error] <0.5696.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.5718.0> exit with reason killed in context child_terminated
2016-04-12 08:47:20.833 [error] <0.5696.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.5718.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:47:20.836 [error] <0.5743.0> gen_server <0.5743.0> terminated with reason: killed
2016-04-12 08:47:20.836 [error] <0.5743.0> CRASH REPORT Process <0.5743.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:20.837 [error] <0.5692.0> CRASH REPORT Process <0.5692.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:22.307 [error] <0.2457.0> CRASH REPORT Process <0.2457.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:23.830 [error] <0.5871.0> gen_server <0.5871.0> terminated with reason: killed
2016-04-12 08:47:23.832 [error] <0.2604.0> gen_server <0.2604.0> terminated with reason: killed
2016-04-12 08:47:23.830 [error] <0.5871.0> CRASH REPORT Process <0.5871.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:23.832 [error] <0.2604.0> CRASH REPORT Process <0.2604.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:23.832 [error] <0.2565.0> gen_server <0.2565.0> terminated with reason: killed
2016-04-12 08:47:23.830 [error] <0.5880.0> gen_server <0.5880.0> terminated with reason: killed
2016-04-12 08:47:23.832 [error] <0.2565.0> CRASH REPORT Process <0.2565.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:23.831 [error] <0.5880.0> CRASH REPORT Process <0.5880.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:23.833 [error] <0.2544.0> CRASH REPORT Process <0.2544.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:23.831 [error] <0.5817.0> CRASH REPORT Process <0.5817.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:26.015 [error] <0.5917.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:47:26.011 [error] <0.2645.0> gen_server <0.2645.0> terminated with reason: killed
2016-04-12 08:47:26.015 [error] <0.5917.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:26.011 [error] <0.2645.0> CRASH REPORT Process <0.2645.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:26.015 [error] <0.5915.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.5918.0>,killed}

2016-04-12 08:47:26.012 [error] <0.2625.0> CRASH REPORT Process <0.2625.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:26.015 [error] <0.5915.0> CRASH REPORT Process mnesia2_event with 0 neighbours exited with reason: killed in gen_event:terminate_server/4 line 315
2016-04-12 08:47:26.017 [error] <0.5912.0> CRASH REPORT Process <0.5912.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:28.152 [error] <0.6006.0> CRASH REPORT Process <0.6006.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:28.152 [error] <0.2695.0> CRASH REPORT Process <0.2695.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:30.355 [error] <0.2770.0> CRASH REPORT Process <0.2770.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:31.396 [error] <0.6092.0> CRASH REPORT Process <0.6092.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:38.493 [error] <0.2916.0> gen_server <0.2916.0> terminated with reason: killed
2016-04-12 08:47:38.504 [error] <0.6218.0> gen_server <0.6218.0> terminated with reason: killed
2016-04-12 08:47:38.494 [error] <0.2916.0> CRASH REPORT Process <0.2916.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:38.504 [error] <0.6218.0> CRASH REPORT Process <0.6218.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:38.494 [error] <0.2840.0> CRASH REPORT Process <0.2840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:38.506 [error] <0.6170.0> CRASH REPORT Process <0.6170.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:39.846 [error] <0.3011.0> gen_server <0.3011.0> terminated with reason: killed
2016-04-12 08:47:39.846 [error] <0.3011.0> CRASH REPORT Process <0.3011.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:39.846 [error] <0.2987.0> gen_server <0.2987.0> terminated with reason: killed
2016-04-12 08:47:39.846 [error] <0.2987.0> CRASH REPORT Process <0.2987.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:39.847 [error] <0.2939.0> CRASH REPORT Process <0.2939.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:39.927 [error] <0.6353.0> gen_server <0.6353.0> terminated with reason: killed
2016-04-12 08:47:39.927 [error] <0.6353.0> CRASH REPORT Process <0.6353.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:39.928 [error] <0.6392.0> gen_server <0.6392.0> terminated with reason: killed
2016-04-12 08:47:39.928 [error] <0.6392.0> CRASH REPORT Process <0.6392.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:39.929 [error] <0.6280.0> CRASH REPORT Process <0.6280.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:39.950 [error] <0.181.0> CRASH REPORT Process <0.181.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:40.891 [error] <0.368.0> gen_server <0.368.0> terminated with reason: killed
2016-04-12 08:47:40.891 [error] <0.368.0> CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:40.891 [error] <0.356.0> gen_server <0.356.0> terminated with reason: killed
2016-04-12 08:47:40.892 [error] <0.356.0> CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:40.894 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:43.036 [error] <0.6512.0> gen_server <0.6512.0> terminated with reason: killed
2016-04-12 08:47:43.037 [error] <0.6512.0> CRASH REPORT Process <0.6512.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:43.037 [error] <0.6481.0> gen_server <0.6481.0> terminated with reason: killed
2016-04-12 08:47:43.037 [error] <0.6481.0> CRASH REPORT Process <0.6481.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:43.057 [error] <0.3129.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3149.0> exit with reason killed in context child_terminated
2016-04-12 08:47:43.037 [error] <0.6402.0> CRASH REPORT Process <0.6402.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:43.057 [error] <0.3129.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3149.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:47:43.058 [error] <0.3226.0> gen_server <0.3226.0> terminated with reason: killed
2016-04-12 08:47:43.058 [error] <0.3226.0> CRASH REPORT Process <0.3226.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:43.058 [error] <0.3125.0> CRASH REPORT Process <0.3125.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:44.007 [error] <0.571.0> gen_server <0.571.0> terminated with reason: killed
2016-04-12 08:47:44.007 [error] <0.571.0> CRASH REPORT Process <0.571.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:44.008 [error] <0.565.0> gen_server <0.565.0> terminated with reason: killed
2016-04-12 08:47:44.008 [error] <0.565.0> CRASH REPORT Process <0.565.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:44.008 [error] <0.489.0> CRASH REPORT Process <0.489.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:44.160 [error] <0.6617.0> gen_server <0.6617.0> terminated with reason: killed
2016-04-12 08:47:44.160 [error] <0.6617.0> CRASH REPORT Process <0.6617.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:44.164 [error] <0.6520.0> CRASH REPORT Process <0.6520.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:44.180 [error] <0.3335.0> gen_server <0.3335.0> terminated with reason: killed
2016-04-12 08:47:44.180 [error] <0.3335.0> CRASH REPORT Process <0.3335.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:44.181 [error] <0.3238.0> CRASH REPORT Process <0.3238.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:45.164 [error] <0.3347.0> CRASH REPORT Process <0.3347.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:45.248 [error] <0.3478.0> gen_server <0.3478.0> terminated with reason: killed
2016-04-12 08:47:45.248 [error] <0.3478.0> CRASH REPORT Process <0.3478.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:45.248 [error] <0.3465.0> gen_server <0.3465.0> terminated with reason: killed
2016-04-12 08:47:45.248 [error] <0.3465.0> CRASH REPORT Process <0.3465.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:45.249 [error] <0.3508.0> gen_server <0.3508.0> terminated with reason: killed
2016-04-12 08:47:45.249 [error] <0.3508.0> CRASH REPORT Process <0.3508.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:45.249 [error] <0.3443.0> CRASH REPORT Process <0.3443.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:46.377 [error] <0.3543.0> gen_server <0.3543.0> terminated with reason: killed
2016-04-12 08:47:46.376 [error] <0.6754.0> gen_server <0.6754.0> terminated with reason: killed
2016-04-12 08:47:46.379 [error] <0.692.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.712.0> exit with reason killed in context child_terminated
2016-04-12 08:47:46.377 [error] <0.3543.0> CRASH REPORT Process <0.3543.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:46.376 [error] <0.6754.0> CRASH REPORT Process <0.6754.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:46.380 [error] <0.692.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.712.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:47:46.377 [error] <0.6632.0> CRASH REPORT Process <0.6632.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:46.379 [error] <0.3521.0> CRASH REPORT Process <0.3521.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:46.380 [error] <0.820.0> gen_server <0.820.0> terminated with reason: killed
2016-04-12 08:47:46.380 [error] <0.820.0> CRASH REPORT Process <0.820.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:46.380 [error] <0.812.0> gen_server <0.812.0> terminated with reason: killed
2016-04-12 08:47:46.380 [error] <0.812.0> CRASH REPORT Process <0.812.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:46.380 [error] <0.771.0> gen_server <0.771.0> terminated with reason: killed
2016-04-12 08:47:46.380 [error] <0.771.0> CRASH REPORT Process <0.771.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:46.381 [error] <0.688.0> CRASH REPORT Process <0.688.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:47.017 [error] <0.3856.0> gen_server <0.3856.0> terminated with reason: killed
2016-04-12 08:47:47.017 [error] <0.3856.0> CRASH REPORT Process <0.3856.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:47.018 [error] <0.3785.0> CRASH REPORT Process <0.3785.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:47.708 [error] <0.3949.0> gen_server <0.3949.0> terminated with reason: killed
2016-04-12 08:47:47.708 [error] <0.3949.0> CRASH REPORT Process <0.3949.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:48.652 [error] <0.7048.0> gen_server <0.7048.0> terminated with reason: killed
2016-04-12 08:47:48.653 [error] <0.4024.0> gen_server <0.4024.0> terminated with reason: killed
2016-04-12 08:47:48.652 [error] <0.7048.0> CRASH REPORT Process <0.7048.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:48.653 [error] <0.4024.0> CRASH REPORT Process <0.4024.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:48.655 [error] <0.6975.0> CRASH REPORT Process <0.6975.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:48.654 [error] <0.3967.0> CRASH REPORT Process <0.3967.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:50.302 [error] <0.7149.0> gen_server <0.7149.0> terminated with reason: killed
2016-04-12 08:47:50.300 [error] <0.903.0> gen_server <0.903.0> terminated with reason: killed
2016-04-12 08:47:50.303 [error] <0.4131.0> gen_server <0.4131.0> terminated with reason: killed
2016-04-12 08:47:50.302 [error] <0.7149.0> CRASH REPORT Process <0.7149.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.300 [error] <0.903.0> CRASH REPORT Process <0.903.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.304 [error] <0.4131.0> CRASH REPORT Process <0.4131.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.301 [error] <0.839.0> CRASH REPORT Process <0.839.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:50.302 [error] <0.7076.0> CRASH REPORT Process <0.7076.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:50.304 [error] <0.4059.0> CRASH REPORT Process <0.4059.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:50.427 [error] <0.1000.0> gen_server <0.1000.0> terminated with reason: killed
2016-04-12 08:47:50.427 [error] <0.1000.0> CRASH REPORT Process <0.1000.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.428 [error] <0.4216.0> gen_server <0.4216.0> terminated with reason: killed
2016-04-12 08:47:50.427 [error] <0.1009.0> gen_server <0.1009.0> terminated with reason: killed
2016-04-12 08:47:50.440 [error] <0.7264.0> gen_server <0.7264.0> terminated with reason: killed
2016-04-12 08:47:50.428 [error] <0.4216.0> CRASH REPORT Process <0.4216.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.427 [error] <0.1009.0> CRASH REPORT Process <0.1009.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.440 [error] <0.7264.0> CRASH REPORT Process <0.7264.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.428 [error] <0.995.0> gen_server <0.995.0> terminated with reason: killed
2016-04-12 08:47:50.440 [error] <0.7259.0> gen_server <0.7259.0> terminated with reason: killed
2016-04-12 08:47:50.428 [error] <0.995.0> CRASH REPORT Process <0.995.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.441 [error] <0.7259.0> CRASH REPORT Process <0.7259.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:50.429 [error] <0.942.0> CRASH REPORT Process <0.942.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:50.441 [error] <0.7188.0> CRASH REPORT Process <0.7188.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:50.537 [error] <0.7283.0> Mnesia2('test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'): ** ERROR ** (core dumped to file: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14.2016-04-12_08.45.13/Mnesia2Core.test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14_1460_450870_536736")
 ** FATAL ** Failed to merge schema: Bad cookie in table definition tab1: 'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14' = {cstruct,tab1,set,['d1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14','d1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'],['test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'],[],0,read_write,false,[],[],false,tab1,[key,val],[],[],[],{{1460450870282104696,-576460752303402878,1},'test7080@testing-worker-linux-docker-0c73b48b-3366-linux-14'},{{2,0},[]}}, 'd1336336o1336360n1336360@testing-worker-linux-docker-0c73b48b-3366-linux-14' = {cstruct,tab1,set,['d1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'],[],[],0,read_write,false,[],[],false,tab1,[key,val],[],[],[],{{1460450870476728941,-576460752303421247,1},'d1336366o1336338n1336338@testing-worker-linux-docker-0c73b48b-3366-linux-14'},{{2,0},[]}}


2016-04-12 08:48:00.538 [error] <0.7282.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-12 08:48:00.538 [error] <0.7285.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:48:00.538 [error] <0.7288.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:48:00.538 [error] <0.7288.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.538 [error] <0.7308.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-12 08:48:00.538 [error] <0.7308.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.538 [error] <0.7286.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:48:00.538 [error] <0.7286.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.538 [error] <0.7280.0> CRASH REPORT Process <0.7280.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
2016-04-12 08:48:00.539 [error] <0.7285.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.664 [error] <0.1077.0> gen_server <0.1077.0> terminated with reason: killed
2016-04-12 08:48:00.664 [error] <0.4283.0> gen_server <0.4283.0> terminated with reason: killed
2016-04-12 08:48:00.664 [error] <0.1077.0> CRASH REPORT Process <0.1077.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.664 [error] <0.4283.0> CRASH REPORT Process <0.4283.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.665 [error] <0.4230.0> CRASH REPORT Process <0.4230.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:48:00.664 [error] <0.1072.0> gen_server <0.1072.0> terminated with reason: killed
2016-04-12 08:48:00.665 [error] <0.1072.0> CRASH REPORT Process <0.1072.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:48:00.665 [error] <0.1019.0> CRASH REPORT Process <0.1019.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
