2016-04-12 08:51:14.935 [info] <0.7.0> Application lager started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:14.935 [info] <0.7.0> Application poolgirl started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:14.968 [info] <0.494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.494.0>
2016-04-12 08:51:14.989 [info] <0.562.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.562.0>
2016-04-12 08:51:15.377 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:15.377 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:15.468 [info] <0.672.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.672.0>
2016-04-12 08:51:15.470 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:15.708 [info] <0.7.0> Application lager started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:15.708 [info] <0.7.0> Application poolgirl started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:15.777 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.99.0>
2016-04-12 08:51:16.358 [error] <0.98.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:51:16.358 [error] <0.98.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:16.362 [error] <0.729.0> gen_server <0.729.0> terminated with reason: killed
2016-04-12 08:51:16.359 [error] <0.92.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.94.0> exit with reason killed in context child_terminated
2016-04-12 08:51:16.362 [error] <0.729.0> CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:16.363 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:16.359 [error] <0.92.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.94.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:51:16.359 [error] <0.96.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:51:16.359 [error] <0.96.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:16.359 [error] <0.95.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:51:16.364 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:16.425 [info] <0.800.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.800.0>
2016-04-12 08:51:16.427 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:16.675 [error] <0.794.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'...

2016-04-12 08:51:16.675 [error] <0.795.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.798.0> exit with reason killed in context child_terminated
2016-04-12 08:51:16.675 [error] <0.795.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.798.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:51:16.360 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-12 08:51:16.430 [info] <0.215.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.215.0>
2016-04-12 08:51:16.706 [info] <0.928.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.928.0>
2016-04-12 08:51:16.798 [info] <0.1028.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1028.0>
2016-04-12 08:51:16.713 [info] <0.368.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.368.0>
2016-04-12 08:51:16.805 [info] <0.459.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.459.0>
2016-04-12 08:51:17.536 [warning] <0.6.0> lager_error_logger_h dropped 51 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:17.536 [error] <0.518.0> gen_server <0.518.0> terminated with reason: killed
2016-04-12 08:51:17.536 [error] <0.518.0> CRASH REPORT Process <0.518.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:17.540 [warning] <0.6.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:17.540 [error] <0.1019.0> CRASH REPORT Process <0.1019.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:17.537 [error] <0.450.0> CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:17.537 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:17.597 [info] <0.548.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.548.0>
2016-04-12 08:51:17.615 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:18.203 [error] <0.661.0> gen_server <0.661.0> terminated with reason: killed
2016-04-12 08:51:17.540 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:17.591 [info] <0.1151.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1151.0>
2016-04-12 08:51:17.595 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:17.715 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:51:17.726 [info] <0.1263.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1263.0>
2016-04-12 08:51:18.205 [error] <0.1321.0> gen_server <0.1321.0> terminated with reason: killed
2016-04-12 08:51:18.203 [error] <0.661.0> CRASH REPORT Process <0.661.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:18.205 [error] <0.1321.0> CRASH REPORT Process <0.1321.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:18.203 [error] <0.539.0> CRASH REPORT Process <0.539.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:18.205 [error] <0.1254.0> CRASH REPORT Process <0.1254.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:18.205 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:18.285 [info] <0.1495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1495.0>
2016-04-12 08:51:18.203 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:18.288 [info] <0.762.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.762.0>
2016-04-12 08:51:18.292 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:18.696 [error] <0.815.0> gen_server <0.815.0> terminated with reason: killed
2016-04-12 08:51:18.696 [error] <0.815.0> CRASH REPORT Process <0.815.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:18.590 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:18.705 [error] <0.1490.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1509.0> exit with reason killed in context child_terminated
2016-04-12 08:51:18.697 [error] <0.753.0> CRASH REPORT Process <0.753.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:18.705 [error] <0.1490.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1509.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:51:18.697 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:18.768 [info] <0.862.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.862.0>
2016-04-12 08:51:18.968 [info] <0.963.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.963.0>
2016-04-12 08:51:19.173 [warning] <0.6.0> lager_error_logger_h dropped 18 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:19.173 [error] <0.996.0> gen_server <0.996.0> terminated with reason: killed
2016-04-12 08:51:18.764 [info] <0.1610.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1610.0>
2016-04-12 08:51:18.964 [info] <0.1726.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1726.0>
2016-04-12 08:51:19.174 [warning] <0.6.0> lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:19.174 [error] <0.1782.0> gen_server <0.1782.0> terminated with reason: killed
2016-04-12 08:51:19.173 [error] <0.996.0> CRASH REPORT Process <0.996.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:19.174 [error] <0.1782.0> CRASH REPORT Process <0.1782.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:19.175 [error] <0.1717.0> CRASH REPORT Process <0.1717.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:19.173 [error] <0.954.0> CRASH REPORT Process <0.954.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:19.173 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:19.176 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:19.231 [info] <0.1852.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1852.0>
2016-04-12 08:51:19.233 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:19.397 [error] <0.1847.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1864.0> exit with reason killed in context child_terminated
2016-04-12 08:51:19.236 [info] <0.1069.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1069.0>
2016-04-12 08:51:19.239 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:19.398 [error] <0.1113.0> gen_server <0.1113.0> terminated with reason: killed
2016-04-12 08:51:19.397 [error] <0.1847.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1864.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:51:19.398 [error] <0.1113.0> CRASH REPORT Process <0.1113.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:19.460 [info] <0.1983.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1983.0>
2016-04-12 08:51:19.974 [info] <0.2117.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2117.0>
2016-04-12 08:51:20.205 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:20.205 [error] <0.2173.0> gen_server <0.2173.0> terminated with reason: killed
2016-04-12 08:51:19.462 [info] <0.1168.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1168.0>
2016-04-12 08:51:19.981 [info] <0.1270.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1270.0>
2016-04-12 08:51:20.205 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:20.205 [error] <0.1324.0> gen_server <0.1324.0> terminated with reason: killed
2016-04-12 08:51:20.205 [error] <0.2173.0> CRASH REPORT Process <0.2173.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:20.205 [error] <0.1324.0> CRASH REPORT Process <0.1324.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:20.205 [error] <0.2108.0> CRASH REPORT Process <0.2108.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:20.205 [error] <0.1261.0> CRASH REPORT Process <0.1261.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:20.205 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:20.271 [info] <0.1376.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1376.0>
2016-04-12 08:51:20.276 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:20.497 [error] <0.1371.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1389.0> exit with reason killed in context child_terminated
2016-04-12 08:51:20.497 [error] <0.1371.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.1389.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:51:20.206 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:20.266 [info] <0.2257.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2257.0>
2016-04-12 08:51:20.269 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:20.499 [error] <0.2311.0> gen_server <0.2311.0> terminated with reason: killed
2016-04-12 08:51:20.499 [error] <0.2311.0> CRASH REPORT Process <0.2311.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:20.568 [info] <0.2388.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2388.0>
2016-04-12 08:51:20.795 [info] <0.2520.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2520.0>
2016-04-12 08:51:21.098 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:21.101 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:21.243 [error] <0.2547.0> gen_server <0.2547.0> terminated with reason: killed
2016-04-12 08:51:20.572 [info] <0.1463.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1463.0>
2016-04-12 08:51:20.798 [info] <0.1575.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1575.0>
2016-04-12 08:51:21.243 [warning] <0.6.0> lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:21.243 [error] <0.1566.0> CRASH REPORT Process <0.1566.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:21.243 [error] <0.2547.0> CRASH REPORT Process <0.2547.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:21.244 [error] <0.2511.0> CRASH REPORT Process <0.2511.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:21.244 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:21.314 [info] <0.1663.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1663.0>
2016-04-12 08:51:21.318 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:21.428 [error] <0.1717.0> gen_server <0.1717.0> terminated with reason: killed
2016-04-12 08:51:21.428 [error] <0.1717.0> CRASH REPORT Process <0.1717.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:51:21.428 [error] <0.1654.0> CRASH REPORT Process <0.1654.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:21.244 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:21.288 [info] <0.2644.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2644.0>
2016-04-12 08:51:21.722 [info] <0.2772.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2772.0>
2016-04-12 08:51:21.803 [info] <0.2866.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2866.0>
2016-04-12 08:51:21.428 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:23.070 [info] <0.2976.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2976.0>
2016-04-12 08:51:23.072 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:24.270 [error] <0.2967.0> CRASH REPORT Process <0.2967.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:24.270 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:26.364 [info] <0.3082.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3082.0>
2016-04-12 08:51:26.366 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:26.368 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:51:26.370 [info] <0.3130.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3130.0>
2016-04-12 08:51:26.374 [info] <0.3178.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3178.0>
2016-04-12 08:51:28.468 [info] <0.3250.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3250.0>
2016-04-12 08:51:28.470 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:28.483 [error] <0.3241.0> CRASH REPORT Process <0.3241.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:28.483 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:31.103 [info] <0.3333.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3333.0>
2016-04-12 08:51:31.105 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:31.131 [info] <0.3327.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-12 08:51:31.131 [info] <0.3327.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4.2016-04-12_08.50.47/Mnesia2.test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4/LATEST.LOG"] -> badarg

2016-04-12 08:51:31.132 [info] <0.3409.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_tm_5 terminated: shutdown

2016-04-12 08:51:31.133 [error] <0.3359.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}}} ({error,{already_started,<0.3409.0>}})

2016-04-12 08:51:31.133 [info] <0.3409.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_tm_3 terminated: shutdown

2016-04-12 08:51:31.133 [error] <0.3324.0> CRASH REPORT Process <0.3324.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:31.133 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:33.210 [info] <0.3429.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_monitor starting: <0.3431.0>

2016-04-12 08:51:33.211 [info] <0.3429.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Mnesia2 debug level set to verbose
2016-04-12 08:51:33.212 [info] <0.3435.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3435.0>
2016-04-12 08:51:33.215 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:33.218 [info] <0.3474.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_tm_1 terminated: shutdown

2016-04-12 08:51:33.218 [info] <0.3474.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_tm_3 terminated: shutdown

2016-04-12 08:51:33.218 [info] <0.3475.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_tm_4 terminated: shutdown

2016-04-12 08:51:33.218 [info] <0.3475.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_tm_2 terminated: shutdown

2016-04-12 08:51:33.218 [info] <0.3476.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_tm_9 terminated: shutdown

2016-04-12 08:51:33.218 [info] <0.3476.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_tm_8 terminated: shutdown

2016-04-12 08:51:33.218 [info] <0.3477.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_tm_13 terminated: shutdown

2016-04-12 08:51:35.230 [warning] <0.6.0> lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:35.230 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_monitor starting: <0.3491.0>

2016-04-12 08:51:35.230 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Version: "1.0.0"

2016-04-12 08:51:35.231 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env access_module: mnesia2

2016-04-12 08:51:35.231 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env auto_repair: true

2016-04-12 08:51:35.231 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env backup_module: mnesia2_backup

2016-04-12 08:51:35.231 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env debug: debug

2016-04-12 08:51:35.231 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4.2016-04-12_08.50.47/Mnesia2.test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4"

2016-04-12 08:51:35.231 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dump_disc_copies_at_startup: true

2016-04-12 08:51:35.231 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dump_log_load_regulation: false

2016-04-12 08:51:35.232 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dump_log_time_threshold: 180000

2016-04-12 08:51:35.232 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dump_log_update_in_place: true

2016-04-12 08:51:35.232 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dump_log_write_threshold: 1000

2016-04-12 08:51:35.232 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env event_module: mnesia2_event

2016-04-12 08:51:35.232 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env extra_db_nodes: []

2016-04-12 08:51:35.232 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env ignore_fallback_at_startup: false

2016-04-12 08:51:35.233 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env fallback_error_function: {mnesia2,lkill}

2016-04-12 08:51:35.233 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env max_wait_for_decision: infinity

2016-04-12 08:51:35.233 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env schema_location: opt_disc

2016-04-12 08:51:35.233 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env core_dir: false

2016-04-12 08:51:35.233 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env pid_sort_order: false

2016-04-12 08:51:35.233 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env no_table_loaders: 2

2016-04-12 08:51:35.233 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dc_dump_limit: 4

2016-04-12 08:51:35.233 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env send_compressed: 0

2016-04-12 08:51:35.234 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env send_max_packets: 20

2016-04-12 08:51:35.234 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env send_max_transfer_size: 7500

2016-04-12 08:51:35.234 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env async_dirty_buffer_size: 524288

2016-04-12 08:51:35.234 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-12 08:51:35.234 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-12 08:51:35.234 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env async_dirty_buffer_min_runtime: 10000

2016-04-12 08:51:35.234 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-12 08:51:35.234 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Mnesia2 debug level set to debug
2016-04-12 08:51:35.235 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_subscr starting: <0.3492.0>

2016-04-12 08:51:35.235 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_locker starting: <0.3493.0>

2016-04-12 08:51:35.235 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_recover starting: <0.3494.0>

2016-04-12 08:51:35.235 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_tm starting: <0.3495.0>

2016-04-12 08:51:35.235 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Schema initiated from: default

2016-04-12 08:51:35.235 [info] <0.3495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3495.0>
2016-04-12 08:51:35.235 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
2016-04-12 08:51:35.236 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_controller starting: <0.3498.0>

2016-04-12 08:51:35.236 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_late_loader starting: <0.3499.0>

2016-04-12 08:51:35.237 [info] <0.3489.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Intend to load tables: []

2016-04-12 08:51:37.262 [warning] <0.6.0> lager_error_logger_h dropped 38 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:37.262 [info] <0.3566.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_monitor starting: <0.3568.0>

2016-04-12 08:51:37.264 [info] <0.3572.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3572.0>
2016-04-12 08:51:37.266 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:37.268 [error] <0.3580.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3611.0>}})

2016-04-12 08:51:37.268 [error] <0.3582.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3611.0>}})

2016-04-12 08:51:37.268 [error] <0.3581.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3611.0>}})

2016-04-12 08:51:37.268 [error] <0.3579.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3611.0>}})

2016-04-12 08:51:37.268 [error] <0.3584.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3611.0>}})

2016-04-12 08:51:39.289 [warning] <0.6.0> lager_error_logger_h dropped 26 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:39.289 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_monitor starting: <0.3649.0>

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Version: "1.0.0"

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env access_module: mnesia2

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env auto_repair: true

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env backup_module: mnesia2_backup

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env debug: debug

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4.2016-04-12_08.50.47/Mnesia2.test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4"

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dump_disc_copies_at_startup: true

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dump_log_load_regulation: false

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dump_log_time_threshold: 180000

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dump_log_update_in_place: true

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dump_log_write_threshold: 1000

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env event_module: mnesia2_event

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env extra_db_nodes: []

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env ignore_fallback_at_startup: false

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env fallback_error_function: {mnesia2,lkill}

2016-04-12 08:51:39.290 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env max_wait_for_decision: infinity

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env schema_location: opt_disc

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env core_dir: false

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env pid_sort_order: false

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env no_table_loaders: 2

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env dc_dump_limit: 4

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env send_compressed: 0

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env send_max_packets: 20

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env send_max_transfer_size: 7500

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env async_dirty_buffer_size: 524288

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env async_dirty_buffer_min_runtime: 10000

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Mnesia2 debug level set to debug
2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_subscr starting: <0.3650.0>

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_locker starting: <0.3651.0>

2016-04-12 08:51:39.291 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_recover starting: <0.3652.0>

2016-04-12 08:51:39.292 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_tm starting: <0.3653.0>

2016-04-12 08:51:39.292 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Schema initiated from: default

2016-04-12 08:51:39.292 [info] <0.3653.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3653.0>
2016-04-12 08:51:39.292 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
2016-04-12 08:51:39.292 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_controller starting: <0.3656.0>

2016-04-12 08:51:39.293 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): mnesia2_late_loader starting: <0.3657.0>

2016-04-12 08:51:39.293 [info] <0.3647.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): Intend to load tables: []

2016-04-12 08:51:41.324 [warning] <0.6.0> lager_error_logger_h dropped 34 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:51:41.326 [info] <0.3730.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3730.0>
2016-04-12 08:51:41.328 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:41.329 [error] <0.3721.0> CRASH REPORT Process <0.3721.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:41.329 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:43.593 [info] <0.3794.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3794.0>
2016-04-12 08:51:43.595 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:43.596 [error] <0.3785.0> CRASH REPORT Process <0.3785.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:51:43.596 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:51:46.996 [info] <0.3865.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3865.0>
2016-04-12 08:51:46.999 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:47.021 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:51:47.044 [info] <0.3926.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3926.0>
2016-04-12 08:51:47.047 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:51:47.847 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:48.235 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:48.291 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:48.671 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:49.046 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:49.446 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:49.827 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:50.212 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:50.594 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:50.781 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:51.182 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:51.562 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:51.949 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:52.143 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:52.538 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:52.924 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:53.302 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:53.686 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:53.794 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:54.189 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:54.582 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:54.983 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:55.584 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:56.255 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:56.703 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:59.209 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:52:01.625 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:52:02.008 [error] <0.3920.0> Mnesia2('test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:52:02.145 [error] <0.3917.0> CRASH REPORT Process <0.3917.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:02.145 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:04.281 [info] <0.4222.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4222.0>
2016-04-12 08:52:04.284 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:10.306 [error] <0.4213.0> CRASH REPORT Process <0.4213.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:10.306 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:14.829 [info] <0.4322.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4322.0>
2016-04-12 08:52:14.832 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:15.900 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:52:18.077 [info] <0.4438.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4438.0>
2016-04-12 08:52:18.082 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:18.096 [error] <0.4429.0> CRASH REPORT Process <0.4429.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:18.097 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:20.347 [info] <0.4505.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4505.0>
2016-04-12 08:52:20.361 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:20.374 [error] <0.4496.0> CRASH REPORT Process <0.4496.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:20.374 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:22.536 [info] <0.4597.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4597.0>
2016-04-12 08:52:22.538 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:22.542 [info] <0.1790.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1790.0>
2016-04-12 08:52:22.545 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:23.565 [error] <0.1842.0> gen_server <0.1842.0> terminated with reason: killed
2016-04-12 08:52:23.565 [error] <0.1842.0> CRASH REPORT Process <0.1842.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:52:23.565 [error] <0.1781.0> CRASH REPORT Process <0.1781.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:23.566 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:28.785 [info] <0.1858.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1858.0>
2016-04-12 08:52:28.806 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:29.808 [error] <0.4660.0> gen_server <0.4660.0> terminated with reason: killed
2016-04-12 08:52:29.808 [error] <0.4660.0> CRASH REPORT Process <0.4660.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:52:29.809 [error] <0.4588.0> CRASH REPORT Process <0.4588.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:29.809 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:30.871 [error] <0.1849.0> CRASH REPORT Process <0.1849.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:30.871 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:31.977 [info] <0.4703.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4703.0>
2016-04-12 08:52:31.980 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:32.029 [error] <0.4694.0> CRASH REPORT Process <0.4694.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:32.021 [info] <0.1940.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1940.0>
2016-04-12 08:52:32.027 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:32.030 [error] <0.1931.0> CRASH REPORT Process <0.1931.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:32.029 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:32.089 [info] <0.4778.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4778.0>
2016-04-12 08:52:32.092 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:32.030 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:36.394 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:52:36.464 [info] <0.4902.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4902.0>
2016-04-12 08:52:36.479 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:36.455 [info] <0.2009.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2009.0>
2016-04-12 08:52:36.456 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:48.435 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:52:48.441 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:52:49.593 [info] <0.2131.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2131.0>
2016-04-12 08:52:49.600 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:49.924 [error] <0.2186.0> gen_server <0.2186.0> terminated with reason: killed
2016-04-12 08:52:49.924 [error] <0.2186.0> CRASH REPORT Process <0.2186.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:52:49.924 [error] <0.2122.0> CRASH REPORT Process <0.2122.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:49.579 [info] <0.5033.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.5033.0>
2016-04-12 08:52:49.883 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:49.947 [error] <0.5024.0> CRASH REPORT Process <0.5024.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:49.924 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:49.947 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:49.992 [info] <0.5122.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.5122.0>
2016-04-12 08:52:52.955 [info] <0.2220.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2220.0>
2016-04-12 08:52:52.965 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:54.734 [warning] <0.6.0> lager_error_logger_h dropped 15 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:52:54.734 [error] <0.5113.0> CRASH REPORT Process <0.5113.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:54.734 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:55.869 [error] <0.2211.0> CRASH REPORT Process <0.2211.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:55.869 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:56.939 [info] <0.2323.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2323.0>
2016-04-12 08:52:56.946 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:56.963 [error] <0.2335.0> gen_server <0.2335.0> terminated with reason: killed
2016-04-12 08:52:56.931 [info] <0.5245.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.5245.0>
2016-04-12 08:52:56.933 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:56.966 [error] <0.5236.0> CRASH REPORT Process <0.5236.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:56.963 [error] <0.2335.0> CRASH REPORT Process <0.2335.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:52:56.963 [error] <0.2314.0> CRASH REPORT Process <0.2314.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:56.966 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:56.963 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:59.731 [info] <0.2398.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2398.0>
2016-04-12 08:52:59.774 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:59.796 [error] <0.2410.0> gen_server <0.2410.0> terminated with reason: killed
2016-04-12 08:52:59.578 [info] <0.5356.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.5356.0>
2016-04-12 08:52:59.581 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:52:59.799 [error] <0.5420.0> gen_server <0.5420.0> terminated with reason: killed
2016-04-12 08:52:59.799 [error] <0.5420.0> CRASH REPORT Process <0.5420.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:52:59.797 [error] <0.2410.0> CRASH REPORT Process <0.2410.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:52:59.799 [error] <0.5347.0> CRASH REPORT Process <0.5347.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:59.797 [error] <0.2389.0> CRASH REPORT Process <0.2389.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:52:59.799 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:52:59.797 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:01.856 [info] <0.5437.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.5437.0>
2016-04-12 08:53:01.869 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:01.926 [error] <0.5497.0> gen_server <0.5497.0> terminated with reason: killed
2016-04-12 08:53:01.926 [error] <0.5497.0> CRASH REPORT Process <0.5497.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:01.927 [error] <0.5427.0> CRASH REPORT Process <0.5427.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:01.841 [info] <0.2457.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2457.0>
2016-04-12 08:53:01.843 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:01.927 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:03.345 [error] <0.2448.0> CRASH REPORT Process <0.2448.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:03.345 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:04.437 [info] <0.5561.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.5561.0>
2016-04-12 08:53:04.440 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:04.856 [error] <0.5614.0> gen_server <0.5614.0> terminated with reason: killed
2016-04-12 08:53:04.444 [info] <0.2544.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2544.0>
2016-04-12 08:53:04.449 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:04.856 [error] <0.2557.0> gen_server <0.2557.0> terminated with reason: killed
2016-04-12 08:53:04.856 [error] <0.5614.0> CRASH REPORT Process <0.5614.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:04.857 [error] <0.2557.0> CRASH REPORT Process <0.2557.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:04.862 [error] <0.5552.0> CRASH REPORT Process <0.5552.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:04.857 [error] <0.2535.0> CRASH REPORT Process <0.2535.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:04.862 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:04.857 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:04.736 [info] <0.7.0> Application lager started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:04.736 [info] <0.7.0> Application poolgirl started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:04.785 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.99.0>
2016-04-12 08:53:04.804 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:06.987 [info] <0.5656.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.5656.0>
2016-04-12 08:53:06.990 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:07.009 [error] <0.5720.0> gen_server <0.5720.0> terminated with reason: killed
2016-04-12 08:53:06.998 [info] <0.2625.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2625.0>
2016-04-12 08:53:07.005 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:07.012 [error] <0.2637.0> gen_server <0.2637.0> terminated with reason: killed
2016-04-12 08:53:07.009 [error] <0.5720.0> CRASH REPORT Process <0.5720.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:07.010 [error] <0.5647.0> CRASH REPORT Process <0.5647.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:07.012 [error] <0.2637.0> CRASH REPORT Process <0.2637.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:07.013 [error] <0.2616.0> CRASH REPORT Process <0.2616.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:07.010 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:07.013 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:09.122 [info] <0.2695.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2695.0>
2016-04-12 08:53:09.127 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:09.145 [error] <0.2707.0> gen_server <0.2707.0> terminated with reason: killed
2016-04-12 08:53:09.117 [info] <0.5750.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.5750.0>
2016-04-12 08:53:09.119 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:09.145 [error] <0.5741.0> CRASH REPORT Process <0.5741.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:09.145 [error] <0.2707.0> CRASH REPORT Process <0.2707.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:09.145 [error] <0.2686.0> CRASH REPORT Process <0.2686.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:09.146 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:09.145 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:11.281 [info] <0.2770.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2770.0>
2016-04-12 08:53:11.295 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:11.577 [error] <0.2823.0> gen_server <0.2823.0> terminated with reason: killed
2016-04-12 08:53:11.577 [error] <0.2823.0> CRASH REPORT Process <0.2823.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:11.579 [error] <0.2761.0> CRASH REPORT Process <0.2761.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:11.266 [info] <0.5836.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.5836.0>
2016-04-12 08:53:11.575 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:11.579 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:12.620 [error] <0.5827.0> CRASH REPORT Process <0.5827.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:12.620 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:15.219 [info] <0.2841.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2841.0>
2016-04-12 08:53:15.220 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:22.064 [info] <0.5915.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.5915.0>
2016-04-12 08:53:22.107 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:22.178 [error] <0.5978.0> gen_server <0.5978.0> terminated with reason: killed
2016-04-12 08:53:22.176 [error] <0.2910.0> gen_server <0.2910.0> terminated with reason: killed
2016-04-12 08:53:22.178 [error] <0.5978.0> CRASH REPORT Process <0.5978.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:22.176 [error] <0.2910.0> CRASH REPORT Process <0.2910.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:22.178 [error] <0.5906.0> CRASH REPORT Process <0.5906.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:22.177 [error] <0.2832.0> CRASH REPORT Process <0.2832.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:22.178 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:22.177 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:23.394 [info] <0.2940.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2940.0>
2016-04-12 08:53:23.414 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:23.553 [error] <0.2931.0> CRASH REPORT Process <0.2931.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:23.370 [info] <0.6025.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.6025.0>
2016-04-12 08:53:23.373 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:23.642 [error] <0.6087.0> gen_server <0.6087.0> terminated with reason: killed
2016-04-12 08:53:23.642 [error] <0.6087.0> CRASH REPORT Process <0.6087.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:23.642 [error] <0.6130.0> gen_server <0.6130.0> terminated with reason: killed
2016-04-12 08:53:23.642 [error] <0.6130.0> CRASH REPORT Process <0.6130.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:23.642 [error] <0.6112.0> gen_server <0.6112.0> terminated with reason: killed
2016-04-12 08:53:23.643 [error] <0.6112.0> CRASH REPORT Process <0.6112.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:23.643 [error] <0.6016.0> CRASH REPORT Process <0.6016.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:23.332 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:53:23.422 [info] <0.189.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.189.0>
2016-04-12 08:53:23.439 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:23.664 [error] <0.180.0> CRASH REPORT Process <0.180.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:23.664 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:23.773 [info] <0.294.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.294.0>
2016-04-12 08:53:23.644 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:23.741 [info] <0.6147.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.6147.0>
2016-04-12 08:53:24.053 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:23.553 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:23.581 [info] <0.3031.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3031.0>
2016-04-12 08:53:23.703 [info] <0.3126.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3126.0>
2016-04-12 08:53:24.566 [warning] <0.6.0> lager_error_logger_h dropped 7 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:53:24.566 [error] <0.333.0> gen_server <0.333.0> terminated with reason: killed
2016-04-12 08:53:24.566 [error] <0.333.0> CRASH REPORT Process <0.333.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:24.567 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:24.567 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:24.592 [info] <0.389.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.389.0>
2016-04-12 08:53:24.594 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:33.221 [error] <0.6245.0> gen_server <0.6245.0> terminated with reason: killed
2016-04-12 08:53:33.246 [warning] <0.6.0> lager_error_logger_h dropped 36 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:53:33.246 [error] <0.3222.0> gen_server <0.3222.0> terminated with reason: killed
2016-04-12 08:53:33.221 [error] <0.6245.0> CRASH REPORT Process <0.6245.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:33.246 [error] <0.3222.0> CRASH REPORT Process <0.3222.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:33.222 [error] <0.6190.0> gen_server <0.6190.0> terminated with reason: killed
2016-04-12 08:53:33.247 [error] <0.3117.0> CRASH REPORT Process <0.3117.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:33.222 [error] <0.6190.0> CRASH REPORT Process <0.6190.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:33.223 [error] <0.6138.0> CRASH REPORT Process <0.6138.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:33.224 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:33.489 [info] <0.6264.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.6264.0>
2016-04-12 08:53:33.813 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:33.247 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:33.495 [info] <0.3241.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3241.0>
2016-04-12 08:53:33.521 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:33.395 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:33.448 [info] <0.495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.495.0>
2016-04-12 08:53:33.450 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:34.329 [error] <0.568.0> gen_server <0.568.0> terminated with reason: killed
2016-04-12 08:53:34.329 [error] <0.568.0> CRASH REPORT Process <0.568.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:34.330 [error] <0.563.0> gen_server <0.563.0> terminated with reason: killed
2016-04-12 08:53:34.330 [error] <0.563.0> CRASH REPORT Process <0.563.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:34.331 [error] <0.486.0> CRASH REPORT Process <0.486.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:34.331 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:34.370 [info] <0.594.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.594.0>
2016-04-12 08:53:34.372 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:34.446 [error] <0.6360.0> gen_server <0.6360.0> terminated with reason: killed
2016-04-12 08:53:34.446 [error] <0.6360.0> CRASH REPORT Process <0.6360.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:34.446 [error] <0.6331.0> gen_server <0.6331.0> terminated with reason: killed
2016-04-12 08:53:34.447 [error] <0.6331.0> CRASH REPORT Process <0.6331.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:34.447 [error] <0.6355.0> gen_server <0.6355.0> terminated with reason: killed
2016-04-12 08:53:34.447 [error] <0.6355.0> CRASH REPORT Process <0.6355.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:34.447 [error] <0.6255.0> CRASH REPORT Process <0.6255.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:34.466 [error] <0.3327.0> gen_server <0.3327.0> terminated with reason: killed
2016-04-12 08:53:34.467 [error] <0.3327.0> CRASH REPORT Process <0.3327.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:34.467 [error] <0.3232.0> CRASH REPORT Process <0.3232.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:34.467 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:34.560 [info] <0.3348.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3348.0>
2016-04-12 08:53:34.578 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:35.401 [error] <0.3339.0> CRASH REPORT Process <0.3339.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:34.447 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:34.553 [info] <0.6377.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.6377.0>
2016-04-12 08:53:34.862 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:35.401 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:35.460 [info] <0.3444.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3444.0>
2016-04-12 08:53:35.472 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:35.486 [error] <0.3500.0> gen_server <0.3500.0> terminated with reason: killed
2016-04-12 08:53:35.487 [error] <0.3500.0> CRASH REPORT Process <0.3500.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:34.491 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:34.519 [info] <0.692.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.692.0>
2016-04-12 08:53:35.487 [error] <0.3492.0> gen_server <0.3492.0> terminated with reason: killed
2016-04-12 08:53:35.487 [error] <0.3492.0> CRASH REPORT Process <0.3492.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:35.487 [error] <0.3457.0> gen_server <0.3457.0> terminated with reason: killed
2016-04-12 08:53:35.487 [error] <0.3457.0> CRASH REPORT Process <0.3457.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:35.488 [error] <0.3435.0> CRASH REPORT Process <0.3435.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:35.488 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:36.511 [info] <0.3522.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3522.0>
2016-04-12 08:53:36.529 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:36.591 [error] <0.3551.0> gen_server <0.3551.0> terminated with reason: killed
2016-04-12 08:53:36.594 [error] <0.6491.0> gen_server <0.6491.0> terminated with reason: killed
2016-04-12 08:53:36.591 [error] <0.3551.0> CRASH REPORT Process <0.3551.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:36.591 [error] <0.816.0> gen_server <0.816.0> terminated with reason: killed
2016-04-12 08:53:36.595 [error] <0.6491.0> CRASH REPORT Process <0.6491.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:36.591 [error] <0.3513.0> CRASH REPORT Process <0.3513.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:36.591 [error] <0.816.0> CRASH REPORT Process <0.816.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:36.595 [error] <0.6368.0> CRASH REPORT Process <0.6368.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:36.591 [error] <0.806.0> gen_server <0.806.0> terminated with reason: killed
2016-04-12 08:53:36.591 [error] <0.806.0> CRASH REPORT Process <0.806.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:36.591 [error] <0.766.0> gen_server <0.766.0> terminated with reason: killed
2016-04-12 08:53:36.592 [error] <0.766.0> CRASH REPORT Process <0.766.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:36.592 [error] <0.683.0> CRASH REPORT Process <0.683.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:36.591 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:36.694 [info] <0.3600.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3600.0>
2016-04-12 08:53:36.800 [info] <0.3695.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3695.0>
2016-04-12 08:53:36.895 [info] <0.3785.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3785.0>
2016-04-12 08:53:36.974 [info] <0.3885.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3885.0>
2016-04-12 08:53:36.595 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:36.668 [info] <0.6523.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.6523.0>
2016-04-12 08:53:36.672 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:36.971 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:37.569 [info] <0.6636.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.6636.0>
2016-04-12 08:53:36.592 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:37.771 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:53:37.772 [error] <0.3940.0> gen_server <0.3940.0> terminated with reason: killed
2016-04-12 08:53:37.772 [error] <0.3940.0> CRASH REPORT Process <0.3940.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:37.772 [error] <0.3876.0> CRASH REPORT Process <0.3876.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:37.623 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:37.770 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:37.941 [info] <0.6719.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.6719.0>
2016-04-12 08:53:38.524 [error] <0.6784.0> gen_server <0.6784.0> terminated with reason: killed
2016-04-12 08:53:37.772 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:38.448 [info] <0.3967.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.3967.0>
2016-04-12 08:53:38.468 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:38.525 [error] <0.3958.0> CRASH REPORT Process <0.3958.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:38.524 [error] <0.6784.0> CRASH REPORT Process <0.6784.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:38.525 [error] <0.6710.0> CRASH REPORT Process <0.6710.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:38.526 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:38.526 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:38.655 [info] <0.4061.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4061.0>
2016-04-12 08:53:38.667 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:38.642 [info] <0.6820.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.6820.0>
2016-04-12 08:53:38.652 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:39.045 [error] <0.6811.0> CRASH REPORT Process <0.6811.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:38.643 [info] <0.843.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.843.0>
2016-04-12 08:53:38.949 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:39.047 [error] <0.907.0> gen_server <0.907.0> terminated with reason: killed
2016-04-12 08:53:39.045 [error] <0.4119.0> gen_server <0.4119.0> terminated with reason: killed
2016-04-12 08:53:39.047 [error] <0.907.0> CRASH REPORT Process <0.907.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:39.045 [error] <0.4119.0> CRASH REPORT Process <0.4119.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:39.047 [error] <0.902.0> gen_server <0.902.0> terminated with reason: killed
2016-04-12 08:53:39.049 [error] <0.4112.0> gen_server <0.4112.0> terminated with reason: killed
2016-04-12 08:53:39.047 [error] <0.902.0> CRASH REPORT Process <0.902.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:39.048 [error] <0.834.0> CRASH REPORT Process <0.834.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:39.049 [error] <0.4112.0> CRASH REPORT Process <0.4112.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:39.049 [error] <0.4050.0> CRASH REPORT Process <0.4050.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:39.048 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:39.071 [info] <0.950.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.950.0>
2016-04-12 08:53:39.073 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:39.193 [error] <0.999.0> gen_server <0.999.0> terminated with reason: killed
2016-04-12 08:53:39.049 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:39.075 [info] <0.4149.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4149.0>
2016-04-12 08:53:39.078 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:39.196 [error] <0.4203.0> gen_server <0.4203.0> terminated with reason: killed
2016-04-12 08:53:39.193 [error] <0.999.0> CRASH REPORT Process <0.999.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:39.045 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:39.112 [info] <0.6931.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.6931.0>
2016-04-12 08:53:39.123 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:39.198 [error] <0.6922.0> CRASH REPORT Process <0.6922.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:39.193 [error] <0.1009.0> gen_server <0.1009.0> terminated with reason: killed
2016-04-12 08:53:39.196 [error] <0.4203.0> CRASH REPORT Process <0.4203.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:39.193 [error] <0.1009.0> CRASH REPORT Process <0.1009.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:39.196 [error] <0.4193.0> gen_server <0.4193.0> terminated with reason: killed
2016-04-12 08:53:39.193 [error] <0.994.0> gen_server <0.994.0> terminated with reason: killed
2016-04-12 08:53:39.196 [error] <0.4193.0> CRASH REPORT Process <0.4193.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:39.193 [error] <0.994.0> CRASH REPORT Process <0.994.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:39.193 [error] <0.941.0> CRASH REPORT Process <0.941.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:39.196 [error] <0.4140.0> CRASH REPORT Process <0.4140.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:39.198 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:39.261 [info] <0.7023.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.7023.0>
2016-04-12 08:53:39.193 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:39.229 [info] <0.1029.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1029.0>
2016-04-12 08:53:39.196 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:39.232 [info] <0.4227.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4227.0>
2016-04-12 08:53:49.286 [error] <0.7016.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-12 08:53:49.286 [error] <0.7019.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:53:49.286 [error] <0.7020.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:53:49.286 [error] <0.7020.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:49.286 [error] <0.7022.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:53:49.286 [error] <0.7022.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:49.286 [error] <0.7042.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-12 08:53:49.286 [error] <0.7042.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:49.286 [error] <0.7014.0> CRASH REPORT Process <0.7014.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-12 08:53:49.287 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-12 08:53:49.287 [error] <0.7019.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:49.374 [error] <0.1078.0> gen_server <0.1078.0> terminated with reason: killed
2016-04-12 08:53:49.374 [error] <0.4271.0> gen_server <0.4271.0> terminated with reason: killed
2016-04-12 08:53:49.374 [error] <0.4271.0> CRASH REPORT Process <0.4271.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:49.374 [error] <0.1078.0> CRASH REPORT Process <0.1078.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:49.375 [error] <0.4218.0> CRASH REPORT Process <0.4218.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:49.374 [error] <0.1073.0> gen_server <0.1073.0> terminated with reason: killed
2016-04-12 08:53:49.374 [error] <0.1073.0> CRASH REPORT Process <0.1073.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 737
2016-04-12 08:53:49.375 [error] <0.1020.0> CRASH REPORT Process <0.1020.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-12 08:53:49.375 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:49.375 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:53:53.069 [info] <0.7132.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.7132.0>
2016-04-12 08:53:53.073 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:58.267 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:53:58.477 [info] <0.7268.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.7268.0>
2016-04-12 08:53:58.486 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:58.471 [info] <0.4317.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4317.0>
2016-04-12 08:53:58.775 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:53:58.475 [info] <0.1126.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1126.0>
2016-04-12 08:53:58.786 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:54:06.319 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:06.504 [info] <0.4433.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4433.0>
2016-04-12 08:54:06.808 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:54:06.323 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:06.497 [info] <0.7396.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.7396.0>
2016-04-12 08:54:06.502 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:54:06.347 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:06.507 [info] <0.1244.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1244.0>
2016-04-12 08:54:06.523 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:54:22.098 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:22.100 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:22.125 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:23.592 [info] <0.7525.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.7525.0>
2016-04-12 08:54:23.595 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:54:23.620 [info] <0.1359.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.1359.0>
2016-04-12 08:54:23.940 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:54:23.637 [info] <0.4549.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4549.0>
2016-04-12 08:54:23.643 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:54:49.144 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:49.144 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:49.339 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:50.180 [info] <0.2485.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2485.0>
2016-04-12 08:54:50.209 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:54:50.178 [info] <0.8663.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.8663.0>
2016-04-12 08:54:50.484 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:54:50.198 [info] <0.5673.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.5673.0>
2016-04-12 08:54:50.219 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:54:57.095 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:57.289 [info] <0.5798.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.5798.0>
2016-04-12 08:54:57.297 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:54:57.120 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:57.324 [info] <0.2610.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.2610.0>
2016-04-12 08:54:57.330 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:54:57.123 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:54:57.267 [info] <0.8802.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.8802.0>
2016-04-12 08:54:57.280 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:55:03.753 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:55:03.910 [info] <0.10283.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.10283.0>
2016-04-12 08:55:03.914 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:55:03.765 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:55:03.918 [info] <0.7269.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.7269.0>
2016-04-12 08:55:03.924 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:55:03.779 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:55:03.929 [info] <0.4078.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4078.0>
2016-04-12 08:55:03.935 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:55:12.263 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:55:12.268 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:55:12.269 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:55:31.493 [info] <0.12050.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.12050.0>
2016-04-12 08:55:31.498 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:55:31.508 [info] <0.8270.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.8270.0>
2016-04-12 08:55:31.510 [info] <0.4672.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4672.0>
2016-04-12 08:55:31.520 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:55:33.217 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:55:40.214 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:55:40.377 [info] <0.9065.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.9065.0>
2016-04-12 08:55:40.392 [info] <0.7.0> Application mnesia2 started on node 'd1276496o1276492n1276492@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:55:40.221 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:55:40.362 [info] <0.12179.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.12179.0>
2016-04-12 08:55:40.365 [info] <0.7.0> Application mnesia2 started on node 'test1684@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:55:40.247 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:55:40.383 [info] <0.4787.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4', <0.4787.0>
2016-04-12 08:55:40.394 [info] <0.7.0> Application mnesia2 started on node 'd1276488o1276468n1276468@testing-worker-linux-docker-3e1e02c7-3394-linux-4'
2016-04-12 08:56:00.575 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:56:00.573 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:56:00.559 [info] <0.7.0> Application mnesia2 exited with reason: stopped
