2016-04-10 16:49:52.809 [info] <0.7.0> Application lager started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:52.810 [info] <0.7.0> Application poolgirl started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:52.837 [info] <0.430.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.430.0>
2016-04-10 16:49:52.856 [info] <0.498.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.498.0>
2016-04-10 16:49:53.258 [error] <0.489.0> CRASH REPORT Process <0.489.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:53.258 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:53.361 [info] <0.608.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.608.0>
2016-04-10 16:49:53.364 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:53.875 [error] <0.665.0> gen_server <0.665.0> terminated with reason: killed
2016-04-10 16:49:53.875 [error] <0.665.0> CRASH REPORT Process <0.665.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:49:53.876 [error] <0.599.0> CRASH REPORT Process <0.599.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:53.956 [info] <0.734.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.734.0>
2016-04-10 16:49:54.124 [warning] <0.6.0> lager_error_logger_h dropped 14 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:49:54.124 [error] <0.728.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'...

2016-04-10 16:49:54.125 [error] <0.729.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.732.0> exit with reason killed in context child_terminated
2016-04-10 16:49:54.125 [error] <0.729.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.732.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:49:54.127 [error] <0.727.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.729.0> exit with reason shutdown in context child_terminated
2016-04-10 16:49:54.127 [error] <0.727.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.729.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:49:53.590 [info] <0.7.0> Application lager started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:53.591 [info] <0.7.0> Application poolgirl started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:53.644 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.99.0>
2016-04-10 16:49:53.962 [info] <0.215.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.215.0>
2016-04-10 16:49:54.157 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:49:54.157 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:49:54.185 [info] <0.368.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.368.0>
2016-04-10 16:49:54.188 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:54.128 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 16:49:54.174 [info] <0.862.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.862.0>
2016-04-10 16:49:54.178 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:54.748 [info] <0.962.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.962.0>
2016-04-10 16:49:55.488 [warning] <0.6.0> lager_error_logger_h dropped 19 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:49:55.488 [error] <0.1023.0> gen_server <0.1023.0> terminated with reason: killed
2016-04-10 16:49:54.717 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:49:54.756 [info] <0.458.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.458.0>
2016-04-10 16:49:55.488 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:49:55.488 [error] <0.516.0> gen_server <0.516.0> terminated with reason: killed
2016-04-10 16:49:55.489 [error] <0.1023.0> CRASH REPORT Process <0.1023.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:49:55.488 [error] <0.516.0> CRASH REPORT Process <0.516.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:49:55.490 [error] <0.953.0> CRASH REPORT Process <0.953.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:55.489 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:55.489 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:55.570 [info] <0.547.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.547.0>
2016-04-10 16:49:55.573 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:55.490 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:55.564 [info] <0.1085.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1085.0>
2016-04-10 16:49:55.567 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:55.704 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:49:55.745 [info] <0.1197.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1197.0>
2016-04-10 16:49:56.146 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:49:56.146 [error] <0.1188.0> CRASH REPORT Process <0.1188.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:56.145 [error] <0.662.0> gen_server <0.662.0> terminated with reason: killed
2016-04-10 16:49:56.145 [error] <0.662.0> CRASH REPORT Process <0.662.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:49:56.146 [error] <0.538.0> CRASH REPORT Process <0.538.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:56.146 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:56.223 [info] <0.761.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.761.0>
2016-04-10 16:49:56.225 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:56.335 [error] <0.752.0> CRASH REPORT Process <0.752.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:56.146 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:56.217 [info] <0.1429.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1429.0>
2016-04-10 16:49:56.219 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:56.335 [error] <0.1485.0> gen_server <0.1485.0> terminated with reason: killed
2016-04-10 16:49:56.335 [error] <0.1485.0> CRASH REPORT Process <0.1485.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:49:56.335 [error] <0.1420.0> CRASH REPORT Process <0.1420.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:56.335 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:56.398 [info] <0.1543.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1543.0>
2016-04-10 16:49:56.335 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:56.401 [info] <0.860.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.860.0>
2016-04-10 16:49:56.596 [info] <0.961.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.961.0>
2016-04-10 16:49:56.885 [info] <0.1068.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1068.0>
2016-04-10 16:49:57.023 [warning] <0.6.0> lager_error_logger_h dropped 9 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:49:57.023 [error] <0.1121.0> gen_server <0.1121.0> terminated with reason: killed
2016-04-10 16:49:56.593 [info] <0.1660.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1660.0>
2016-04-10 16:49:56.879 [info] <0.1786.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1786.0>
2016-04-10 16:49:57.023 [warning] <0.6.0> lager_error_logger_h dropped 25 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:49:57.023 [error] <0.1777.0> CRASH REPORT Process <0.1777.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:57.023 [error] <0.1121.0> CRASH REPORT Process <0.1121.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:49:57.023 [error] <0.1058.0> CRASH REPORT Process <0.1058.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:57.023 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:57.094 [info] <0.1166.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1166.0>
2016-04-10 16:49:57.097 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:57.024 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:57.089 [info] <0.1917.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1917.0>
2016-04-10 16:49:57.092 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:57.246 [error] <0.1973.0> gen_server <0.1973.0> terminated with reason: killed
2016-04-10 16:49:57.248 [error] <0.1157.0> CRASH REPORT Process <0.1157.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:57.247 [error] <0.1973.0> CRASH REPORT Process <0.1973.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:49:57.247 [error] <0.1908.0> CRASH REPORT Process <0.1908.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:57.247 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:57.324 [info] <0.2050.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2050.0>
2016-04-10 16:49:57.596 [info] <0.2190.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2190.0>
2016-04-10 16:49:57.840 [info] <0.2321.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2321.0>
2016-04-10 16:49:58.000 [warning] <0.6.0> lager_error_logger_h dropped 30 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:49:58.000 [error] <0.2377.0> gen_server <0.2377.0> terminated with reason: killed
2016-04-10 16:49:58.001 [error] <0.2377.0> CRASH REPORT Process <0.2377.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:49:58.001 [error] <0.2312.0> CRASH REPORT Process <0.2312.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:57.248 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:57.340 [info] <0.1267.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1267.0>
2016-04-10 16:49:57.601 [info] <0.1373.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1373.0>
2016-04-10 16:49:57.845 [info] <0.1460.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1460.0>
2016-04-10 16:49:58.042 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:49:58.054 [info] <0.1572.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1572.0>
2016-04-10 16:49:58.056 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:58.001 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:58.051 [info] <0.2453.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2453.0>
2016-04-10 16:49:58.357 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:58.502 [error] <0.2495.0> gen_server <0.2495.0> terminated with reason: killed
2016-04-10 16:49:58.502 [error] <0.1625.0> gen_server <0.1625.0> terminated with reason: killed
2016-04-10 16:49:58.502 [error] <0.2495.0> CRASH REPORT Process <0.2495.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:49:58.503 [error] <0.1625.0> CRASH REPORT Process <0.1625.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:49:58.503 [error] <0.1563.0> CRASH REPORT Process <0.1563.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:58.551 [info] <0.2577.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2577.0>
2016-04-10 16:49:59.241 [info] <0.2705.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2705.0>
2016-04-10 16:49:59.244 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:49:59.280 [error] <0.2696.0> CRASH REPORT Process <0.2696.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:49:58.503 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:58.555 [info] <0.1660.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1660.0>
2016-04-10 16:49:59.280 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:49:59.328 [info] <0.2799.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2799.0>
2016-04-10 16:50:00.563 [info] <0.2909.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2909.0>
2016-04-10 16:50:00.566 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:50:01.746 [error] <0.2900.0> CRASH REPORT Process <0.2900.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:50:01.746 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:50:03.839 [info] <0.3015.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3015.0>
2016-04-10 16:50:03.841 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:50:03.842 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:50:03.843 [info] <0.3063.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3063.0>
2016-04-10 16:50:03.848 [info] <0.3111.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3111.0>
2016-04-10 16:50:05.930 [info] <0.3183.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3183.0>
2016-04-10 16:50:05.933 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:50:05.945 [error] <0.3174.0> CRASH REPORT Process <0.3174.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:50:05.945 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:50:07.981 [info] <0.3266.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3266.0>
2016-04-10 16:50:07.984 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:50:07.990 [info] <0.3260.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 16:50:07.990 [info] <0.3260.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test852@testing-worker-linux-docker-c44eb143-3382-linux-7.2016-04-10_16.49.27/Mnesia2.test852@testing-worker-linux-docker-c44eb143-3382-linux-7/LATEST.LOG"] -> badarg

2016-04-10 16:50:07.991 [error] <0.3302.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3342.0>}})

2016-04-10 16:50:07.991 [error] <0.3301.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3342.0>}})

2016-04-10 16:50:07.991 [error] <0.3304.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3342.0>}})

2016-04-10 16:50:07.991 [error] <0.3305.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}}} ({error,{already_started,<0.3342.0>}})

2016-04-10 16:50:07.992 [error] <0.3303.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}}} ({error,{already_started,<0.3342.0>}})

2016-04-10 16:50:07.992 [error] <0.3320.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}}} ({error,{already_started,<0.3342.0>}})

2016-04-10 16:50:07.992 [error] <0.3322.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3342.0>}})

2016-04-10 16:50:07.992 [error] <0.3324.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_29,shutdown]}}}} ({error,{already_started,<0.3342.0>}})

2016-04-10 16:50:10.068 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:50:10.069 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_monitor starting: <0.3381.0>

2016-04-10 16:50:10.069 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Mnesia2 debug level set to verbose
2016-04-10 16:50:10.070 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_subscr starting: <0.3382.0>

2016-04-10 16:50:10.070 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_locker starting: <0.3383.0>

2016-04-10 16:50:10.070 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_recover starting: <0.3384.0>

2016-04-10 16:50:10.071 [info] <0.3385.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3385.0>
2016-04-10 16:50:10.071 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_tm starting: <0.3385.0>

2016-04-10 16:50:10.071 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Schema initiated from: default

2016-04-10 16:50:10.071 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_controller starting: <0.3388.0>

2016-04-10 16:50:10.072 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_late_loader starting: <0.3389.0>

2016-04-10 16:50:10.072 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Intend to load tables: []

2016-04-10 16:50:10.073 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_tm_1 starting: <0.3391.0>

2016-04-10 16:50:10.073 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_tm_2 starting: <0.3392.0>

2016-04-10 16:50:10.073 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_tm_3 starting: <0.3393.0>

2016-04-10 16:50:10.073 [info] <0.3379.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_tm_4 starting: <0.3394.0>

2016-04-10 16:50:12.097 [warning] <0.6.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:50:12.098 [info] <0.3438.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_monitor starting: <0.3440.0>

2016-04-10 16:50:12.098 [info] <0.3438.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Version: "1.0.0"

2016-04-10 16:50:12.098 [info] <0.3438.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env access_module: mnesia2

2016-04-10 16:50:12.098 [info] <0.3438.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env auto_repair: true

2016-04-10 16:50:12.098 [info] <0.3438.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env backup_module: mnesia2_backup

2016-04-10 16:50:12.098 [info] <0.3438.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env debug: debug

2016-04-10 16:50:12.099 [info] <0.3438.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test852@testing-worker-linux-docker-c44eb143-3382-linux-7.2016-04-10_16.49.27/Mnesia2.test852@testing-worker-linux-docker-c44eb143-3382-linux-7"

2016-04-10 16:50:12.099 [info] <0.3438.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env dump_disc_copies_at_startup: true

2016-04-10 16:50:12.099 [info] <0.3438.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env dump_log_load_regulation: false

2016-04-10 16:50:12.099 [info] <0.3438.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env dump_log_time_threshold: 180000

2016-04-10 16:50:12.100 [info] <0.3444.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3444.0>
2016-04-10 16:50:12.100 [info] <0.3438.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env dump_log_update_in_place: true

2016-04-10 16:50:12.100 [info] <0.3438.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env dump_log_write_threshold: 1000

2016-04-10 16:50:12.101 [info] <0.3438.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env event_module: mnesia2_event

2016-04-10 16:50:14.128 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:50:14.128 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_monitor starting: <0.3492.0>

2016-04-10 16:50:14.129 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Version: "1.0.0"

2016-04-10 16:50:14.129 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env access_module: mnesia2

2016-04-10 16:50:14.129 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env auto_repair: true

2016-04-10 16:50:14.129 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env backup_module: mnesia2_backup

2016-04-10 16:50:14.130 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env debug: trace

2016-04-10 16:50:14.130 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test852@testing-worker-linux-docker-c44eb143-3382-linux-7.2016-04-10_16.49.27/Mnesia2.test852@testing-worker-linux-docker-c44eb143-3382-linux-7"

2016-04-10 16:50:14.130 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env dump_disc_copies_at_startup: true

2016-04-10 16:50:14.130 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env dump_log_load_regulation: false

2016-04-10 16:50:14.130 [info] <0.3496.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3496.0>
2016-04-10 16:50:14.131 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env dump_log_time_threshold: 180000

2016-04-10 16:50:14.131 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env dump_log_update_in_place: true

2016-04-10 16:50:14.131 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env dump_log_write_threshold: 1000

2016-04-10 16:50:14.131 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env event_module: mnesia2_event

2016-04-10 16:50:14.132 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env extra_db_nodes: []

2016-04-10 16:50:14.132 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env ignore_fallback_at_startup: false

2016-04-10 16:50:14.132 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 16:50:14.133 [info] <0.3490.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env max_wait_for_decision: infinity

2016-04-10 16:50:16.160 [warning] <0.6.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:50:16.160 [info] <0.3543.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): mnesia2_monitor starting: <0.3545.0>

2016-04-10 16:50:16.161 [info] <0.3543.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Version: "1.0.0"

2016-04-10 16:50:16.161 [info] <0.3543.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env access_module: mnesia2

2016-04-10 16:50:16.162 [info] <0.3549.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3549.0>
2016-04-10 16:50:16.162 [info] <0.3543.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env auto_repair: true

2016-04-10 16:50:16.162 [info] <0.3543.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env backup_module: mnesia2_backup

2016-04-10 16:50:16.162 [info] <0.3543.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env debug: debug

2016-04-10 16:50:16.163 [info] <0.3543.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test852@testing-worker-linux-docker-c44eb143-3382-linux-7.2016-04-10_16.49.27/Mnesia2.test852@testing-worker-linux-docker-c44eb143-3382-linux-7"

2016-04-10 16:50:18.187 [info] <0.3601.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3601.0>
2016-04-10 16:50:18.190 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:50:18.191 [error] <0.3592.0> CRASH REPORT Process <0.3592.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:50:18.191 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:50:20.278 [info] <0.3665.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3665.0>
2016-04-10 16:50:20.281 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:50:20.282 [error] <0.3656.0> CRASH REPORT Process <0.3656.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:50:20.282 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:50:21.388 [info] <0.3736.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3736.0>
2016-04-10 16:50:21.390 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:50:21.394 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:50:21.401 [info] <0.3797.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3797.0>
2016-04-10 16:50:23.864 [error] <0.3791.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:50:24.251 [error] <0.3791.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:50:24.638 [error] <0.3791.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:50:29.325 [error] <0.3791.0> Mnesia2('test852@testing-worker-linux-docker-c44eb143-3382-linux-7'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:50:36.472 [error] <0.3788.0> CRASH REPORT Process <0.3788.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:50:36.472 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:50:38.602 [info] <0.4367.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4367.0>
2016-04-10 16:50:38.604 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:50:44.611 [error] <0.4358.0> CRASH REPORT Process <0.4358.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:50:44.611 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:50:46.699 [info] <0.4467.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4467.0>
2016-04-10 16:50:46.701 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:50:47.732 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:50:49.852 [info] <0.4583.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4583.0>
2016-04-10 16:50:49.854 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:50:49.859 [error] <0.4574.0> CRASH REPORT Process <0.4574.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:50:49.859 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:50:52.150 [info] <0.4650.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4650.0>
2016-04-10 16:50:52.153 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:50:52.178 [error] <0.4641.0> CRASH REPORT Process <0.4641.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:50:52.178 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:50:55.642 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:50:55.663 [info] <0.1787.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1787.0>
2016-04-10 16:50:55.667 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:50:55.660 [info] <0.4742.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4742.0>
2016-04-10 16:50:55.966 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:50:56.967 [error] <0.1840.0> gen_server <0.1840.0> terminated with reason: killed
2016-04-10 16:50:56.967 [error] <0.1840.0> CRASH REPORT Process <0.1840.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:50:56.969 [error] <0.1778.0> CRASH REPORT Process <0.1778.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:50:56.969 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:50:59.013 [info] <0.1856.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1856.0>
2016-04-10 16:50:59.018 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:00.021 [error] <0.4733.0> CRASH REPORT Process <0.4733.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:00.021 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:01.071 [error] <0.1847.0> CRASH REPORT Process <0.1847.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:01.071 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:02.196 [info] <0.1937.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1937.0>
2016-04-10 16:51:02.207 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:02.208 [error] <0.1928.0> CRASH REPORT Process <0.1928.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:02.176 [info] <0.4849.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4849.0>
2016-04-10 16:51:02.179 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:02.208 [error] <0.4840.0> CRASH REPORT Process <0.4840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:02.208 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:02.266 [info] <0.4924.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4924.0>
2016-04-10 16:51:02.208 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:06.405 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:51:06.478 [info] <0.5048.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5048.0>
2016-04-10 16:51:06.482 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:06.470 [info] <0.2007.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2007.0>
2016-04-10 16:51:06.471 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:16.005 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:51:16.007 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:51:17.160 [info] <0.2129.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2129.0>
2016-04-10 16:51:17.171 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:17.209 [error] <0.2181.0> gen_server <0.2181.0> terminated with reason: killed
2016-04-10 16:51:17.209 [error] <0.2181.0> CRASH REPORT Process <0.2181.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:17.210 [error] <0.2120.0> CRASH REPORT Process <0.2120.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:17.144 [info] <0.5179.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5179.0>
2016-04-10 16:51:17.146 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:17.231 [error] <0.5170.0> CRASH REPORT Process <0.5170.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:17.231 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:17.262 [info] <0.5267.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5267.0>
2016-04-10 16:51:17.210 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:17.470 [info] <0.2217.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2217.0>
2016-04-10 16:51:18.958 [warning] <0.6.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:51:18.958 [error] <0.2208.0> CRASH REPORT Process <0.2208.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:18.959 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:20.017 [info] <0.2320.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2320.0>
2016-04-10 16:51:20.022 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:20.032 [error] <0.2332.0> gen_server <0.2332.0> terminated with reason: killed
2016-04-10 16:51:20.005 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:51:20.010 [info] <0.5390.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5390.0>
2016-04-10 16:51:20.013 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:20.040 [error] <0.5381.0> CRASH REPORT Process <0.5381.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:20.032 [error] <0.2332.0> CRASH REPORT Process <0.2332.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:20.032 [error] <0.2311.0> CRASH REPORT Process <0.2311.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:20.041 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:20.032 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:22.151 [info] <0.2395.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2395.0>
2016-04-10 16:51:22.157 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:22.158 [error] <0.2436.0> gen_server <0.2436.0> terminated with reason: killed
2016-04-10 16:51:22.145 [info] <0.5501.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5501.0>
2016-04-10 16:51:22.147 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:22.158 [error] <0.5565.0> gen_server <0.5565.0> terminated with reason: killed
2016-04-10 16:51:22.159 [error] <0.5565.0> CRASH REPORT Process <0.5565.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:22.158 [error] <0.2436.0> CRASH REPORT Process <0.2436.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:22.159 [error] <0.5492.0> CRASH REPORT Process <0.5492.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:22.159 [error] <0.2386.0> CRASH REPORT Process <0.2386.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:22.159 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:22.159 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:24.199 [info] <0.5581.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5581.0>
2016-04-10 16:51:24.205 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:24.226 [error] <0.5625.0> gen_server <0.5625.0> terminated with reason: killed
2016-04-10 16:51:24.226 [error] <0.5625.0> CRASH REPORT Process <0.5625.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:24.226 [error] <0.5572.0> CRASH REPORT Process <0.5572.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:24.183 [info] <0.2454.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2454.0>
2016-04-10 16:51:24.184 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:24.226 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:25.674 [error] <0.2445.0> CRASH REPORT Process <0.2445.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:25.674 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:26.772 [info] <0.2543.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2543.0>
2016-04-10 16:51:26.777 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:27.114 [error] <0.2594.0> gen_server <0.2594.0> terminated with reason: killed
2016-04-10 16:51:26.757 [info] <0.5706.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5706.0>
2016-04-10 16:51:26.759 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:27.114 [error] <0.5701.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5707.0> exit with reason killed in context child_terminated
2016-04-10 16:51:27.114 [error] <0.5701.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5707.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:51:27.004 [info] <0.7.0> Application lager started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:27.004 [info] <0.7.0> Application poolgirl started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:27.029 [info] <0.101.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.101.0>
2016-04-10 16:51:27.047 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:27.127 [error] <0.148.0> gen_server <0.148.0> terminated with reason: killed
2016-04-10 16:51:27.115 [error] <0.5699.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5701.0> exit with reason shutdown in context child_terminated
2016-04-10 16:51:27.115 [error] <0.5699.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5701.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:51:27.114 [error] <0.2594.0> CRASH REPORT Process <0.2594.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:27.127 [error] <0.148.0> CRASH REPORT Process <0.148.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:27.115 [error] <0.2585.0> gen_server <0.2585.0> terminated with reason: killed
2016-04-10 16:51:27.127 [error] <0.143.0> gen_server <0.143.0> terminated with reason: killed
2016-04-10 16:51:27.115 [error] <0.2585.0> CRASH REPORT Process <0.2585.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:27.127 [error] <0.143.0> CRASH REPORT Process <0.143.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:27.115 [error] <0.2534.0> CRASH REPORT Process <0.2534.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:27.127 [error] <0.92.0> CRASH REPORT Process <0.92.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:27.116 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 16:51:27.115 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:27.127 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:29.239 [info] <0.2624.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2624.0>
2016-04-10 16:51:29.244 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:29.246 [error] <0.2644.0> gen_server <0.2644.0> terminated with reason: killed
2016-04-10 16:51:29.233 [info] <0.5801.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5801.0>
2016-04-10 16:51:29.235 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:29.247 [error] <0.5792.0> CRASH REPORT Process <0.5792.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:29.246 [error] <0.2644.0> CRASH REPORT Process <0.2644.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:29.246 [error] <0.2615.0> CRASH REPORT Process <0.2615.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:29.247 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:29.246 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:31.334 [info] <0.2694.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2694.0>
2016-04-10 16:51:31.337 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:31.340 [error] <0.2706.0> gen_server <0.2706.0> terminated with reason: killed
2016-04-10 16:51:31.329 [info] <0.5895.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5895.0>
2016-04-10 16:51:31.331 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:31.342 [error] <0.5939.0> gen_server <0.5939.0> terminated with reason: killed
2016-04-10 16:51:31.342 [error] <0.5939.0> CRASH REPORT Process <0.5939.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:31.340 [error] <0.2706.0> CRASH REPORT Process <0.2706.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:31.343 [error] <0.5886.0> CRASH REPORT Process <0.5886.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:31.341 [error] <0.2685.0> CRASH REPORT Process <0.2685.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:31.343 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:31.341 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:35.759 [info] <0.2769.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2769.0>
2016-04-10 16:51:35.773 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:35.956 [error] <0.2760.0> CRASH REPORT Process <0.2760.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:35.743 [info] <0.5981.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5981.0>
2016-04-10 16:51:35.745 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:35.957 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:37.945 [error] <0.5972.0> CRASH REPORT Process <0.5972.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:37.945 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:40.000 [info] <0.2839.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2839.0>
2016-04-10 16:51:40.001 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:45.045 [error] <0.2906.0> gen_server <0.2906.0> terminated with reason: killed
2016-04-10 16:51:45.017 [info] <0.6059.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.6059.0>
2016-04-10 16:51:45.040 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:45.046 [error] <0.6122.0> gen_server <0.6122.0> terminated with reason: killed
2016-04-10 16:51:45.045 [error] <0.2906.0> CRASH REPORT Process <0.2906.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:45.046 [error] <0.6122.0> CRASH REPORT Process <0.6122.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:45.046 [error] <0.2830.0> CRASH REPORT Process <0.2830.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:45.048 [error] <0.6050.0> CRASH REPORT Process <0.6050.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:45.048 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:45.046 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:46.215 [info] <0.2938.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2938.0>
2016-04-10 16:51:46.222 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:46.557 [error] <0.3000.0> gen_server <0.3000.0> terminated with reason: killed
2016-04-10 16:51:46.557 [error] <0.3000.0> CRASH REPORT Process <0.3000.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:46.557 [error] <0.2995.0> gen_server <0.2995.0> terminated with reason: killed
2016-04-10 16:51:46.557 [error] <0.2995.0> CRASH REPORT Process <0.2995.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:46.558 [error] <0.2929.0> CRASH REPORT Process <0.2929.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:46.213 [info] <0.6169.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.6169.0>
2016-04-10 16:51:46.519 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:46.631 [error] <0.6234.0> gen_server <0.6234.0> terminated with reason: killed
2016-04-10 16:51:46.631 [error] <0.6234.0> CRASH REPORT Process <0.6234.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:46.631 [error] <0.6257.0> gen_server <0.6257.0> terminated with reason: killed
2016-04-10 16:51:46.631 [error] <0.6257.0> CRASH REPORT Process <0.6257.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:46.631 [error] <0.6273.0> gen_server <0.6273.0> terminated with reason: killed
2016-04-10 16:51:46.632 [error] <0.6273.0> CRASH REPORT Process <0.6273.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:46.632 [error] <0.6160.0> CRASH REPORT Process <0.6160.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:46.229 [info] <0.191.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.191.0>
2016-04-10 16:51:46.267 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:46.653 [error] <0.182.0> CRASH REPORT Process <0.182.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:46.632 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:46.729 [info] <0.6292.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.6292.0>
2016-04-10 16:51:46.558 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:46.583 [info] <0.3030.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3030.0>
2016-04-10 16:51:46.702 [info] <0.3125.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3125.0>
2016-04-10 16:51:46.653 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:46.730 [info] <0.295.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.295.0>
2016-04-10 16:51:47.267 [error] <0.367.0> gen_server <0.367.0> terminated with reason: killed
2016-04-10 16:51:47.267 [error] <0.367.0> CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:47.267 [error] <0.361.0> gen_server <0.361.0> terminated with reason: killed
2016-04-10 16:51:47.267 [error] <0.361.0> CRASH REPORT Process <0.361.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:47.267 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:47.267 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:47.292 [info] <0.393.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.393.0>
2016-04-10 16:51:47.293 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:49.345 [warning] <0.6.0> lager_error_logger_h dropped 24 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:51:49.345 [error] <0.6389.0> gen_server <0.6389.0> terminated with reason: killed
2016-04-10 16:51:49.345 [error] <0.6389.0> CRASH REPORT Process <0.6389.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:49.345 [error] <0.6357.0> gen_server <0.6357.0> terminated with reason: killed
2016-04-10 16:51:49.345 [error] <0.6357.0> CRASH REPORT Process <0.6357.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:49.345 [error] <0.6283.0> CRASH REPORT Process <0.6283.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:49.366 [warning] <0.6.0> lager_error_logger_h dropped 23 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:51:49.366 [error] <0.3217.0> gen_server <0.3217.0> terminated with reason: killed
2016-04-10 16:51:49.366 [error] <0.3217.0> CRASH REPORT Process <0.3217.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:49.367 [error] <0.3116.0> CRASH REPORT Process <0.3116.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:49.391 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:51:49.434 [info] <0.499.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.499.0>
2016-04-10 16:51:49.435 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:50.283 [error] <0.490.0> CRASH REPORT Process <0.490.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:49.345 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:49.449 [info] <0.6408.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.6408.0>
2016-04-10 16:51:49.764 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:50.356 [error] <0.6503.0> gen_server <0.6503.0> terminated with reason: killed
2016-04-10 16:51:50.357 [error] <0.6503.0> CRASH REPORT Process <0.6503.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:50.357 [error] <0.6497.0> gen_server <0.6497.0> terminated with reason: killed
2016-04-10 16:51:50.358 [error] <0.6497.0> CRASH REPORT Process <0.6497.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:50.358 [error] <0.6477.0> gen_server <0.6477.0> terminated with reason: killed
2016-04-10 16:51:50.358 [error] <0.6477.0> CRASH REPORT Process <0.6477.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:50.358 [error] <0.6399.0> CRASH REPORT Process <0.6399.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:49.367 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:49.463 [info] <0.3238.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3238.0>
2016-04-10 16:51:49.467 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:50.383 [error] <0.3324.0> gen_server <0.3324.0> terminated with reason: killed
2016-04-10 16:51:50.283 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:50.317 [info] <0.599.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.599.0>
2016-04-10 16:51:50.318 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:50.383 [error] <0.3324.0> CRASH REPORT Process <0.3324.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:50.384 [error] <0.3229.0> CRASH REPORT Process <0.3229.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:50.384 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:50.465 [info] <0.3345.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3345.0>
2016-04-10 16:51:50.481 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:51.277 [error] <0.3408.0> gen_server <0.3408.0> terminated with reason: killed
2016-04-10 16:51:51.277 [error] <0.3408.0> CRASH REPORT Process <0.3408.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:51.277 [error] <0.3415.0> gen_server <0.3415.0> terminated with reason: killed
2016-04-10 16:51:51.277 [error] <0.3415.0> CRASH REPORT Process <0.3415.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:51.277 [error] <0.3336.0> CRASH REPORT Process <0.3336.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:50.358 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:50.462 [info] <0.6521.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.6521.0>
2016-04-10 16:51:51.277 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:51.335 [info] <0.3441.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3441.0>
2016-04-10 16:51:51.360 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:51.369 [error] <0.3499.0> gen_server <0.3499.0> terminated with reason: killed
2016-04-10 16:51:51.369 [error] <0.3499.0> CRASH REPORT Process <0.3499.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:51.369 [error] <0.3455.0> gen_server <0.3455.0> terminated with reason: killed
2016-04-10 16:51:51.369 [error] <0.3455.0> CRASH REPORT Process <0.3455.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:50.407 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:51:50.419 [info] <0.700.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.700.0>
2016-04-10 16:51:52.392 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:51:52.395 [info] <0.3519.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3519.0>
2016-04-10 16:51:52.403 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:52.476 [error] <0.3567.0> gen_server <0.3567.0> terminated with reason: killed
2016-04-10 16:51:52.478 [error] <0.6634.0> gen_server <0.6634.0> terminated with reason: killed
2016-04-10 16:51:52.476 [error] <0.3533.0> gen_server <0.3533.0> terminated with reason: killed
2016-04-10 16:51:52.478 [error] <0.817.0> gen_server <0.817.0> terminated with reason: killed
2016-04-10 16:51:52.479 [error] <0.6634.0> CRASH REPORT Process <0.6634.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:52.476 [error] <0.3567.0> CRASH REPORT Process <0.3567.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:52.478 [error] <0.817.0> CRASH REPORT Process <0.817.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:52.476 [error] <0.3533.0> CRASH REPORT Process <0.3533.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:52.479 [error] <0.6585.0> gen_server <0.6585.0> terminated with reason: killed
2016-04-10 16:51:52.478 [error] <0.824.0> gen_server <0.824.0> terminated with reason: killed
2016-04-10 16:51:52.476 [error] <0.3510.0> CRASH REPORT Process <0.3510.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:52.479 [error] <0.6585.0> CRASH REPORT Process <0.6585.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:52.478 [error] <0.824.0> CRASH REPORT Process <0.824.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:52.478 [error] <0.773.0> gen_server <0.773.0> terminated with reason: killed
2016-04-10 16:51:52.479 [error] <0.6512.0> CRASH REPORT Process <0.6512.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:52.478 [error] <0.773.0> CRASH REPORT Process <0.773.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:52.479 [error] <0.691.0> CRASH REPORT Process <0.691.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:52.476 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:52.534 [info] <0.3597.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3597.0>
2016-04-10 16:51:52.911 [info] <0.3693.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3693.0>
2016-04-10 16:51:53.008 [info] <0.3783.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3783.0>
2016-04-10 16:51:53.013 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:53.021 [error] <0.3844.0> gen_server <0.3844.0> terminated with reason: killed
2016-04-10 16:51:53.021 [error] <0.3844.0> CRASH REPORT Process <0.3844.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:53.021 [error] <0.3774.0> CRASH REPORT Process <0.3774.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:53.021 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:53.065 [info] <0.3883.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3883.0>
2016-04-10 16:51:52.479 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:52.532 [info] <0.6667.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.6667.0>
2016-04-10 16:51:52.836 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:53.048 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:51:52.479 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:54.166 [info] <0.3965.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.3965.0>
2016-04-10 16:51:54.193 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:54.235 [error] <0.4016.0> gen_server <0.4016.0> terminated with reason: killed
2016-04-10 16:51:53.580 [info] <0.6781.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.6781.0>
2016-04-10 16:51:53.594 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:53.604 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:51:53.662 [info] <0.6864.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.6864.0>
2016-04-10 16:51:54.237 [error] <0.6855.0> CRASH REPORT Process <0.6855.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:54.235 [error] <0.4016.0> CRASH REPORT Process <0.4016.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:54.236 [error] <0.3956.0> CRASH REPORT Process <0.3956.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:54.237 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:54.301 [info] <0.6965.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.6965.0>
2016-04-10 16:51:54.310 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:54.670 [error] <0.7020.0> gen_server <0.7020.0> terminated with reason: killed
2016-04-10 16:51:54.303 [info] <0.851.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.851.0>
2016-04-10 16:51:54.314 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:54.670 [error] <0.911.0> gen_server <0.911.0> terminated with reason: killed
2016-04-10 16:51:54.670 [error] <0.7020.0> CRASH REPORT Process <0.7020.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:54.670 [error] <0.6956.0> CRASH REPORT Process <0.6956.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:54.670 [error] <0.911.0> CRASH REPORT Process <0.911.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:51:54.670 [error] <0.842.0> CRASH REPORT Process <0.842.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:51:54.236 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:54.300 [info] <0.4057.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4057.0>
2016-04-10 16:51:54.695 [info] <0.4152.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4152.0>
2016-04-10 16:51:54.781 [info] <0.4229.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4229.0>
2016-04-10 16:51:54.670 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:54.695 [info] <0.954.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.954.0>
2016-04-10 16:51:54.696 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:51:54.783 [info] <0.1032.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1032.0>
2016-04-10 16:51:54.670 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:51:54.730 [info] <0.7075.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.7075.0>
2016-04-10 16:51:54.807 [info] <0.7167.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.7167.0>
2016-04-10 16:52:04.814 [warning] <0.6.0> lager_error_logger_h dropped 18 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:52:04.814 [error] <0.7160.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 16:52:04.814 [error] <0.7163.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 16:52:04.814 [error] <0.7164.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 16:52:04.814 [error] <0.7164.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:52:04.814 [error] <0.7166.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 16:52:04.815 [error] <0.7186.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 16:52:04.815 [error] <0.7166.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:52:04.815 [error] <0.7186.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:52:04.815 [error] <0.7158.0> CRASH REPORT Process <0.7158.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-10 16:52:04.815 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 16:52:04.817 [error] <0.7163.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:52:04.908 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:52:04.908 [error] <0.4273.0> gen_server <0.4273.0> terminated with reason: killed
2016-04-10 16:52:04.908 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 16:52:04.908 [error] <0.1081.0> gen_server <0.1081.0> terminated with reason: killed
2016-04-10 16:52:04.908 [error] <0.4273.0> CRASH REPORT Process <0.4273.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:52:04.909 [error] <0.1081.0> CRASH REPORT Process <0.1081.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:52:04.909 [error] <0.1076.0> gen_server <0.1076.0> terminated with reason: killed
2016-04-10 16:52:04.909 [error] <0.4220.0> CRASH REPORT Process <0.4220.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:52:04.909 [error] <0.1076.0> CRASH REPORT Process <0.1076.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 746
2016-04-10 16:52:04.909 [error] <0.1023.0> CRASH REPORT Process <0.1023.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:52:04.909 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:52:04.909 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 16:52:07.294 [info] <0.7276.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.7276.0>
2016-04-10 16:52:07.296 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:13.755 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:13.903 [info] <0.7412.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.7412.0>
2016-04-10 16:52:14.228 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:13.905 [info] <0.4319.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4319.0>
2016-04-10 16:52:14.209 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:13.909 [info] <0.1129.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1129.0>
2016-04-10 16:52:13.915 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:20.376 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:20.508 [info] <0.4437.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4437.0>
2016-04-10 16:52:20.814 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:20.378 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:20.495 [info] <0.7541.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.7541.0>
2016-04-10 16:52:20.508 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:20.381 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:20.513 [info] <0.1244.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1244.0>
2016-04-10 16:52:20.518 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:26.909 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:27.046 [info] <0.4553.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4553.0>
2016-04-10 16:52:27.051 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:26.910 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:27.045 [info] <0.1358.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.1358.0>
2016-04-10 16:52:27.350 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:26.914 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:27.038 [info] <0.7671.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.7671.0>
2016-04-10 16:52:27.041 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:44.268 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:44.418 [info] <0.8809.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.8809.0>
2016-04-10 16:52:44.724 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:44.272 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:44.421 [info] <0.2484.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2484.0>
2016-04-10 16:52:44.450 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:44.292 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:44.420 [info] <0.5677.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5677.0>
2016-04-10 16:52:44.434 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:51.187 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:51.189 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:51.193 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:52.448 [info] <0.8948.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.8948.0>
2016-04-10 16:52:52.450 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:52.458 [info] <0.2610.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.2610.0>
2016-04-10 16:52:52.462 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:52.453 [info] <0.5801.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5801.0>
2016-04-10 16:52:52.504 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:59.002 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:59.139 [info] <0.10429.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.10429.0>
2016-04-10 16:52:59.141 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:59.019 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:59.144 [info] <0.4078.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.4078.0>
2016-04-10 16:52:59.449 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:52:59.021 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:52:59.147 [info] <0.7272.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.7272.0>
2016-04-10 16:52:59.152 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:53:05.678 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:53:05.805 [info] <0.10872.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.10872.0>
2016-04-10 16:53:06.112 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:53:05.682 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:53:05.808 [info] <0.5429.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5429.0>
2016-04-10 16:53:05.816 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:53:05.698 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:53:05.808 [info] <0.9003.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.9003.0>
2016-04-10 16:53:05.813 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:53:12.245 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:53:12.401 [info] <0.5545.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.5545.0>
2016-04-10 16:53:12.404 [info] <0.7.0> Application mnesia2 started on node 'd1101377o1101387n1101391@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:53:12.248 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:53:12.395 [info] <0.11002.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.11002.0>
2016-04-10 16:53:12.398 [info] <0.7.0> Application mnesia2 started on node 'test852@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:53:12.266 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:53:12.408 [info] <0.9796.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7', <0.9796.0>
2016-04-10 16:53:12.425 [info] <0.7.0> Application mnesia2 started on node 'd1101391o1101381n1101383@testing-worker-linux-docker-c44eb143-3382-linux-7'
2016-04-10 16:53:18.621 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:53:18.615 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 16:53:18.619 [info] <0.7.0> Application mnesia2 exited with reason: stopped
