2016-04-10 16:45:19.426 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:20.058 [error] <0.155.0> gen_server <0.155.0> terminated with reason: killed
2016-04-10 16:45:20.058 [error] <0.155.0> CRASH REPORT Process <0.155.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:20.060 [error] <0.729.0> gen_server <0.729.0> terminated with reason: killed
2016-04-10 16:45:20.058 [error] <0.90.0> CRASH REPORT Process <0.90.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:20.060 [error] <0.729.0> CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:20.060 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:20.442 [error] <0.792.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1225791o1225973n1225975@testing-worker-linux-docker-236c71da-3354-linux-4'...

2016-04-10 16:45:20.442 [error] <0.793.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.796.0> exit with reason killed in context child_terminated
2016-04-10 16:45:21.786 [error] <0.514.0> gen_server <0.514.0> terminated with reason: killed
2016-04-10 16:45:21.787 [error] <0.1017.0> CRASH REPORT Process <0.1017.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:21.786 [error] <0.514.0> CRASH REPORT Process <0.514.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:21.786 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:22.410 [error] <0.662.0> gen_server <0.662.0> terminated with reason: killed
2016-04-10 16:45:22.411 [error] <0.1252.0> CRASH REPORT Process <0.1252.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:22.410 [error] <0.662.0> CRASH REPORT Process <0.662.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:22.411 [error] <0.538.0> CRASH REPORT Process <0.538.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:22.631 [error] <0.815.0> gen_server <0.815.0> terminated with reason: killed
2016-04-10 16:45:22.633 [error] <0.1547.0> gen_server <0.1547.0> terminated with reason: killed
2016-04-10 16:45:22.631 [error] <0.815.0> CRASH REPORT Process <0.815.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:22.643 [error] <0.1547.0> CRASH REPORT Process <0.1547.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:22.644 [error] <0.1484.0> CRASH REPORT Process <0.1484.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:23.126 [error] <0.1013.0> gen_server <0.1013.0> terminated with reason: killed
2016-04-10 16:45:23.129 [error] <0.1779.0> gen_server <0.1779.0> terminated with reason: killed
2016-04-10 16:45:23.126 [error] <0.1013.0> CRASH REPORT Process <0.1013.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:23.129 [error] <0.1779.0> CRASH REPORT Process <0.1779.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:23.129 [error] <0.1714.0> CRASH REPORT Process <0.1714.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:23.126 [error] <0.952.0> CRASH REPORT Process <0.952.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:23.353 [error] <0.1119.0> gen_server <0.1119.0> terminated with reason: killed
2016-04-10 16:45:23.355 [error] <0.1903.0> gen_server <0.1903.0> terminated with reason: killed
2016-04-10 16:45:23.353 [error] <0.1119.0> CRASH REPORT Process <0.1119.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:23.355 [error] <0.1903.0> CRASH REPORT Process <0.1903.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:24.187 [error] <0.2309.0> gen_server <0.2309.0> terminated with reason: killed
2016-04-10 16:45:24.186 [error] <0.1427.0> gen_server <0.1427.0> terminated with reason: killed
2016-04-10 16:45:24.187 [error] <0.2309.0> CRASH REPORT Process <0.2309.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:24.186 [error] <0.1427.0> CRASH REPORT Process <0.1427.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:24.188 [error] <0.2244.0> CRASH REPORT Process <0.2244.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:24.187 [error] <0.1364.0> CRASH REPORT Process <0.1364.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:24.497 [error] <0.2440.0> gen_server <0.2440.0> terminated with reason: killed
2016-04-10 16:45:24.497 [error] <0.1514.0> gen_server <0.1514.0> terminated with reason: killed
2016-04-10 16:45:24.497 [error] <0.2440.0> CRASH REPORT Process <0.2440.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:24.497 [error] <0.1514.0> CRASH REPORT Process <0.1514.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:45:25.115 [error] <0.2630.0> CRASH REPORT Process <0.2630.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:25.189 [error] <0.2758.0> CRASH REPORT Process <0.2758.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:27.671 [error] <0.2962.0> CRASH REPORT Process <0.2962.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:31.888 [error] <0.3236.0> CRASH REPORT Process <0.3236.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:34.328 [error] <0.3321.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.3323.0> exit with reason killed in context child_terminated
2016-04-10 16:45:34.329 [error] <0.3321.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.3323.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:45:34.330 [error] <0.3354.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.330 [error] <0.3356.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.330 [error] <0.3358.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.330 [error] <0.3357.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.330 [error] <0.3355.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.330 [error] <0.3360.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3362.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3361.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3364.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3366.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3365.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3363.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3368.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3370.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3369.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_16,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.331 [error] <0.3372.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_19,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.332 [error] <0.3374.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_21,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.332 [error] <0.3373.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_20,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.332 [error] <0.3371.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_18,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_18,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.332 [error] <0.3367.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_14,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_14,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.377 [error] <0.3376.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_23,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.377 [error] <0.3378.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_25,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.377 [error] <0.3380.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3427.0>}})

2016-04-10 16:45:34.377 [error] <0.3319.0> CRASH REPORT Process <0.3319.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:36.429 [error] <0.3458.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.429 [error] <0.3460.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.429 [error] <0.3462.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.429 [error] <0.3461.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.430 [error] <0.3459.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.430 [error] <0.3464.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.430 [error] <0.3465.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.430 [error] <0.3466.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:36.430 [error] <0.3468.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3512.0>}})

2016-04-10 16:45:44.544 [error] <0.3726.0> CRASH REPORT Process <0.3726.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:46.628 [error] <0.3790.0> CRASH REPORT Process <0.3790.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:45:49.994 [error] <0.3925.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:45:54.963 [error] <0.3925.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:45:59.429 [error] <0.3925.0> Mnesia2('test1018@testing-worker-linux-docker-236c71da-3354-linux-4'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 16:46:02.783 [error] <0.3922.0> CRASH REPORT Process <0.3922.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:10.919 [error] <0.4543.0> CRASH REPORT Process <0.4543.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:16.156 [error] <0.4759.0> CRASH REPORT Process <0.4759.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:18.221 [error] <0.4826.0> CRASH REPORT Process <0.4826.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:21.372 [error] <0.1834.0> gen_server <0.1834.0> terminated with reason: killed
2016-04-10 16:46:21.372 [error] <0.1834.0> CRASH REPORT Process <0.1834.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:21.373 [error] <0.1777.0> CRASH REPORT Process <0.1777.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:24.427 [error] <0.4922.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4939.0> exit with reason killed in context child_terminated
2016-04-10 16:46:24.427 [error] <0.4922.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4939.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:46:24.429 [error] <0.4990.0> gen_server <0.4990.0> terminated with reason: killed
2016-04-10 16:46:24.429 [error] <0.4990.0> CRASH REPORT Process <0.4990.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:24.429 [error] <0.4918.0> CRASH REPORT Process <0.4918.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:25.482 [error] <0.1845.0> CRASH REPORT Process <0.1845.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:26.611 [error] <0.5024.0> CRASH REPORT Process <0.5024.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:26.612 [error] <0.1926.0> CRASH REPORT Process <0.1926.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:41.212 [error] <0.2179.0> gen_server <0.2179.0> terminated with reason: killed
2016-04-10 16:46:41.212 [error] <0.2179.0> CRASH REPORT Process <0.2179.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:41.213 [error] <0.2119.0> CRASH REPORT Process <0.2119.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:41.235 [error] <0.5354.0> CRASH REPORT Process <0.5354.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:43.099 [error] <0.2210.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.2236.0> exit with reason killed in context child_terminated
2016-04-10 16:46:43.100 [error] <0.2210.0> Supervisor mnesia2_kernel_sup had child mnesia2_controller started with mnesia2_controller:start() at <0.2236.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:46:43.100 [error] <0.2210.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2234.0> exit with reason killed in context shutdown_error
2016-04-10 16:46:43.101 [error] <0.2208.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2210.0> exit with reason killed in context child_terminated
2016-04-10 16:46:43.101 [error] <0.2208.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2210.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:46:43.101 [error] <0.2211.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 16:46:43.101 [error] <0.2211.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:43.101 [error] <0.2214.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 16:46:43.101 [error] <0.2214.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:44.204 [error] <0.2331.0> gen_server <0.2331.0> terminated with reason: killed
2016-04-10 16:46:44.213 [error] <0.5638.0> gen_server <0.5638.0> terminated with reason: killed
2016-04-10 16:46:44.205 [error] <0.2331.0> CRASH REPORT Process <0.2331.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:44.213 [error] <0.5638.0> CRASH REPORT Process <0.5638.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:44.205 [error] <0.2310.0> CRASH REPORT Process <0.2310.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:44.214 [error] <0.5565.0> CRASH REPORT Process <0.5565.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:46.344 [error] <0.2389.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2396.0> exit with reason killed in context child_terminated
2016-04-10 16:46:46.346 [error] <0.5749.0> gen_server <0.5749.0> terminated with reason: killed
2016-04-10 16:46:46.345 [error] <0.2389.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2396.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:46:46.346 [error] <0.5749.0> CRASH REPORT Process <0.5749.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:46.345 [error] <0.2406.0> gen_server <0.2406.0> terminated with reason: killed
2016-04-10 16:46:46.348 [error] <0.5676.0> CRASH REPORT Process <0.5676.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:46.345 [error] <0.2406.0> CRASH REPORT Process <0.2406.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:46.345 [error] <0.2385.0> CRASH REPORT Process <0.2385.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:48.428 [error] <0.5760.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5782.0> exit with reason killed in context child_terminated
2016-04-10 16:46:48.428 [error] <0.5760.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5782.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:46:48.428 [error] <0.5826.0> gen_server <0.5826.0> terminated with reason: killed
2016-04-10 16:46:48.429 [error] <0.5826.0> CRASH REPORT Process <0.5826.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:48.429 [error] <0.5756.0> CRASH REPORT Process <0.5756.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:49.871 [error] <0.2444.0> CRASH REPORT Process <0.2444.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:51.382 [error] <0.5943.0> gen_server <0.5943.0> terminated with reason: killed
2016-04-10 16:46:51.382 [error] <0.2553.0> gen_server <0.2553.0> terminated with reason: killed
2016-04-10 16:46:51.382 [error] <0.5943.0> CRASH REPORT Process <0.5943.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:51.382 [error] <0.2553.0> CRASH REPORT Process <0.2553.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:51.382 [error] <0.5935.0> gen_server <0.5935.0> terminated with reason: killed
2016-04-10 16:46:51.382 [error] <0.2531.0> CRASH REPORT Process <0.2531.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:51.382 [error] <0.5935.0> CRASH REPORT Process <0.5935.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:51.383 [error] <0.5881.0> CRASH REPORT Process <0.5881.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:53.515 [error] <0.5976.0> CRASH REPORT Process <0.5976.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:53.516 [error] <0.2645.0> gen_server <0.2645.0> terminated with reason: killed
2016-04-10 16:46:53.516 [error] <0.2645.0> CRASH REPORT Process <0.2645.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:53.516 [error] <0.2612.0> CRASH REPORT Process <0.2612.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:55.654 [error] <0.6124.0> gen_server <0.6124.0> terminated with reason: killed
2016-04-10 16:46:55.652 [error] <0.2703.0> gen_server <0.2703.0> terminated with reason: killed
2016-04-10 16:46:55.654 [error] <0.6124.0> CRASH REPORT Process <0.6124.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:55.653 [error] <0.2703.0> CRASH REPORT Process <0.2703.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:55.655 [error] <0.6070.0> CRASH REPORT Process <0.6070.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:55.653 [error] <0.2682.0> CRASH REPORT Process <0.2682.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:58.105 [error] <0.2821.0> gen_server <0.2821.0> terminated with reason: killed
2016-04-10 16:46:58.105 [error] <0.2821.0> CRASH REPORT Process <0.2821.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:46:58.105 [error] <0.2757.0> CRASH REPORT Process <0.2757.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:46:59.133 [error] <0.6156.0> CRASH REPORT Process <0.6156.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:06.228 [error] <0.6301.0> gen_server <0.6301.0> terminated with reason: killed
2016-04-10 16:47:06.227 [error] <0.2832.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2850.0> exit with reason killed in context child_terminated
2016-04-10 16:47:06.227 [error] <0.2832.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.2850.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:47:06.228 [error] <0.6301.0> CRASH REPORT Process <0.6301.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:06.227 [error] <0.2904.0> gen_server <0.2904.0> terminated with reason: killed
2016-04-10 16:47:06.230 [error] <0.6235.0> CRASH REPORT Process <0.6235.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:06.227 [error] <0.2904.0> CRASH REPORT Process <0.2904.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:06.227 [error] <0.2828.0> CRASH REPORT Process <0.2828.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:07.493 [error] <0.2997.0> gen_server <0.2997.0> terminated with reason: killed
2016-04-10 16:47:07.493 [error] <0.2997.0> CRASH REPORT Process <0.2997.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:07.493 [error] <0.2988.0> gen_server <0.2988.0> terminated with reason: killed
2016-04-10 16:47:07.493 [error] <0.2988.0> CRASH REPORT Process <0.2988.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:07.493 [error] <0.2927.0> CRASH REPORT Process <0.2927.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:07.556 [error] <0.6349.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6366.0> exit with reason killed in context child_terminated
2016-04-10 16:47:07.558 [error] <0.6349.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6366.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 16:47:07.558 [error] <0.6457.0> gen_server <0.6457.0> terminated with reason: killed
2016-04-10 16:47:07.558 [error] <0.6457.0> CRASH REPORT Process <0.6457.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:07.558 [error] <0.6441.0> gen_server <0.6441.0> terminated with reason: killed
2016-04-10 16:47:07.558 [error] <0.6441.0> CRASH REPORT Process <0.6441.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:07.558 [error] <0.6418.0> gen_server <0.6418.0> terminated with reason: killed
2016-04-10 16:47:07.558 [error] <0.6418.0> CRASH REPORT Process <0.6418.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:07.559 [error] <0.6345.0> CRASH REPORT Process <0.6345.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:07.584 [error] <0.273.0> gen_server <0.273.0> terminated with reason: killed
2016-04-10 16:47:07.584 [error] <0.273.0> CRASH REPORT Process <0.273.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:08.821 [error] <0.356.0> gen_server <0.356.0> terminated with reason: killed
2016-04-10 16:47:08.821 [error] <0.356.0> CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:08.821 [error] <0.368.0> gen_server <0.368.0> terminated with reason: killed
2016-04-10 16:47:08.821 [error] <0.368.0> CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:08.821 [error] <0.285.0> CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:10.894 [error] <0.6575.0> gen_server <0.6575.0> terminated with reason: killed
2016-04-10 16:47:10.894 [error] <0.6575.0> CRASH REPORT Process <0.6575.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:10.894 [error] <0.6547.0> gen_server <0.6547.0> terminated with reason: killed
2016-04-10 16:47:10.895 [error] <0.6547.0> CRASH REPORT Process <0.6547.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:10.895 [error] <0.6467.0> CRASH REPORT Process <0.6467.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:10.916 [error] <0.3113.0> CRASH REPORT Process <0.3113.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:11.849 [error] <0.571.0> gen_server <0.571.0> terminated with reason: killed
2016-04-10 16:47:11.851 [error] <0.571.0> CRASH REPORT Process <0.571.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:11.851 [error] <0.564.0> gen_server <0.564.0> terminated with reason: killed
2016-04-10 16:47:11.851 [error] <0.564.0> CRASH REPORT Process <0.564.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:11.851 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:11.947 [error] <0.6683.0> gen_server <0.6683.0> terminated with reason: killed
2016-04-10 16:47:11.947 [error] <0.6683.0> CRASH REPORT Process <0.6683.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:11.948 [error] <0.6663.0> gen_server <0.6663.0> terminated with reason: killed
2016-04-10 16:47:11.948 [error] <0.6663.0> CRASH REPORT Process <0.6663.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:11.948 [error] <0.6689.0> gen_server <0.6689.0> terminated with reason: killed
2016-04-10 16:47:11.948 [error] <0.6689.0> CRASH REPORT Process <0.6689.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:11.950 [error] <0.6585.0> CRASH REPORT Process <0.6585.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:11.968 [error] <0.3322.0> gen_server <0.3322.0> terminated with reason: killed
2016-04-10 16:47:11.968 [error] <0.3322.0> CRASH REPORT Process <0.3322.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:11.969 [error] <0.3226.0> CRASH REPORT Process <0.3226.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:12.875 [error] <0.3412.0> gen_server <0.3412.0> terminated with reason: killed
2016-04-10 16:47:12.875 [error] <0.3412.0> CRASH REPORT Process <0.3412.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:12.875 [error] <0.3395.0> gen_server <0.3395.0> terminated with reason: killed
2016-04-10 16:47:12.875 [error] <0.3395.0> CRASH REPORT Process <0.3395.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:12.876 [error] <0.3334.0> CRASH REPORT Process <0.3334.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:13.000 [error] <0.3452.0> gen_server <0.3452.0> terminated with reason: killed
2016-04-10 16:47:13.000 [error] <0.3452.0> CRASH REPORT Process <0.3452.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:13.000 [error] <0.3494.0> gen_server <0.3494.0> terminated with reason: killed
2016-04-10 16:47:13.000 [error] <0.3494.0> CRASH REPORT Process <0.3494.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:13.000 [error] <0.3486.0> gen_server <0.3486.0> terminated with reason: killed
2016-04-10 16:47:13.001 [error] <0.3486.0> CRASH REPORT Process <0.3486.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:13.001 [error] <0.3429.0> CRASH REPORT Process <0.3429.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:14.115 [error] <0.6820.0> gen_server <0.6820.0> terminated with reason: killed
2016-04-10 16:47:14.118 [error] <0.823.0> gen_server <0.823.0> terminated with reason: killed
2016-04-10 16:47:14.116 [error] <0.3564.0> gen_server <0.3564.0> terminated with reason: killed
2016-04-10 16:47:14.118 [error] <0.823.0> CRASH REPORT Process <0.823.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:14.115 [error] <0.6820.0> CRASH REPORT Process <0.6820.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:14.117 [error] <0.3564.0> CRASH REPORT Process <0.3564.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:14.115 [error] <0.6771.0> gen_server <0.6771.0> terminated with reason: killed
2016-04-10 16:47:14.118 [error] <0.812.0> gen_server <0.812.0> terminated with reason: killed
2016-04-10 16:47:14.119 [error] <0.3507.0> CRASH REPORT Process <0.3507.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:14.115 [error] <0.6771.0> CRASH REPORT Process <0.6771.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:14.118 [error] <0.812.0> CRASH REPORT Process <0.812.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:14.115 [error] <0.6698.0> CRASH REPORT Process <0.6698.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:14.118 [error] <0.771.0> gen_server <0.771.0> terminated with reason: killed
2016-04-10 16:47:14.118 [error] <0.771.0> CRASH REPORT Process <0.771.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:14.118 [error] <0.688.0> CRASH REPORT Process <0.688.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:15.034 [error] <0.3870.0> CRASH REPORT Process <0.3870.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:15.794 [error] <0.7041.0> CRASH REPORT Process <0.7041.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:15.795 [error] <0.4000.0> gen_server <0.4000.0> terminated with reason: killed
2016-04-10 16:47:15.795 [error] <0.4000.0> CRASH REPORT Process <0.4000.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:15.796 [error] <0.3952.0> CRASH REPORT Process <0.3952.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:16.253 [error] <0.4111.0> gen_server <0.4111.0> terminated with reason: killed
2016-04-10 16:47:16.255 [error] <0.7199.0> gen_server <0.7199.0> terminated with reason: killed
2016-04-10 16:47:16.255 [error] <0.7199.0> CRASH REPORT Process <0.7199.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.256 [error] <0.913.0> gen_server <0.913.0> terminated with reason: killed
2016-04-10 16:47:16.255 [error] <0.7214.0> gen_server <0.7214.0> terminated with reason: killed
2016-04-10 16:47:16.254 [error] <0.4111.0> CRASH REPORT Process <0.4111.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.255 [error] <0.7214.0> CRASH REPORT Process <0.7214.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.256 [error] <0.913.0> CRASH REPORT Process <0.913.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.254 [error] <0.4106.0> gen_server <0.4106.0> terminated with reason: killed
2016-04-10 16:47:16.256 [error] <0.906.0> gen_server <0.906.0> terminated with reason: killed
2016-04-10 16:47:16.255 [error] <0.7142.0> CRASH REPORT Process <0.7142.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:16.256 [error] <0.906.0> CRASH REPORT Process <0.906.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.254 [error] <0.4106.0> CRASH REPORT Process <0.4106.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.259 [error] <0.840.0> CRASH REPORT Process <0.840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:16.254 [error] <0.4044.0> CRASH REPORT Process <0.4044.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:16.332 [error] <0.1013.0> gen_server <0.1013.0> terminated with reason: killed
2016-04-10 16:47:16.332 [error] <0.1013.0> CRASH REPORT Process <0.1013.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.332 [error] <0.1003.0> gen_server <0.1003.0> terminated with reason: killed
2016-04-10 16:47:16.333 [error] <0.1003.0> CRASH REPORT Process <0.1003.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:16.333 [error] <0.945.0> CRASH REPORT Process <0.945.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:26.389 [error] <0.7349.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 16:47:26.389 [error] <0.7352.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 16:47:26.389 [error] <0.7355.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 16:47:26.389 [error] <0.7355.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.389 [error] <0.7375.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 16:47:26.390 [error] <0.7375.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.390 [error] <0.7353.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 16:47:26.390 [error] <0.7353.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.390 [error] <0.7347.0> CRASH REPORT Process <0.7347.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-10 16:47:26.390 [error] <0.7352.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.476 [error] <0.4265.0> gen_server <0.4265.0> terminated with reason: killed
2016-04-10 16:47:26.476 [error] <0.1082.0> gen_server <0.1082.0> terminated with reason: killed
2016-04-10 16:47:26.476 [error] <0.4265.0> CRASH REPORT Process <0.4265.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.476 [error] <0.1082.0> CRASH REPORT Process <0.1082.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.476 [error] <0.1077.0> gen_server <0.1077.0> terminated with reason: killed
2016-04-10 16:47:26.476 [error] <0.1077.0> CRASH REPORT Process <0.1077.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 16:47:26.476 [error] <0.1024.0> CRASH REPORT Process <0.1024.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 16:47:26.476 [error] <0.4212.0> CRASH REPORT Process <0.4212.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
