--- Test run on 2016/04/10 22:43:52 ---
Converting "/home/travis/build/lrascao/mnesia2/." to "/home/travis/build/lrascao/mnesia2" and re-inserting with add_patha/1


Common Test v1.11 starting (cwd is /home/travis/build/lrascao/mnesia2)


Common Test: Running make in test directories...
Recompile: mnesia2_extra_light_SUITE
Recompile: ts_install_cth
ts_install_cth.erl:247: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
Recompile: mt
Recompile: mnesia2_trans_access_test
Recompile: mnesia2_tpcb
Recompile: mnesia2_test_lib
Recompile: mnesia2_schema_recovery_test
mnesia2_schema_recovery_test.erl:261: Warning: variable 'Bad' is unused
Recompile: mnesia2_registry_test
Recompile: mnesia2_recovery_test
mnesia2_recovery_test.erl:1571: Warning: variable 'Config' is unused
Recompile: mnesia2_qlc_test
Recompile: mnesia2_nice_coverage_test
Recompile: mnesia2_meter
Recompile: mnesia2_measure_test
Recompile: mnesia2_majority_test
Recompile: mnesia2_isolation_test
Recompile: mnesia2_install_test
Recompile: mnesia2_inconsistent_database_test
Recompile: mnesia2_frag_test
Recompile: mnesia2_frag_hash_test
Recompile: mnesia2_examples_test
Recompile: mnesia2_evil_coverage_test
Recompile: mnesia2_evil_backup
Recompile: mnesia2_durability_test
Recompile: mnesia2_dirty_access_test
Recompile: mnesia2_dbn_meters
Recompile: mnesia2_cost
Recompile: mnesia2_consistency_test
Recompile: mnesia2_config_test
Recompile: mnesia2_config_event
Recompile: mnesia2_config_backup
Recompile: mnesia2_atomicity_test

CWD set to: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13.2016-04-10_22.43.52"

TEST INFO: 1 test(s), 52 case(s) in 1 suite(s)

Cover compiling 'mnesia2' (32 files) - this may take some time... done

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: Starting test, 52 test cases

----------------------------------------------------
2016-04-10 22:44:12.080
starting test group: extra_light


----------------------------------------------------
2016-04-10 22:44:12.105
starting test group: install


----------------------------------------------------
2016-04-10 22:44:12.183
starting test case: silly_durability

22:44:12.262 [info] Application lager started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:12.262 [info] Application poolgirl started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:12.300 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.495.0>
22:44:12.320 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.563.0>

----------------------------------------------------
2016-04-10 22:44:12.324
ending test case: silly_durability


----------------------------------------------------
2016-04-10 22:44:12.349
starting test case: silly_move

22:44:12.818 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.673.0>
22:44:13.044 [info] Application lager started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:13.044 [info] Application poolgirl started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:13.095 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.100.0>
22:44:13.113 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'

----------------------------------------------------
2016-04-10 22:44:13.208
ending test case: silly_move


----------------------------------------------------
2016-04-10 22:44:13.234
starting test case: silly_upgrade

22:44:13.239 [error] CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:13.239 [info] Application mnesia2 exited with reason: killed
22:44:13.236 [error] gen_server <0.156.0> terminated with reason: killed
22:44:13.236 [error] CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:13.236 [error] CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:13.237 [info] Application mnesia2 exited with reason: killed
22:44:13.302 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.799.0>
22:44:13.304 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:13.321 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.216.0>
22:44:13.538 [error] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'...

22:44:13.538 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.797.0> exit with reason killed in context child_terminated
22:44:13.539 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.797.0> exit with reason reached_max_restart_intensity in context shutdown
22:44:13.560 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.927.0>
22:44:13.583 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.369.0>
22:44:14.127 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
22:44:14.127 [info] Application mnesia2 exited with reason: stopped
22:44:14.127 [info] Application mnesia2 exited with reason: stopped
22:44:14.158 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1027.0>
22:44:14.163 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:14.178 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.459.0>
22:44:14.182 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'

----------------------------------------------------
2016-04-10 22:44:14.692
ending test case: silly_upgrade


----------------------------------------------------
2016-04-10 22:44:14.771
ending test group: install


----------------------------------------------------
2016-04-10 22:44:14.796
starting test group: nice


----------------------------------------------------
2016-04-10 22:44:14.874
starting test case: nice

22:44:14.877 [error] CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:14.877 [info] Application mnesia2 exited with reason: killed
22:44:14.877 [error] gen_server mnesia2_subscr terminated with reason: killed
22:44:14.877 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:14.877 [error] gen_server mnesia2_monitor terminated with reason: killed
22:44:14.877 [error] gen_server mnesia2_recover terminated with reason: killed
22:44:14.877 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:14.948 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1150.0>
22:44:14.951 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.549.0>
22:44:15.061 [warning] lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
22:44:15.061 [info] Application mnesia2 exited with reason: stopped
22:44:15.072 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1262.0>
22:44:15.078 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'

----------------------------------------------------
2016-04-10 22:44:15.240
ending test case: nice


----------------------------------------------------
2016-04-10 22:44:15.321
ending test group: nice


----------------------------------------------------
2016-04-10 22:44:15.346
starting test group: qlc


----------------------------------------------------
2016-04-10 22:44:15.449
starting test case: dirty_nice_ram_copies

22:44:15.451 [warning] lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
22:44:15.451 [error] CRASH REPORT Process <0.1253.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:15.452 [info] Application mnesia2 exited with reason: killed
22:44:15.451 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.564.0> exit with reason killed in context child_terminated
22:44:15.451 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.564.0> exit with reason reached_max_restart_intensity in context shutdown
22:44:15.451 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.562.0> exit with reason killed in context shutdown_error
22:44:15.452 [error] CRASH REPORT Process <0.540.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:15.453 [info] Application mnesia2 exited with reason: killed
22:44:15.506 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1494.0>
22:44:15.513 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.764.0>
22:44:15.517 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'

----------------------------------------------------
2016-04-10 22:44:15.589
ending test case: dirty_nice_ram_copies


----------------------------------------------------
2016-04-10 22:44:15.616
starting test case: dirty_nice_disc_copies

22:44:15.618 [error] gen_server <0.797.0> terminated with reason: killed
22:44:15.670 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1608.0>
22:44:15.686 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.862.0>

----------------------------------------------------
2016-04-10 22:44:16.079
ending test case: dirty_nice_disc_copies


----------------------------------------------------
2016-04-10 22:44:16.104
starting test case: dirty_nice_disc_only_copies

22:44:16.108 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
22:44:16.108 [error] CRASH REPORT Process <0.1599.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:16.106 [error] gen_server <0.915.0> terminated with reason: killed
22:44:16.108 [info] Application mnesia2 exited with reason: killed
22:44:16.107 [error] CRASH REPORT Process <0.915.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:16.107 [error] CRASH REPORT Process <0.853.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:16.107 [info] Application mnesia2 exited with reason: killed
22:44:16.171 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1725.0>
22:44:16.173 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:16.186 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.964.0>
22:44:16.199 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'

----------------------------------------------------
2016-04-10 22:44:16.312
ending test case: dirty_nice_disc_only_copies


----------------------------------------------------
2016-04-10 22:44:16.388
starting test case: trans_nice_ram_copies

22:44:16.390 [error] gen_server <0.1016.0> terminated with reason: killed
22:44:16.390 [error] CRASH REPORT Process <0.1016.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:16.393 [error] CRASH REPORT Process <0.1716.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:16.393 [info] Application mnesia2 exited with reason: killed
22:44:16.448 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1851.0>
22:44:16.451 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1070.0>

----------------------------------------------------
2016-04-10 22:44:16.596
ending test case: trans_nice_ram_copies


----------------------------------------------------
2016-04-10 22:44:16.622
starting test case: trans_nice_disc_copies

22:44:16.678 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1982.0>
22:44:16.693 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1169.0>

----------------------------------------------------
2016-04-10 22:44:16.844
ending test case: trans_nice_disc_copies


----------------------------------------------------
2016-04-10 22:44:16.871
starting test case: trans_nice_disc_only_copies

22:44:16.932 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2115.0>
22:44:16.934 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1270.0>
22:44:17.235 [warning] lager_error_logger_h dropped 17 messages in the last second that exceeded the limit of 50 messages/sec
22:44:17.236 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'

----------------------------------------------------
2016-04-10 22:44:17.406
ending test case: trans_nice_disc_only_copies


----------------------------------------------------
2016-04-10 22:44:17.456
starting test case: atomic_eval

22:44:17.470 [error] CRASH REPORT Process <0.2106.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:17.470 [info] Application mnesia2 exited with reason: killed
22:44:17.470 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
22:44:17.470 [error] gen_server <0.1325.0> terminated with reason: killed
22:44:17.470 [error] CRASH REPORT Process <0.1325.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:17.471 [error] CRASH REPORT Process <0.1261.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:17.471 [info] Application mnesia2 exited with reason: killed
22:44:17.526 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2256.0>
22:44:17.532 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1377.0>
22:44:17.543 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'

----------------------------------------------------
2016-04-10 22:44:17.632
ending test case: atomic_eval


----------------------------------------------------
2016-04-10 22:44:17.707
starting test case: frag

22:44:17.709 [error] gen_server <0.1431.0> terminated with reason: killed
22:44:17.709 [error] CRASH REPORT Process <0.1431.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:17.775 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2387.0>
22:44:17.781 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1464.0>

----------------------------------------------------
2016-04-10 22:44:17.926
ending test case: frag


----------------------------------------------------
2016-04-10 22:44:17.952
starting test case: info

22:44:18.011 [warning] lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
22:44:18.010 [warning] lager_error_logger_h dropped 39 messages in the last second that exceeded the limit of 50 messages/sec
22:44:18.025 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2519.0>
22:44:18.027 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:18.038 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1576.0>
22:44:18.051 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'

----------------------------------------------------
2016-04-10 22:44:18.155
ending test case: info


----------------------------------------------------
2016-04-10 22:44:18.181
starting test case: mnesia2_down

22:44:18.183 [error] gen_server <0.1628.0> terminated with reason: killed
22:44:18.184 [error] CRASH REPORT Process <0.2510.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:18.185 [info] Application mnesia2 exited with reason: killed
22:44:18.183 [error] CRASH REPORT Process <0.1628.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:18.183 [error] CRASH REPORT Process <0.1567.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:18.183 [info] Application mnesia2 exited with reason: killed
22:44:18.234 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2642.0>
22:44:18.250 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1663.0>
---> Participant transactions <--- 
---> Coordinator transactions <---
Tid: 14 (owned by <0.2720.0>) 

----------------------------------------------------
2016-04-10 22:44:18.611
ending test case: mnesia2_down


----------------------------------------------------
2016-04-10 22:44:18.690
ending test group: qlc


----------------------------------------------------
2016-04-10 22:44:18.729
starting test group: registry


----------------------------------------------------
2016-04-10 22:44:18.807
starting test case: good_dump

22:44:18.845 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2771.0>

----------------------------------------------------
2016-04-10 22:44:18.855
ending test case: good_dump


----------------------------------------------------
2016-04-10 22:44:18.880
starting test case: bad_dump

22:44:18.917 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2865.0>

----------------------------------------------------
2016-04-10 22:44:18.925
ending test case: bad_dump


----------------------------------------------------
2016-04-10 22:44:19.004
ending test group: registry


----------------------------------------------------
2016-04-10 22:44:19.029
starting test group: config


----------------------------------------------------
2016-04-10 22:44:19.107
starting test case: access_module

22:44:20.193 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:44:20.198 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2975.0>
22:44:20.200 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:21.400 [error] CRASH REPORT Process <0.2966.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:21.400 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:44:22.423
ending test case: access_module


----------------------------------------------------
2016-04-10 22:44:22.450
starting test case: auto_repair

22:44:23.480 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3081.0>
22:44:23.482 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:23.484 [info] Application mnesia2 exited with reason: stopped
22:44:23.486 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3129.0>
22:44:23.490 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3177.0>

----------------------------------------------------
2016-04-10 22:44:24.505
ending test case: auto_repair


----------------------------------------------------
2016-04-10 22:44:24.531
starting test case: backup_module

22:44:25.570 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3249.0>
22:44:25.572 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:25.584 [error] CRASH REPORT Process <0.3240.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:25.584 [info] Application mnesia2 exited with reason: killed
22:44:27.618 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3332.0>
22:44:27.621 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:28.849 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

22:44:28.849 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13.2016-04-10_22.43.52/Mnesia2.test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13/LATEST.LOG"] -> badarg

22:44:28.850 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3327.0> exit with reason killed in context child_terminated
22:44:28.850 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3327.0> exit with reason reached_max_restart_intensity in context shutdown
22:44:28.851 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_tm_26 terminated: shutdown

22:44:28.851 [error] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_27,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

22:44:28.851 [error] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_32,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

22:44:28.851 [error] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_31,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_31,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

22:44:28.851 [error] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_30,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_30,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

22:44:28.851 [error] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_22,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_22,shutdown]}}}} ({error,{already_started,<0.3412.0>}})

22:44:28.851 [error] CRASH REPORT Process <0.3323.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:28.851 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:44:29.873
ending test case: backup_module


----------------------------------------------------
2016-04-10 22:44:29.918
starting test case: debug

22:44:30.948 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_monitor starting: <0.3435.0>

22:44:30.949 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Mnesia2 debug level set to verbose
22:44:30.950 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_subscr starting: <0.3436.0>

22:44:30.950 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3439.0>
22:44:30.953 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:30.954 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_tm_1 terminated: shutdown

22:44:30.955 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_tm_3 terminated: shutdown

22:44:30.955 [error] CRASH REPORT Process <0.3430.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:30.956 [info] Application mnesia2 exited with reason: killed
22:44:32.976 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_monitor starting: <0.3485.0>

22:44:32.977 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Version: "1.0.0"

22:44:32.977 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env access_module: mnesia2

22:44:32.977 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env auto_repair: true

22:44:32.977 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env backup_module: mnesia2_backup

22:44:32.977 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env debug: debug

22:44:32.977 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13.2016-04-10_22.43.52/Mnesia2.test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13"

22:44:32.977 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_disc_copies_at_startup: true

22:44:32.978 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_log_load_regulation: false

22:44:32.978 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_log_time_threshold: 180000

22:44:32.978 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_log_update_in_place: true

22:44:32.978 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_log_write_threshold: 1000

22:44:32.978 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env event_module: mnesia2_event

22:44:32.978 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env extra_db_nodes: []

22:44:32.979 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env ignore_fallback_at_startup: false

22:44:32.979 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env fallback_error_function: {mnesia2,lkill}

22:44:32.979 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env max_wait_for_decision: infinity

22:44:32.979 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env schema_location: opt_disc

22:44:32.979 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env core_dir: false

22:44:32.979 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env pid_sort_order: false

22:44:32.980 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env no_table_loaders: 2

22:44:32.980 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dc_dump_limit: 4

22:44:32.981 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3489.0>
22:44:32.981 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env send_compressed: 0

22:44:32.981 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env send_max_packets: 20

22:44:32.982 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env send_max_transfer_size: 7500

22:44:32.982 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env async_dirty_buffer_size: 524288

22:44:32.983 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env async_dirty_max_buffer_file_size: 100000000

22:44:32.983 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env async_dirty_tx_backlog_threshold: 200000

22:44:32.983 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env async_dirty_buffer_min_runtime: 10000

22:44:32.984 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env async_dirty_buffer_drained_cutoff: 5

22:44:32.984 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Mnesia2 debug level set to debug
22:44:32.984 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_subscr starting: <0.3486.0>

22:44:32.984 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_locker starting: <0.3487.0>

22:44:32.985 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_recover starting: <0.3488.0>

22:44:32.985 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_tm starting: <0.3489.0>

22:44:32.985 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Schema initiated from: default

22:44:32.985 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
22:44:32.986 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_controller starting: <0.3492.0>

22:44:32.986 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_late_loader starting: <0.3493.0>

22:44:32.986 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Intend to load tables: []

22:44:32.987 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): debug fun {mnesia2_controller,late_disc_load} in ets mnesia2_debug does not exist, ignoring
22:44:32.987 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:32.987 [error] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}}} ({error,{already_started,<0.3528.0>}})

22:44:32.987 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_tm_2 terminated: shutdown

22:44:32.987 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_tm_3 terminated: shutdown

22:44:32.988 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_tm_5 terminated: shutdown

22:44:32.988 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_tm_4 terminated: shutdown

22:44:32.988 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_tm_7 terminated: shutdown

22:44:32.988 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_tm_9 terminated: shutdown

22:44:32.988 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_tm_8 terminated: shutdown

22:44:32.988 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_tm_11 terminated: shutdown

22:44:32.989 [error] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}}} ({error,{already_started,<0.3530.0>}})

22:44:32.989 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_tm_22 terminated: shutdown

22:44:32.989 [error] CRASH REPORT Process <0.3480.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:35.018 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_monitor starting: <0.3539.0>

22:44:35.018 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Version: "1.0.0"

22:44:35.018 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env access_module: mnesia2

22:44:35.018 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env auto_repair: true

22:44:35.019 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env backup_module: mnesia2_backup

22:44:35.019 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env debug: trace

22:44:35.019 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13.2016-04-10_22.43.52/Mnesia2.test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13"

22:44:35.020 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3543.0>
22:44:35.020 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_disc_copies_at_startup: true

22:44:35.020 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_log_load_regulation: false

22:44:35.020 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_log_time_threshold: 180000

22:44:35.021 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_log_update_in_place: true

22:44:35.021 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_log_write_threshold: 1000

22:44:35.021 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env event_module: mnesia2_event

22:44:35.021 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env extra_db_nodes: []

22:44:35.022 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env ignore_fallback_at_startup: false

22:44:35.022 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env fallback_error_function: {mnesia2,lkill}

22:44:35.023 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env max_wait_for_decision: infinity

22:44:37.046 [warning] lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
22:44:37.047 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): mnesia2_monitor starting: <0.3591.0>

22:44:37.047 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Version: "1.0.0"

22:44:37.047 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env access_module: mnesia2

22:44:37.048 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env auto_repair: true

22:44:37.048 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env backup_module: mnesia2_backup

22:44:37.048 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env debug: debug

22:44:37.048 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3595.0>
22:44:37.049 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13.2016-04-10_22.43.52/Mnesia2.test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13"

22:44:37.049 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_disc_copies_at_startup: true

22:44:37.049 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_log_load_regulation: false

22:44:37.049 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_log_time_threshold: 180000

22:44:37.049 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_log_update_in_place: true

22:44:37.050 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env dump_log_write_threshold: 1000

22:44:37.050 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env event_module: mnesia2_event

22:44:37.051 [info] Mnesia2('test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): Env extra_db_nodes: []

22:44:39.074 [warning] lager_error_logger_h dropped 11 messages in the last second that exceeded the limit of 50 messages/sec
22:44:39.076 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3652.0>
22:44:39.078 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:39.079 [error] CRASH REPORT Process <0.3643.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:39.079 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:44:40.102
ending test case: debug


----------------------------------------------------
2016-04-10 22:44:40.129
starting test case: dir

22:44:41.158 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3716.0>
22:44:41.160 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:41.162 [error] CRASH REPORT Process <0.3707.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:41.162 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:44:42.197
ending test case: dir


----------------------------------------------------
2016-04-10 22:44:42.224
starting test case: dump_log_load_regulation

22:44:42.250 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3787.0>
22:44:42.252 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:44:42.254 [info] Application mnesia2 exited with reason: stopped
22:44:42.260 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3848.0>
22:44:57.299 [error] CRASH REPORT Process <0.3839.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:57.299 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:44:58.322
ending test case: dump_log_load_regulation


----------------------------------------------------
2016-04-10 22:44:58.376
starting test case: dump_log_time_threshold

22:44:59.421 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4443.0>
22:44:59.424 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:05.433 [error] CRASH REPORT Process <0.4434.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:05.433 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:45:06.456
ending test case: dump_log_time_threshold


----------------------------------------------------
2016-04-10 22:45:06.483
starting test case: dump_log_write_threshold

22:45:07.531 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4543.0>
22:45:07.534 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:08.553 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:45:09.567
ending test case: dump_log_write_threshold


----------------------------------------------------
2016-04-10 22:45:09.624
starting test case: dump_log_update_in_place

22:45:10.675 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4659.0>
22:45:10.678 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:10.683 [error] CRASH REPORT Process <0.4650.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:10.683 [info] Application mnesia2 exited with reason: killed
22:45:12.726 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4726.0>
22:45:12.729 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:12.753 [error] CRASH REPORT Process <0.4717.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:12.753 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:45:13.776
ending test case: dump_log_update_in_place


----------------------------------------------------
2016-04-10 22:45:13.803
starting test case: event_module

22:45:14.869 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:45:14.882 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4818.0>
22:45:14.884 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:14.891 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1791.0>
22:45:14.901 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'}}
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'}}
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'}}
22:45:15.903 [error] gen_server <0.1843.0> terminated with reason: killed
22:45:15.903 [error] CRASH REPORT Process <0.1843.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:15.904 [error] CRASH REPORT Process <0.1782.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:15.904 [info] Application mnesia2 exited with reason: killed
22:45:17.942 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1859.0>
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'}}
22:45:17.960 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'}}
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'}}
22:45:18.963 [error] gen_server <0.4881.0> terminated with reason: killed
22:45:18.963 [error] CRASH REPORT Process <0.4881.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:18.964 [error] CRASH REPORT Process <0.4809.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:18.964 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:45:19.987
ending test case: event_module


----------------------------------------------------
2016-04-10 22:45:20.015
starting test case: inconsistent_database

22:45:20.018 [error] CRASH REPORT Process <0.1850.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:20.018 [info] Application mnesia2 exited with reason: killed
22:45:21.104 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4924.0>
22:45:21.106 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:21.121 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1941.0>
22:45:21.124 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:21.125 [error] gen_server <0.4978.0> terminated with reason: killed
22:45:21.125 [error] CRASH REPORT Process <0.4978.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:21.126 [error] CRASH REPORT Process <0.4915.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:21.127 [error] gen_server <0.1975.0> terminated with reason: killed
22:45:21.126 [info] Application mnesia2 exited with reason: killed
22:45:21.127 [error] CRASH REPORT Process <0.1975.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:21.128 [error] CRASH REPORT Process <0.1931.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:21.129 [info] Application mnesia2 exited with reason: killed
22:45:21.171 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.5004.0>
22:45:27.228 [info] Application mnesia2 exited with reason: stopped
22:45:27.358 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2015.0>
22:45:27.360 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:27.369 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.5128.0>
22:45:27.376 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:39.070 [info] Application mnesia2 exited with reason: stopped
22:45:39.071 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:45:40.102
ending test case: inconsistent_database


----------------------------------------------------
2016-04-10 22:45:40.130
starting test case: max_wait_for_decision


----------------------------------------------------
2016-04-10 22:45:40.130
ending test case: max_wait_for_decision


----------------------------------------------------
2016-04-10 22:45:40.172
starting test case: send_compressed

22:45:40.222 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.5259.0>
22:45:40.225 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:40.226 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2137.0>
22:45:40.230 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:40.281 [error] gen_server <0.2189.0> terminated with reason: killed
22:45:40.281 [error] CRASH REPORT Process <0.2189.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:40.282 [error] CRASH REPORT Process <0.2128.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:40.282 [info] Application mnesia2 exited with reason: killed
22:45:40.303 [error] CRASH REPORT Process <0.5250.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:40.303 [info] Application mnesia2 exited with reason: killed
22:45:40.336 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.5347.0>
22:45:40.582 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2225.0>

----------------------------------------------------
2016-04-10 22:45:41.994
ending test case: send_compressed


----------------------------------------------------
2016-04-10 22:45:42.035
starting test case: app_test


----------------------------------------------------
2016-04-10 22:45:42.042
ending test case: app_test


----------------------------------------------------
2016-04-10 22:45:42.094
starting test case: start_one_disc_full_then_one_disc_less

22:45:42.106 [warning] lager_error_logger_h dropped 12 messages in the last second that exceeded the limit of 50 messages/sec
22:45:42.106 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2244.0> exit with reason killed in context child_terminated
22:45:42.106 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2244.0> exit with reason reached_max_restart_intensity in context shutdown
22:45:42.108 [error] CRASH REPORT Process <0.2216.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:42.108 [info] Application mnesia2 exited with reason: killed
22:45:43.161 [warning] lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
22:45:43.166 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.5470.0>
22:45:43.168 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:43.188 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2329.0>
22:45:43.199 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:43.224 [error] gen_server <0.5534.0> terminated with reason: killed
22:45:43.224 [error] CRASH REPORT Process <0.5534.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:43.225 [error] CRASH REPORT Process <0.5461.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:43.225 [info] Application mnesia2 exited with reason: killed
22:45:43.226 [error] gen_server <0.2340.0> terminated with reason: killed
22:45:43.226 [error] CRASH REPORT Process <0.2340.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:43.227 [error] CRASH REPORT Process <0.2320.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:43.227 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:45:44.250
ending test case: start_one_disc_full_then_one_disc_less


----------------------------------------------------
2016-04-10 22:45:44.276
starting test case: start_first_one_disc_less_then_one_disc_full

22:45:45.327 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.5581.0>
22:45:45.329 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:45.334 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2404.0>
22:45:45.366 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:45.368 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2406.0> exit with reason killed in context child_terminated
22:45:45.370 [error] CRASH REPORT Process <0.5572.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:45.370 [info] Application mnesia2 exited with reason: killed
22:45:45.369 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2406.0> exit with reason reached_max_restart_intensity in context shutdown
22:45:45.369 [error] gen_server <0.2413.0> terminated with reason: killed
22:45:45.369 [error] CRASH REPORT Process <0.2413.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:45.369 [error] CRASH REPORT Process <0.2395.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:45.369 [info] Application mnesia2 exited with reason: killed
22:45:47.398 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2464.0>
22:45:47.403 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.5661.0>
22:45:47.409 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:47.702 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:47.715 [error] gen_server <0.5722.0> terminated with reason: killed
22:45:47.715 [error] CRASH REPORT Process <0.5722.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:47.716 [error] CRASH REPORT Process <0.5652.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:47.716 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:45:48.738
ending test case: start_first_one_disc_less_then_one_disc_full


----------------------------------------------------
2016-04-10 22:45:48.765
starting test case: start_first_one_disc_less_then_two_more_disc_less

22:45:49.165 [error] CRASH REPORT Process <0.2454.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:49.165 [info] Application mnesia2 exited with reason: killed
22:45:50.245 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.5788.0>
22:45:50.248 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:50.250 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2550.0>
22:45:50.253 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:50.480 [info] Application lager started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:50.480 [info] Application poolgirl started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:50.504 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.101.0>
22:45:50.521 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:50.563 [error] gen_server <0.5841.0> terminated with reason: killed
22:45:50.564 [error] gen_server <0.2562.0> terminated with reason: killed
22:45:50.564 [error] CRASH REPORT Process <0.2562.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:50.564 [error] CRASH REPORT Process <0.5841.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:50.564 [error] gen_server <0.5833.0> terminated with reason: killed
22:45:50.565 [error] gen_server <0.2601.0> terminated with reason: killed
22:45:50.564 [error] CRASH REPORT Process <0.5833.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:50.565 [error] CRASH REPORT Process <0.2601.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:50.564 [error] CRASH REPORT Process <0.5779.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:50.564 [info] Application mnesia2 exited with reason: killed
22:45:50.565 [error] CRASH REPORT Process <0.2541.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:50.566 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:45:51.595
ending test case: start_first_one_disc_less_then_two_more_disc_less


----------------------------------------------------
2016-04-10 22:45:51.631
starting test case: schema_location_and_extra_db_nodes_combinations

22:45:52.679 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.5883.0>
22:45:52.681 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:52.687 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2631.0>
22:45:52.692 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:52.696 [error] gen_server <0.5947.0> terminated with reason: killed
22:45:52.695 [error] gen_server <0.2642.0> terminated with reason: killed
22:45:52.695 [error] CRASH REPORT Process <0.2642.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:52.697 [error] CRASH REPORT Process <0.5947.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:52.696 [error] CRASH REPORT Process <0.2622.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:52.696 [info] Application mnesia2 exited with reason: killed
22:45:52.698 [error] CRASH REPORT Process <0.5874.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:52.698 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:45:53.731
ending test case: schema_location_and_extra_db_nodes_combinations


----------------------------------------------------
2016-04-10 22:45:53.758
starting test case: table_load_to_disc_less_nodes

22:45:54.805 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.5977.0>
22:45:54.807 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:54.822 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2701.0>
22:45:54.826 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:54.830 [error] gen_server <0.6021.0> terminated with reason: killed
22:45:54.830 [error] gen_server <0.2710.0> terminated with reason: killed
22:45:54.830 [error] CRASH REPORT Process <0.6021.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:54.830 [error] CRASH REPORT Process <0.2710.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:54.831 [error] CRASH REPORT Process <0.5968.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:54.831 [info] Application mnesia2 exited with reason: killed
22:45:54.830 [error] CRASH REPORT Process <0.2692.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:54.831 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:45:55.854
ending test case: table_load_to_disc_less_nodes


----------------------------------------------------
2016-04-10 22:45:55.883
starting test case: schema_merge

22:45:57.181 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.6063.0>
22:45:57.183 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:57.187 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2776.0>
22:45:57.190 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:45:57.317 [error] gen_server <0.2830.0> terminated with reason: killed
22:45:57.317 [error] CRASH REPORT Process <0.2830.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:57.317 [error] CRASH REPORT Process <0.2767.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:57.317 [info] Application mnesia2 exited with reason: killed
22:45:58.382 [error] CRASH REPORT Process <0.6054.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:58.382 [info] Application mnesia2 exited with reason: killed
22:46:00.430 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2846.0>
22:46:00.432 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:05.463 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.6141.0>
22:46:05.472 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:05.487 [error] CRASH REPORT Process <0.6132.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:05.487 [info] Application mnesia2 exited with reason: killed
22:46:05.486 [error] Mnesia2('d701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.2843.0>,killed}

22:46:05.486 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.2841.0> exit with reason killed in context child_terminated
22:46:05.486 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.2841.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:05.486 [error] gen_server mnesia2_monitor terminated with reason: killed
22:46:05.486 [error] gen_server mnesia2_recover terminated with reason: killed
22:46:05.486 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:05.487 [error] CRASH REPORT Process <0.2837.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:05.487 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:46:06.511
ending test case: schema_merge


----------------------------------------------------
2016-04-10 22:46:06.562
starting test case: dynamic_basic

22:46:06.610 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
22:46:06.655 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.6252.0>
22:46:06.657 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:06.661 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2945.0>
22:46:06.674 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:06.687 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.191.0>
22:46:06.690 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:06.735 [error] gen_server <0.3006.0> terminated with reason: killed
22:46:06.735 [error] CRASH REPORT Process <0.3006.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:06.735 [error] gen_server <0.2997.0> terminated with reason: killed
22:46:06.735 [error] CRASH REPORT Process <0.2997.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:06.735 [error] CRASH REPORT Process <0.2936.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:06.735 [info] Application mnesia2 exited with reason: killed
22:46:06.761 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3036.0>
22:46:06.824 [error] gen_server <0.6357.0> terminated with reason: killed
22:46:06.824 [error] CRASH REPORT Process <0.6357.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:06.824 [error] gen_server <0.6316.0> terminated with reason: killed
22:46:06.824 [error] CRASH REPORT Process <0.6316.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:06.825 [error] gen_server <0.6339.0> terminated with reason: killed
22:46:06.846 [error] gen_server <0.274.0> terminated with reason: killed
22:46:07.012 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:46:07.012 [info] Application mnesia2 exited with reason: stopped
22:46:06.825 [error] CRASH REPORT Process <0.6339.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:06.846 [error] CRASH REPORT Process <0.274.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:07.147 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3131.0>
22:46:06.826 [error] CRASH REPORT Process <0.6243.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:06.826 [info] Application mnesia2 exited with reason: killed
22:46:07.149 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:07.199 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.295.0>
22:46:07.200 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.6374.0>
22:46:07.207 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:07.241 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:07.746 [error] gen_server <0.359.0> terminated with reason: killed
22:46:07.746 [error] CRASH REPORT Process <0.359.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:07.746 [error] gen_server <0.367.0> terminated with reason: killed
22:46:07.746 [error] CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:07.746 [error] CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:07.746 [info] Application mnesia2 exited with reason: killed
22:46:07.772 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.392.0>
22:46:09.836 [error] gen_server <0.6470.0> terminated with reason: killed
22:46:09.836 [error] CRASH REPORT Process <0.6470.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:09.836 [error] gen_server <0.6438.0> terminated with reason: killed
22:46:09.836 [error] CRASH REPORT Process <0.6438.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:09.837 [error] CRASH REPORT Process <0.6365.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:09.837 [info] Application mnesia2 exited with reason: killed
22:46:09.860 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3146.0> exit with reason killed in context child_terminated
22:46:09.861 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3146.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:09.861 [error] gen_server <0.3223.0> terminated with reason: killed
22:46:09.861 [error] CRASH REPORT Process <0.3223.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:09.861 [error] CRASH REPORT Process <0.3122.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:09.861 [info] Application mnesia2 exited with reason: killed
22:46:09.892 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
22:46:09.892 [info] Application mnesia2 exited with reason: stopped
22:46:09.932 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.498.0>
22:46:09.934 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:09.950 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.6489.0>
22:46:09.950 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3244.0>
22:46:09.958 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:09.974 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:10.477 [error] gen_server <0.566.0> terminated with reason: killed
22:46:10.477 [error] CRASH REPORT Process <0.566.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:10.477 [error] gen_server <0.573.0> terminated with reason: killed
22:46:10.478 [error] CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:10.478 [error] CRASH REPORT Process <0.489.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:10.478 [info] Application mnesia2 exited with reason: killed
22:46:10.504 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.597.0>
22:46:10.506 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:10.576 [error] gen_server <0.6559.0> terminated with reason: killed
22:46:10.576 [error] CRASH REPORT Process <0.6559.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:10.576 [error] gen_server <0.6583.0> terminated with reason: killed
22:46:10.576 [error] CRASH REPORT Process <0.6583.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:10.576 [error] gen_server <0.6578.0> terminated with reason: killed
22:46:10.576 [error] CRASH REPORT Process <0.6578.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:10.577 [error] CRASH REPORT Process <0.6480.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:10.577 [info] Application mnesia2 exited with reason: killed
22:46:10.598 [error] gen_server <0.3331.0> terminated with reason: killed
22:46:10.598 [error] CRASH REPORT Process <0.3331.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:10.598 [error] CRASH REPORT Process <0.3235.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:10.598 [info] Application mnesia2 exited with reason: killed
22:46:10.630 [info] Application mnesia2 exited with reason: stopped
22:46:10.652 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.698.0>
22:46:10.698 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.6600.0>
22:46:10.704 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3352.0>
22:46:10.714 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:11.003 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:11.513 [error] gen_server <0.3422.0> terminated with reason: killed
22:46:11.513 [error] CRASH REPORT Process <0.3422.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:11.513 [error] gen_server <0.3413.0> terminated with reason: killed
22:46:11.513 [error] CRASH REPORT Process <0.3413.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:11.514 [error] CRASH REPORT Process <0.3343.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:11.514 [info] Application mnesia2 exited with reason: killed
22:46:11.557 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3448.0>
22:46:11.579 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:11.592 [error] gen_server <0.3506.0> terminated with reason: killed
22:46:11.593 [error] CRASH REPORT Process <0.3506.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:11.593 [error] gen_server <0.3486.0> terminated with reason: killed
22:46:11.593 [error] CRASH REPORT Process <0.3486.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:11.593 [error] gen_server <0.3460.0> terminated with reason: killed
22:46:11.593 [error] CRASH REPORT Process <0.3460.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:11.593 [error] CRASH REPORT Process <0.3439.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:12.618 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3526.0>
22:46:12.626 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'

----------------------------------------------------
2016-04-10 22:46:12.641
ending test case: dynamic_basic


----------------------------------------------------
2016-04-10 22:46:12.667
starting test case: dynamic_ext

22:46:12.671 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
22:46:12.671 [error] CRASH REPORT Process <0.6591.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:12.671 [info] Application mnesia2 exited with reason: killed
22:46:12.673 [error] CRASH REPORT Process <0.3517.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:12.673 [info] Application mnesia2 exited with reason: killed
22:46:12.671 [error] gen_server <0.822.0> terminated with reason: killed
22:46:12.671 [error] CRASH REPORT Process <0.822.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:12.671 [error] gen_server <0.814.0> terminated with reason: killed
22:46:12.671 [error] CRASH REPORT Process <0.814.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:12.671 [error] gen_server <0.771.0> terminated with reason: killed
22:46:12.671 [error] CRASH REPORT Process <0.771.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:12.672 [error] CRASH REPORT Process <0.689.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:12.672 [info] Application mnesia2 exited with reason: killed
22:46:12.763 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.6746.0>
22:46:12.765 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:12.767 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3604.0>
22:46:12.855 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3699.0>
22:46:12.922 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3789.0>
22:46:13.519 [warning] lager_error_logger_h dropped 9 messages in the last second that exceeded the limit of 50 messages/sec
22:46:13.519 [error] gen_server <0.3853.0> terminated with reason: killed
22:46:13.615 [info] Application mnesia2 exited with reason: stopped
22:46:13.519 [error] CRASH REPORT Process <0.3853.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:13.519 [error] CRASH REPORT Process <0.3780.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:13.519 [info] Application mnesia2 exited with reason: killed
22:46:13.618 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3889.0>
22:46:13.619 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:14.298 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.6859.0>
22:46:14.314 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:14.342 [info] Application mnesia2 exited with reason: stopped
22:46:14.343 [error] gen_server <0.3944.0> terminated with reason: killed
22:46:14.343 [error] CRASH REPORT Process <0.3944.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:14.343 [error] CRASH REPORT Process <0.3880.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:14.343 [info] Application mnesia2 exited with reason: killed
22:46:14.379 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.6942.0>
22:46:14.885 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.3971.0>
22:46:14.896 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'

----------------------------------------------------
2016-04-10 22:46:14.931
ending test case: dynamic_ext


----------------------------------------------------
2016-04-10 22:46:14.957
starting test case: dynamic_bad

22:46:14.960 [error] gen_server <0.4017.0> terminated with reason: killed
22:46:14.960 [error] CRASH REPORT Process <0.4017.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:14.961 [error] CRASH REPORT Process <0.3962.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:14.961 [info] Application mnesia2 exited with reason: killed
22:46:15.004 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
22:46:15.033 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.7043.0>
22:46:15.036 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:15.039 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.849.0>
22:46:15.041 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4063.0>
22:46:15.063 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:15.343 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:15.835 [error] CRASH REPORT Process <0.7034.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:15.836 [info] Application mnesia2 exited with reason: killed
22:46:15.835 [error] gen_server <0.4125.0> terminated with reason: killed
22:46:15.837 [error] CRASH REPORT Process <0.840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:15.838 [info] Application mnesia2 exited with reason: killed
22:46:15.835 [error] CRASH REPORT Process <0.4125.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:15.835 [error] gen_server <0.4118.0> terminated with reason: killed
22:46:15.835 [error] CRASH REPORT Process <0.4118.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:15.835 [error] CRASH REPORT Process <0.4054.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:15.835 [info] Application mnesia2 exited with reason: killed
22:46:15.866 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.954.0>
22:46:15.867 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:15.869 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4155.0>
22:46:15.885 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.7154.0>
22:46:15.925 [error] gen_server <0.1013.0> terminated with reason: killed
22:46:15.925 [error] CRASH REPORT Process <0.1013.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:15.974 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1033.0>
22:46:15.976 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4233.0>
22:46:15.992 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.7246.0>
22:46:25.999 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec

----------------------------------------------------
2016-04-10 22:46:26.001
ending test case: dynamic_bad

22:46:25.999 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
22:46:25.999 [error] gen_server mnesia2_monitor terminated with reason: killed
22:46:25.999 [error] gen_server mnesia2_recover terminated with reason: killed
22:46:26.000 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:26.000 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
22:46:26.000 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:26.000 [error] gen_server mnesia2_subscr terminated with reason: killed
22:46:26.000 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:26.000 [error] CRASH REPORT Process <0.7237.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
22:46:26.000 [info] Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
22:46:26.000 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826

----------------------------------------------------
2016-04-10 22:46:26.079
starting test case: unknown_config

22:46:26.082 [warning] lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
22:46:26.082 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:46:26.082 [error] gen_server <0.4277.0> terminated with reason: killed
22:46:26.082 [error] gen_server <0.1082.0> terminated with reason: killed
22:46:26.082 [error] CRASH REPORT Process <0.4277.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:26.083 [error] CRASH REPORT Process <0.1082.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:26.083 [error] CRASH REPORT Process <0.4224.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:26.083 [info] Application mnesia2 exited with reason: killed
22:46:26.083 [error] gen_server <0.1077.0> terminated with reason: killed
22:46:26.083 [error] CRASH REPORT Process <0.1077.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:26.083 [error] CRASH REPORT Process <0.1024.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:26.083 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:46:28.135
ending test case: unknown_config


----------------------------------------------------
2016-04-10 22:46:28.232
ending test group: config


----------------------------------------------------
2016-04-10 22:46:28.258
starting test group: examples


----------------------------------------------------
2016-04-10 22:46:28.336
starting test case: bup


----------------------------------------------------
2016-04-10 22:46:28.373
ending test case: bup


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error detected: error
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: *** FAILED test case 41 of 52 ***

----------------------------------------------------
2016-04-10 22:46:28.402
starting test case: company


----------------------------------------------------
2016-04-10 22:46:28.403
ending test case: company


----------------------------------------------------
2016-04-10 22:46:28.429
starting test case: meter

22:46:28.471 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.7355.0>
22:46:28.473 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:32.783 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:46:32.803
ending test case: meter


----------------------------------------------------
2016-04-10 22:46:32.853
starting test case: replica_test

22:46:32.939 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.7491.0>
22:46:32.941 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4323.0>
22:46:32.949 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1130.0>
22:46:32.954 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:32.962 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:33.246 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:39.335 [info] Application mnesia2 exited with reason: stopped
22:46:39.339 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:46:39.366
ending test case: replica_test

22:46:39.366 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:46:39.393
starting test case: sticky_replica_test

22:46:39.464 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.7621.0>
22:46:39.466 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:39.483 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4437.0>
22:46:39.501 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1248.0>
22:46:39.505 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:39.806 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:45.869 [info] Application mnesia2 exited with reason: stopped
22:46:45.874 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:46:45.888
ending test case: sticky_replica_test

22:46:45.887 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:46:45.922
starting test case: dist_test

22:46:46.020 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.7751.0>
22:46:46.022 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:46.040 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4553.0>
22:46:46.044 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:46:46.047 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.1361.0>
22:46:46.058 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:03.590 [info] Application mnesia2 exited with reason: stopped
22:47:03.608 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:03.616
ending test case: dist_test

22:47:03.596 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:03.656
starting test case: conflict_test

22:47:03.749 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.8890.0>
22:47:03.751 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.5678.0>
22:47:03.754 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2483.0>
22:47:03.766 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:04.056 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:04.192 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:10.650 [info] Application mnesia2 exited with reason: stopped
22:47:10.655 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:10.656
ending test case: conflict_test

22:47:10.655 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:10.683
starting test case: frag_test

22:47:10.758 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.9029.0>
22:47:10.760 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:10.780 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.2608.0>
22:47:10.798 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.5806.0>
22:47:10.802 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:11.102 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:17.382 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:17.384
ending test case: frag_test

22:47:17.383 [info] Application mnesia2 exited with reason: stopped
22:47:17.383 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:17.411
starting test case: frag2_test

22:47:17.518 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.10510.0>
22:47:17.519 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.7275.0>
22:47:17.523 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4080.0>
22:47:17.533 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:17.825 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:17.844 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:24.080 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:24.087
ending test case: frag2_test

22:47:24.081 [info] Application mnesia2 exited with reason: stopped
22:47:24.080 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:24.115
starting test case: remote_test

22:47:24.196 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.12284.0>
22:47:24.200 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:24.234 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.8342.0>
22:47:24.238 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:24.242 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4739.0>
22:47:24.254 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:30.396 [info] Application mnesia2 exited with reason: stopped
22:47:30.401 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:30.419
ending test case: remote_test

22:47:30.418 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:30.446
starting test case: remote_frag2_test

22:47:30.529 [info] starting mnesia2_tm, 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.12414.0>
22:47:30.531 [info] starting mnesia2_tm, 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.4852.0>
22:47:30.546 [info] starting mnesia2_tm, 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13', <0.9136.0>
22:47:30.551 [info] Application mnesia2 started on node 'd701794o701786n701786@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:30.843 [info] Application mnesia2 started on node 'test5133@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:30.846 [info] Application mnesia2 started on node 'd701788o701984n701984@testing-worker-linux-docker-26d6cbdf-3358-linux-13'
22:47:37.046 [info] Application mnesia2 exited with reason: stopped
22:47:37.052 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:37.067
ending test case: remote_frag2_test

22:47:37.067 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:37.174
ending test group: examples


----------------------------------------------------
2016-04-10 22:47:37.200
ending test group: extra_light


----------------------------------------------------
2016-04-10 22:47:37.225
starting test case: clean_up_suite


----------------------------------------------------
2016-04-10 22:47:37.244
ending test case: clean_up_suite

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: TEST COMPLETE, 51 ok, 1 failed of 52 test cases

Cover analysing... done

Updating /home/travis/build/lrascao/mnesia2/logs/index.html... done
Updating /home/travis/build/lrascao/mnesia2/logs/all_runs.html... done

