--- Test run on 2016/04/10 22:43:56 ---
Converting "/home/travis/build/lrascao/mnesia2/." to "/home/travis/build/lrascao/mnesia2" and re-inserting with add_patha/1


Common Test v1.11.1 starting (cwd is /home/travis/build/lrascao/mnesia2)


Common Test: Running make in test directories...
Recompile: mnesia2_extra_light_SUITE
Recompile: ts_install_cth
ts_install_cth.erl:247: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
Recompile: mt
Recompile: mnesia2_trans_access_test
Recompile: mnesia2_tpcb
Recompile: mnesia2_test_lib
Recompile: mnesia2_schema_recovery_test
mnesia2_schema_recovery_test.erl:261: Warning: variable 'Bad' is unused
Recompile: mnesia2_registry_test
Recompile: mnesia2_recovery_test
mnesia2_recovery_test.erl:1571: Warning: variable 'Config' is unused
Recompile: mnesia2_qlc_test
Recompile: mnesia2_nice_coverage_test
Recompile: mnesia2_meter
Recompile: mnesia2_measure_test
Recompile: mnesia2_majority_test
Recompile: mnesia2_isolation_test
Recompile: mnesia2_install_test
Recompile: mnesia2_inconsistent_database_test
Recompile: mnesia2_frag_test
Recompile: mnesia2_frag_hash_test
Recompile: mnesia2_examples_test
Recompile: mnesia2_evil_coverage_test
Recompile: mnesia2_evil_backup
Recompile: mnesia2_durability_test
Recompile: mnesia2_dirty_access_test
Recompile: mnesia2_dbn_meters
Recompile: mnesia2_cost
Recompile: mnesia2_consistency_test
Recompile: mnesia2_config_test
Recompile: mnesia2_config_event
Recompile: mnesia2_config_backup
Recompile: mnesia2_atomicity_test

CWD set to: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test8686@testing-worker-linux-docker-e93d2010-3388-linux-10.2016-04-10_22.43.57"

TEST INFO: 1 test(s), 52 case(s) in 1 suite(s)

Cover compiling 'mnesia2' (32 files) - this may take some time... done

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: Starting test, 52 test cases

----------------------------------------------------
2016-04-10 22:44:29.264
starting test group: extra_light


----------------------------------------------------
2016-04-10 22:44:29.292
starting test group: install


----------------------------------------------------
2016-04-10 22:44:29.379
starting test case: silly_durability

22:44:29.493 [info] Application lager started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:29.493 [info] Application poolgirl started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:29.527 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.495.0>
22:44:29.552 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.563.0>

----------------------------------------------------
2016-04-10 22:44:29.558
ending test case: silly_durability


----------------------------------------------------
2016-04-10 22:44:29.586
starting test case: silly_move

22:44:30.071 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:44:30.071 [error] CRASH REPORT Process <0.554.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:30.071 [info] Application mnesia2 exited with reason: killed
22:44:30.206 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.673.0>
22:44:30.215 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:30.570 [info] Application lager started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:30.570 [info] Application poolgirl started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:30.658 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.100.0>

----------------------------------------------------
2016-04-10 22:44:30.840
ending test case: silly_move


----------------------------------------------------
2016-04-10 22:44:30.877
starting test case: silly_upgrade

22:44:30.882 [error] gen_server <0.730.0> terminated with reason: killed
22:44:30.882 [error] CRASH REPORT Process <0.730.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:30.883 [error] CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:30.945 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.799.0>
22:44:30.962 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.216.0>
22:44:31.277 [info] Application mnesia2 exited with reason: stopped
22:44:31.279 [warning] lager_error_logger_h dropped 39 messages in the last second that exceeded the limit of 50 messages/sec
22:44:31.279 [error] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'...

22:44:31.280 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.797.0> exit with reason killed in context child_terminated
22:44:31.280 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.797.0> exit with reason reached_max_restart_intensity in context shutdown
22:44:31.283 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason shutdown in context child_terminated
22:44:31.283 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason reached_max_restart_intensity in context shutdown
22:44:31.285 [info] Application mnesia2 exited with reason: shutdown
22:44:31.312 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.927.0>
22:44:31.316 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:31.342 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.369.0>
22:44:31.353 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:31.406 [info] Application mnesia2 exited with reason: stopped
22:44:31.432 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1027.0>
22:44:31.464 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.459.0>

----------------------------------------------------
2016-04-10 22:44:31.990
ending test case: silly_upgrade


----------------------------------------------------
2016-04-10 22:44:32.110
ending test group: install


----------------------------------------------------
2016-04-10 22:44:32.138
starting test group: nice


----------------------------------------------------
2016-04-10 22:44:32.256
starting test case: nice

22:44:32.259 [warning] lager_error_logger_h dropped 28 messages in the last second that exceeded the limit of 50 messages/sec
22:44:32.261 [error] CRASH REPORT Process <0.1018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:32.261 [info] Application mnesia2 exited with reason: killed
22:44:32.259 [error] gen_server <0.517.0> terminated with reason: killed
22:44:32.259 [error] CRASH REPORT Process <0.517.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:32.260 [error] CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:32.260 [info] Application mnesia2 exited with reason: killed
22:44:32.347 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1150.0>
22:44:32.351 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.548.0>
22:44:32.363 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:32.656 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:32.809 [info] Application mnesia2 exited with reason: stopped
22:44:32.824 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1263.0>

----------------------------------------------------
2016-04-10 22:44:33.055
ending test case: nice


----------------------------------------------------
2016-04-10 22:44:33.148
ending test group: nice


----------------------------------------------------
2016-04-10 22:44:33.178
starting test group: qlc


----------------------------------------------------
2016-04-10 22:44:33.296
starting test case: dirty_nice_ram_copies

22:44:33.303 [error] gen_server <0.662.0> terminated with reason: killed
22:44:33.305 [error] gen_server <0.1301.0> terminated with reason: killed
22:44:33.303 [error] CRASH REPORT Process <0.662.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:33.305 [error] CRASH REPORT Process <0.1301.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:33.304 [error] CRASH REPORT Process <0.539.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:33.304 [info] Application mnesia2 exited with reason: killed
22:44:33.305 [error] CRASH REPORT Process <0.1254.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:33.305 [info] Application mnesia2 exited with reason: killed
22:44:33.359 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1495.0>
22:44:33.364 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:33.368 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.763.0>
22:44:33.389 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'

----------------------------------------------------
2016-04-10 22:44:33.515
ending test case: dirty_nice_ram_copies


----------------------------------------------------
2016-04-10 22:44:33.556
starting test case: dirty_nice_disc_copies

22:44:33.560 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.776.0> exit with reason killed in context child_terminated
22:44:33.560 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.776.0> exit with reason reached_max_restart_intensity in context shutdown
22:44:33.566 [error] CRASH REPORT Process <0.1486.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:33.566 [info] Application mnesia2 exited with reason: killed
22:44:33.562 [error] gen_server <0.804.0> terminated with reason: killed
22:44:33.562 [error] CRASH REPORT Process <0.804.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:33.626 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1609.0>
22:44:33.644 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.862.0>

----------------------------------------------------
2016-04-10 22:44:33.810
ending test case: dirty_nice_disc_copies


----------------------------------------------------
2016-04-10 22:44:33.841
starting test case: dirty_nice_disc_only_copies

22:44:33.932 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1725.0>
22:44:33.968 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.963.0>

----------------------------------------------------
2016-04-10 22:44:34.127
ending test case: dirty_nice_disc_only_copies


----------------------------------------------------
2016-04-10 22:44:34.227
starting test case: trans_nice_ram_copies

22:44:34.232 [warning] lager_error_logger_h dropped 29 messages in the last second that exceeded the limit of 50 messages/sec
22:44:34.235 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
22:44:34.232 [error] gen_server <0.1781.0> terminated with reason: killed
22:44:34.232 [error] CRASH REPORT Process <0.1781.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:34.235 [error] gen_server <0.1017.0> terminated with reason: killed
22:44:34.232 [error] CRASH REPORT Process <0.1716.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:34.232 [info] Application mnesia2 exited with reason: killed
22:44:34.235 [error] CRASH REPORT Process <0.1017.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:34.236 [error] CRASH REPORT Process <0.954.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:34.236 [info] Application mnesia2 exited with reason: killed
22:44:34.306 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1069.0>
22:44:34.308 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1851.0>
22:44:34.315 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:34.611 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'

----------------------------------------------------
2016-04-10 22:44:34.811
ending test case: trans_nice_ram_copies


----------------------------------------------------
2016-04-10 22:44:34.842
starting test case: trans_nice_disc_copies

22:44:34.846 [error] gen_server <0.1124.0> terminated with reason: killed
22:44:34.849 [error] gen_server <0.1906.0> terminated with reason: killed
22:44:34.846 [error] CRASH REPORT Process <0.1124.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:34.849 [error] CRASH REPORT Process <0.1906.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:34.917 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1981.0>
22:44:34.923 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1171.0>

----------------------------------------------------
2016-04-10 22:44:35.134
ending test case: trans_nice_disc_copies


----------------------------------------------------
2016-04-10 22:44:35.166
starting test case: trans_nice_disc_only_copies

22:44:35.172 [error] gen_server <0.2037.0> terminated with reason: killed
22:44:35.172 [error] gen_server <0.1223.0> terminated with reason: killed
22:44:35.172 [error] CRASH REPORT Process <0.2037.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:35.173 [error] CRASH REPORT Process <0.1223.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:35.172 [error] CRASH REPORT Process <0.1972.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:35.172 [info] Application mnesia2 exited with reason: killed
22:44:35.174 [error] CRASH REPORT Process <0.1162.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:35.174 [info] Application mnesia2 exited with reason: killed
22:44:35.247 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2114.0>
22:44:35.251 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:35.258 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1272.0>
22:44:35.264 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'

----------------------------------------------------
2016-04-10 22:44:35.456
ending test case: trans_nice_disc_only_copies


----------------------------------------------------
2016-04-10 22:44:35.514
starting test case: atomic_eval

22:44:35.517 [error] gen_server <0.1309.0> terminated with reason: killed
22:44:35.517 [error] CRASH REPORT Process <0.1309.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:35.522 [error] CRASH REPORT Process <0.2105.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:35.522 [info] Application mnesia2 exited with reason: killed
22:44:35.584 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2254.0>
22:44:35.612 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1378.0>

----------------------------------------------------
2016-04-10 22:44:36.026
ending test case: atomic_eval


----------------------------------------------------
2016-04-10 22:44:36.111
starting test case: frag

22:44:36.121 [warning] lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
22:44:36.118 [error] gen_server <0.1431.0> terminated with reason: killed
22:44:36.119 [error] CRASH REPORT Process <0.1431.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:36.121 [error] CRASH REPORT Process <0.2245.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:36.121 [info] Application mnesia2 exited with reason: killed
22:44:36.119 [error] CRASH REPORT Process <0.1369.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:36.119 [info] Application mnesia2 exited with reason: killed
22:44:36.173 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2386.0>
22:44:36.188 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1466.0>
22:44:36.204 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:36.481 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'

----------------------------------------------------
2016-04-10 22:44:36.657
ending test case: frag


----------------------------------------------------
2016-04-10 22:44:36.687
starting test case: info

22:44:36.695 [error] CRASH REPORT Process <0.2377.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:36.696 [info] Application mnesia2 exited with reason: killed
22:44:36.692 [error] gen_server <0.1519.0> terminated with reason: killed
22:44:36.692 [error] CRASH REPORT Process <0.1519.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:36.768 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2519.0>
22:44:36.784 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1579.0>
22:44:37.077 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'

----------------------------------------------------
2016-04-10 22:44:37.254
ending test case: info


----------------------------------------------------
2016-04-10 22:44:37.284
starting test case: mnesia2_down

22:44:37.287 [error] gen_server <0.1633.0> terminated with reason: killed
22:44:37.291 [error] gen_server <0.2549.0> terminated with reason: killed
22:44:37.288 [error] CRASH REPORT Process <0.1633.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:37.291 [error] CRASH REPORT Process <0.2549.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:37.288 [error] CRASH REPORT Process <0.1570.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:37.288 [info] Application mnesia2 exited with reason: killed
22:44:37.292 [error] CRASH REPORT Process <0.2510.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:37.292 [info] Application mnesia2 exited with reason: killed
22:44:37.349 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1668.0>
22:44:37.352 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2643.0>
22:44:37.655 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
---> Participant transactions <--- 
---> Coordinator transactions <---
Tid: 14 (owned by <0.2719.0>) 
22:44:37.747 [error] gen_server <0.1716.0> terminated with reason: killed
22:44:37.747 [error] CRASH REPORT Process <0.1716.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826

----------------------------------------------------
2016-04-10 22:44:37.769
ending test case: mnesia2_down


----------------------------------------------------
2016-04-10 22:44:37.898
ending test group: qlc


----------------------------------------------------
2016-04-10 22:44:37.927
starting test group: registry


----------------------------------------------------
2016-04-10 22:44:38.017
starting test case: good_dump

22:44:38.020 [error] gen_server mnesia2_monitor terminated with reason: killed
22:44:38.020 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:38.020 [error] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.2640.0>,killed}

22:44:38.021 [error] CRASH REPORT Process mnesia2_event with 0 neighbours exited with reason: killed in gen_event:terminate_server/4 line 315
22:44:38.021 [error] CRASH REPORT Process <0.2634.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:38.021 [info] Application mnesia2 exited with reason: killed
22:44:38.054 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2770.0>
22:44:38.057 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'

----------------------------------------------------
2016-04-10 22:44:38.072
ending test case: good_dump


----------------------------------------------------
2016-04-10 22:44:38.102
starting test case: bad_dump

22:44:38.159 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2864.0>

----------------------------------------------------
2016-04-10 22:44:38.189
ending test case: bad_dump


----------------------------------------------------
2016-04-10 22:44:38.283
ending test group: registry


----------------------------------------------------
2016-04-10 22:44:38.312
starting test group: config


----------------------------------------------------
2016-04-10 22:44:38.402
starting test case: access_module

22:44:39.455 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
22:44:39.463 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2974.0>
22:44:39.466 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:40.812 [error] CRASH REPORT Process <0.2965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:40.812 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:44:41.834
ending test case: access_module


----------------------------------------------------
2016-04-10 22:44:41.865
starting test case: auto_repair

22:44:42.901 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3080.0>
22:44:42.904 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:42.906 [info] Application mnesia2 exited with reason: stopped
22:44:42.909 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3128.0>
22:44:42.916 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3176.0>

----------------------------------------------------
2016-04-10 22:44:43.934
ending test case: auto_repair


----------------------------------------------------
2016-04-10 22:44:43.964
starting test case: backup_module

22:44:45.010 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3248.0>
22:44:45.014 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:45.045 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3243.0> exit with reason killed in context child_terminated
22:44:45.046 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3243.0> exit with reason reached_max_restart_intensity in context shutdown
22:44:45.046 [error] gen_server mnesia2_subscr terminated with reason: killed
22:44:45.046 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:45.046 [error] gen_server mnesia2_recover terminated with reason: killed
22:44:45.046 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:44:47.072 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
22:44:47.342 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3331.0>
22:44:47.347 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:47.356 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

22:44:47.357 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test8686@testing-worker-linux-docker-e93d2010-3388-linux-10.2016-04-10_22.43.57/Mnesia2.test8686@testing-worker-linux-docker-e93d2010-3388-linux-10/LATEST.LOG"] -> badarg

22:44:47.358 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_tm_13 terminated: shutdown

22:44:47.358 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_tm_1 terminated: shutdown

22:44:47.359 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_tm_3 terminated: shutdown

22:44:47.359 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_tm_5 terminated: shutdown


----------------------------------------------------
2016-04-10 22:44:48.382
ending test case: backup_module


----------------------------------------------------
2016-04-10 22:44:48.410
starting test case: debug

22:44:49.442 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_monitor starting: <0.3453.0>

22:44:49.444 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Mnesia2 debug level set to verbose
22:44:49.445 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3457.0>
22:44:49.448 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_subscr starting: <0.3454.0>

22:44:49.449 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:49.450 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_tm_1 terminated: shutdown

22:44:49.451 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_tm_3 terminated: shutdown

22:44:49.452 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_tm_5 terminated: shutdown

22:44:51.473 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_monitor starting: <0.3503.0>

22:44:51.477 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Version: "1.0.0"

22:44:51.477 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env access_module: mnesia2

22:44:51.477 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env auto_repair: true

22:44:51.477 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env backup_module: mnesia2_backup

22:44:51.477 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env debug: debug

22:44:51.478 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test8686@testing-worker-linux-docker-e93d2010-3388-linux-10.2016-04-10_22.43.57/Mnesia2.test8686@testing-worker-linux-docker-e93d2010-3388-linux-10"

22:44:51.478 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_disc_copies_at_startup: true

22:44:51.478 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_log_load_regulation: false

22:44:51.479 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_log_time_threshold: 180000

22:44:51.479 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_log_update_in_place: true

22:44:51.479 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_log_write_threshold: 1000

22:44:51.479 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env event_module: mnesia2_event

22:44:51.479 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env extra_db_nodes: []

22:44:51.479 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3507.0>
22:44:51.480 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env ignore_fallback_at_startup: false

22:44:51.480 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env fallback_error_function: {mnesia2,lkill}

22:44:51.480 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env max_wait_for_decision: infinity

22:44:51.480 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env schema_location: opt_disc

22:44:51.480 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env core_dir: false

22:44:51.480 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env pid_sort_order: false

22:44:51.480 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env no_table_loaders: 2

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dc_dump_limit: 4

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env send_compressed: 0

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env send_max_packets: 20

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env send_max_transfer_size: 7500

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_buffer_size: 524288

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_max_buffer_file_size: 100000000

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_tx_backlog_threshold: 200000

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_buffer_min_runtime: 10000

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_buffer_drained_cutoff: 5

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Mnesia2 debug level set to debug
22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_subscr starting: <0.3504.0>

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_locker starting: <0.3505.0>

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_recover starting: <0.3506.0>

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_tm starting: <0.3507.0>

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Schema initiated from: default

22:44:51.481 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
22:44:51.482 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_controller starting: <0.3510.0>

22:44:51.484 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_late_loader starting: <0.3511.0>

22:44:51.485 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Intend to load tables: []

22:44:53.513 [warning] lager_error_logger_h dropped 30 messages in the last second that exceeded the limit of 50 messages/sec
22:44:53.513 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_monitor starting: <0.3584.0>

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Version: "1.0.0"

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env access_module: mnesia2

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env auto_repair: true

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env backup_module: mnesia2_backup

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env debug: trace

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test8686@testing-worker-linux-docker-e93d2010-3388-linux-10.2016-04-10_22.43.57/Mnesia2.test8686@testing-worker-linux-docker-e93d2010-3388-linux-10"

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_disc_copies_at_startup: true

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_log_load_regulation: false

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_log_time_threshold: 180000

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_log_update_in_place: true

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_log_write_threshold: 1000

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env event_module: mnesia2_event

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env extra_db_nodes: []

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env ignore_fallback_at_startup: false

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env fallback_error_function: {mnesia2,lkill}

22:44:53.517 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env max_wait_for_decision: infinity

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env schema_location: opt_disc

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env core_dir: false

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env pid_sort_order: false

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env no_table_loaders: 2

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dc_dump_limit: 4

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env send_compressed: 0

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env send_max_packets: 20

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env send_max_transfer_size: 7500

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_buffer_size: 524288

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_max_buffer_file_size: 100000000

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_tx_backlog_threshold: 200000

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_buffer_min_runtime: 10000

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_buffer_drained_cutoff: 5

22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Mnesia2 debug level set to trace
22:44:53.518 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_subscr starting: <0.3585.0>

22:44:53.519 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_locker starting: <0.3586.0>

22:44:53.522 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3588.0>
22:44:53.523 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_recover starting: <0.3587.0>

22:44:53.523 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_tm starting: <0.3588.0>

22:44:53.524 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Schema initiated from: default

22:44:53.524 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
22:44:53.524 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_controller starting: <0.3591.0>

22:44:53.524 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_late_loader starting: <0.3592.0>

22:44:53.525 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Intend to load tables: []

22:44:55.559 [warning] lager_error_logger_h dropped 33 messages in the last second that exceeded the limit of 50 messages/sec
22:44:55.560 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_monitor starting: <0.3633.0>

22:44:55.560 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Version: "1.0.0"

22:44:55.561 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env access_module: mnesia2

22:44:55.561 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env auto_repair: true

22:44:55.561 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env backup_module: mnesia2_backup

22:44:55.561 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env debug: debug

22:44:55.563 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test8686@testing-worker-linux-docker-e93d2010-3388-linux-10.2016-04-10_22.43.57/Mnesia2.test8686@testing-worker-linux-docker-e93d2010-3388-linux-10"

22:44:55.563 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_disc_copies_at_startup: true

22:44:55.564 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_log_load_regulation: false

22:44:55.564 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_log_time_threshold: 180000

22:44:55.564 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_log_update_in_place: true

22:44:55.564 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dump_log_write_threshold: 1000

22:44:55.565 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env event_module: mnesia2_event

22:44:55.565 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env extra_db_nodes: []

22:44:55.565 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env ignore_fallback_at_startup: false

22:44:55.565 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env fallback_error_function: {mnesia2,lkill}

22:44:55.566 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env max_wait_for_decision: infinity

22:44:55.566 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env schema_location: opt_disc

22:44:55.566 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env core_dir: false

22:44:55.567 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env pid_sort_order: false

22:44:55.567 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env no_table_loaders: 2

22:44:55.567 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env dc_dump_limit: 4

22:44:55.568 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3637.0>
22:44:55.568 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env send_compressed: 0

22:44:55.569 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env send_max_packets: 20

22:44:55.569 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env send_max_transfer_size: 7500

22:44:55.569 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_buffer_size: 524288

22:44:55.569 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_max_buffer_file_size: 100000000

22:44:55.569 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_tx_backlog_threshold: 200000

22:44:55.569 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_buffer_min_runtime: 10000

22:44:55.570 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Env async_dirty_buffer_drained_cutoff: 5

22:44:55.570 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Mnesia2 debug level set to debug
22:44:55.570 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_subscr starting: <0.3634.0>

22:44:55.571 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_locker starting: <0.3635.0>

22:44:55.571 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_recover starting: <0.3636.0>

22:44:55.572 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_tm starting: <0.3637.0>

22:44:55.572 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Schema initiated from: default

22:44:55.572 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
22:44:55.573 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_controller starting: <0.3640.0>

22:44:55.573 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): mnesia2_late_loader starting: <0.3641.0>

22:44:55.573 [info] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): Intend to load tables: []

22:44:57.600 [warning] lager_error_logger_h dropped 27 messages in the last second that exceeded the limit of 50 messages/sec
22:44:57.603 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3686.0>
22:44:57.606 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:57.608 [error] CRASH REPORT Process <0.3677.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:57.608 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:44:58.645
ending test case: debug


----------------------------------------------------
2016-04-10 22:44:58.674
starting test case: dir

22:44:59.707 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3750.0>
22:44:59.710 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:44:59.712 [error] CRASH REPORT Process <0.3741.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:44:59.713 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:45:00.747
ending test case: dir


----------------------------------------------------
2016-04-10 22:45:00.777
starting test case: dump_log_load_regulation

22:45:00.836 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3821.0>
22:45:00.843 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:45:00.848 [info] Application mnesia2 exited with reason: stopped
22:45:00.858 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3882.0>
22:45:05.295 [warning] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:45:10.981 [warning] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:45:12.792 [warning] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:45:13.364 [warning] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:45:13.942 [warning] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:45:14.518 [warning] Mnesia2('test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

22:45:15.921 [error] CRASH REPORT Process <0.3873.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:15.921 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:45:16.941
ending test case: dump_log_load_regulation


----------------------------------------------------
2016-04-10 22:45:16.999
starting test case: dump_log_time_threshold

22:45:18.073 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4295.0>
22:45:18.077 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:45:24.086 [error] CRASH REPORT Process <0.4286.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:24.087 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:45:25.109
ending test case: dump_log_time_threshold


----------------------------------------------------
2016-04-10 22:45:25.141
starting test case: dump_log_write_threshold

22:45:26.206 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4395.0>
22:45:26.210 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:45:27.248 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:45:28.262
ending test case: dump_log_write_threshold


----------------------------------------------------
2016-04-10 22:45:28.333
starting test case: dump_log_update_in_place

22:45:29.396 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4511.0>
22:45:29.399 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:45:29.407 [error] CRASH REPORT Process <0.4502.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:29.407 [info] Application mnesia2 exited with reason: killed
22:45:31.602 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4578.0>
22:45:31.606 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:45:31.647 [error] CRASH REPORT Process <0.4569.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:31.647 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:45:32.684
ending test case: dump_log_update_in_place


----------------------------------------------------
2016-04-10 22:45:32.714
starting test case: event_module

22:45:46.045 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4670.0>
22:45:46.048 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:45:46.081 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1798.0>
22:45:46.087 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'}}
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'}}
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'}}
22:45:47.090 [error] gen_server <0.1850.0> terminated with reason: killed
22:45:47.090 [error] CRASH REPORT Process <0.1850.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:47.091 [error] CRASH REPORT Process <0.1789.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:47.091 [info] Application mnesia2 exited with reason: killed
22:45:49.146 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1866.0>
22:45:49.152 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'}}
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'}}
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'}}
22:45:50.154 [error] gen_server <0.4733.0> terminated with reason: killed
22:45:50.154 [error] CRASH REPORT Process <0.4733.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:50.156 [error] CRASH REPORT Process <0.4661.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:50.157 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:45:51.178
ending test case: event_module


----------------------------------------------------
2016-04-10 22:45:51.208
starting test case: inconsistent_database

22:45:51.212 [error] CRASH REPORT Process <0.1857.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:51.213 [info] Application mnesia2 exited with reason: killed
22:45:52.326 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4776.0>
22:45:52.330 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:45:52.352 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1947.0>
22:45:52.366 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:45:52.365 [error] gen_server <0.4830.0> terminated with reason: killed
22:45:52.366 [error] gen_server <0.1988.0> terminated with reason: killed
22:45:52.365 [error] CRASH REPORT Process <0.4830.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:52.366 [error] CRASH REPORT Process <0.1988.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:45:52.366 [error] CRASH REPORT Process <0.4767.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:52.367 [info] Application mnesia2 exited with reason: killed
22:45:52.366 [error] CRASH REPORT Process <0.1938.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:45:52.366 [info] Application mnesia2 exited with reason: killed
22:45:52.429 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4856.0>
22:45:58.797 [info] Application mnesia2 exited with reason: stopped
22:45:58.842 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2022.0>
22:45:58.844 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:45:58.854 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4980.0>
22:45:58.862 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:13.481 [info] Application mnesia2 exited with reason: stopped
22:46:13.482 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:46:14.520
ending test case: inconsistent_database


----------------------------------------------------
2016-04-10 22:46:14.568
starting test case: max_wait_for_decision


----------------------------------------------------
2016-04-10 22:46:14.571
ending test case: max_wait_for_decision


----------------------------------------------------
2016-04-10 22:46:14.601
starting test case: send_compressed

22:46:14.650 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.5111.0>
22:46:14.653 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:14.664 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2144.0>
22:46:14.679 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:14.716 [error] gen_server <0.2196.0> terminated with reason: killed
22:46:14.716 [error] CRASH REPORT Process <0.2196.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:14.718 [error] CRASH REPORT Process <0.2135.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:14.718 [info] Application mnesia2 exited with reason: killed
22:46:14.739 [error] CRASH REPORT Process <0.5102.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:14.740 [info] Application mnesia2 exited with reason: killed
22:46:14.789 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.5199.0>
22:46:15.127 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2232.0>
22:46:15.135 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:15.717 [warning] lager_error_logger_h dropped 20 messages in the last second that exceeded the limit of 50 messages/sec
22:46:15.718 [error] CRASH REPORT Process <0.5190.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:15.718 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:46:16.749
ending test case: send_compressed


----------------------------------------------------
2016-04-10 22:46:16.779
starting test case: app_test


----------------------------------------------------
2016-04-10 22:46:16.788
ending test case: app_test


----------------------------------------------------
2016-04-10 22:46:16.847
starting test case: start_one_disc_full_then_one_disc_less

22:46:16.851 [error] CRASH REPORT Process <0.2223.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:16.851 [info] Application mnesia2 exited with reason: killed
22:46:17.912 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.5322.0>
22:46:17.915 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:17.922 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2335.0>
22:46:17.930 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:17.970 [error] gen_server <0.5386.0> terminated with reason: killed
22:46:17.970 [error] gen_server <0.2346.0> terminated with reason: killed
22:46:17.970 [error] CRASH REPORT Process <0.5386.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:17.970 [error] CRASH REPORT Process <0.2346.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:17.971 [error] CRASH REPORT Process <0.5313.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:17.971 [info] Application mnesia2 exited with reason: killed
22:46:17.972 [error] CRASH REPORT Process <0.2326.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:17.973 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:46:18.997
ending test case: start_one_disc_full_then_one_disc_less


----------------------------------------------------
2016-04-10 22:46:19.045
starting test case: start_first_one_disc_less_then_one_disc_full

22:46:20.097 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.5433.0>
22:46:20.100 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:20.106 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2410.0>
22:46:20.114 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:20.118 [error] CRASH REPORT Process <0.2401.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:20.118 [error] CRASH REPORT Process <0.5424.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:20.119 [info] Application mnesia2 exited with reason: killed
22:46:20.118 [info] Application mnesia2 exited with reason: killed
22:46:22.148 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2469.0>
22:46:22.150 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:22.173 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.5513.0>
22:46:22.183 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:22.201 [error] gen_server <0.5558.0> terminated with reason: killed
22:46:22.202 [error] CRASH REPORT Process <0.5558.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:22.202 [error] CRASH REPORT Process <0.5504.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:22.202 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:46:23.228
ending test case: start_first_one_disc_less_then_one_disc_full


----------------------------------------------------
2016-04-10 22:46:23.259
starting test case: start_first_one_disc_less_then_two_more_disc_less

22:46:23.747 [error] CRASH REPORT Process <0.2460.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:23.747 [info] Application mnesia2 exited with reason: killed
22:46:24.877 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.5638.0>
22:46:24.880 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:24.900 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2556.0>
22:46:24.906 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:25.232 [info] Application lager started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:25.232 [info] Application poolgirl started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:25.270 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.101.0>
22:46:25.297 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:25.364 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.2551.0> exit with reason killed in context child_terminated
22:46:25.368 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.5639.0> exit with reason killed in context child_terminated
22:46:25.364 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.2551.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:25.368 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.5639.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:25.370 [error] CRASH REPORT Process <0.92.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:25.370 [info] Application mnesia2 exited with reason: killed
22:46:25.365 [error] gen_server mnesia2_subscr terminated with reason: killed
22:46:25.371 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.5633.0> exit with reason shutdown in context child_terminated
22:46:25.371 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.5633.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:25.372 [info] Application mnesia2 exited with reason: shutdown
22:46:25.365 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:25.365 [error] gen_server mnesia2_monitor terminated with reason: killed
22:46:25.365 [error] gen_server mnesia2_recover terminated with reason: killed
22:46:25.365 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:25.365 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
22:46:25.365 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:25.367 [info] Application mnesia2 exited with reason: shutdown

----------------------------------------------------
2016-04-10 22:46:26.403
ending test case: start_first_one_disc_less_then_two_more_disc_less


----------------------------------------------------
2016-04-10 22:46:26.448
starting test case: schema_location_and_extra_db_nodes_combinations

22:46:27.504 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.5733.0>
22:46:27.507 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:27.539 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2637.0>
22:46:27.560 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:27.563 [error] gen_server <0.5797.0> terminated with reason: killed
22:46:27.563 [error] CRASH REPORT Process <0.5797.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:27.566 [error] CRASH REPORT Process <0.2628.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:27.566 [info] Application mnesia2 exited with reason: killed
22:46:27.564 [error] CRASH REPORT Process <0.5724.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:27.564 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:46:28.598
ending test case: schema_location_and_extra_db_nodes_combinations


----------------------------------------------------
2016-04-10 22:46:28.630
starting test case: table_load_to_disc_less_nodes

22:46:29.682 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.5827.0>
22:46:29.686 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:29.689 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2707.0>
22:46:29.695 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:29.717 [error] gen_server <0.2721.0> terminated with reason: killed
22:46:29.717 [error] CRASH REPORT Process <0.2721.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:29.720 [error] gen_server <0.5871.0> terminated with reason: killed
22:46:29.718 [error] CRASH REPORT Process <0.2698.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:29.720 [error] CRASH REPORT Process <0.5871.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:29.718 [info] Application mnesia2 exited with reason: killed
22:46:29.721 [error] CRASH REPORT Process <0.5818.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:29.722 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:46:30.746
ending test case: table_load_to_disc_less_nodes


----------------------------------------------------
2016-04-10 22:46:30.776
starting test case: schema_merge

22:46:31.840 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2782.0>
22:46:31.842 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.5913.0>
22:46:31.848 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:32.145 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:32.194 [error] gen_server <0.2839.0> terminated with reason: killed
22:46:32.194 [error] CRASH REPORT Process <0.2839.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:32.195 [error] CRASH REPORT Process <0.2773.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:32.195 [info] Application mnesia2 exited with reason: killed
22:46:33.221 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.5927.0> exit with reason killed in context child_terminated
22:46:33.222 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.5927.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:33.223 [error] CRASH REPORT Process <0.5904.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:33.223 [info] Application mnesia2 exited with reason: killed
22:46:35.275 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2855.0>
22:46:35.277 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:40.317 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.5990.0>
22:46:40.332 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:40.337 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.6008.0> exit with reason killed in context child_terminated
22:46:40.347 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.6008.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:40.348 [error] gen_server <0.6022.0> terminated with reason: killed
22:46:40.338 [error] gen_server <0.2922.0> terminated with reason: killed
22:46:40.348 [error] CRASH REPORT Process <0.6022.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:40.350 [error] CRASH REPORT Process <0.5981.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:40.350 [info] Application mnesia2 exited with reason: killed
22:46:40.338 [error] CRASH REPORT Process <0.2922.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:40.338 [error] CRASH REPORT Process <0.2846.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:40.339 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:46:41.364
ending test case: schema_merge


----------------------------------------------------
2016-04-10 22:46:41.435
starting test case: dynamic_basic

22:46:41.539 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.6100.0>
22:46:41.542 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:41.596 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2954.0>
22:46:41.607 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.192.0>
22:46:41.641 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:41.652 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:41.717 [error] gen_server <0.3017.0> terminated with reason: killed
22:46:41.718 [error] CRASH REPORT Process <0.3017.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:41.718 [error] CRASH REPORT Process <0.2945.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:41.718 [info] Application mnesia2 exited with reason: killed
22:46:41.749 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3045.0>
22:46:41.826 [error] gen_server <0.6199.0> terminated with reason: killed
22:46:41.826 [error] CRASH REPORT Process <0.6199.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:41.826 [error] gen_server <0.6183.0> terminated with reason: killed
22:46:41.826 [error] CRASH REPORT Process <0.6183.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:41.829 [error] CRASH REPORT Process <0.6091.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:41.829 [info] Application mnesia2 exited with reason: killed
22:46:41.839 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.187.0> exit with reason killed in context child_terminated
22:46:41.839 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.187.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:41.839 [error] gen_server mnesia2_subscr terminated with reason: killed
22:46:41.839 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:41.839 [error] gen_server mnesia2_monitor terminated with reason: killed
22:46:41.839 [error] gen_server mnesia2_recover terminated with reason: killed
22:46:41.839 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:41.839 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
22:46:41.839 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:41.841 [info] Application mnesia2 exited with reason: shutdown
22:46:41.899 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3141.0>
22:46:41.944 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.296.0>
22:46:41.956 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.6218.0>
22:46:42.261 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:42.769 [error] gen_server <0.364.0> terminated with reason: killed
22:46:42.769 [error] CRASH REPORT Process <0.364.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:42.769 [error] gen_server <0.371.0> terminated with reason: killed
22:46:42.770 [error] CRASH REPORT Process <0.371.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:42.770 [error] CRASH REPORT Process <0.287.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:42.770 [info] Application mnesia2 exited with reason: killed
22:46:42.795 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.395.0>
22:46:44.862 [warning] lager_error_logger_h dropped 29 messages in the last second that exceeded the limit of 50 messages/sec
22:46:44.862 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.6213.0> exit with reason killed in context child_terminated
22:46:44.862 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.6213.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:44.862 [error] gen_server mnesia2_monitor terminated with reason: killed
22:46:44.862 [error] gen_server mnesia2_subscr terminated with reason: killed
22:46:44.863 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:44.863 [error] gen_server mnesia2_recover terminated with reason: killed
22:46:44.863 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:44.863 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
22:46:44.863 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:44.867 [info] Application mnesia2 exited with reason: shutdown
22:46:44.889 [warning] lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
22:46:44.889 [error] gen_server <0.3233.0> terminated with reason: killed
22:46:44.889 [error] CRASH REPORT Process <0.3233.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:44.889 [error] CRASH REPORT Process <0.3132.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:44.889 [info] Application mnesia2 exited with reason: killed
22:46:44.924 [info] Application mnesia2 exited with reason: stopped
22:46:44.941 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.501.0>
22:46:44.943 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:44.978 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.6333.0>
22:46:44.993 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3255.0>
22:46:45.005 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:45.287 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:45.817 [error] CRASH REPORT Process <0.492.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:45.818 [info] Application mnesia2 exited with reason: killed
22:46:45.868 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.600.0>
22:46:45.877 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:45.942 [error] CRASH REPORT Process <0.6324.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:45.942 [info] Application mnesia2 exited with reason: killed
22:46:45.963 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3250.0> exit with reason killed in context child_terminated
22:46:45.963 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3250.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:45.963 [error] gen_server mnesia2_subscr terminated with reason: killed
22:46:45.963 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:45.963 [error] gen_server mnesia2_monitor terminated with reason: killed
22:46:45.963 [error] gen_server mnesia2_recover terminated with reason: killed
22:46:45.963 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:45.964 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
22:46:45.964 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:45.965 [error] gen_server <0.3342.0> terminated with reason: killed
22:46:45.990 [info] Application mnesia2 exited with reason: stopped
22:46:45.965 [error] CRASH REPORT Process <0.3342.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:45.965 [info] Application mnesia2 exited with reason: shutdown
22:46:46.027 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.702.0>
22:46:46.030 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:46.070 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.6446.0>
22:46:46.090 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3363.0>
22:46:46.100 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:46.396 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:46.937 [error] gen_server <0.3400.0> terminated with reason: killed
22:46:46.937 [error] CRASH REPORT Process <0.3400.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:46.937 [error] gen_server <0.3433.0> terminated with reason: killed
22:46:46.937 [error] CRASH REPORT Process <0.3433.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:46.938 [error] CRASH REPORT Process <0.3354.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:46.938 [info] Application mnesia2 exited with reason: killed
22:46:46.985 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3459.0>
22:46:47.011 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:47.045 [error] CRASH REPORT Process <0.3450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:47.045 [info] Application mnesia2 exited with reason: killed
22:46:48.069 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3537.0>
22:46:48.086 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'

----------------------------------------------------
2016-04-10 22:46:48.143
ending test case: dynamic_basic


----------------------------------------------------
2016-04-10 22:46:48.177
starting test case: dynamic_ext

22:46:48.182 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3539.0> exit with reason killed in context child_terminated
22:46:48.182 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3539.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:48.181 [error] gen_server <0.6559.0> terminated with reason: killed
22:46:48.184 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.697.0> exit with reason killed in context child_terminated
22:46:48.181 [error] CRASH REPORT Process <0.6559.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:48.184 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3532.0> exit with reason shutdown in context child_terminated
22:46:48.184 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.697.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:48.185 [error] gen_server mnesia2_recover terminated with reason: killed
22:46:48.183 [error] gen_server <0.6514.0> terminated with reason: killed
22:46:48.184 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3532.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:48.185 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:48.185 [info] Application mnesia2 exited with reason: shutdown
22:46:48.184 [error] CRASH REPORT Process <0.6514.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:48.185 [error] gen_server mnesia2_subscr terminated with reason: killed
22:46:48.189 [error] CRASH REPORT Process <0.6437.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:48.189 [info] Application mnesia2 exited with reason: killed
22:46:48.185 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:48.185 [error] gen_server mnesia2_monitor terminated with reason: killed
22:46:48.185 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
22:46:48.185 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:48.187 [info] Application mnesia2 exited with reason: shutdown
22:46:48.286 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.6592.0>
22:46:48.289 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:48.292 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3616.0>
22:46:48.306 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:48.388 [error] Mnesia2('d742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.3613.0>,killed}

22:46:48.420 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3711.0>
22:46:48.545 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3801.0>
22:46:48.612 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3901.0>
22:46:49.146 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.6706.0>
22:46:49.169 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:49.193 [info] Application mnesia2 exited with reason: stopped
22:46:49.200 [warning] lager_error_logger_h dropped 40 messages in the last second that exceeded the limit of 50 messages/sec
22:46:49.200 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3903.0> exit with reason killed in context child_terminated
22:46:49.200 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3903.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:49.201 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.3905.0> exit with reason killed in context shutdown_error
22:46:49.202 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3896.0> exit with reason killed in context child_terminated
22:46:49.202 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3896.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:49.202 [error] gen_server mnesia2_subscr terminated with reason: killed
22:46:49.202 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:49.202 [error] gen_server mnesia2_monitor terminated with reason: killed
22:46:49.202 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:49.204 [info] Application mnesia2 exited with reason: shutdown
22:46:49.255 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.6789.0>
22:46:49.762 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.3983.0>

----------------------------------------------------
2016-04-10 22:46:49.809
ending test case: dynamic_ext


----------------------------------------------------
2016-04-10 22:46:49.839
starting test case: dynamic_bad

22:46:49.935 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.6890.0>
22:46:49.955 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4075.0>
22:46:49.957 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.853.0>
22:46:49.967 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:50.259 [warning] lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
22:46:50.262 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:50.354 [warning] lager_error_logger_h dropped 63 messages in the last second that exceeded the limit of 50 messages/sec
22:46:50.355 [error] CRASH REPORT Process <0.6881.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:50.355 [info] Application mnesia2 exited with reason: killed
22:46:50.353 [error] gen_server <0.4136.0> terminated with reason: killed
22:46:50.358 [error] CRASH REPORT Process <0.844.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:50.359 [info] Application mnesia2 exited with reason: killed
22:46:50.353 [error] CRASH REPORT Process <0.4136.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:50.353 [error] gen_server <0.4117.0> terminated with reason: killed
22:46:50.391 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.957.0>
22:46:50.393 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:50.354 [error] CRASH REPORT Process <0.4117.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:50.354 [error] CRASH REPORT Process <0.4066.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:50.354 [info] Application mnesia2 exited with reason: killed
22:46:50.394 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4168.0>
22:46:50.439 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.7001.0>
22:46:50.463 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:46:50.500 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.958.0> exit with reason killed in context child_terminated
22:46:50.512 [error] gen_server mnesia2_monitor terminated with reason: killed
22:46:50.500 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.958.0> exit with reason reached_max_restart_intensity in context shutdown
22:46:50.514 [error] gen_server <0.7068.0> terminated with reason: killed
22:46:50.500 [error] gen_server <0.1006.0> terminated with reason: killed
22:46:50.514 [error] CRASH REPORT Process <0.7068.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:50.500 [error] CRASH REPORT Process <0.1006.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:50.514 [error] gen_server <0.7063.0> terminated with reason: killed
22:46:50.501 [error] gen_server <0.1016.0> terminated with reason: killed
22:46:50.501 [error] CRASH REPORT Process <0.1016.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:50.501 [error] gen_server <0.1001.0> terminated with reason: killed
22:46:50.501 [error] CRASH REPORT Process <0.1001.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:46:50.501 [error] CRASH REPORT Process <0.948.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:46:50.501 [info] Application mnesia2 exited with reason: killed
22:46:50.537 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1036.0>
22:46:50.540 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4247.0>
22:46:50.587 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.7093.0>

----------------------------------------------------
2016-04-10 22:47:00.601
ending test case: dynamic_bad

22:47:00.597 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
22:47:00.597 [error] gen_server mnesia2_recover terminated with reason: killed
22:47:00.598 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:47:00.598 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
22:47:00.598 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:47:00.598 [error] gen_server mnesia2_subscr terminated with reason: killed
22:47:00.598 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:47:00.598 [error] CRASH REPORT Process <0.7084.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
22:47:00.598 [error] gen_server mnesia2_monitor terminated with reason: killed
22:47:00.599 [info] Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
22:47:00.600 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826

----------------------------------------------------
2016-04-10 22:47:00.710
starting test case: unknown_config

22:47:00.714 [warning] lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
22:47:00.714 [error] gen_server <0.4291.0> terminated with reason: killed
22:47:00.717 [error] gen_server <0.1085.0> terminated with reason: killed
22:47:00.714 [error] CRASH REPORT Process <0.4291.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:47:00.717 [error] CRASH REPORT Process <0.1085.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
22:47:00.715 [error] CRASH REPORT Process <0.4238.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:47:00.715 [info] Application mnesia2 exited with reason: killed
22:47:00.719 [error] CRASH REPORT Process <0.1027.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
22:47:00.719 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 22:47:02.781
ending test case: unknown_config


----------------------------------------------------
2016-04-10 22:47:02.890
ending test group: config


----------------------------------------------------
2016-04-10 22:47:02.919
starting test group: examples


----------------------------------------------------
2016-04-10 22:47:03.011
starting test case: bup


----------------------------------------------------
2016-04-10 22:47:03.044
ending test case: bup


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error detected: error
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: *** FAILED test case 41 of 52 ***

----------------------------------------------------
2016-04-10 22:47:03.079
starting test case: company


----------------------------------------------------
2016-04-10 22:47:03.082
ending test case: company


----------------------------------------------------
2016-04-10 22:47:03.113
starting test case: meter

22:47:03.165 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.7203.0>
22:47:03.168 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:09.455 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:09.462
ending test case: meter


----------------------------------------------------
2016-04-10 22:47:09.523
starting test case: replica_test

22:47:09.626 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.7339.0>
22:47:09.628 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4338.0>
22:47:09.630 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1134.0>
22:47:09.644 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:09.659 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:09.947 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:16.058 [info] Application mnesia2 exited with reason: stopped
22:47:16.061 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:16.107
ending test case: replica_test

22:47:16.087 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:16.139
starting test case: sticky_replica_test

22:47:16.257 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.7469.0>
22:47:16.261 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:16.270 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4452.0>
22:47:16.271 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1250.0>
22:47:16.279 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:16.291 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:22.416 [info] Application mnesia2 exited with reason: stopped
22:47:22.422 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:22.448
ending test case: sticky_replica_test

22:47:22.448 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:22.495
starting test case: dist_test

22:47:22.586 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.7598.0>
22:47:22.590 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:22.605 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.1366.0>
22:47:22.608 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4565.0>
22:47:22.623 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:22.922 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:46.404 [info] Application mnesia2 exited with reason: stopped
22:47:46.397 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:46.415
ending test case: dist_test

22:47:46.406 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:46.475
starting test case: conflict_test

22:47:46.562 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.8736.0>
22:47:46.566 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:46.576 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.5689.0>
22:47:46.599 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:46.606 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2492.0>
22:47:46.619 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:52.957 [info] Application mnesia2 exited with reason: stopped
22:47:52.964 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:52.969
ending test case: conflict_test

22:47:52.969 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:53.001
starting test case: frag_test

22:47:53.125 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.2615.0>
22:47:53.127 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:53.131 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.8876.0>
22:47:53.144 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.5814.0>
22:47:53.153 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:53.175 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:59.719 [info] Application mnesia2 exited with reason: stopped
22:47:59.721 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:59.734
ending test case: frag_test

22:47:59.734 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:47:59.765
starting test case: frag2_test

22:47:59.880 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.10354.0>
22:47:59.883 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.7283.0>
22:47:59.889 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:47:59.906 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4087.0>
22:47:59.938 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:48:00.188 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:48:06.570 [info] Application mnesia2 exited with reason: stopped
22:48:06.570 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:48:06.574
ending test case: frag2_test

22:48:06.573 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:48:06.605
starting test case: remote_test

22:48:06.714 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.12020.0>
22:48:06.720 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.4590.0>
22:48:06.730 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:48:06.735 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.8297.0>
22:48:06.744 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:48:07.022 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:48:13.216 [info] Application mnesia2 exited with reason: stopped
22:48:13.223 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:48:13.242
ending test case: remote_test

22:48:13.242 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:48:13.274
starting test case: remote_frag2_test

22:48:13.405 [info] starting mnesia2_tm, 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.12151.0>
22:48:13.408 [info] Application mnesia2 started on node 'test8686@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:48:13.421 [info] starting mnesia2_tm, 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.8409.0>
22:48:13.426 [info] Application mnesia2 started on node 'd742187o742161n742163@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:48:13.452 [info] starting mnesia2_tm, 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10', <0.5386.0>
22:48:13.461 [info] Application mnesia2 started on node 'd742180o742172n742172@testing-worker-linux-docker-e93d2010-3388-linux-10'
22:48:19.777 [info] Application mnesia2 exited with reason: stopped
22:48:19.771 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:48:19.811
ending test case: remote_frag2_test

22:48:19.811 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 22:48:19.936
ending test group: examples


----------------------------------------------------
2016-04-10 22:48:19.973
ending test group: extra_light


----------------------------------------------------
2016-04-10 22:48:20.002
starting test case: clean_up_suite


----------------------------------------------------
2016-04-10 22:48:20.033
ending test case: clean_up_suite

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: TEST COMPLETE, 51 ok, 1 failed of 52 test cases

Cover analysing... done

Updating /home/travis/build/lrascao/mnesia2/logs/index.html... done
Updating /home/travis/build/lrascao/mnesia2/logs/all_runs.html... done

