<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Test mnesia2_config_test:dump_log_update_in_place result</title>
<meta http-equiv="cache-control" content="no-cache">
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<link rel="stylesheet" href="../../ct_default.css" type="text/css">
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

=== <a href="mnesia2_config_test.src.html#dump_log_update_in_place-1">source code for mnesia2_config_test:dump_log_update_in_place/1</a>

<pre>
<a name="top"></a>
=== Test case started with:
mnesia2_config_test:dump_log_update_in_place([{watchdog,<0.807.0>},
                                              {tc_logfile,
                                               "/home/travis/build/lrascao/mnesia2/logs/ct_run.test1313@testing-worker-linux-docker-a2f23725-3371-linux-4.2016-04-12_08.54.07/lrascao.mnesia2.mnesia2_extra_light_SUITE.logs/run.2016-04-12_08.54.31/mnesia2_config_test.dump_log_update_in_place.html"},
                                              {tc_group_properties,
                                               [{suite,mnesia2_config_test}]},
                                              {tc_group_path,
                                               [[{name,config}],
                                                [{name,registry}],
                                                [{name,registry}],
                                                [{name,qlc}],
                                                [{name,qlc}],
                                                [{name,nice}],
                                                [{name,nice}],
                                                [{name,install}],
                                                [{name,install}],
                                                [{name,extra_light}]]},
                                              {data_dir,
                                               "/home/travis/build/lrascao/mnesia2/test/mnesia2_config_test_data/"},
                                              {priv_dir,
                                               "/home/travis/build/lrascao/mnesia2/logs/ct_run.test1313@testing-worker-linux-docker-a2f23725-3371-linux-4.2016-04-12_08.54.07/lrascao.mnesia2.mnesia2_extra_light_SUITE.logs/run.2016-04-12_08.54.31/log_private/"},
                                              {nodenames,
                                               ['d724846o724854n724854@testing-worker-linux-docker-a2f23725-3371-linux-4',
                                                'd724849o724843n724844@testing-worker-linux-docker-a2f23725-3371-linux-4']}])

=== Current directory is "/home/travis/build/lrascao/mnesia2/logs/ct_run.test1313@testing-worker-linux-docker-a2f23725-3371-linux-4.2016-04-12_08.54.07"

=== Started at 2016-04-12 08:55:02

<br />
[2016-04-12 08:55:03] mnesia2_test_lib.erl(694): <>ERROR<>
Cannot start appls [mnesia2]: [{badrpc,mnesia2,
                                {'EXIT',
                                 {undef,
                                  [{application,ensure_all_started,
                                    [mnesia2,temporary],
                                    []},
                                   {timer,tc,3,
                                    [{file,"timer.erl"},{line,194}]},
                                   {mnesia2,start,0,
                                    [{file,"src/mnesia2.erl"},{line,200}]},
                                   {mnesia2_test_lib,remote_start,3,
                                    [{file,"mnesia2_test_lib.erl"},
                                     {line,828}]},
                                   {rpc,'-handle_call_call/6-fun-0-',5,
                                    [{file,"rpc.erl"},{line,205}]}]}}}]

<div class="ct_error_notify"><b>*** User 2016-04-12 08:55:03.859 ***</b>
mnesia2_test_lib:do_prepare failed on line 694
Reason: {test_case_fatal,"Cannot start appls ~p: ~p~n",[[...]|...],[...],...}
</div>
<a name="end"></a>


=== Ended at 2016-04-12 08:55:03
=== location [{mnesia2_test_lib,do_prepare,694},
              {mnesia2_config_test,dump_log_update_in_place,401},
              {test_server,ts_tc,1362},
              {test_server,run_test_case_eval1,979},
              {test_server,run_test_case_eval,928}]
=== reason = {test_case_fatal,"Cannot start appls ~p: ~p~n",
                  [[mnesia2],
                   [{badrpc,mnesia2,
                     {'EXIT',
                      {undef,
                       [{application,ensure_all_started,
                         [mnesia2,temporary],
                         []},
                        {timer,tc,3,[{file,"timer.erl"},{line,194}]},
                        {mnesia2,start,0,
                         [{file,"src/mnesia2.erl"},{line,200}]},
                        {mnesia2_test_lib,remote_start,3,
                         [{file,"mnesia2_test_lib.erl"},{line,828}]},
                        {rpc,'-handle_call_call/6-fun-0-',5,
                         [{file,"rpc.erl"},{line,205}]}]}}}]],
                  "mnesia2_test_lib.erl",694}
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>
</p>
<div class="copyright">Copyright &copy; 2016 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!date>Tue Apr 12 2016 08:55:02<!/date><br />
</div>
</center>
</body>
</html>
