2016-04-12 08:50:43.408 [error] <0.519.0> CRASH REPORT Process <0.519.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:44.139 [error] <0.759.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1271145o1271151n1271189@testing-worker-linux-docker-f366a174-3354-linux-15'...

2016-04-12 08:50:44.139 [error] <0.760.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.763.0> exit with reason killed in context child_terminated
2016-04-12 08:50:44.139 [error] <0.760.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.763.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:50:44.141 [error] <0.758.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.760.0> exit with reason shutdown in context child_terminated
2016-04-12 08:50:44.141 [error] <0.758.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.760.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:50:45.505 [error] <0.517.0> gen_server <0.517.0> terminated with reason: killed
2016-04-12 08:50:45.507 [error] <0.1054.0> gen_server <0.1054.0> terminated with reason: killed
2016-04-12 08:50:45.505 [error] <0.517.0> CRASH REPORT Process <0.517.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:50:45.507 [error] <0.1054.0> CRASH REPORT Process <0.1054.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:50:45.505 [error] <0.450.0> CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:45.508 [error] <0.984.0> CRASH REPORT Process <0.984.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:46.416 [error] <0.661.0> gen_server <0.661.0> terminated with reason: killed
2016-04-12 08:50:46.417 [error] <0.1279.0> gen_server <0.1279.0> terminated with reason: killed
2016-04-12 08:50:46.416 [error] <0.661.0> CRASH REPORT Process <0.661.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:50:46.418 [error] <0.1279.0> CRASH REPORT Process <0.1279.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:50:46.416 [error] <0.539.0> CRASH REPORT Process <0.539.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:46.419 [error] <0.1219.0> CRASH REPORT Process <0.1219.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:46.609 [error] <0.759.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:50:46.610 [error] <0.759.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:50:46.610 [error] <0.755.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.757.0> exit with reason killed in context child_terminated
2016-04-12 08:50:46.610 [error] <0.755.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.757.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:50:47.102 [error] <0.953.0> CRASH REPORT Process <0.953.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:47.102 [error] <0.1682.0> CRASH REPORT Process <0.1682.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:47.607 [error] <0.1808.0> CRASH REPORT Process <0.1808.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:47.605 [error] <0.1123.0> gen_server <0.1123.0> terminated with reason: killed
2016-04-12 08:50:47.605 [error] <0.1123.0> CRASH REPORT Process <0.1123.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:50:47.606 [error] <0.1059.0> CRASH REPORT Process <0.1059.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:48.111 [error] <0.1323.0> gen_server <0.1323.0> terminated with reason: killed
2016-04-12 08:50:48.126 [error] <0.2138.0> gen_server <0.2138.0> terminated with reason: killed
2016-04-12 08:50:48.126 [error] <0.2138.0> CRASH REPORT Process <0.2138.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:50:48.111 [error] <0.1323.0> CRASH REPORT Process <0.1323.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:50:48.111 [error] <0.1260.0> CRASH REPORT Process <0.1260.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:48.128 [error] <0.2073.0> CRASH REPORT Process <0.2073.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:48.670 [error] <0.2279.0> gen_server <0.2279.0> terminated with reason: killed
2016-04-12 08:50:48.670 [error] <0.1428.0> gen_server <0.1428.0> terminated with reason: killed
2016-04-12 08:50:48.670 [error] <0.2279.0> CRASH REPORT Process <0.2279.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:50:48.670 [error] <0.1428.0> CRASH REPORT Process <0.1428.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:50:49.177 [error] <0.2477.0> CRASH REPORT Process <0.2477.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:49.178 [error] <0.1627.0> gen_server <0.1627.0> terminated with reason: killed
2016-04-12 08:50:49.178 [error] <0.1627.0> CRASH REPORT Process <0.1627.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:50:49.178 [error] <0.1566.0> CRASH REPORT Process <0.1566.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:49.330 [error] <0.1714.0> gen_server <0.1714.0> terminated with reason: killed
2016-04-12 08:50:49.330 [error] <0.1714.0> CRASH REPORT Process <0.1714.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:50:49.593 [error] <0.2600.0> CRASH REPORT Process <0.2600.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:52.614 [error] <0.2932.0> CRASH REPORT Process <0.2932.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:56.813 [error] <0.3206.0> CRASH REPORT Process <0.3206.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:50:58.860 [error] <0.3336.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3374.0>}})

2016-04-12 08:50:58.860 [error] <0.3335.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3374.0>}})

2016-04-12 08:50:58.860 [error] <0.3338.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3374.0>}})

2016-04-12 08:50:58.860 [error] <0.3324.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_1,shutdown]}}}} ({error,{already_started,<0.3374.0>}})

2016-04-12 08:50:58.861 [error] <0.3326.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3374.0>}})

2016-04-12 08:50:58.861 [error] <0.3289.0> CRASH REPORT Process <0.3289.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:51:00.945 [error] <0.3412.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3443.0>}})

2016-04-12 08:51:00.945 [error] <0.3414.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3443.0>}})

2016-04-12 08:51:00.945 [error] <0.3413.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3443.0>}})

2016-04-12 08:51:05.007 [error] <0.3550.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3581.0>}})

2016-04-12 08:51:05.007 [error] <0.3552.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3581.0>}})

2016-04-12 08:51:05.007 [error] <0.3551.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3581.0>}})

2016-04-12 08:51:05.008 [error] <0.3549.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3581.0>}})

2016-04-12 08:51:05.008 [error] <0.3554.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3581.0>}})

2016-04-12 08:51:05.008 [error] <0.3556.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3581.0>}})

2016-04-12 08:51:05.009 [error] <0.3555.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3581.0>}})

2016-04-12 08:51:05.009 [error] <0.3558.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3581.0>}})

2016-04-12 08:51:05.009 [error] <0.3560.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3581.0>}})

2016-04-12 08:51:05.009 [error] <0.3559.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_12,shutdown]}}}} ({error,{already_started,<0.3581.0>}})

2016-04-12 08:51:05.009 [error] <0.3557.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_10,shutdown]}}}} ({error,{already_started,<0.3581.0>}})

2016-04-12 08:51:05.009 [error] <0.3562.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_15,shutdown]}}}} ({error,{already_started,<0.3581.0>}})

2016-04-12 08:51:05.010 [error] <0.3564.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_17,shutdown]}}}} ({error,{already_started,<0.3581.0>}})

2016-04-12 08:51:09.064 [error] <0.3677.0> CRASH REPORT Process <0.3677.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:51:11.161 [error] <0.3741.0> CRASH REPORT Process <0.3741.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:51:14.526 [error] <0.3876.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:17.878 [error] <0.3876.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:24.037 [error] <0.3876.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:24.937 [error] <0.3876.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:27.087 [error] <0.3876.0> Mnesia2('test6532@testing-worker-linux-docker-f366a174-3354-linux-15'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-12 08:51:27.309 [error] <0.3873.0> CRASH REPORT Process <0.3873.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:51:35.441 [error] <0.4423.0> CRASH REPORT Process <0.4423.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:51:41.115 [error] <0.4639.0> CRASH REPORT Process <0.4639.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:51:43.189 [error] <0.4710.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4730.0> exit with reason killed in context child_terminated
2016-04-12 08:51:43.190 [error] <0.4710.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.4730.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:51:43.191 [error] <0.4706.0> CRASH REPORT Process <0.4706.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:51:47.429 [error] <0.1841.0> gen_server <0.1841.0> terminated with reason: killed
2016-04-12 08:51:47.429 [error] <0.1841.0> CRASH REPORT Process <0.1841.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:51:47.430 [error] <0.1780.0> CRASH REPORT Process <0.1780.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:51:50.479 [error] <0.4800.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.4802.0> exit with reason killed in context child_terminated
2016-04-12 08:51:50.480 [error] <0.4800.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.4802.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:51:50.480 [error] <0.4803.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:51:50.480 [error] <0.4806.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:51:50.480 [error] <0.4806.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:51:51.534 [error] <0.1848.0> CRASH REPORT Process <0.1848.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:51:52.749 [error] <0.4904.0> CRASH REPORT Process <0.4904.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:51:52.750 [error] <0.1930.0> CRASH REPORT Process <0.1930.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:09.166 [error] <0.2191.0> gen_server <0.2191.0> terminated with reason: killed
2016-04-12 08:52:09.166 [error] <0.2191.0> CRASH REPORT Process <0.2191.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:09.167 [error] <0.2128.0> CRASH REPORT Process <0.2128.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:09.188 [error] <0.5232.0> CRASH REPORT Process <0.5232.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:10.928 [error] <0.2218.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2220.0> exit with reason killed in context child_terminated
2016-04-12 08:52:10.928 [error] <0.2218.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.2220.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:52:10.928 [error] <0.2222.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:52:10.928 [error] <0.2222.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:10.928 [error] <0.2221.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:52:10.928 [error] <0.2221.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:10.928 [error] <0.2224.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:52:10.928 [error] <0.2224.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:10.928 [error] <0.2245.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-12 08:52:10.928 [error] <0.2245.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:12.079 [error] <0.5516.0> gen_server <0.5516.0> terminated with reason: killed
2016-04-12 08:52:12.077 [error] <0.2340.0> gen_server <0.2340.0> terminated with reason: killed
2016-04-12 08:52:12.077 [error] <0.2340.0> CRASH REPORT Process <0.2340.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:12.079 [error] <0.5516.0> CRASH REPORT Process <0.5516.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:12.080 [error] <0.5443.0> CRASH REPORT Process <0.5443.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:12.078 [error] <0.2319.0> CRASH REPORT Process <0.2319.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:14.284 [error] <0.2415.0> gen_server <0.2415.0> terminated with reason: killed
2016-04-12 08:52:14.297 [error] <0.5627.0> gen_server <0.5627.0> terminated with reason: killed
2016-04-12 08:52:14.284 [error] <0.2415.0> CRASH REPORT Process <0.2415.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:14.297 [error] <0.5627.0> CRASH REPORT Process <0.5627.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:14.285 [error] <0.2394.0> CRASH REPORT Process <0.2394.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:14.297 [error] <0.5554.0> CRASH REPORT Process <0.5554.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:16.397 [error] <0.5704.0> gen_server <0.5704.0> terminated with reason: killed
2016-04-12 08:52:16.397 [error] <0.5704.0> CRASH REPORT Process <0.5704.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:16.398 [error] <0.5634.0> CRASH REPORT Process <0.5634.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:17.825 [error] <0.2453.0> CRASH REPORT Process <0.2453.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:19.378 [error] <0.5813.0> gen_server <0.5813.0> terminated with reason: killed
2016-04-12 08:52:19.379 [error] <0.2564.0> gen_server <0.2564.0> terminated with reason: killed
2016-04-12 08:52:19.379 [error] <0.5813.0> CRASH REPORT Process <0.5813.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:19.379 [error] <0.2564.0> CRASH REPORT Process <0.2564.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:19.380 [error] <0.5821.0> gen_server <0.5821.0> terminated with reason: killed
2016-04-12 08:52:19.381 [error] <0.2602.0> gen_server <0.2602.0> terminated with reason: killed
2016-04-12 08:52:19.380 [error] <0.5821.0> CRASH REPORT Process <0.5821.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:19.381 [error] <0.2602.0> CRASH REPORT Process <0.2602.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:19.380 [error] <0.5759.0> CRASH REPORT Process <0.5759.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:19.382 [error] <0.2542.0> CRASH REPORT Process <0.2542.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:21.510 [error] <0.2644.0> gen_server <0.2644.0> terminated with reason: killed
2016-04-12 08:52:21.512 [error] <0.5854.0> CRASH REPORT Process <0.5854.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:21.510 [error] <0.2644.0> CRASH REPORT Process <0.2644.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:21.511 [error] <0.2623.0> CRASH REPORT Process <0.2623.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:23.636 [error] <0.6001.0> gen_server <0.6001.0> terminated with reason: killed
2016-04-12 08:52:23.635 [error] <0.2714.0> gen_server <0.2714.0> terminated with reason: killed
2016-04-12 08:52:23.637 [error] <0.6001.0> CRASH REPORT Process <0.6001.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:23.635 [error] <0.2714.0> CRASH REPORT Process <0.2714.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:23.637 [error] <0.5948.0> CRASH REPORT Process <0.5948.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:23.635 [error] <0.2693.0> CRASH REPORT Process <0.2693.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:29.080 [error] <0.2768.0> CRASH REPORT Process <0.2768.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:30.121 [error] <0.6034.0> CRASH REPORT Process <0.6034.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:37.285 [error] <0.2916.0> gen_server <0.2916.0> terminated with reason: killed
2016-04-12 08:52:37.285 [error] <0.6182.0> gen_server <0.6182.0> terminated with reason: killed
2016-04-12 08:52:37.285 [error] <0.6182.0> CRASH REPORT Process <0.6182.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:37.285 [error] <0.2916.0> CRASH REPORT Process <0.2916.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:37.285 [error] <0.2838.0> CRASH REPORT Process <0.2838.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:37.287 [error] <0.6112.0> CRASH REPORT Process <0.6112.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:38.558 [error] <0.2937.0> CRASH REPORT Process <0.2937.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:38.631 [error] <0.6334.0> gen_server <0.6334.0> terminated with reason: killed
2016-04-12 08:52:38.631 [error] <0.6318.0> gen_server <0.6318.0> terminated with reason: killed
2016-04-12 08:52:38.631 [error] <0.6318.0> CRASH REPORT Process <0.6318.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:38.631 [error] <0.6334.0> CRASH REPORT Process <0.6334.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:38.631 [error] <0.6222.0> CRASH REPORT Process <0.6222.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:38.650 [error] <0.276.0> gen_server <0.276.0> terminated with reason: killed
2016-04-12 08:52:38.650 [error] <0.276.0> CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:39.571 [error] <0.290.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.314.0> exit with reason killed in context child_terminated
2016-04-12 08:52:39.572 [error] <0.290.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.314.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:52:39.572 [error] <0.362.0> gen_server <0.362.0> terminated with reason: killed
2016-04-12 08:52:39.572 [error] <0.362.0> CRASH REPORT Process <0.362.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:39.572 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:41.817 [error] <0.6450.0> gen_server <0.6450.0> terminated with reason: killed
2016-04-12 08:52:41.817 [error] <0.6450.0> CRASH REPORT Process <0.6450.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:41.817 [error] <0.6418.0> gen_server <0.6418.0> terminated with reason: killed
2016-04-12 08:52:41.817 [error] <0.6418.0> CRASH REPORT Process <0.6418.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:41.817 [error] <0.6344.0> CRASH REPORT Process <0.6344.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:41.852 [error] <0.3225.0> gen_server <0.3225.0> terminated with reason: killed
2016-04-12 08:52:41.852 [error] <0.3225.0> CRASH REPORT Process <0.3225.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:41.853 [error] <0.3123.0> CRASH REPORT Process <0.3123.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:42.762 [error] <0.574.0> gen_server <0.574.0> terminated with reason: killed
2016-04-12 08:52:42.762 [error] <0.574.0> CRASH REPORT Process <0.574.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:42.762 [error] <0.568.0> gen_server <0.568.0> terminated with reason: killed
2016-04-12 08:52:42.762 [error] <0.568.0> CRASH REPORT Process <0.568.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:42.763 [error] <0.491.0> CRASH REPORT Process <0.491.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:42.830 [error] <0.6540.0> gen_server <0.6540.0> terminated with reason: killed
2016-04-12 08:52:42.830 [error] <0.6540.0> CRASH REPORT Process <0.6540.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:42.830 [error] <0.6558.0> gen_server <0.6558.0> terminated with reason: killed
2016-04-12 08:52:42.830 [error] <0.6558.0> CRASH REPORT Process <0.6558.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:42.831 [error] <0.6460.0> CRASH REPORT Process <0.6460.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:42.851 [error] <0.3332.0> gen_server <0.3332.0> terminated with reason: killed
2016-04-12 08:52:42.851 [error] <0.3332.0> CRASH REPORT Process <0.3332.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:42.852 [error] <0.3237.0> CRASH REPORT Process <0.3237.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:43.943 [error] <0.3344.0> CRASH REPORT Process <0.3344.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:44.051 [error] <0.3444.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3451.0> exit with reason killed in context child_terminated
2016-04-12 08:52:44.052 [error] <0.3444.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3451.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:52:44.052 [error] <0.3475.0> gen_server <0.3475.0> terminated with reason: killed
2016-04-12 08:52:44.052 [error] <0.3475.0> CRASH REPORT Process <0.3475.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:44.052 [error] <0.3463.0> gen_server <0.3463.0> terminated with reason: killed
2016-04-12 08:52:44.052 [error] <0.3463.0> CRASH REPORT Process <0.3463.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:44.069 [error] <0.3507.0> gen_server <0.3507.0> terminated with reason: killed
2016-04-12 08:52:44.069 [error] <0.3507.0> CRASH REPORT Process <0.3507.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:45.218 [error] <0.6577.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6603.0> exit with reason killed in context child_terminated
2016-04-12 08:52:45.217 [error] <0.825.0> gen_server <0.825.0> terminated with reason: killed
2016-04-12 08:52:45.218 [error] <0.6577.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.6603.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:52:45.218 [error] <0.825.0> CRASH REPORT Process <0.825.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:45.220 [error] <0.6695.0> gen_server <0.6695.0> terminated with reason: killed
2016-04-12 08:52:45.220 [error] <0.3541.0> gen_server <0.3541.0> terminated with reason: killed
2016-04-12 08:52:45.220 [error] <0.6695.0> CRASH REPORT Process <0.6695.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:45.218 [error] <0.819.0> gen_server <0.819.0> terminated with reason: killed
2016-04-12 08:52:45.220 [error] <0.3541.0> CRASH REPORT Process <0.3541.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:45.220 [error] <0.6648.0> gen_server <0.6648.0> terminated with reason: killed
2016-04-12 08:52:45.218 [error] <0.819.0> CRASH REPORT Process <0.819.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:45.220 [error] <0.6648.0> CRASH REPORT Process <0.6648.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:45.222 [error] <0.3575.0> gen_server <0.3575.0> terminated with reason: killed
2016-04-12 08:52:45.218 [error] <0.775.0> gen_server <0.775.0> terminated with reason: killed
2016-04-12 08:52:45.220 [error] <0.6573.0> CRASH REPORT Process <0.6573.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:45.222 [error] <0.3575.0> CRASH REPORT Process <0.3575.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:45.218 [error] <0.775.0> CRASH REPORT Process <0.775.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:45.223 [error] <0.3518.0> CRASH REPORT Process <0.3518.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:45.218 [error] <0.692.0> CRASH REPORT Process <0.692.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:46.367 [error] <0.3882.0> CRASH REPORT Process <0.3882.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:47.010 [error] <0.6990.0> gen_server <0.6990.0> terminated with reason: killed
2016-04-12 08:52:47.013 [error] <0.4024.0> gen_server <0.4024.0> terminated with reason: killed
2016-04-12 08:52:47.010 [error] <0.6990.0> CRASH REPORT Process <0.6990.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:47.013 [error] <0.4024.0> CRASH REPORT Process <0.4024.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:47.012 [error] <0.6916.0> CRASH REPORT Process <0.6916.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:47.013 [error] <0.3964.0> CRASH REPORT Process <0.3964.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:47.527 [error] <0.7017.0> CRASH REPORT Process <0.7017.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:47.528 [error] <0.4127.0> gen_server <0.4127.0> terminated with reason: killed
2016-04-12 08:52:47.527 [error] <0.916.0> gen_server <0.916.0> terminated with reason: killed
2016-04-12 08:52:47.528 [error] <0.4127.0> CRASH REPORT Process <0.4127.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:47.527 [error] <0.916.0> CRASH REPORT Process <0.916.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:47.528 [error] <0.4120.0> gen_server <0.4120.0> terminated with reason: killed
2016-04-12 08:52:47.528 [error] <0.911.0> gen_server <0.911.0> terminated with reason: killed
2016-04-12 08:52:47.528 [error] <0.4120.0> CRASH REPORT Process <0.4120.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:47.528 [error] <0.911.0> CRASH REPORT Process <0.911.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:47.528 [error] <0.4056.0> CRASH REPORT Process <0.4056.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:47.529 [error] <0.843.0> CRASH REPORT Process <0.843.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:57.691 [error] <0.7222.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-12 08:52:57.691 [error] <0.7225.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:52:57.691 [error] <0.7228.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:52:57.692 [error] <0.7228.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:57.692 [error] <0.7248.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-12 08:52:57.692 [error] <0.7248.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:57.692 [error] <0.7226.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:52:57.692 [error] <0.7226.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:57.692 [error] <0.7220.0> CRASH REPORT Process <0.7220.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-12 08:52:57.692 [error] <0.7225.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:57.781 [error] <0.4227.0> CRASH REPORT Process <0.4227.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
2016-04-12 08:52:57.780 [error] <0.1083.0> gen_server <0.1083.0> terminated with reason: killed
2016-04-12 08:52:57.780 [error] <0.1083.0> CRASH REPORT Process <0.1083.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:57.780 [error] <0.1078.0> gen_server <0.1078.0> terminated with reason: killed
2016-04-12 08:52:57.780 [error] <0.1078.0> CRASH REPORT Process <0.1078.0> with 0 neighbours exited with reason: killed in gen_server:terminate/6 line 744
2016-04-12 08:52:57.781 [error] <0.1025.0> CRASH REPORT Process <0.1025.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 224
