2016-04-10 22:34:37.113 [error] <0.99.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:34:37.113 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:37.113 [error] <0.99.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:37.113 [error] <0.93.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.95.0> exit with reason killed in context child_terminated
2016-04-10 22:34:37.113 [error] <0.93.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.95.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:34:37.113 [error] <0.97.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:34:37.113 [error] <0.97.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:37.113 [error] <0.96.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:34:37.329 [error] <0.794.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd923283o923277n923275@testing-worker-linux-docker-03d9c4fa-3371-linux-15'...

2016-04-10 22:34:37.329 [error] <0.795.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.798.0> exit with reason killed in context child_terminated
2016-04-10 22:34:37.329 [error] <0.795.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.798.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:34:37.331 [error] <0.793.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.795.0> exit with reason shutdown in context child_terminated
2016-04-10 22:34:38.158 [error] <0.1089.0> gen_server <0.1089.0> terminated with reason: killed
2016-04-10 22:34:38.159 [error] <0.450.0> CRASH REPORT Process <0.450.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:38.158 [error] <0.1089.0> CRASH REPORT Process <0.1089.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:38.160 [error] <0.1019.0> CRASH REPORT Process <0.1019.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:38.706 [error] <0.661.0> gen_server <0.661.0> terminated with reason: killed
2016-04-10 22:34:38.706 [error] <0.661.0> CRASH REPORT Process <0.661.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:38.707 [error] <0.539.0> CRASH REPORT Process <0.539.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:39.072 [error] <0.1665.0> gen_server <0.1665.0> terminated with reason: killed
2016-04-10 22:34:39.072 [error] <0.858.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:34:39.072 [error] <0.1665.0> CRASH REPORT Process <0.1665.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:39.072 [error] <0.858.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:39.073 [error] <0.1600.0> CRASH REPORT Process <0.1600.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:39.072 [error] <0.854.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.856.0> exit with reason killed in context child_terminated
2016-04-10 22:34:39.072 [error] <0.854.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.856.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:34:39.072 [error] <0.857.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:34:39.072 [error] <0.860.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:34:39.072 [error] <0.860.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:39.073 [error] <0.852.0> CRASH REPORT Process <0.852.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:39.372 [error] <0.1717.0> CRASH REPORT Process <0.1717.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:40.360 [error] <0.2169.0> gen_server <0.2169.0> terminated with reason: killed
2016-04-10 22:34:40.359 [error] <0.1320.0> gen_server <0.1320.0> terminated with reason: killed
2016-04-10 22:34:40.360 [error] <0.2169.0> CRASH REPORT Process <0.2169.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:40.359 [error] <0.1320.0> CRASH REPORT Process <0.1320.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:40.360 [error] <0.2107.0> CRASH REPORT Process <0.2107.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:40.360 [error] <0.1259.0> CRASH REPORT Process <0.1259.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:40.632 [error] <0.2311.0> gen_server <0.2311.0> terminated with reason: killed
2016-04-10 22:34:40.632 [error] <0.2311.0> CRASH REPORT Process <0.2311.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:41.145 [error] <0.1517.0> gen_server <0.1517.0> terminated with reason: killed
2016-04-10 22:34:41.147 [error] <0.2377.0> CRASH REPORT Process <0.2377.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:41.145 [error] <0.1517.0> CRASH REPORT Process <0.1517.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:34:41.145 [error] <0.1455.0> CRASH REPORT Process <0.1455.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:41.336 [error] <0.1568.0> CRASH REPORT Process <0.1568.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:44.391 [error] <0.2965.0> CRASH REPORT Process <0.2965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:49.141 [error] <0.3239.0> CRASH REPORT Process <0.3239.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:34:51.185 [error] <0.3359.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.185 [error] <0.3362.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.185 [error] <0.3360.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.186 [error] <0.3358.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.186 [error] <0.3365.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.186 [error] <0.3367.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.186 [error] <0.3366.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:34:51.186 [error] <0.3373.0> Mnesia2('test7817@testing-worker-linux-docker-03d9c4fa-3371-linux-15'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3407.0>}})

2016-04-10 22:35:01.381 [error] <0.3697.0> CRASH REPORT Process <0.3697.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:03.465 [error] <0.3765.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3771.0> exit with reason killed in context child_terminated
2016-04-10 22:35:03.465 [error] <0.3765.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3771.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:35:03.466 [error] <0.3761.0> CRASH REPORT Process <0.3761.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:19.697 [error] <0.3893.0> CRASH REPORT Process <0.3893.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:27.836 [error] <0.4527.0> CRASH REPORT Process <0.4527.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:33.090 [error] <0.4743.0> CRASH REPORT Process <0.4743.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:35.146 [error] <0.4810.0> CRASH REPORT Process <0.4810.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:38.568 [error] <0.1844.0> gen_server <0.1844.0> terminated with reason: killed
2016-04-10 22:35:38.568 [error] <0.1844.0> CRASH REPORT Process <0.1844.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:35:38.569 [error] <0.1782.0> CRASH REPORT Process <0.1782.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:41.619 [error] <0.4975.0> gen_server <0.4975.0> terminated with reason: killed
2016-04-10 22:35:41.619 [error] <0.4975.0> CRASH REPORT Process <0.4975.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:35:41.620 [error] <0.4902.0> CRASH REPORT Process <0.4902.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:42.669 [error] <0.1855.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1873.0> exit with reason killed in context child_terminated
2016-04-10 22:35:42.670 [error] <0.1855.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1873.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:35:42.670 [error] <0.1851.0> CRASH REPORT Process <0.1851.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:43.770 [error] <0.5009.0> CRASH REPORT Process <0.5009.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:43.770 [error] <0.1993.0> gen_server <0.1993.0> terminated with reason: killed
2016-04-10 22:35:43.770 [error] <0.1993.0> CRASH REPORT Process <0.1993.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:35:43.770 [error] <0.1932.0> CRASH REPORT Process <0.1932.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:58.314 [error] <0.2190.0> gen_server <0.2190.0> terminated with reason: killed
2016-04-10 22:35:58.314 [error] <0.2190.0> CRASH REPORT Process <0.2190.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:35:58.314 [error] <0.2129.0> CRASH REPORT Process <0.2129.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:35:58.336 [error] <0.5339.0> CRASH REPORT Process <0.5339.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:00.049 [error] <0.2217.0> CRASH REPORT Process <0.2217.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:01.138 [error] <0.5623.0> gen_server <0.5623.0> terminated with reason: killed
2016-04-10 22:36:01.138 [error] <0.5623.0> CRASH REPORT Process <0.5623.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:01.138 [error] <0.5550.0> CRASH REPORT Process <0.5550.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:01.139 [error] <0.2340.0> gen_server <0.2340.0> terminated with reason: killed
2016-04-10 22:36:01.139 [error] <0.2340.0> CRASH REPORT Process <0.2340.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:01.139 [error] <0.2320.0> CRASH REPORT Process <0.2320.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:03.511 [error] <0.2415.0> gen_server <0.2415.0> terminated with reason: killed
2016-04-10 22:36:03.512 [error] <0.5732.0> gen_server <0.5732.0> terminated with reason: killed
2016-04-10 22:36:03.511 [error] <0.2415.0> CRASH REPORT Process <0.2415.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:03.512 [error] <0.5732.0> CRASH REPORT Process <0.5732.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:03.512 [error] <0.2395.0> CRASH REPORT Process <0.2395.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:03.512 [error] <0.5661.0> CRASH REPORT Process <0.5661.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:05.571 [error] <0.5741.0> CRASH REPORT Process <0.5741.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:07.014 [error] <0.2454.0> CRASH REPORT Process <0.2454.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:08.461 [error] <0.5866.0> CRASH REPORT Process <0.5866.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:08.460 [error] <0.2603.0> gen_server <0.2603.0> terminated with reason: killed
2016-04-10 22:36:08.460 [error] <0.2603.0> CRASH REPORT Process <0.2603.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:08.460 [error] <0.2564.0> gen_server <0.2564.0> terminated with reason: killed
2016-04-10 22:36:08.461 [error] <0.2564.0> CRASH REPORT Process <0.2564.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:08.461 [error] <0.2543.0> CRASH REPORT Process <0.2543.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:10.603 [error] <0.2644.0> gen_server <0.2644.0> terminated with reason: killed
2016-04-10 22:36:10.610 [error] <0.6034.0> gen_server <0.6034.0> terminated with reason: killed
2016-04-10 22:36:10.603 [error] <0.2644.0> CRASH REPORT Process <0.2644.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:10.610 [error] <0.6034.0> CRASH REPORT Process <0.6034.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:10.603 [error] <0.2624.0> CRASH REPORT Process <0.2624.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:10.613 [error] <0.5961.0> CRASH REPORT Process <0.5961.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:12.740 [error] <0.2698.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2705.0> exit with reason killed in context child_terminated
2016-04-10 22:36:12.741 [error] <0.6057.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.6059.0> exit with reason killed in context child_terminated
2016-04-10 22:36:12.740 [error] <0.2698.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2705.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:12.741 [error] <0.6057.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.6059.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:12.740 [error] <0.2716.0> gen_server <0.2716.0> terminated with reason: killed
2016-04-10 22:36:12.741 [error] <0.6061.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:36:12.740 [error] <0.2716.0> CRASH REPORT Process <0.2716.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:12.741 [error] <0.6061.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:12.740 [error] <0.2694.0> CRASH REPORT Process <0.2694.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:12.741 [error] <0.6066.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:36:12.742 [error] <0.6066.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:14.927 [error] <0.2832.0> gen_server <0.2832.0> terminated with reason: killed
2016-04-10 22:36:14.927 [error] <0.2832.0> CRASH REPORT Process <0.2832.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:14.928 [error] <0.2769.0> CRASH REPORT Process <0.2769.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:15.954 [error] <0.6141.0> CRASH REPORT Process <0.6141.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:23.040 [error] <0.6275.0> gen_server <0.6275.0> terminated with reason: killed
2016-04-10 22:36:23.040 [error] <0.6275.0> CRASH REPORT Process <0.6275.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:23.041 [error] <0.2917.0> gen_server <0.2917.0> terminated with reason: killed
2016-04-10 22:36:23.041 [error] <0.6219.0> CRASH REPORT Process <0.6219.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:23.041 [error] <0.2917.0> CRASH REPORT Process <0.2917.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:23.041 [error] <0.2839.0> CRASH REPORT Process <0.2839.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:24.885 [error] <0.2938.0> CRASH REPORT Process <0.2938.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:25.205 [error] <0.6403.0> gen_server <0.6403.0> terminated with reason: killed
2016-04-10 22:36:25.205 [error] <0.6403.0> CRASH REPORT Process <0.6403.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:25.206 [error] <0.6329.0> CRASH REPORT Process <0.6329.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:25.226 [error] <0.276.0> gen_server <0.276.0> terminated with reason: killed
2016-04-10 22:36:25.227 [error] <0.276.0> CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:25.227 [error] <0.183.0> CRASH REPORT Process <0.183.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:25.873 [error] <0.368.0> gen_server <0.368.0> terminated with reason: killed
2016-04-10 22:36:25.873 [error] <0.368.0> CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:25.873 [error] <0.358.0> gen_server <0.358.0> terminated with reason: killed
2016-04-10 22:36:25.874 [error] <0.358.0> CRASH REPORT Process <0.358.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:27.950 [error] <0.6553.0> gen_server <0.6553.0> terminated with reason: killed
2016-04-10 22:36:27.950 [error] <0.6523.0> gen_server <0.6523.0> terminated with reason: killed
2016-04-10 22:36:27.950 [error] <0.6553.0> CRASH REPORT Process <0.6553.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:27.951 [error] <0.6523.0> CRASH REPORT Process <0.6523.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:27.951 [error] <0.6448.0> CRASH REPORT Process <0.6448.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:27.973 [error] <0.3227.0> gen_server <0.3227.0> terminated with reason: killed
2016-04-10 22:36:27.973 [error] <0.3227.0> CRASH REPORT Process <0.3227.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:27.973 [error] <0.3125.0> CRASH REPORT Process <0.3125.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:28.887 [error] <0.565.0> gen_server <0.565.0> terminated with reason: killed
2016-04-10 22:36:28.887 [error] <0.565.0> CRASH REPORT Process <0.565.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:28.888 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:28.998 [error] <0.6668.0> gen_server <0.6668.0> terminated with reason: killed
2016-04-10 22:36:28.998 [error] <0.6668.0> CRASH REPORT Process <0.6668.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:28.998 [error] <0.6661.0> gen_server <0.6661.0> terminated with reason: killed
2016-04-10 22:36:28.998 [error] <0.6661.0> CRASH REPORT Process <0.6661.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:29.003 [error] <0.6563.0> CRASH REPORT Process <0.6563.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:29.022 [error] <0.3337.0> gen_server <0.3337.0> terminated with reason: killed
2016-04-10 22:36:29.023 [error] <0.3337.0> CRASH REPORT Process <0.3337.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:29.023 [error] <0.3239.0> CRASH REPORT Process <0.3239.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:29.950 [error] <0.3425.0> gen_server <0.3425.0> terminated with reason: killed
2016-04-10 22:36:29.951 [error] <0.3425.0> CRASH REPORT Process <0.3425.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:29.952 [error] <0.3406.0> gen_server <0.3406.0> terminated with reason: killed
2016-04-10 22:36:29.952 [error] <0.3406.0> CRASH REPORT Process <0.3406.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:30.065 [error] <0.3499.0> gen_server <0.3499.0> terminated with reason: killed
2016-04-10 22:36:30.065 [error] <0.3499.0> CRASH REPORT Process <0.3499.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:30.065 [error] <0.3509.0> gen_server <0.3509.0> terminated with reason: killed
2016-04-10 22:36:30.065 [error] <0.3509.0> CRASH REPORT Process <0.3509.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:30.066 [error] <0.3464.0> gen_server <0.3464.0> terminated with reason: killed
2016-04-10 22:36:30.066 [error] <0.3464.0> CRASH REPORT Process <0.3464.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:30.066 [error] <0.3442.0> CRASH REPORT Process <0.3442.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:31.151 [error] <0.3520.0> CRASH REPORT Process <0.3520.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:31.151 [error] <0.6798.0> gen_server <0.6798.0> terminated with reason: killed
2016-04-10 22:36:31.153 [error] <0.821.0> gen_server <0.821.0> terminated with reason: killed
2016-04-10 22:36:31.151 [error] <0.6798.0> CRASH REPORT Process <0.6798.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:31.152 [error] <0.6676.0> CRASH REPORT Process <0.6676.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:31.153 [error] <0.821.0> CRASH REPORT Process <0.821.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:31.153 [error] <0.812.0> gen_server <0.812.0> terminated with reason: killed
2016-04-10 22:36:31.153 [error] <0.812.0> CRASH REPORT Process <0.812.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:31.154 [error] <0.688.0> CRASH REPORT Process <0.688.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:32.017 [error] <0.3883.0> CRASH REPORT Process <0.3883.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:32.641 [error] <0.3969.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.3978.0> exit with reason killed in context child_terminated
2016-04-10 22:36:32.641 [error] <0.3969.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.3978.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:32.644 [error] <0.7018.0> CRASH REPORT Process <0.7018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:32.642 [error] <0.3969.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.3976.0> exit with reason killed in context shutdown_error
2016-04-10 22:36:32.643 [error] <0.3967.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.3969.0> exit with reason shutdown in context child_terminated
2016-04-10 22:36:33.223 [error] <0.7192.0> gen_server <0.7192.0> terminated with reason: killed
2016-04-10 22:36:33.220 [error] <0.913.0> gen_server <0.913.0> terminated with reason: killed
2016-04-10 22:36:33.219 [error] <0.4061.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.4081.0> exit with reason killed in context child_terminated
2016-04-10 22:36:33.223 [error] <0.7192.0> CRASH REPORT Process <0.7192.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.220 [error] <0.913.0> CRASH REPORT Process <0.913.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.223 [error] <0.7187.0> gen_server <0.7187.0> terminated with reason: killed
2016-04-10 22:36:33.219 [error] <0.4061.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.4081.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:33.223 [error] <0.7187.0> CRASH REPORT Process <0.7187.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.220 [error] <0.906.0> gen_server <0.906.0> terminated with reason: killed
2016-04-10 22:36:33.223 [error] <0.7119.0> CRASH REPORT Process <0.7119.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:33.220 [error] <0.4061.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_controller:start() at <0.4083.0> exit with reason killed in context shutdown_error
2016-04-10 22:36:33.220 [error] <0.906.0> CRASH REPORT Process <0.906.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.221 [error] <0.840.0> CRASH REPORT Process <0.840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:33.221 [error] <0.4059.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.4061.0> exit with reason shutdown in context child_terminated
2016-04-10 22:36:33.221 [error] <0.4059.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.4061.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:33.322 [error] <0.1003.0> gen_server <0.1003.0> terminated with reason: killed
2016-04-10 22:36:33.322 [error] <0.1003.0> CRASH REPORT Process <0.1003.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.323 [error] <0.1012.0> gen_server <0.1012.0> terminated with reason: killed
2016-04-10 22:36:33.323 [error] <0.1012.0> CRASH REPORT Process <0.1012.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.323 [error] <0.998.0> gen_server <0.998.0> terminated with reason: killed
2016-04-10 22:36:33.323 [error] <0.998.0> CRASH REPORT Process <0.998.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:33.323 [error] <0.945.0> CRASH REPORT Process <0.945.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:43.384 [error] <0.7328.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:36:43.384 [error] <0.7331.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:36:43.384 [error] <0.7331.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:43.384 [error] <0.7351.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:36:43.384 [error] <0.7351.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:43.384 [error] <0.7325.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 22:36:43.384 [error] <0.7329.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:36:43.384 [error] <0.7329.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:43.384 [error] <0.7323.0> CRASH REPORT Process <0.7323.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
2016-04-10 22:36:43.386 [error] <0.7328.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:43.470 [error] <0.4280.0> gen_server <0.4280.0> terminated with reason: killed
2016-04-10 22:36:43.472 [error] <0.1026.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1032.0> exit with reason killed in context child_terminated
2016-04-10 22:36:43.470 [error] <0.4280.0> CRASH REPORT Process <0.4280.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-10 22:36:43.470 [error] <0.4227.0> CRASH REPORT Process <0.4227.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-10 22:36:43.472 [error] <0.1026.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1032.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:36:43.473 [error] <0.1024.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1026.0> exit with reason shutdown in context child_terminated
2016-04-10 22:36:43.474 [error] <0.1024.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1026.0> exit with reason reached_max_restart_intensity in context shutdown
