2016-04-10 22:45:06.209 [info] <0.7.0> Application lager started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:06.209 [info] <0.7.0> Application poolgirl started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:06.236 [info] <0.494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.494.0>
2016-04-10 22:45:06.264 [info] <0.562.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.562.0>
2016-04-10 22:45:06.787 [info] <0.672.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.672.0>
2016-04-10 22:45:07.016 [info] <0.7.0> Application lager started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:07.016 [info] <0.7.0> Application poolgirl started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:07.070 [info] <0.99.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.99.0>
2016-04-10 22:45:07.083 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:07.263 [error] <0.98.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:45:07.265 [error] <0.663.0> CRASH REPORT Process <0.663.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:07.263 [error] <0.98.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:45:07.264 [error] <0.92.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.94.0> exit with reason killed in context child_terminated
2016-04-10 22:45:07.264 [error] <0.92.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.94.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:45:07.264 [error] <0.96.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:45:07.264 [error] <0.96.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:45:07.264 [error] <0.95.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:45:07.265 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:07.335 [info] <0.799.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.799.0>
2016-04-10 22:45:07.338 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:07.649 [error] <0.793.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'...

2016-04-10 22:45:07.649 [error] <0.794.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.797.0> exit with reason killed in context child_terminated
2016-04-10 22:45:07.649 [error] <0.794.0> Supervisor mnesia2_kernel_sup had child mnesia2_locker started with mnesia2_locker:start() at <0.797.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:45:07.265 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:45:07.361 [info] <0.215.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.215.0>
2016-04-10 22:45:07.711 [info] <0.368.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.368.0>
2016-04-10 22:45:07.805 [info] <0.458.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.458.0>
2016-04-10 22:45:07.705 [info] <0.927.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.927.0>
2016-04-10 22:45:07.763 [info] <0.1027.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1027.0>
2016-04-10 22:45:08.522 [warning] <0.6.0> lager_error_logger_h dropped 24 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:08.522 [error] <0.516.0> gen_server <0.516.0> terminated with reason: killed
2016-04-10 22:45:08.523 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:08.523 [error] <0.1088.0> gen_server <0.1088.0> terminated with reason: killed
2016-04-10 22:45:08.522 [error] <0.516.0> CRASH REPORT Process <0.516.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:45:08.524 [error] <0.1088.0> CRASH REPORT Process <0.1088.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:45:08.523 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:08.524 [error] <0.1018.0> CRASH REPORT Process <0.1018.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:08.524 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:08.582 [info] <0.1150.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1150.0>
2016-04-10 22:45:08.586 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:08.713 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:45:08.725 [info] <0.1262.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1262.0>
2016-04-10 22:45:09.178 [error] <0.1318.0> gen_server <0.1318.0> terminated with reason: killed
2016-04-10 22:45:08.523 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:08.588 [info] <0.547.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.547.0>
2016-04-10 22:45:08.601 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:09.176 [error] <0.660.0> gen_server <0.660.0> terminated with reason: killed
2016-04-10 22:45:09.178 [error] <0.1318.0> CRASH REPORT Process <0.1318.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:45:09.176 [error] <0.660.0> CRASH REPORT Process <0.660.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:45:09.178 [error] <0.1253.0> CRASH REPORT Process <0.1253.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:09.176 [error] <0.538.0> CRASH REPORT Process <0.538.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:09.176 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:09.259 [info] <0.761.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.761.0>
2016-04-10 22:45:09.266 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:09.404 [error] <0.813.0> gen_server <0.813.0> terminated with reason: killed
2016-04-10 22:45:09.178 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:09.255 [info] <0.1494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1494.0>
2016-04-10 22:45:09.258 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:09.406 [error] <0.1485.0> CRASH REPORT Process <0.1485.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:09.404 [error] <0.813.0> CRASH REPORT Process <0.813.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:45:09.405 [error] <0.752.0> CRASH REPORT Process <0.752.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:09.405 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:09.459 [info] <0.860.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.860.0>
2016-04-10 22:45:09.407 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:09.458 [info] <0.1608.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1608.0>
2016-04-10 22:45:09.998 [info] <0.962.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.962.0>
2016-04-10 22:45:10.006 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:10.007 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:10.215 [error] <0.1016.0> gen_server <0.1016.0> terminated with reason: killed
2016-04-10 22:45:09.975 [info] <0.1725.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1725.0>
2016-04-10 22:45:10.219 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:10.220 [error] <0.1716.0> CRASH REPORT Process <0.1716.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:10.215 [error] <0.1016.0> CRASH REPORT Process <0.1016.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:45:10.216 [error] <0.953.0> CRASH REPORT Process <0.953.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:10.220 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:10.273 [info] <0.1851.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1851.0>
2016-04-10 22:45:10.578 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:10.777 [error] <0.1842.0> CRASH REPORT Process <0.1842.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:10.778 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:10.851 [info] <0.1983.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1983.0>
2016-04-10 22:45:10.216 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:10.275 [info] <0.1068.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1068.0>
2016-04-10 22:45:10.860 [info] <0.1169.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1169.0>
2016-04-10 22:45:11.061 [error] <0.1974.0> CRASH REPORT Process <0.1974.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:11.059 [warning] <0.6.0> lager_error_logger_h dropped 31 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:11.059 [error] <0.1222.0> gen_server <0.1222.0> terminated with reason: killed
2016-04-10 22:45:11.059 [error] <0.1222.0> CRASH REPORT Process <0.1222.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:45:11.059 [error] <0.1159.0> CRASH REPORT Process <0.1159.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:11.059 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:11.358 [info] <0.1269.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1269.0>
2016-04-10 22:45:11.361 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:11.914 [error] <0.1322.0> gen_server <0.1322.0> terminated with reason: killed
2016-04-10 22:45:11.061 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:11.355 [info] <0.2116.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2116.0>
2016-04-10 22:45:11.675 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:11.914 [error] <0.2173.0> gen_server <0.2173.0> terminated with reason: killed
2016-04-10 22:45:11.914 [error] <0.2173.0> CRASH REPORT Process <0.2173.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:45:11.914 [error] <0.1322.0> CRASH REPORT Process <0.1322.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:45:11.915 [error] <0.2107.0> CRASH REPORT Process <0.2107.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:12.038 [info] <0.1376.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1376.0>
2016-04-10 22:45:12.042 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:11.915 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:12.023 [info] <0.2257.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2257.0>
2016-04-10 22:45:12.026 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:12.244 [error] <0.1430.0> gen_server <0.1430.0> terminated with reason: killed
2016-04-10 22:45:12.246 [error] <0.2313.0> gen_server <0.2313.0> terminated with reason: killed
2016-04-10 22:45:12.246 [error] <0.2313.0> CRASH REPORT Process <0.2313.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:45:12.245 [error] <0.1430.0> CRASH REPORT Process <0.1430.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:45:12.246 [error] <0.2248.0> CRASH REPORT Process <0.2248.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:12.245 [error] <0.1367.0> CRASH REPORT Process <0.1367.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:12.247 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:12.331 [info] <0.2388.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2388.0>
2016-04-10 22:45:12.644 [info] <0.2520.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2520.0>
2016-04-10 22:45:12.903 [info] <0.2643.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2643.0>
2016-04-10 22:45:13.216 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:13.216 [error] <0.2634.0> CRASH REPORT Process <0.2634.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:12.245 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:12.349 [info] <0.1463.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1463.0>
2016-04-10 22:45:12.652 [info] <0.1575.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1575.0>
2016-04-10 22:45:12.919 [info] <0.1663.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1663.0>
2016-04-10 22:45:13.216 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:13.257 [info] <0.2771.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2771.0>
2016-04-10 22:45:13.260 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:13.309 [error] <0.2762.0> CRASH REPORT Process <0.2762.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:13.309 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:13.359 [info] <0.2865.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2865.0>
2016-04-10 22:45:14.630 [info] <0.2975.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2975.0>
2016-04-10 22:45:14.633 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:15.893 [error] <0.2966.0> CRASH REPORT Process <0.2966.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:15.893 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:17.983 [info] <0.3081.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3081.0>
2016-04-10 22:45:17.985 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:17.987 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:45:17.988 [info] <0.3129.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3129.0>
2016-04-10 22:45:17.993 [info] <0.3177.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3177.0>
2016-04-10 22:45:20.093 [info] <0.3249.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3249.0>
2016-04-10 22:45:20.095 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:20.185 [error] <0.3240.0> CRASH REPORT Process <0.3240.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:20.185 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:22.297 [info] <0.3332.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3332.0>
2016-04-10 22:45:22.300 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:22.340 [info] <0.3326.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-10 22:45:22.342 [info] <0.3326.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test946@testing-worker-linux-docker-c74eb140-3365-linux-10.2016-04-10_22.44.38/Mnesia2.test946@testing-worker-linux-docker-c74eb140-3365-linux-10/LATEST.LOG"] -> badarg

2016-04-10 22:45:22.344 [error] <0.3360.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_3,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:22.344 [error] <0.3362.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_5,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:22.344 [error] <0.3361.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_4,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:22.344 [error] <0.3359.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:22.344 [error] <0.3366.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:22.344 [error] <0.3367.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:22.345 [info] <0.3408.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_tm_18 terminated: shutdown

2016-04-10 22:45:22.345 [error] <0.3365.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_6,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-10 22:45:24.438 [warning] <0.6.0> lager_error_logger_h dropped 22 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:24.438 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_monitor starting: <0.3446.0>

2016-04-10 22:45:24.439 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Mnesia2 debug level set to verbose
2016-04-10 22:45:24.440 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_subscr starting: <0.3447.0>

2016-04-10 22:45:24.441 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_locker starting: <0.3448.0>

2016-04-10 22:45:24.441 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_recover starting: <0.3449.0>

2016-04-10 22:45:24.441 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_tm starting: <0.3450.0>

2016-04-10 22:45:24.442 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Schema initiated from: default

2016-04-10 22:45:24.442 [info] <0.3450.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3450.0>
2016-04-10 22:45:24.442 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_controller starting: <0.3453.0>

2016-04-10 22:45:24.443 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_late_loader starting: <0.3454.0>

2016-04-10 22:45:24.443 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Intend to load tables: []

2016-04-10 22:45:24.444 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_tm_1 starting: <0.3456.0>

2016-04-10 22:45:24.444 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_tm_2 starting: <0.3457.0>

2016-04-10 22:45:24.444 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_tm_3 starting: <0.3458.0>

2016-04-10 22:45:24.445 [info] <0.3444.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_tm_4 starting: <0.3459.0>

2016-04-10 22:45:26.468 [warning] <0.6.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:26.469 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_monitor starting: <0.3503.0>

2016-04-10 22:45:26.469 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Version: "1.0.0"

2016-04-10 22:45:26.469 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env access_module: mnesia2

2016-04-10 22:45:26.470 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env auto_repair: true

2016-04-10 22:45:26.470 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env backup_module: mnesia2_backup

2016-04-10 22:45:26.470 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env debug: debug

2016-04-10 22:45:26.470 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test946@testing-worker-linux-docker-c74eb140-3365-linux-10.2016-04-10_22.44.38/Mnesia2.test946@testing-worker-linux-docker-c74eb140-3365-linux-10"

2016-04-10 22:45:26.471 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_disc_copies_at_startup: true

2016-04-10 22:45:26.471 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_log_load_regulation: false

2016-04-10 22:45:26.471 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_log_time_threshold: 180000

2016-04-10 22:45:26.471 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_log_update_in_place: true

2016-04-10 22:45:26.471 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_log_write_threshold: 1000

2016-04-10 22:45:26.472 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env event_module: mnesia2_event

2016-04-10 22:45:26.472 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env extra_db_nodes: []

2016-04-10 22:45:26.472 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env ignore_fallback_at_startup: false

2016-04-10 22:45:26.472 [info] <0.3507.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3507.0>
2016-04-10 22:45:26.472 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:45:26.472 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env max_wait_for_decision: infinity

2016-04-10 22:45:26.473 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env schema_location: opt_disc

2016-04-10 22:45:26.473 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env core_dir: false

2016-04-10 22:45:26.473 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env pid_sort_order: false

2016-04-10 22:45:26.473 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env no_table_loaders: 2

2016-04-10 22:45:26.473 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dc_dump_limit: 4

2016-04-10 22:45:26.473 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env send_compressed: 0

2016-04-10 22:45:26.474 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env send_max_packets: 20

2016-04-10 22:45:26.474 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env send_max_transfer_size: 7500

2016-04-10 22:45:26.474 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env async_dirty_buffer_size: 524288

2016-04-10 22:45:26.474 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:45:26.474 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-10 22:45:26.474 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env async_dirty_buffer_min_runtime: 10000

2016-04-10 22:45:26.475 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-10 22:45:26.475 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Mnesia2 debug level set to debug
2016-04-10 22:45:26.475 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_subscr starting: <0.3504.0>

2016-04-10 22:45:26.475 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_locker starting: <0.3505.0>

2016-04-10 22:45:26.475 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_recover starting: <0.3506.0>

2016-04-10 22:45:26.475 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_tm starting: <0.3507.0>

2016-04-10 22:45:26.475 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Schema initiated from: default

2016-04-10 22:45:26.475 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): debug fun {mnesia2_tm,init} in ets mnesia2_debug does not exist, ignoring
2016-04-10 22:45:26.475 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_controller starting: <0.3510.0>

2016-04-10 22:45:26.475 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_late_loader starting: <0.3511.0>

2016-04-10 22:45:26.476 [info] <0.3501.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Intend to load tables: []

2016-04-10 22:45:28.502 [warning] <0.6.0> lager_error_logger_h dropped 29 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:28.502 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_monitor starting: <0.3565.0>

2016-04-10 22:45:28.503 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Version: "1.0.0"

2016-04-10 22:45:28.503 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env access_module: mnesia2

2016-04-10 22:45:28.503 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env auto_repair: true

2016-04-10 22:45:28.503 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env backup_module: mnesia2_backup

2016-04-10 22:45:28.504 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env debug: trace

2016-04-10 22:45:28.505 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test946@testing-worker-linux-docker-c74eb140-3365-linux-10.2016-04-10_22.44.38/Mnesia2.test946@testing-worker-linux-docker-c74eb140-3365-linux-10"

2016-04-10 22:45:28.505 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_disc_copies_at_startup: true

2016-04-10 22:45:28.505 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_log_load_regulation: false

2016-04-10 22:45:28.506 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_log_time_threshold: 180000

2016-04-10 22:45:28.506 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_log_update_in_place: true

2016-04-10 22:45:28.506 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_log_write_threshold: 1000

2016-04-10 22:45:28.506 [info] <0.3569.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3569.0>
2016-04-10 22:45:28.507 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env event_module: mnesia2_event

2016-04-10 22:45:28.507 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env extra_db_nodes: []

2016-04-10 22:45:28.507 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env ignore_fallback_at_startup: false

2016-04-10 22:45:28.507 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:45:28.508 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env max_wait_for_decision: infinity

2016-04-10 22:45:28.508 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env schema_location: opt_disc

2016-04-10 22:45:28.508 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env core_dir: false

2016-04-10 22:45:28.509 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env pid_sort_order: false

2016-04-10 22:45:28.509 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env no_table_loaders: 2

2016-04-10 22:45:28.509 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dc_dump_limit: 4

2016-04-10 22:45:28.510 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env send_compressed: 0

2016-04-10 22:45:28.510 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env send_max_packets: 20

2016-04-10 22:45:28.510 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env send_max_transfer_size: 7500

2016-04-10 22:45:28.510 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env async_dirty_buffer_size: 524288

2016-04-10 22:45:28.511 [info] <0.3563.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:45:30.536 [warning] <0.6.0> lager_error_logger_h dropped 30 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:30.537 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): mnesia2_monitor starting: <0.3617.0>

2016-04-10 22:45:30.537 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Version: "1.0.0"

2016-04-10 22:45:30.537 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env access_module: mnesia2

2016-04-10 22:45:30.537 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env auto_repair: true

2016-04-10 22:45:30.537 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env backup_module: mnesia2_backup

2016-04-10 22:45:30.537 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env debug: debug

2016-04-10 22:45:30.538 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test946@testing-worker-linux-docker-c74eb140-3365-linux-10.2016-04-10_22.44.38/Mnesia2.test946@testing-worker-linux-docker-c74eb140-3365-linux-10"

2016-04-10 22:45:30.538 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_disc_copies_at_startup: true

2016-04-10 22:45:30.539 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_log_load_regulation: false

2016-04-10 22:45:30.540 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_log_time_threshold: 180000

2016-04-10 22:45:30.540 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_log_update_in_place: true

2016-04-10 22:45:30.540 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dump_log_write_threshold: 1000

2016-04-10 22:45:30.540 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env event_module: mnesia2_event

2016-04-10 22:45:30.540 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env extra_db_nodes: []

2016-04-10 22:45:30.540 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env ignore_fallback_at_startup: false

2016-04-10 22:45:30.541 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env fallback_error_function: {mnesia2,lkill}

2016-04-10 22:45:30.541 [info] <0.3621.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3621.0>
2016-04-10 22:45:30.541 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env max_wait_for_decision: infinity

2016-04-10 22:45:30.541 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env schema_location: opt_disc

2016-04-10 22:45:30.541 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env core_dir: false

2016-04-10 22:45:30.541 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env pid_sort_order: false

2016-04-10 22:45:30.542 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env no_table_loaders: 2

2016-04-10 22:45:30.542 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env dc_dump_limit: 4

2016-04-10 22:45:30.542 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env send_compressed: 0

2016-04-10 22:45:30.543 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env send_max_packets: 20

2016-04-10 22:45:30.543 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env send_max_transfer_size: 7500

2016-04-10 22:45:30.543 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env async_dirty_buffer_size: 524288

2016-04-10 22:45:30.543 [info] <0.3615.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-10 22:45:32.568 [warning] <0.6.0> lager_error_logger_h dropped 36 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:45:32.570 [info] <0.3702.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3702.0>
2016-04-10 22:45:32.572 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:32.573 [error] <0.3693.0> CRASH REPORT Process <0.3693.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:32.574 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:34.667 [info] <0.3766.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3766.0>
2016-04-10 22:45:34.669 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:34.670 [error] <0.3757.0> CRASH REPORT Process <0.3757.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:34.671 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:37.107 [info] <0.3837.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3837.0>
2016-04-10 22:45:37.110 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:45:37.302 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:45:37.369 [info] <0.3898.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3898.0>
2016-04-10 22:45:38.890 [error] <0.3892.0> Mnesia2('test946@testing-worker-linux-docker-c74eb140-3365-linux-10'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

2016-04-10 22:45:52.552 [error] <0.3889.0> CRASH REPORT Process <0.3889.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:45:52.552 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:45:54.684 [info] <0.4480.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.4480.0>
2016-04-10 22:45:54.688 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:00.696 [error] <0.4471.0> CRASH REPORT Process <0.4471.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:00.696 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:02.854 [info] <0.4580.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.4580.0>
2016-04-10 22:46:02.857 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:04.147 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:46:06.257 [info] <0.4696.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.4696.0>
2016-04-10 22:46:06.260 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:06.265 [error] <0.4687.0> CRASH REPORT Process <0.4687.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:06.265 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:08.297 [info] <0.4763.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.4763.0>
2016-04-10 22:46:08.299 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:08.324 [error] <0.4754.0> CRASH REPORT Process <0.4754.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:08.324 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:10.415 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:46:10.437 [info] <0.1789.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1789.0>
2016-04-10 22:46:10.440 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:10.430 [info] <0.4855.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.4855.0>
2016-04-10 22:46:10.432 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:11.442 [error] <0.1841.0> gen_server <0.1841.0> terminated with reason: killed
2016-04-10 22:46:11.442 [error] <0.1841.0> CRASH REPORT Process <0.1841.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:11.442 [error] <0.1780.0> CRASH REPORT Process <0.1780.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:11.442 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:13.491 [info] <0.1857.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1857.0>
2016-04-10 22:46:13.500 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:14.504 [error] <0.4846.0> CRASH REPORT Process <0.4846.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:14.504 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:15.555 [error] <0.1848.0> CRASH REPORT Process <0.1848.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:15.555 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:16.657 [info] <0.1939.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1939.0>
2016-04-10 22:46:16.661 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:16.663 [error] <0.1929.0> CRASH REPORT Process <0.1929.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:16.649 [info] <0.4961.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.4961.0>
2016-04-10 22:46:16.651 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:16.664 [error] <0.4952.0> CRASH REPORT Process <0.4952.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:16.664 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:16.711 [info] <0.5036.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.5036.0>
2016-04-10 22:46:16.663 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:21.221 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:46:21.278 [info] <0.5160.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.5160.0>
2016-04-10 22:46:21.283 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:21.269 [info] <0.2008.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2008.0>
2016-04-10 22:46:21.271 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:32.268 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:46:32.272 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:46:33.459 [info] <0.2130.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2130.0>
2016-04-10 22:46:33.463 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:33.506 [error] <0.2182.0> gen_server <0.2182.0> terminated with reason: killed
2016-04-10 22:46:33.506 [error] <0.2182.0> CRASH REPORT Process <0.2182.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:33.507 [error] <0.2121.0> CRASH REPORT Process <0.2121.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:33.453 [info] <0.5291.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.5291.0>
2016-04-10 22:46:33.456 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:33.527 [error] <0.5286.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5303.0> exit with reason killed in context child_terminated
2016-04-10 22:46:33.527 [error] <0.5286.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5303.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:46:33.529 [error] <0.5282.0> CRASH REPORT Process <0.5282.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:33.529 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:33.563 [info] <0.5379.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.5379.0>
2016-04-10 22:46:34.245 [error] <0.5450.0> gen_server <0.5450.0> terminated with reason: killed
2016-04-10 22:46:34.245 [error] <0.5450.0> CRASH REPORT Process <0.5450.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:34.246 [error] <0.5370.0> CRASH REPORT Process <0.5370.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:34.246 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:33.507 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:33.824 [info] <0.2218.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2218.0>
2016-04-10 22:46:35.370 [warning] <0.6.0> lager_error_logger_h dropped 15 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:46:35.370 [error] <0.2209.0> CRASH REPORT Process <0.2209.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:35.370 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:36.427 [info] <0.5502.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.5502.0>
2016-04-10 22:46:36.430 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:36.464 [error] <0.5566.0> gen_server <0.5566.0> terminated with reason: killed
2016-04-10 22:46:36.435 [info] <0.2321.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2321.0>
2016-04-10 22:46:36.440 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:36.464 [error] <0.2312.0> CRASH REPORT Process <0.2312.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:36.464 [error] <0.5566.0> CRASH REPORT Process <0.5566.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:36.465 [error] <0.5493.0> CRASH REPORT Process <0.5493.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:36.465 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:36.464 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:38.566 [info] <0.2396.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2396.0>
2016-04-10 22:46:38.574 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:38.577 [error] <0.2408.0> gen_server <0.2408.0> terminated with reason: killed
2016-04-10 22:46:38.556 [info] <0.5613.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.5613.0>
2016-04-10 22:46:38.559 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:38.578 [error] <0.5677.0> gen_server <0.5677.0> terminated with reason: killed
2016-04-10 22:46:38.577 [error] <0.2408.0> CRASH REPORT Process <0.2408.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:38.578 [error] <0.5677.0> CRASH REPORT Process <0.5677.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:38.579 [error] <0.2387.0> CRASH REPORT Process <0.2387.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:38.582 [error] <0.5604.0> CRASH REPORT Process <0.5604.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:38.582 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:38.579 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:40.611 [info] <0.5693.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.5693.0>
2016-04-10 22:46:40.619 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:40.648 [error] <0.5735.0> gen_server <0.5735.0> terminated with reason: killed
2016-04-10 22:46:40.648 [error] <0.5735.0> CRASH REPORT Process <0.5735.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:40.649 [error] <0.5684.0> CRASH REPORT Process <0.5684.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:40.602 [info] <0.2455.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2455.0>
2016-04-10 22:46:40.603 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:40.649 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:42.082 [error] <0.2446.0> CRASH REPORT Process <0.2446.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:42.082 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:43.206 [info] <0.5818.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.5818.0>
2016-04-10 22:46:43.208 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:43.594 [error] <0.5813.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5819.0> exit with reason killed in context child_terminated
2016-04-10 22:46:43.211 [info] <0.2544.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2544.0>
2016-04-10 22:46:43.216 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:43.594 [error] <0.2595.0> gen_server <0.2595.0> terminated with reason: killed
2016-04-10 22:46:43.594 [error] <0.5813.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.5819.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:46:43.594 [error] <0.2595.0> CRASH REPORT Process <0.2595.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:43.595 [error] <0.5811.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5813.0> exit with reason shutdown in context child_terminated
2016-04-10 22:46:43.595 [error] <0.2535.0> CRASH REPORT Process <0.2535.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:43.595 [error] <0.5811.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.5813.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:46:43.596 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:46:43.595 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:43.497 [info] <0.7.0> Application lager started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:43.497 [info] <0.7.0> Application poolgirl started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:43.523 [info] <0.101.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.101.0>
2016-04-10 22:46:43.548 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:45.714 [info] <0.2625.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2625.0>
2016-04-10 22:46:45.719 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:45.723 [error] <0.2637.0> gen_server <0.2637.0> terminated with reason: killed
2016-04-10 22:46:45.707 [info] <0.5913.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.5913.0>
2016-04-10 22:46:45.709 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:45.736 [error] <0.5904.0> CRASH REPORT Process <0.5904.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:45.723 [error] <0.2637.0> CRASH REPORT Process <0.2637.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:45.724 [error] <0.2616.0> CRASH REPORT Process <0.2616.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:45.736 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:45.724 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:47.833 [info] <0.2695.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2695.0>
2016-04-10 22:46:47.851 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:47.857 [error] <0.2686.0> CRASH REPORT Process <0.2686.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:47.828 [info] <0.6007.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.6007.0>
2016-04-10 22:46:47.830 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:47.857 [error] <0.5998.0> CRASH REPORT Process <0.5998.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:47.857 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:47.857 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:50.022 [info] <0.2770.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2770.0>
2016-04-10 22:46:50.035 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:50.056 [error] <0.2761.0> CRASH REPORT Process <0.2761.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:49.978 [info] <0.6093.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.6093.0>
2016-04-10 22:46:49.980 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:50.057 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:51.083 [error] emulator Error in process <0.6153.0> on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10' with exit value: {badarg,[{erlang,unlink,[undefined],[]},{mnesia2_schema,schema_coordinator,3,[{file,"src/mnesia2_schema.erl"},{line,619}]}]}


2016-04-10 22:46:51.084 [error] <0.6084.0> CRASH REPORT Process <0.6084.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:51.084 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:53.130 [info] <0.2840.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2840.0>
2016-04-10 22:46:53.131 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:58.180 [error] <0.2907.0> gen_server <0.2907.0> terminated with reason: killed
2016-04-10 22:46:58.166 [info] <0.6171.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.6171.0>
2016-04-10 22:46:58.175 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:58.183 [error] <0.6215.0> gen_server <0.6215.0> terminated with reason: killed
2016-04-10 22:46:58.180 [error] <0.2907.0> CRASH REPORT Process <0.2907.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:58.183 [error] <0.6215.0> CRASH REPORT Process <0.6215.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:58.181 [error] <0.2831.0> CRASH REPORT Process <0.2831.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:58.183 [error] <0.6162.0> CRASH REPORT Process <0.6162.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:58.183 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:58.181 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:59.386 [info] <0.2939.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2939.0>
2016-04-10 22:46:59.394 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:59.756 [error] <0.2996.0> gen_server <0.2996.0> terminated with reason: killed
2016-04-10 22:46:59.756 [error] <0.2996.0> CRASH REPORT Process <0.2996.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:59.756 [error] <0.3001.0> gen_server <0.3001.0> terminated with reason: killed
2016-04-10 22:46:59.756 [error] <0.3001.0> CRASH REPORT Process <0.3001.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:59.756 [error] <0.2930.0> CRASH REPORT Process <0.2930.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:59.384 [info] <0.6281.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.6281.0>
2016-04-10 22:46:59.690 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:59.839 [error] <0.6369.0> gen_server <0.6369.0> terminated with reason: killed
2016-04-10 22:46:59.839 [error] <0.6369.0> CRASH REPORT Process <0.6369.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:59.839 [error] <0.6346.0> gen_server <0.6346.0> terminated with reason: killed
2016-04-10 22:46:59.840 [error] <0.6346.0> CRASH REPORT Process <0.6346.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:59.840 [error] <0.6385.0> gen_server <0.6385.0> terminated with reason: killed
2016-04-10 22:46:59.840 [error] <0.6385.0> CRASH REPORT Process <0.6385.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:59.841 [error] <0.6272.0> CRASH REPORT Process <0.6272.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:46:59.315 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:46:59.433 [info] <0.191.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.191.0>
2016-04-10 22:46:59.438 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:59.862 [error] <0.276.0> gen_server <0.276.0> terminated with reason: killed
2016-04-10 22:46:59.862 [error] <0.276.0> CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:46:59.984 [info] <0.295.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.295.0>
2016-04-10 22:46:59.841 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:59.979 [info] <0.6404.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.6404.0>
2016-04-10 22:47:00.285 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:46:59.756 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:46:59.782 [info] <0.3031.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3031.0>
2016-04-10 22:46:59.948 [info] <0.3126.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3126.0>
2016-04-10 22:47:00.816 [warning] <0.6.0> lager_error_logger_h dropped 32 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:47:00.816 [error] <0.367.0> gen_server <0.367.0> terminated with reason: killed
2016-04-10 22:47:00.816 [error] <0.367.0> CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:00.816 [error] <0.358.0> gen_server <0.358.0> terminated with reason: killed
2016-04-10 22:47:00.816 [error] <0.358.0> CRASH REPORT Process <0.358.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:00.816 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:00.816 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:01.161 [info] <0.391.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.391.0>
2016-04-10 22:47:01.162 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:03.275 [error] <0.6395.0> CRASH REPORT Process <0.6395.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:03.296 [warning] <0.6.0> lager_error_logger_h dropped 30 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:47:03.296 [error] <0.3219.0> gen_server <0.3219.0> terminated with reason: killed
2016-04-10 22:47:03.296 [error] <0.3219.0> CRASH REPORT Process <0.3219.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:03.298 [error] <0.3117.0> CRASH REPORT Process <0.3117.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:03.339 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:03.356 [info] <0.497.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.497.0>
2016-04-10 22:47:03.358 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:04.252 [error] <0.572.0> gen_server <0.572.0> terminated with reason: killed
2016-04-10 22:47:04.252 [error] <0.572.0> CRASH REPORT Process <0.572.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:04.252 [error] <0.566.0> gen_server <0.566.0> terminated with reason: killed
2016-04-10 22:47:04.252 [error] <0.566.0> CRASH REPORT Process <0.566.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:03.275 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:03.386 [info] <0.6521.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.6521.0>
2016-04-10 22:47:03.705 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:04.252 [error] <0.488.0> CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:03.298 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:03.405 [info] <0.3240.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3240.0>
2016-04-10 22:47:03.418 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:04.252 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:04.289 [info] <0.597.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.597.0>
2016-04-10 22:47:04.290 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:04.421 [error] <0.6617.0> gen_server <0.6617.0> terminated with reason: killed
2016-04-10 22:47:04.421 [error] <0.6617.0> CRASH REPORT Process <0.6617.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:04.442 [error] <0.3326.0> gen_server <0.3326.0> terminated with reason: killed
2016-04-10 22:47:04.421 [error] <0.6612.0> gen_server <0.6612.0> terminated with reason: killed
2016-04-10 22:47:04.442 [error] <0.3326.0> CRASH REPORT Process <0.3326.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:04.421 [error] <0.6612.0> CRASH REPORT Process <0.6612.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:04.443 [error] <0.3231.0> CRASH REPORT Process <0.3231.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:04.421 [error] <0.6591.0> gen_server <0.6591.0> terminated with reason: killed
2016-04-10 22:47:04.421 [error] <0.6591.0> CRASH REPORT Process <0.6591.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:04.421 [error] <0.6512.0> CRASH REPORT Process <0.6512.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:04.443 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:04.558 [info] <0.3347.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3347.0>
2016-04-10 22:47:04.861 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:05.376 [error] <0.3342.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3367.0> exit with reason killed in context child_terminated
2016-04-10 22:47:04.421 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:04.559 [info] <0.6634.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.6634.0>
2016-04-10 22:47:04.566 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:04.481 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:04.513 [info] <0.698.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.698.0>
2016-04-10 22:47:05.377 [error] <0.3342.0> Supervisor mnesia2_kernel_sup had child mnesia2_checkpoint_sup started with mnesia2_checkpoint_sup:start() at <0.3367.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:47:05.377 [error] <0.3421.0> gen_server <0.3421.0> terminated with reason: killed
2016-04-10 22:47:05.377 [error] <0.3421.0> CRASH REPORT Process <0.3421.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:05.377 [error] <0.3413.0> gen_server <0.3413.0> terminated with reason: killed
2016-04-10 22:47:05.377 [error] <0.3413.0> CRASH REPORT Process <0.3413.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:05.378 [error] <0.3338.0> CRASH REPORT Process <0.3338.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:05.378 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:06.459 [info] <0.3445.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3445.0>
2016-04-10 22:47:06.505 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:06.551 [error] <0.3487.0> gen_server <0.3487.0> terminated with reason: killed
2016-04-10 22:47:06.551 [error] <0.3487.0> CRASH REPORT Process <0.3487.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:06.551 [error] <0.3459.0> gen_server <0.3459.0> terminated with reason: killed
2016-04-10 22:47:06.551 [error] <0.3459.0> CRASH REPORT Process <0.3459.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:06.551 [error] <0.3503.0> gen_server <0.3503.0> terminated with reason: killed
2016-04-10 22:47:06.551 [error] <0.3503.0> CRASH REPORT Process <0.3503.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:06.552 [error] <0.3436.0> CRASH REPORT Process <0.3436.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:06.552 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:07.577 [info] <0.3523.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3523.0>
2016-04-10 22:47:07.603 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:07.683 [error] <0.3514.0> CRASH REPORT Process <0.3514.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:07.683 [error] <0.691.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.693.0> exit with reason killed in context child_terminated
2016-04-10 22:47:07.686 [error] <0.6697.0> gen_server <0.6697.0> terminated with reason: killed
2016-04-10 22:47:07.686 [error] <0.6697.0> CRASH REPORT Process <0.6697.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:07.683 [error] <0.691.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at <0.693.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-10 22:47:07.686 [error] <0.6746.0> gen_server <0.6746.0> terminated with reason: killed
2016-04-10 22:47:07.683 [error] <0.695.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:47:07.683 [error] <0.695.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:07.687 [error] <0.6746.0> CRASH REPORT Process <0.6746.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:07.683 [error] <0.694.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:47:07.687 [error] <0.6625.0> CRASH REPORT Process <0.6625.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:07.683 [error] <0.697.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:47:07.683 [error] <0.697.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:07.683 [error] <0.714.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:47:07.683 [error] <0.714.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:07.683 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:07.788 [info] <0.3602.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3602.0>
2016-04-10 22:47:07.792 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:07.886 [error] <0.3656.0> gen_server <0.3656.0> terminated with reason: killed
2016-04-10 22:47:07.886 [error] <0.3656.0> CRASH REPORT Process <0.3656.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:07.886 [error] <0.3593.0> CRASH REPORT Process <0.3593.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:07.886 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:07.932 [info] <0.3697.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3697.0>
2016-04-10 22:47:08.018 [info] <0.3787.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3787.0>
2016-04-10 22:47:08.018 [warning] <0.6.0> lager_error_logger_h dropped 24 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:47:08.022 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:08.065 [error] <0.3851.0> gen_server <0.3851.0> terminated with reason: killed
2016-04-10 22:47:08.066 [error] <0.3851.0> CRASH REPORT Process <0.3851.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:08.067 [error] <0.3778.0> CRASH REPORT Process <0.3778.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:08.067 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:08.110 [info] <0.3887.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3887.0>
2016-04-10 22:47:07.684 [info] <0.7.0> Application mnesia2 exited with reason: shutdown
2016-04-10 22:47:07.687 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:07.780 [info] <0.6778.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.6778.0>
2016-04-10 22:47:07.784 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:08.096 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:08.639 [info] <0.6891.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.6891.0>
2016-04-10 22:47:08.665 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:08.680 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:08.721 [info] <0.6974.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.6974.0>
2016-04-10 22:47:09.323 [error] <0.7039.0> gen_server <0.7039.0> terminated with reason: killed
2016-04-10 22:47:09.227 [info] <0.3969.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.3969.0>
2016-04-10 22:47:09.261 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:09.325 [error] <0.4020.0> gen_server <0.4020.0> terminated with reason: killed
2016-04-10 22:47:09.324 [error] <0.7039.0> CRASH REPORT Process <0.7039.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:09.324 [error] <0.6965.0> CRASH REPORT Process <0.6965.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:09.325 [error] <0.4020.0> CRASH REPORT Process <0.4020.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:09.325 [error] <0.3960.0> CRASH REPORT Process <0.3960.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:09.324 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:09.418 [info] <0.7075.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.7075.0>
2016-04-10 22:47:09.437 [info] <0.849.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.849.0>
2016-04-10 22:47:09.444 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:09.813 [error] <0.911.0> gen_server <0.911.0> terminated with reason: killed
2016-04-10 22:47:09.725 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:09.813 [error] <0.7072.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-10 22:47:09.813 [error] <0.911.0> CRASH REPORT Process <0.911.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:09.813 [error] <0.7072.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:09.813 [error] <0.904.0> gen_server <0.904.0> terminated with reason: killed
2016-04-10 22:47:09.813 [error] <0.904.0> CRASH REPORT Process <0.904.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:09.813 [error] <0.840.0> CRASH REPORT Process <0.840.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:09.325 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:09.420 [info] <0.4061.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.4061.0>
2016-04-10 22:47:09.840 [info] <0.4157.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.4157.0>
2016-04-10 22:47:09.918 [info] <0.4235.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.4235.0>
2016-04-10 22:47:09.813 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:09.838 [info] <0.952.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.952.0>
2016-04-10 22:47:09.916 [info] <0.1031.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1031.0>
2016-04-10 22:47:09.858 [info] <0.7187.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.7187.0>
2016-04-10 22:47:09.966 [info] <0.7279.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.7279.0>
2016-04-10 22:47:19.974 [warning] <0.6.0> lager_error_logger_h dropped 9 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:47:19.974 [error] <0.7272.0> Supervisor mnesia2_sup had child mnesia2_kernel_sup started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-10 22:47:19.974 [error] <0.7275.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-10 22:47:19.974 [error] <0.7278.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-10 22:47:19.974 [error] <0.7278.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:19.974 [error] <0.7298.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-10 22:47:19.975 [error] <0.7298.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:19.975 [error] <0.7270.0> CRASH REPORT Process <0.7270.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 133
2016-04-10 22:47:19.975 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-10 22:47:19.975 [error] <0.7275.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:19.977 [error] <0.7276.0> gen_server mnesia2_subscr terminated with reason: {aborted,{node_not_running,'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'}} in mnesia2:abort/1 line 313
2016-04-10 22:47:19.977 [error] <0.7276.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: {aborted,{node_not_running,'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'}} in gen_server:terminate/7 line 792
2016-04-10 22:47:20.058 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:47:20.058 [error] <0.4279.0> gen_server <0.4279.0> terminated with reason: killed
2016-04-10 22:47:20.058 [warning] <0.6.0> lager_error_logger_h dropped 24 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-10 22:47:20.058 [error] <0.1081.0> gen_server <0.1081.0> terminated with reason: killed
2016-04-10 22:47:20.059 [error] <0.4279.0> CRASH REPORT Process <0.4279.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:20.058 [error] <0.1081.0> CRASH REPORT Process <0.1081.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:20.059 [error] <0.4226.0> CRASH REPORT Process <0.4226.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:20.059 [error] <0.1075.0> gen_server <0.1075.0> terminated with reason: killed
2016-04-10 22:47:20.059 [error] <0.1075.0> CRASH REPORT Process <0.1075.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 804
2016-04-10 22:47:20.059 [error] <0.1022.0> CRASH REPORT Process <0.1022.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 227
2016-04-10 22:47:20.059 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:20.059 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-10 22:47:22.478 [info] <0.7389.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.7389.0>
2016-04-10 22:47:22.481 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:27.034 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:27.191 [info] <0.7525.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.7525.0>
2016-04-10 22:47:27.496 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:27.193 [info] <0.1128.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1128.0>
2016-04-10 22:47:27.210 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:27.195 [info] <0.4325.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.4325.0>
2016-04-10 22:47:27.258 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:33.593 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:33.790 [info] <0.1243.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1243.0>
2016-04-10 22:47:34.114 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:33.592 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:33.768 [info] <0.7655.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.7655.0>
2016-04-10 22:47:33.771 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:33.604 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:33.810 [info] <0.4440.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.4440.0>
2016-04-10 22:47:33.815 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:40.302 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:40.443 [info] <0.4553.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.4553.0>
2016-04-10 22:47:40.768 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:40.304 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:40.466 [info] <0.1360.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.1360.0>
2016-04-10 22:47:40.470 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:40.308 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:40.437 [info] <0.7785.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.7785.0>
2016-04-10 22:47:40.443 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:59.627 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:59.795 [info] <0.8924.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.8924.0>
2016-04-10 22:48:00.101 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:59.628 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:59.799 [info] <0.5679.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.5679.0>
2016-04-10 22:47:59.822 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:47:59.637 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:47:59.804 [info] <0.2483.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2483.0>
2016-04-10 22:47:59.809 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:48:06.500 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:06.685 [info] <0.2606.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.2606.0>
2016-04-10 22:48:06.700 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:48:06.494 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:06.673 [info] <0.9064.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.9064.0>
2016-04-10 22:48:06.980 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:48:06.533 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:06.678 [info] <0.5805.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.5805.0>
2016-04-10 22:48:06.682 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:48:13.368 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:13.531 [info] <0.7277.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.7277.0>
2016-04-10 22:48:13.548 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:48:13.371 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:13.494 [info] <0.10546.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.10546.0>
2016-04-10 22:48:13.497 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:48:13.374 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:13.522 [info] <0.4074.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.4074.0>
2016-04-10 22:48:13.543 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:48:19.797 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:19.970 [info] <0.5293.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.5293.0>
2016-04-10 22:48:19.978 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:48:19.804 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:19.969 [info] <0.12243.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.12243.0>
2016-04-10 22:48:19.982 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:48:19.831 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:19.971 [info] <0.7611.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.7611.0>
2016-04-10 22:48:19.987 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:48:26.140 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:26.284 [info] <0.12371.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.12371.0>
2016-04-10 22:48:26.289 [info] <0.7.0> Application mnesia2 started on node 'test946@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:48:26.141 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:26.296 [info] <0.6089.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.6089.0>
2016-04-10 22:48:26.600 [info] <0.7.0> Application mnesia2 started on node 'd1087124o1087132n1087132@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:48:26.161 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:26.298 [info] <0.7725.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10', <0.7725.0>
2016-04-10 22:48:26.304 [info] <0.7.0> Application mnesia2 started on node 'd1087130o1087126n1087126@testing-worker-linux-docker-c74eb140-3365-linux-10'
2016-04-10 22:48:32.818 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:32.817 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-10 22:48:32.818 [info] <0.7.0> Application mnesia2 exited with reason: stopped
