--- Test run on 2016/04/10 16:45:02 ---
Converting "/home/travis/build/lrascao/mnesia2/." to "/home/travis/build/lrascao/mnesia2" and re-inserting with add_patha/1


Common Test v1.11.1 starting (cwd is /home/travis/build/lrascao/mnesia2)


Common Test: Running make in test directories...
Recompile: mnesia2_extra_light_SUITE
Recompile: ts_install_cth
ts_install_cth.erl:247: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
Recompile: mt
Recompile: mnesia2_trans_access_test
Recompile: mnesia2_tpcb
Recompile: mnesia2_test_lib
Recompile: mnesia2_schema_recovery_test
mnesia2_schema_recovery_test.erl:261: Warning: variable 'Bad' is unused
Recompile: mnesia2_registry_test
Recompile: mnesia2_recovery_test
mnesia2_recovery_test.erl:1571: Warning: variable 'Config' is unused
Recompile: mnesia2_qlc_test
Recompile: mnesia2_nice_coverage_test
Recompile: mnesia2_meter
Recompile: mnesia2_measure_test
Recompile: mnesia2_majority_test
Recompile: mnesia2_isolation_test
Recompile: mnesia2_install_test
Recompile: mnesia2_inconsistent_database_test
Recompile: mnesia2_frag_test
Recompile: mnesia2_frag_hash_test
Recompile: mnesia2_examples_test
Recompile: mnesia2_evil_coverage_test
Recompile: mnesia2_evil_backup
Recompile: mnesia2_durability_test
Recompile: mnesia2_dirty_access_test
Recompile: mnesia2_dbn_meters
Recompile: mnesia2_cost
Recompile: mnesia2_consistency_test
Recompile: mnesia2_config_test
Recompile: mnesia2_config_event
Recompile: mnesia2_config_backup
Recompile: mnesia2_atomicity_test

CWD set to: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7013@testing-worker-linux-docker-e93d2010-3388-linux-11.2016-04-10_16.45.02"

TEST INFO: 1 test(s), 52 case(s) in 1 suite(s)

Cover compiling 'mnesia2' (32 files) - this may take some time... done

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: Starting test, 52 test cases

----------------------------------------------------
2016-04-10 16:45:26.711
starting test group: extra_light


----------------------------------------------------
2016-04-10 16:45:26.738
starting test group: install


----------------------------------------------------
2016-04-10 16:45:26.818
starting test case: silly_durability

16:45:26.903 [info] Application lager started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:26.903 [info] Application poolgirl started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:26.929 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.495.0>
16:45:26.950 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.563.0>

----------------------------------------------------
2016-04-10 16:45:26.955
ending test case: silly_durability


----------------------------------------------------
2016-04-10 16:45:26.980
starting test case: silly_move

16:45:27.415 [error] CRASH REPORT Process <0.554.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:27.415 [info] Application mnesia2 exited with reason: killed
16:45:27.532 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.673.0>
16:45:27.534 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:27.761 [info] Application lager started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:27.761 [info] Application poolgirl started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:27.818 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.100.0>

----------------------------------------------------
2016-04-10 16:45:27.976
ending test case: silly_move


----------------------------------------------------
2016-04-10 16:45:28.002
starting test case: silly_upgrade

16:45:28.005 [error] gen_server <0.156.0> terminated with reason: killed
16:45:28.005 [error] CRASH REPORT Process <0.156.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:45:28.006 [error] CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:28.006 [info] Application mnesia2 exited with reason: killed
16:45:28.006 [error] CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:28.006 [info] Application mnesia2 exited with reason: killed
16:45:28.074 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.799.0>
16:45:28.076 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:28.089 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.216.0>
16:45:28.102 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:28.346 [error] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): ** ERROR ** (ignoring core) ** FATAL ** A fallback is installed and Mnesia2 must be restarted. Forcing shutdown after mnesia2_down from 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'...

16:45:28.347 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.797.0> exit with reason killed in context child_terminated
16:45:28.350 [info] Application mnesia2 exited with reason: stopped
16:45:28.347 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_locker:start() at <0.797.0> exit with reason reached_max_restart_intensity in context shutdown
16:45:28.349 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason shutdown in context child_terminated
16:45:28.349 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.794.0> exit with reason reached_max_restart_intensity in context shutdown
16:45:28.351 [info] Application mnesia2 exited with reason: shutdown
16:45:28.399 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.927.0>
16:45:28.401 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.369.0>
16:45:29.229 [info] Application mnesia2 exited with reason: stopped
16:45:29.230 [warning] lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
16:45:29.230 [info] Application mnesia2 exited with reason: stopped
16:45:29.268 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1024.0>
16:45:29.270 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:29.279 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.464.0>
16:45:29.283 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'

----------------------------------------------------
2016-04-10 16:45:29.817
ending test case: silly_upgrade


----------------------------------------------------
2016-04-10 16:45:29.898
ending test group: install


----------------------------------------------------
2016-04-10 16:45:29.924
starting test group: nice


----------------------------------------------------
2016-04-10 16:45:30.004
starting test case: nice

16:45:30.008 [error] gen_server <0.1085.0> terminated with reason: killed
16:45:30.006 [error] gen_server <0.522.0> terminated with reason: killed
16:45:30.006 [error] CRASH REPORT Process <0.522.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:45:30.008 [error] CRASH REPORT Process <0.1085.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:45:30.007 [error] CRASH REPORT Process <0.455.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:30.007 [info] Application mnesia2 exited with reason: killed
16:45:30.008 [error] CRASH REPORT Process <0.1015.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:30.008 [info] Application mnesia2 exited with reason: killed
16:45:30.068 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1147.0>
16:45:30.071 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:30.088 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.553.0>
16:45:30.100 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:30.384 [info] Application mnesia2 exited with reason: stopped
16:45:30.395 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1259.0>

----------------------------------------------------
2016-04-10 16:45:30.629
ending test case: nice


----------------------------------------------------
2016-04-10 16:45:30.718
ending test group: nice


----------------------------------------------------
2016-04-10 16:45:30.744
starting test group: qlc


----------------------------------------------------
2016-04-10 16:45:30.849
starting test case: dirty_nice_ram_copies

16:45:30.852 [error] gen_server <0.666.0> terminated with reason: killed
16:45:31.827 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
16:45:30.852 [error] CRASH REPORT Process <0.666.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:45:31.837 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1491.0>
16:45:31.839 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:30.852 [error] CRASH REPORT Process <0.544.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:30.852 [info] Application mnesia2 exited with reason: killed
16:45:31.857 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.767.0>
16:45:31.860 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'

----------------------------------------------------
2016-04-10 16:45:31.973
ending test case: dirty_nice_ram_copies


----------------------------------------------------
2016-04-10 16:45:32.004
starting test case: dirty_nice_disc_copies

16:45:32.006 [error] gen_server <0.821.0> terminated with reason: killed
16:45:32.008 [error] CRASH REPORT Process <0.1482.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:32.008 [info] Application mnesia2 exited with reason: killed
16:45:32.006 [error] CRASH REPORT Process <0.821.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:45:32.006 [error] CRASH REPORT Process <0.758.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:32.006 [info] Application mnesia2 exited with reason: killed
16:45:32.051 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1605.0>
16:45:32.053 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:32.057 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.866.0>
16:45:32.074 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'

----------------------------------------------------
2016-04-10 16:45:32.164
ending test case: dirty_nice_disc_copies


----------------------------------------------------
2016-04-10 16:45:32.191
starting test case: dirty_nice_disc_only_copies

16:45:32.194 [error] gen_server <0.1661.0> terminated with reason: killed
16:45:32.194 [error] CRASH REPORT Process <0.1661.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:45:32.194 [error] CRASH REPORT Process <0.1596.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:32.194 [info] Application mnesia2 exited with reason: killed
16:45:32.196 [error] gen_server <0.920.0> terminated with reason: killed
16:45:32.196 [error] CRASH REPORT Process <0.920.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:45:32.196 [error] CRASH REPORT Process <0.857.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:32.196 [info] Application mnesia2 exited with reason: killed
16:45:32.291 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1721.0>
16:45:32.311 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.967.0>

----------------------------------------------------
2016-04-10 16:45:32.477
ending test case: dirty_nice_disc_only_copies


----------------------------------------------------
2016-04-10 16:45:32.558
starting test case: trans_nice_ram_copies

16:45:32.625 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1847.0>
16:45:32.630 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1073.0>

----------------------------------------------------
2016-04-10 16:45:32.738
ending test case: trans_nice_ram_copies


----------------------------------------------------
2016-04-10 16:45:32.765
starting test case: trans_nice_disc_copies

16:45:32.814 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1978.0>
16:45:32.824 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1173.0>
16:45:33.126 [warning] lager_error_logger_h dropped 41 messages in the last second that exceeded the limit of 50 messages/sec
16:45:33.127 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'

----------------------------------------------------
2016-04-10 16:45:33.231
ending test case: trans_nice_disc_copies


----------------------------------------------------
2016-04-10 16:45:33.269
starting test case: trans_nice_disc_only_copies

16:45:33.272 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
16:45:33.273 [error] CRASH REPORT Process <0.1969.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:33.273 [info] Application mnesia2 exited with reason: killed
16:45:33.272 [error] gen_server <0.1226.0> terminated with reason: killed
16:45:33.272 [error] CRASH REPORT Process <0.1226.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:45:33.272 [error] CRASH REPORT Process <0.1164.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:33.272 [info] Application mnesia2 exited with reason: killed
16:45:33.345 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2112.0>
16:45:33.350 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1275.0>
16:45:33.361 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'

----------------------------------------------------
2016-04-10 16:45:33.496
ending test case: trans_nice_disc_only_copies


----------------------------------------------------
2016-04-10 16:45:33.549
starting test case: atomic_eval

16:45:33.552 [error] gen_server <0.1321.0> terminated with reason: killed
16:45:33.552 [error] CRASH REPORT Process <0.1321.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:45:33.604 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2252.0>
16:45:33.624 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1381.0>

----------------------------------------------------
2016-04-10 16:45:33.735
ending test case: atomic_eval


----------------------------------------------------
2016-04-10 16:45:33.813
starting test case: frag

16:45:33.872 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2383.0>
16:45:33.894 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1468.0>

----------------------------------------------------
2016-04-10 16:45:34.014
ending test case: frag


----------------------------------------------------
2016-04-10 16:45:34.055
starting test case: info

16:45:34.057 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
16:45:34.064 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
16:45:34.057 [error] gen_server <0.2439.0> terminated with reason: killed
16:45:34.064 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1481.0> exit with reason killed in context child_terminated
16:45:34.057 [error] CRASH REPORT Process <0.2439.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:45:34.059 [error] CRASH REPORT Process <0.2374.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:34.059 [info] Application mnesia2 exited with reason: killed
16:45:34.064 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1481.0> exit with reason reached_max_restart_intensity in context shutdown
16:45:34.064 [error] gen_server <0.1520.0> terminated with reason: killed
16:45:34.064 [error] CRASH REPORT Process <0.1520.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:45:34.065 [error] CRASH REPORT Process <0.1459.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:34.065 [info] Application mnesia2 exited with reason: killed
16:45:34.109 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2515.0>
16:45:34.111 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:34.126 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1580.0>
16:45:34.146 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'

----------------------------------------------------
2016-04-10 16:45:34.237
ending test case: info


----------------------------------------------------
2016-04-10 16:45:34.279
starting test case: mnesia2_down

16:45:34.283 [error] gen_server <0.2571.0> terminated with reason: killed
16:45:34.283 [error] CRASH REPORT Process <0.2571.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:45:34.353 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2638.0>
16:45:34.360 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1667.0>
---> Participant transactions <--- 
---> Coordinator transactions <---
Tid: 10 (owned by <0.2715.0>) 

----------------------------------------------------
2016-04-10 16:45:34.467
ending test case: mnesia2_down


----------------------------------------------------
2016-04-10 16:45:34.550
ending test group: qlc


----------------------------------------------------
2016-04-10 16:45:34.589
starting test group: registry


----------------------------------------------------
2016-04-10 16:45:34.669
starting test case: good_dump

16:45:34.713 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2766.0>

----------------------------------------------------
2016-04-10 16:45:34.727
ending test case: good_dump


----------------------------------------------------
2016-04-10 16:45:34.756
starting test case: bad_dump

16:45:34.796 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2860.0>

----------------------------------------------------
2016-04-10 16:45:34.807
ending test case: bad_dump


----------------------------------------------------
2016-04-10 16:45:34.895
ending test group: registry


----------------------------------------------------
2016-04-10 16:45:34.924
starting test group: config


----------------------------------------------------
2016-04-10 16:45:35.008
starting test case: access_module

16:45:36.043 [warning] lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
16:45:36.049 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2970.0>
16:45:36.051 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:37.259 [error] CRASH REPORT Process <0.2961.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:37.259 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:45:38.282
ending test case: access_module


----------------------------------------------------
2016-04-10 16:45:38.309
starting test case: auto_repair

16:45:39.341 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3076.0>
16:45:39.344 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:39.345 [info] Application mnesia2 exited with reason: stopped
16:45:39.347 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3124.0>
16:45:39.351 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3172.0>

----------------------------------------------------
2016-04-10 16:45:40.380
ending test case: auto_repair


----------------------------------------------------
2016-04-10 16:45:40.406
starting test case: backup_module

16:45:41.448 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3244.0>
16:45:41.450 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:41.464 [error] CRASH REPORT Process <0.3235.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:41.464 [info] Application mnesia2 exited with reason: killed
16:45:43.498 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3327.0>
16:45:43.501 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:43.506 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

16:45:43.506 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test7013@testing-worker-linux-docker-e93d2010-3388-linux-11.2016-04-10_16.45.02/Mnesia2.test7013@testing-worker-linux-docker-e93d2010-3388-linux-11/LATEST.LOG"] -> badarg

16:45:43.508 [error] CRASH REPORT Process <0.3318.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:43.508 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:45:44.544
ending test case: backup_module


----------------------------------------------------
2016-04-10 16:45:44.572
starting test case: debug

16:45:45.603 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_monitor starting: <0.3423.0>

16:45:45.605 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Mnesia2 debug level set to verbose
16:45:45.605 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_subscr starting: <0.3424.0>

16:45:45.606 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_locker starting: <0.3425.0>

16:45:45.606 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_recover starting: <0.3426.0>

16:45:45.606 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_tm starting: <0.3427.0>

16:45:45.607 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3427.0>
16:45:45.607 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Schema initiated from: default

16:45:45.608 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_controller starting: <0.3430.0>

16:45:45.609 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_late_loader starting: <0.3431.0>

16:45:45.610 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Intend to load tables: []

16:45:45.610 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:45.610 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_tm_1 starting: <0.3433.0>

16:45:45.612 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_tm_31 terminated: shutdown

16:45:47.633 [warning] lager_error_logger_h dropped 10 messages in the last second that exceeded the limit of 50 messages/sec
16:45:47.633 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_monitor starting: <0.3474.0>

16:45:47.634 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Version: "1.0.0"

16:45:47.634 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env access_module: mnesia2

16:45:47.635 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env auto_repair: true

16:45:47.635 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env backup_module: mnesia2_backup

16:45:47.635 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env debug: debug

16:45:47.636 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7013@testing-worker-linux-docker-e93d2010-3388-linux-11.2016-04-10_16.45.02/Mnesia2.test7013@testing-worker-linux-docker-e93d2010-3388-linux-11"

16:45:47.636 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env dump_disc_copies_at_startup: true

16:45:47.636 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env dump_log_load_regulation: false

16:45:47.636 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env dump_log_time_threshold: 180000

16:45:47.636 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env dump_log_update_in_place: true

16:45:47.636 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env dump_log_write_threshold: 1000

16:45:47.637 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env event_module: mnesia2_event

16:45:47.637 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env extra_db_nodes: []

16:45:47.637 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env ignore_fallback_at_startup: false

16:45:47.637 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env fallback_error_function: {mnesia2,lkill}

16:45:47.637 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env max_wait_for_decision: infinity

16:45:47.637 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env schema_location: opt_disc

16:45:47.638 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env core_dir: false

16:45:47.638 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env pid_sort_order: false

16:45:47.638 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env no_table_loaders: 2

16:45:47.638 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env dc_dump_limit: 4

16:45:47.638 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env send_compressed: 0

16:45:47.638 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env send_max_packets: 20

16:45:47.638 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Env send_max_transfer_size: 7500

16:45:47.639 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Mnesia2 debug level set to debug
16:45:47.641 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3478.0>
16:45:49.668 [warning] lager_error_logger_h dropped 21 messages in the last second that exceeded the limit of 50 messages/sec
16:45:49.668 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_monitor starting: <0.3523.0>

16:45:49.670 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3527.0>
16:45:49.673 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:49.674 [error] CRASH REPORT Process <0.3518.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:49.675 [info] Application mnesia2 exited with reason: killed
16:45:51.704 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_monitor starting: <0.3572.0>

16:45:51.705 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Version: "1.0.0"

16:45:51.707 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3576.0>
16:45:51.710 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:51.712 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_tm_30 terminated: shutdown

16:45:51.712 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_tm_26 terminated: shutdown

16:45:51.712 [info] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): mnesia2_tm_22 terminated: shutdown

16:45:51.714 [error] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3618.0>}})

16:45:51.714 [error] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_9,shutdown]}}}} ({error,{already_started,<0.3618.0>}})

16:45:51.714 [error] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_8,shutdown]}}}} ({error,{already_started,<0.3618.0>}})

16:45:51.714 [error] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_11,shutdown]}}}} ({error,{already_started,<0.3618.0>}})

16:45:53.733 [warning] lager_error_logger_h dropped 19 messages in the last second that exceeded the limit of 50 messages/sec
16:45:53.735 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3655.0>
16:45:53.739 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:53.740 [error] CRASH REPORT Process <0.3646.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:53.741 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:45:54.763
ending test case: debug


----------------------------------------------------
2016-04-10 16:45:54.802
starting test case: dir

16:45:55.833 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3719.0>
16:45:55.837 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:55.838 [error] CRASH REPORT Process <0.3710.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:45:55.838 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:45:56.873
ending test case: dir


----------------------------------------------------
2016-04-10 16:45:56.900
starting test case: dump_log_load_regulation

16:45:56.927 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3790.0>
16:45:56.929 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:45:56.933 [info] Application mnesia2 exited with reason: stopped
16:45:56.939 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3851.0>
16:45:58.816 [warning] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

16:46:03.109 [warning] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): ** WARNING ** Mnesia2 is overloaded: {dump_log,write_threshold}

16:46:11.989 [error] CRASH REPORT Process <0.3842.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:11.989 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:46:13.011
ending test case: dump_log_load_regulation


----------------------------------------------------
2016-04-10 16:46:13.077
starting test case: dump_log_time_threshold

16:46:14.129 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4433.0>
16:46:14.132 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:20.153 [error] CRASH REPORT Process <0.4424.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:20.153 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:46:21.177
ending test case: dump_log_time_threshold


----------------------------------------------------
2016-04-10 16:46:21.204
starting test case: dump_log_write_threshold

16:46:22.266 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4533.0>
16:46:22.269 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:23.291 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:46:24.305
ending test case: dump_log_write_threshold


----------------------------------------------------
2016-04-10 16:46:24.356
starting test case: dump_log_update_in_place

16:46:25.504 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4649.0>
16:46:25.506 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:25.512 [error] CRASH REPORT Process <0.4640.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:25.512 [info] Application mnesia2 exited with reason: killed
16:46:27.543 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4716.0>
16:46:27.545 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:27.568 [error] CRASH REPORT Process <0.4707.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:27.568 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:46:28.592
ending test case: dump_log_update_in_place


----------------------------------------------------
2016-04-10 16:46:28.618
starting test case: event_module

16:46:29.678 [warning] lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
16:46:29.694 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4808.0>
16:46:29.696 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:29.700 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1794.0>
16:46:29.703 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'}}
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'}}
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'}}
16:46:30.705 [error] gen_server <0.1846.0> terminated with reason: killed
16:46:30.705 [error] CRASH REPORT Process <0.1846.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:46:30.706 [error] CRASH REPORT Process <0.1785.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:30.706 [info] Application mnesia2 exited with reason: killed
16:46:32.760 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1862.0>
16:46:32.764 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'}}
Got event: {mnesia2_system_event,
               {mnesia2_up,
                   'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'}}
Got event: {mnesia2_system_event,
               {mnesia2_down,
                   'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'}}
16:46:33.767 [error] gen_server <0.4871.0> terminated with reason: killed
16:46:33.767 [error] CRASH REPORT Process <0.4871.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:46:33.767 [error] CRASH REPORT Process <0.4799.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:33.767 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:46:34.790
ending test case: event_module


----------------------------------------------------
2016-04-10 16:46:34.817
starting test case: inconsistent_database

16:46:34.820 [error] CRASH REPORT Process <0.1853.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:34.820 [info] Application mnesia2 exited with reason: killed
16:46:35.913 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4914.0>
16:46:35.915 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:35.934 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1944.0>
16:46:35.938 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:35.939 [error] gen_server <0.4968.0> terminated with reason: killed
16:46:35.940 [error] gen_server <0.1995.0> terminated with reason: killed
16:46:35.939 [error] CRASH REPORT Process <0.4968.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:46:35.940 [error] CRASH REPORT Process <0.1995.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:46:35.941 [error] CRASH REPORT Process <0.4905.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:35.941 [info] Application mnesia2 exited with reason: killed
16:46:35.941 [error] CRASH REPORT Process <0.1934.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:35.941 [info] Application mnesia2 exited with reason: killed
16:46:35.985 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4994.0>
16:46:39.856 [info] Application mnesia2 exited with reason: stopped
16:46:39.911 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2018.0>
16:46:39.912 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:39.919 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.5118.0>
16:46:39.924 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:49.038 [info] Application mnesia2 exited with reason: stopped
16:46:49.037 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:46:50.058
ending test case: inconsistent_database


----------------------------------------------------
2016-04-10 16:46:50.085
starting test case: max_wait_for_decision


----------------------------------------------------
2016-04-10 16:46:50.086
ending test case: max_wait_for_decision


----------------------------------------------------
2016-04-10 16:46:50.112
starting test case: send_compressed

16:46:50.176 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.5249.0>
16:46:50.192 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2140.0>
16:46:50.195 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:50.482 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:50.507 [error] gen_server <0.2193.0> terminated with reason: killed
16:46:50.507 [error] CRASH REPORT Process <0.2193.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:46:50.508 [error] CRASH REPORT Process <0.2131.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:50.508 [info] Application mnesia2 exited with reason: killed
16:46:50.529 [error] CRASH REPORT Process <0.5240.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:50.529 [info] Application mnesia2 exited with reason: killed
16:46:50.565 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.5338.0>
16:46:50.743 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2229.0>
16:46:51.149 [error] gen_server <0.5409.0> terminated with reason: killed
16:46:51.149 [error] CRASH REPORT Process <0.5409.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:46:51.150 [error] CRASH REPORT Process <0.5329.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:51.150 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:46:52.181
ending test case: send_compressed


----------------------------------------------------
2016-04-10 16:46:52.207
starting test case: app_test


----------------------------------------------------
2016-04-10 16:46:52.213
ending test case: app_test


----------------------------------------------------
2016-04-10 16:46:52.266
starting test case: start_one_disc_full_then_one_disc_less

16:46:52.267 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2248.0> exit with reason killed in context child_terminated
16:46:52.267 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2248.0> exit with reason reached_max_restart_intensity in context shutdown
16:46:52.269 [error] CRASH REPORT Process <0.2220.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:52.269 [info] Application mnesia2 exited with reason: killed
16:46:53.336 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.5461.0>
16:46:53.338 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:53.342 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2332.0>
16:46:53.372 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:53.383 [error] CRASH REPORT Process <0.5452.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:53.383 [info] Application mnesia2 exited with reason: killed
16:46:53.383 [error] gen_server <0.2343.0> terminated with reason: killed
16:46:53.383 [error] CRASH REPORT Process <0.2343.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:46:53.383 [error] CRASH REPORT Process <0.2323.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:53.384 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:46:54.408
ending test case: start_one_disc_full_then_one_disc_less


----------------------------------------------------
2016-04-10 16:46:54.449
starting test case: start_first_one_disc_less_then_one_disc_full

16:46:55.505 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.5572.0>
16:46:55.507 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:55.511 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2407.0>
16:46:55.528 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:55.530 [error] gen_server mnesia2_monitor terminated with reason: killed
16:46:55.531 [error] gen_server <0.5636.0> terminated with reason: killed
16:46:55.531 [error] CRASH REPORT Process <0.5636.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:46:55.532 [error] CRASH REPORT Process <0.5563.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:55.532 [info] Application mnesia2 exited with reason: killed
16:46:55.530 [error] gen_server mnesia2_recover terminated with reason: killed
16:46:55.531 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:46:55.531 [error] Mnesia2('d1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'): ** ERROR ** mnesia2_event got unexpected event: {'EXIT',<0.2404.0>,killed}

16:46:55.531 [error] gen_server <0.2418.0> terminated with reason: killed
16:46:55.531 [error] CRASH REPORT Process <0.2418.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:46:55.532 [error] CRASH REPORT Process <0.2398.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:55.532 [info] Application mnesia2 exited with reason: killed
16:46:57.564 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2466.0>
16:46:57.566 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:57.573 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.5653.0>
16:46:57.579 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:46:57.590 [error] gen_server <0.5694.0> terminated with reason: killed
16:46:57.590 [error] CRASH REPORT Process <0.5694.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:46:57.590 [error] CRASH REPORT Process <0.5644.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:57.591 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:46:58.613
ending test case: start_first_one_disc_less_then_one_disc_full


----------------------------------------------------
2016-04-10 16:46:58.641
starting test case: start_first_one_disc_less_then_two_more_disc_less

16:46:59.016 [error] CRASH REPORT Process <0.2457.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:46:59.016 [info] Application mnesia2 exited with reason: killed
16:47:00.102 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.5778.0>
16:47:00.104 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:00.107 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2554.0>
16:47:00.126 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:00.343 [info] Application lager started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:00.343 [info] Application poolgirl started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:00.381 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.100.0>
16:47:00.398 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:00.447 [error] CRASH REPORT Process <0.5769.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:00.447 [info] Application mnesia2 exited with reason: killed
16:47:00.447 [error] gen_server <0.2605.0> terminated with reason: killed
16:47:00.447 [error] CRASH REPORT Process <0.2605.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:00.447 [error] gen_server <0.2566.0> terminated with reason: killed
16:47:00.447 [error] CRASH REPORT Process <0.2566.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:00.447 [error] CRASH REPORT Process <0.2545.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:00.447 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:47:01.482
ending test case: start_first_one_disc_less_then_two_more_disc_less


----------------------------------------------------
2016-04-10 16:47:01.510
starting test case: schema_location_and_extra_db_nodes_combinations

16:47:02.560 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.5873.0>
16:47:02.562 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:02.567 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2635.0>
16:47:02.573 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:02.576 [error] gen_server <0.5935.0> terminated with reason: killed
16:47:02.574 [error] gen_server <0.2646.0> terminated with reason: killed
16:47:02.576 [error] CRASH REPORT Process <0.5935.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:02.574 [error] CRASH REPORT Process <0.2646.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:02.576 [error] CRASH REPORT Process <0.5864.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:02.576 [info] Application mnesia2 exited with reason: killed
16:47:02.575 [error] CRASH REPORT Process <0.2626.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:02.575 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:47:03.601
ending test case: schema_location_and_extra_db_nodes_combinations


----------------------------------------------------
2016-04-10 16:47:03.628
starting test case: table_load_to_disc_less_nodes

16:47:04.672 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.5967.0>
16:47:04.674 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:04.677 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2705.0>
16:47:04.681 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:04.701 [error] gen_server <0.6011.0> terminated with reason: killed
16:47:04.702 [error] CRASH REPORT Process <0.2696.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:04.702 [info] Application mnesia2 exited with reason: killed
16:47:04.701 [error] CRASH REPORT Process <0.6011.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:04.703 [error] CRASH REPORT Process <0.5958.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:04.703 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:47:05.726
ending test case: table_load_to_disc_less_nodes


----------------------------------------------------
2016-04-10 16:47:05.752
starting test case: schema_merge

16:47:06.814 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.6053.0>
16:47:06.816 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:06.824 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2780.0>
16:47:06.828 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:06.829 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2793.0> exit with reason killed in context child_terminated
16:47:06.829 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2793.0> exit with reason reached_max_restart_intensity in context shutdown
16:47:06.830 [error] gen_server <0.2828.0> terminated with reason: killed
16:47:06.830 [error] CRASH REPORT Process <0.2828.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:06.830 [error] CRASH REPORT Process <0.2771.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:06.830 [info] Application mnesia2 exited with reason: killed
16:47:07.858 [error] CRASH REPORT Process <0.6044.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:07.858 [info] Application mnesia2 exited with reason: killed
16:47:09.890 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2850.0>
16:47:09.891 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:14.910 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.6131.0>
16:47:14.944 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:14.948 [error] gen_server <0.6186.0> terminated with reason: killed
16:47:14.949 [error] gen_server <0.2917.0> terminated with reason: killed
16:47:14.948 [error] CRASH REPORT Process <0.6186.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:14.949 [error] CRASH REPORT Process <0.2917.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:14.949 [error] CRASH REPORT Process <0.6122.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:14.949 [info] Application mnesia2 exited with reason: killed
16:47:14.949 [error] CRASH REPORT Process <0.2841.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:14.949 [info] Application mnesia2 exited with reason: killed

----------------------------------------------------
2016-04-10 16:47:15.973
ending test case: schema_merge


----------------------------------------------------
2016-04-10 16:47:16.027
starting test case: dynamic_basic

16:47:16.085 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
16:47:16.123 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.6241.0>
16:47:16.126 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:16.143 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2949.0>
16:47:16.158 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.190.0>
16:47:16.163 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:16.462 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:16.532 [error] gen_server <0.3013.0> terminated with reason: killed
16:47:16.532 [error] CRASH REPORT Process <0.3013.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:16.532 [error] gen_server <0.3008.0> terminated with reason: killed
16:47:16.532 [error] CRASH REPORT Process <0.3008.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:16.532 [error] CRASH REPORT Process <0.2940.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:16.532 [info] Application mnesia2 exited with reason: killed
16:47:16.565 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3041.0>
16:47:16.644 [error] gen_server <0.6340.0> terminated with reason: killed
16:47:16.645 [error] CRASH REPORT Process <0.6340.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:16.645 [error] gen_server <0.6298.0> terminated with reason: killed
16:47:16.645 [error] CRASH REPORT Process <0.6298.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:16.645 [error] gen_server <0.6327.0> terminated with reason: killed
16:47:16.666 [error] gen_server <0.276.0> terminated with reason: killed
16:47:16.645 [error] CRASH REPORT Process <0.6327.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:16.666 [error] CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:16.646 [error] CRASH REPORT Process <0.6232.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:16.646 [info] Application mnesia2 exited with reason: killed
16:47:16.746 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3136.0>
16:47:16.777 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.6359.0>
16:47:16.780 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.295.0>
16:47:17.083 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:17.612 [warning] lager_error_logger_h dropped 28 messages in the last second that exceeded the limit of 50 messages/sec
16:47:17.612 [error] gen_server <0.357.0> terminated with reason: killed
16:47:17.613 [error] CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:17.613 [error] gen_server <0.368.0> terminated with reason: killed
16:47:17.613 [error] CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:17.614 [error] CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:17.614 [info] Application mnesia2 exited with reason: killed
16:47:17.641 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.391.0>
16:47:17.643 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:19.713 [error] gen_server <0.6457.0> terminated with reason: killed
16:47:19.713 [error] CRASH REPORT Process <0.6457.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:19.713 [error] gen_server <0.6429.0> terminated with reason: killed
16:47:19.713 [error] CRASH REPORT Process <0.6429.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:19.734 [warning] lager_error_logger_h dropped 16 messages in the last second that exceeded the limit of 50 messages/sec
16:47:19.714 [error] CRASH REPORT Process <0.6350.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:19.714 [info] Application mnesia2 exited with reason: killed
16:47:19.734 [error] gen_server <0.3229.0> terminated with reason: killed
16:47:19.734 [error] CRASH REPORT Process <0.3229.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:19.735 [error] CRASH REPORT Process <0.3127.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:19.735 [info] Application mnesia2 exited with reason: killed
16:47:19.762 [info] Application mnesia2 exited with reason: stopped
16:47:19.784 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.497.0>
16:47:19.787 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:19.806 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.6476.0>
16:47:19.810 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3250.0>
16:47:19.837 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:20.112 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:20.642 [error] gen_server <0.570.0> terminated with reason: killed
16:47:20.642 [error] CRASH REPORT Process <0.570.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:20.642 [error] gen_server <0.565.0> terminated with reason: killed
16:47:20.642 [error] CRASH REPORT Process <0.565.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:20.643 [error] CRASH REPORT Process <0.488.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:20.643 [info] Application mnesia2 exited with reason: killed
16:47:20.676 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.596.0>
16:47:20.678 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:20.862 [error] gen_server <0.6545.0> terminated with reason: killed
16:47:20.863 [error] CRASH REPORT Process <0.6545.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:20.864 [error] CRASH REPORT Process <0.6467.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:20.864 [info] Application mnesia2 exited with reason: killed
16:47:20.884 [error] gen_server <0.3337.0> terminated with reason: killed
16:47:20.884 [error] CRASH REPORT Process <0.3337.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:20.885 [error] CRASH REPORT Process <0.3241.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:20.885 [info] Application mnesia2 exited with reason: killed
16:47:20.924 [info] Application mnesia2 exited with reason: stopped
16:47:20.937 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.697.0>
16:47:20.997 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.6589.0>
16:47:21.170 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3358.0>
16:47:21.184 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:21.320 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:21.841 [error] CRASH REPORT Process <0.3349.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:21.841 [info] Application mnesia2 exited with reason: killed
16:47:21.877 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3454.0>
16:47:21.896 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:21.943 [error] gen_server <0.3512.0> terminated with reason: killed
16:47:21.943 [error] CRASH REPORT Process <0.3512.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:21.943 [error] gen_server <0.3480.0> terminated with reason: killed
16:47:21.943 [error] CRASH REPORT Process <0.3480.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:21.943 [error] gen_server <0.3467.0> terminated with reason: killed
16:47:21.944 [error] CRASH REPORT Process <0.3467.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:21.944 [error] CRASH REPORT Process <0.3445.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:21.944 [info] Application mnesia2 exited with reason: killed
16:47:22.981 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3532.0>
16:47:22.994 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'

----------------------------------------------------
2016-04-10 16:47:23.020
ending test case: dynamic_basic


----------------------------------------------------
2016-04-10 16:47:23.048
starting test case: dynamic_ext

16:47:23.052 [error] CRASH REPORT Process <0.3523.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:23.055 [error] gen_server <0.822.0> terminated with reason: killed
16:47:23.052 [info] Application mnesia2 exited with reason: killed
16:47:23.056 [error] CRASH REPORT Process <0.6580.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:23.056 [info] Application mnesia2 exited with reason: killed
16:47:23.055 [error] CRASH REPORT Process <0.822.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:23.055 [error] gen_server <0.771.0> terminated with reason: killed
16:47:23.055 [error] CRASH REPORT Process <0.771.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:23.056 [error] CRASH REPORT Process <0.688.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:23.056 [info] Application mnesia2 exited with reason: killed
16:47:23.119 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.6735.0>
16:47:23.122 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:23.123 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3610.0>
16:47:23.146 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:23.231 [error] gen_server <0.3664.0> terminated with reason: killed
16:47:23.231 [error] CRASH REPORT Process <0.3664.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:23.232 [error] CRASH REPORT Process <0.3601.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:23.232 [info] Application mnesia2 exited with reason: killed
16:47:23.257 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3705.0>
16:47:23.346 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3795.0>
16:47:23.387 [info] Application mnesia2 exited with reason: stopped
16:47:23.400 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3895.0>
16:47:23.918 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.6848.0>
16:47:24.014 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.6931.0>
16:47:24.017 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:24.518 [warning] lager_error_logger_h dropped 36 messages in the last second that exceeded the limit of 50 messages/sec
16:47:24.521 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.3977.0>
16:47:24.551 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'

----------------------------------------------------
2016-04-10 16:47:24.570
ending test case: dynamic_ext


----------------------------------------------------
2016-04-10 16:47:24.600
starting test case: dynamic_bad

16:47:24.604 [error] CRASH REPORT Process <0.6922.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:24.604 [info] Application mnesia2 exited with reason: killed
16:47:24.606 [error] gen_server <0.4020.0> terminated with reason: killed
16:47:24.606 [error] CRASH REPORT Process <0.4020.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:24.607 [error] CRASH REPORT Process <0.3968.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:24.607 [info] Application mnesia2 exited with reason: killed
16:47:24.681 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.7032.0>
16:47:24.698 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.848.0>
16:47:24.706 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:24.708 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4070.0>
16:47:24.816 [error] CRASH REPORT Process <0.839.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:24.816 [info] Application mnesia2 exited with reason: killed
16:47:24.839 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.952.0>
16:47:24.840 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:24.849 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4159.0>
16:47:24.876 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.7144.0>
16:47:24.929 [error] gen_server <0.1001.0> terminated with reason: killed
16:47:24.929 [error] CRASH REPORT Process <0.1001.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:24.929 [error] gen_server <0.1010.0> terminated with reason: killed
16:47:24.929 [error] CRASH REPORT Process <0.1010.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:24.962 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1030.0>
16:47:24.966 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4238.0>
16:47:25.002 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.7236.0>
16:47:25.002 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
16:47:25.028 [error] Mnesia2('test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'): ** ERROR ** (core dumped to file: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test7013@testing-worker-linux-docker-e93d2010-3388-linux-11.2016-04-10_16.45.02/Mnesia2Core.test7013@testing-worker-linux-docker-e93d2010-3388-linux-11_1460_306845_11932")
 ** FATAL ** Failed to merge schema: Bad cookie in table definition tab1: 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11' = {cstruct,tab1,set,['d1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11','d1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'],['test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'],[],0,read_write,false,[],[],false,tab1,[key,val],[],[],[],{{1460306844807077513,-576460752303399806,1},'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'},{{2,0},[]}}, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11' = {cstruct,tab1,set,['d1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'],[],[],0,read_write,false,[],[],false,tab1,[key,val],[],[],[],{{1460306844972268416,-576460752303420223,1},'d1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'},{{2,0},[]}}



----------------------------------------------------
2016-04-10 16:47:35.015
ending test case: dynamic_bad

16:47:35.013 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
16:47:35.013 [error] gen_server mnesia2_monitor terminated with reason: killed
16:47:35.013 [error] gen_server mnesia2_recover terminated with reason: killed
16:47:35.013 [error] CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:35.013 [error] gen_server mnesia2_snmp_sup terminated with reason: killed
16:47:35.013 [error] CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:35.013 [error] gen_server mnesia2_subscr terminated with reason: killed
16:47:35.013 [error] CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:35.014 [error] CRASH REPORT Process <0.7227.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
16:47:35.014 [info] Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}

----------------------------------------------------
2016-04-10 16:47:35.098
starting test case: unknown_config

16:47:35.014 [error] CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:35.101 [warning] lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
16:47:35.100 [warning] lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
16:47:35.100 [error] gen_server <0.4282.0> terminated with reason: killed
16:47:35.101 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1031.0> exit with reason killed in context child_terminated
16:47:35.100 [error] CRASH REPORT Process <0.4282.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
16:47:35.101 [error] Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.1031.0> exit with reason reached_max_restart_intensity in context shutdown
16:47:35.101 [error] CRASH REPORT Process <0.4229.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
16:47:35.102 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1025.0> exit with reason shutdown in context child_terminated
16:47:35.101 [info] Application mnesia2 exited with reason: killed
16:47:35.102 [error] Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at <0.1025.0> exit with reason reached_max_restart_intensity in context shutdown
16:47:35.103 [info] Application mnesia2 exited with reason: shutdown

----------------------------------------------------
2016-04-10 16:47:37.155
ending test case: unknown_config


----------------------------------------------------
2016-04-10 16:47:37.241
ending test group: config


----------------------------------------------------
2016-04-10 16:47:37.269
starting test group: examples


----------------------------------------------------
2016-04-10 16:47:37.370
starting test case: bup


----------------------------------------------------
2016-04-10 16:47:37.400
ending test case: bup


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error detected: error
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: *** FAILED test case 41 of 52 ***

----------------------------------------------------
2016-04-10 16:47:37.431
starting test case: company


----------------------------------------------------
2016-04-10 16:47:37.432
ending test case: company


----------------------------------------------------
2016-04-10 16:47:37.461
starting test case: meter

16:47:37.506 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.7345.0>
16:47:37.508 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:41.616 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:47:41.622
ending test case: meter


----------------------------------------------------
2016-04-10 16:47:41.677
starting test case: replica_test

16:47:41.780 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.7481.0>
16:47:41.780 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1126.0>
16:47:41.780 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4329.0>
16:47:41.793 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:41.798 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:41.799 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:47.920 [info] Application mnesia2 exited with reason: stopped
16:47:47.924 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:47:47.968
ending test case: replica_test

16:47:47.968 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:47:47.999
starting test case: sticky_replica_test

16:47:48.101 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1240.0>
16:47:48.102 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.7610.0>
16:47:48.128 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4445.0>
16:47:48.144 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:48.405 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:48.445 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:54.523 [info] Application mnesia2 exited with reason: stopped
16:47:54.529 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:47:54.531
ending test case: sticky_replica_test

16:47:54.531 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:47:54.572
starting test case: dist_test

16:47:54.632 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.7740.0>
16:47:54.634 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:54.637 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.1358.0>
16:47:54.638 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4559.0>
16:47:54.643 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:47:54.941 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:12.241 [info] Application mnesia2 exited with reason: stopped
16:48:12.243 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:48:12.282
ending test case: dist_test

16:48:12.281 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:48:12.310
starting test case: conflict_test

16:48:12.397 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.8878.0>
16:48:12.424 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2484.0>
16:48:12.425 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.5683.0>
16:48:12.445 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:12.703 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:12.729 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:19.541 [info] Application mnesia2 exited with reason: stopped
16:48:19.545 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:48:19.560
ending test case: conflict_test

16:48:19.560 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:48:19.587
starting test case: frag_test

16:48:19.692 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.9017.0>
16:48:19.696 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.2611.0>
16:48:19.700 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.5809.0>
16:48:19.710 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:19.999 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:20.004 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:26.352 [info] Application mnesia2 exited with reason: stopped
16:48:26.355 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:48:26.362
ending test case: frag_test

16:48:26.361 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:48:26.389
starting test case: frag2_test

16:48:26.466 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.10499.0>
16:48:26.468 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:26.496 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.7278.0>
16:48:26.496 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.4084.0>
16:48:26.503 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:26.522 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:32.756 [info] Application mnesia2 exited with reason: stopped
16:48:32.779 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:48:32.783
ending test case: frag2_test

16:48:32.783 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:48:32.822
starting test case: remote_test

16:48:32.923 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.10949.0>
16:48:32.925 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:32.952 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.8358.0>
16:48:32.953 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.6144.0>
16:48:32.959 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:33.257 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:39.416 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:48:39.421
ending test case: remote_test

16:48:39.421 [info] Application mnesia2 exited with reason: stopped
16:48:39.421 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:48:39.449
starting test case: remote_frag2_test

16:48:39.523 [info] starting mnesia2_tm, 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.11078.0>
16:48:39.525 [info] Application mnesia2 started on node 'test7013@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:39.540 [info] starting mnesia2_tm, 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.8475.0>
16:48:39.541 [info] starting mnesia2_tm, 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11', <0.6936.0>
16:48:39.556 [info] Application mnesia2 started on node 'd1285075o1285085n1285083@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:39.844 [info] Application mnesia2 started on node 'd1285069o1285091n1285089@testing-worker-linux-docker-e93d2010-3388-linux-11'
16:48:46.021 [info] Application mnesia2 exited with reason: stopped
16:48:46.028 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:48:46.029
ending test case: remote_frag2_test

16:48:46.028 [info] Application mnesia2 exited with reason: stopped

----------------------------------------------------
2016-04-10 16:48:46.139
ending test group: examples


----------------------------------------------------
2016-04-10 16:48:46.165
ending test group: extra_light


----------------------------------------------------
2016-04-10 16:48:46.190
starting test case: clean_up_suite


----------------------------------------------------
2016-04-10 16:48:46.213
ending test case: clean_up_suite

Testing lrascao.mnesia2.mnesia2_extra_light_SUITE: TEST COMPLETE, 51 ok, 1 failed of 52 test cases

Cover analysing... done

Updating /home/travis/build/lrascao/mnesia2/logs/index.html... done
Updating /home/travis/build/lrascao/mnesia2/logs/all_runs.html... done

