2016-04-12 08:45:33.455 [info] <0.7.0> Application lager started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:33.455 [info] <0.7.0> Application poolgirl started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:33.477 [info] <0.495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.495.0>
2016-04-12 08:45:33.497 [info] <0.563.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.563.0>
2016-04-12 08:45:34.000 [info] <0.673.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.673.0>
2016-04-12 08:45:34.000 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:34.002 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:34.430 [error] <0.664.0> CRASH REPORT Process <0.664.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:34.431 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:34.203 [info] <0.7.0> Application lager started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:34.203 [info] <0.7.0> Application poolgirl started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:34.256 [info] <0.100.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.100.0>
2016-04-12 08:45:34.507 [info] <0.216.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.216.0>
2016-04-12 08:45:34.814 [info] <0.369.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.369.0>
2016-04-12 08:45:34.873 [info] <0.460.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.460.0>
2016-04-12 08:45:34.490 [info] <0.800.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.800.0>
2016-04-12 08:45:34.782 [info] <0.928.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.928.0>
2016-04-12 08:45:34.867 [info] <0.1028.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1028.0>
2016-04-12 08:45:35.578 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:35.578 [error] <0.1089.0> gen_server <0.1089.0> terminated with reason: killed
2016-04-12 08:45:35.578 [warning] <0.6.0> lager_error_logger_h dropped 11 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:35.578 [error] <0.451.0> CRASH REPORT Process <0.451.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:35.578 [error] <0.1089.0> CRASH REPORT Process <0.1089.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:35.578 [error] <0.1019.0> CRASH REPORT Process <0.1019.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:35.578 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:35.666 [info] <0.549.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.549.0>
2016-04-12 08:45:35.670 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:36.319 [error] <0.662.0> gen_server <0.662.0> terminated with reason: killed
2016-04-12 08:45:35.578 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:35.648 [info] <0.1151.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1151.0>
2016-04-12 08:45:35.650 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:35.947 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:45:35.959 [info] <0.1263.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1263.0>
2016-04-12 08:45:36.321 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:36.321 [error] <0.1321.0> gen_server <0.1321.0> terminated with reason: killed
2016-04-12 08:45:36.319 [error] <0.662.0> CRASH REPORT Process <0.662.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:36.322 [error] <0.1321.0> CRASH REPORT Process <0.1321.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:36.320 [error] <0.540.0> CRASH REPORT Process <0.540.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:36.322 [error] <0.1254.0> CRASH REPORT Process <0.1254.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:36.320 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:36.395 [info] <0.763.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.763.0>
2016-04-12 08:45:36.398 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:36.510 [error] <0.758.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.776.0> exit with reason killed in context child_terminated
2016-04-12 08:45:36.322 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:36.390 [info] <0.1495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1495.0>
2016-04-12 08:45:36.393 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:36.513 [error] <0.1551.0> gen_server <0.1551.0> terminated with reason: killed
2016-04-12 08:45:36.511 [error] <0.758.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.776.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:45:36.511 [error] <0.817.0> gen_server <0.817.0> terminated with reason: killed
2016-04-12 08:45:36.513 [error] <0.1551.0> CRASH REPORT Process <0.1551.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:36.511 [error] <0.817.0> CRASH REPORT Process <0.817.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:36.511 [error] <0.754.0> CRASH REPORT Process <0.754.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:36.569 [info] <0.1609.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1609.0>
2016-04-12 08:45:36.511 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:36.817 [info] <0.1725.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1725.0>
2016-04-12 08:45:37.015 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:37.015 [error] <0.1781.0> gen_server <0.1781.0> terminated with reason: killed
2016-04-12 08:45:36.586 [info] <0.862.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.862.0>
2016-04-12 08:45:36.821 [info] <0.963.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.963.0>
2016-04-12 08:45:37.014 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:37.014 [error] <0.1017.0> gen_server <0.1017.0> terminated with reason: killed
2016-04-12 08:45:37.015 [error] <0.1781.0> CRASH REPORT Process <0.1781.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:37.014 [error] <0.1017.0> CRASH REPORT Process <0.1017.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:37.015 [error] <0.1716.0> CRASH REPORT Process <0.1716.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:37.014 [error] <0.954.0> CRASH REPORT Process <0.954.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:37.014 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:37.072 [info] <0.1069.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1069.0>
2016-04-12 08:45:37.085 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:37.585 [error] <0.1124.0> gen_server <0.1124.0> terminated with reason: killed
2016-04-12 08:45:37.015 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:37.069 [info] <0.1851.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1851.0>
2016-04-12 08:45:37.374 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:37.586 [error] <0.1842.0> CRASH REPORT Process <0.1842.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:37.585 [error] <0.1124.0> CRASH REPORT Process <0.1124.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:37.586 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:37.645 [info] <0.1983.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1983.0>
2016-04-12 08:45:38.099 [error] <0.2038.0> gen_server <0.2038.0> terminated with reason: killed
2016-04-12 08:45:37.646 [info] <0.1169.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1169.0>
2016-04-12 08:45:38.099 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:38.099 [error] <0.1160.0> CRASH REPORT Process <0.1160.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:38.099 [error] <0.2038.0> CRASH REPORT Process <0.2038.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:38.099 [error] <0.1974.0> CRASH REPORT Process <0.1974.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:38.099 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:38.142 [info] <0.2117.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2117.0>
2016-04-12 08:45:38.144 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:38.340 [error] <0.2108.0> CRASH REPORT Process <0.2108.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:38.099 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:38.147 [info] <0.1272.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1272.0>
2016-04-12 08:45:38.162 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:38.340 [error] <0.1324.0> gen_server <0.1324.0> terminated with reason: killed
2016-04-12 08:45:38.340 [error] <0.1324.0> CRASH REPORT Process <0.1324.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:38.340 [error] <0.1263.0> CRASH REPORT Process <0.1263.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:38.341 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:38.411 [info] <0.1378.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1378.0>
2016-04-12 08:45:38.341 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:38.406 [info] <0.2257.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2257.0>
2016-04-12 08:45:38.642 [info] <0.2388.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2388.0>
2016-04-12 08:45:39.069 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:39.069 [error] <0.2444.0> gen_server <0.2444.0> terminated with reason: killed
2016-04-12 08:45:38.646 [info] <0.1465.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1465.0>
2016-04-12 08:45:39.070 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:39.070 [error] <0.1456.0> CRASH REPORT Process <0.1456.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:39.069 [error] <0.2444.0> CRASH REPORT Process <0.2444.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:39.069 [error] <0.2379.0> CRASH REPORT Process <0.2379.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:39.070 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:39.070 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:39.161 [info] <0.1577.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1577.0>
2016-04-12 08:45:39.180 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:39.317 [error] <0.1631.0> gen_server <0.1631.0> terminated with reason: killed
2016-04-12 08:45:39.125 [info] <0.2520.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2520.0>
2016-04-12 08:45:39.127 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:39.318 [error] <0.2574.0> gen_server <0.2574.0> terminated with reason: killed
2016-04-12 08:45:39.317 [error] <0.1631.0> CRASH REPORT Process <0.1631.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:39.318 [error] <0.2574.0> CRASH REPORT Process <0.2574.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:45:39.318 [error] <0.1568.0> CRASH REPORT Process <0.1568.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:39.318 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:39.373 [info] <0.1664.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1664.0>
2016-04-12 08:45:39.369 [info] <0.2643.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2643.0>
2016-04-12 08:45:39.685 [info] <0.2771.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2771.0>
2016-04-12 08:45:39.759 [info] <0.2865.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2865.0>
2016-04-12 08:45:41.234 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:41.240 [info] <0.2975.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2975.0>
2016-04-12 08:45:41.242 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:42.442 [error] <0.2966.0> CRASH REPORT Process <0.2966.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:42.442 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:44.522 [info] <0.3081.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3081.0>
2016-04-12 08:45:44.524 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:44.525 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:45:44.527 [info] <0.3129.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3129.0>
2016-04-12 08:45:44.531 [info] <0.3177.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3177.0>
2016-04-12 08:45:46.623 [info] <0.3249.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3249.0>
2016-04-12 08:45:46.625 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:46.637 [error] <0.3240.0> CRASH REPORT Process <0.3240.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:46.637 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:45:48.724 [info] <0.3332.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3332.0>
2016-04-12 08:45:48.727 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:48.733 [info] <0.3326.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Restore aborted. mnesia2_config_backup:open_read["NonExisting.FILE"] -> {enoent,error}

2016-04-12 08:45:48.734 [info] <0.3326.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Restore aborted. mnesia2_config_backup:open_read["/home/travis/build/lrascao/mnesia2/logs/ct_run.test8024@testing-worker-linux-docker-f366a174-3354-linux-14.2016-04-12_08.45.13/Mnesia2.test8024@testing-worker-linux-docker-f366a174-3354-linux-14/LATEST.LOG"] -> badarg

2016-04-12 08:45:48.735 [error] <0.3359.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_2,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-12 08:45:48.736 [error] <0.3366.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_7,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-12 08:45:48.736 [error] <0.3372.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_13,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-12 08:45:48.736 [error] <0.3373.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Cannot report event {mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_14,shutdown]}}: {badarg,{mnesia2_event,{mnesia2_system_event,{mnesia2_info,"~p terminated: ~p~n",[mnesia2_tm_14,shutdown]}}}} ({error,{already_started,<0.3408.0>}})

2016-04-12 08:45:48.736 [info] <0.3408.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_tm_4 terminated: shutdown

2016-04-12 08:45:48.736 [info] <0.3408.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_tm_9 terminated: shutdown

2016-04-12 08:45:48.736 [info] <0.3408.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_tm_8 terminated: shutdown

2016-04-12 08:45:48.736 [info] <0.3408.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_tm_3 terminated: shutdown

2016-04-12 08:45:50.815 [warning] <0.6.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:50.815 [info] <0.3434.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_monitor starting: <0.3436.0>

2016-04-12 08:45:50.816 [info] <0.3434.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Mnesia2 debug level set to verbose
2016-04-12 08:45:50.816 [info] <0.3434.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_subscr starting: <0.3437.0>

2016-04-12 08:45:50.816 [info] <0.3434.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_locker starting: <0.3438.0>

2016-04-12 08:45:50.817 [info] <0.3434.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_recover starting: <0.3439.0>

2016-04-12 08:45:50.817 [info] <0.3434.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_tm starting: <0.3440.0>

2016-04-12 08:45:50.818 [info] <0.3434.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Schema initiated from: default

2016-04-12 08:45:50.818 [info] <0.3440.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3440.0>
2016-04-12 08:45:50.819 [info] <0.3434.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_controller starting: <0.3443.0>

2016-04-12 08:45:50.819 [info] <0.3434.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_late_loader starting: <0.3444.0>

2016-04-12 08:45:50.819 [info] <0.3434.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Intend to load tables: []

2016-04-12 08:45:50.820 [info] <0.3434.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_tm_1 starting: <0.3446.0>

2016-04-12 08:45:50.820 [info] <0.3434.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_tm_2 starting: <0.3447.0>

2016-04-12 08:45:52.844 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:52.845 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_monitor starting: <0.3491.0>

2016-04-12 08:45:52.845 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Version: "1.0.0"

2016-04-12 08:45:52.846 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env access_module: mnesia2

2016-04-12 08:45:52.846 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env auto_repair: true

2016-04-12 08:45:52.846 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env backup_module: mnesia2_backup

2016-04-12 08:45:52.847 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env debug: debug

2016-04-12 08:45:52.847 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test8024@testing-worker-linux-docker-f366a174-3354-linux-14.2016-04-12_08.45.13/Mnesia2.test8024@testing-worker-linux-docker-f366a174-3354-linux-14"

2016-04-12 08:45:52.847 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_disc_copies_at_startup: true

2016-04-12 08:45:52.847 [info] <0.3495.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3495.0>
2016-04-12 08:45:52.847 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_log_load_regulation: false

2016-04-12 08:45:52.848 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_log_time_threshold: 180000

2016-04-12 08:45:52.848 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_log_update_in_place: true

2016-04-12 08:45:52.848 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_log_write_threshold: 1000

2016-04-12 08:45:52.849 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env event_module: mnesia2_event

2016-04-12 08:45:52.849 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env extra_db_nodes: []

2016-04-12 08:45:52.850 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env ignore_fallback_at_startup: false

2016-04-12 08:45:52.850 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env fallback_error_function: {mnesia2,lkill}

2016-04-12 08:45:52.850 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env max_wait_for_decision: infinity

2016-04-12 08:45:52.850 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env schema_location: opt_disc

2016-04-12 08:45:52.850 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env core_dir: false

2016-04-12 08:45:52.850 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env pid_sort_order: false

2016-04-12 08:45:52.850 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env no_table_loaders: 2

2016-04-12 08:45:52.851 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dc_dump_limit: 4

2016-04-12 08:45:52.851 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env send_compressed: 0

2016-04-12 08:45:52.851 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env send_max_packets: 20

2016-04-12 08:45:52.851 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env send_max_transfer_size: 7500

2016-04-12 08:45:52.852 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env async_dirty_buffer_size: 524288

2016-04-12 08:45:52.852 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env async_dirty_max_buffer_file_size: 100000000

2016-04-12 08:45:52.852 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env async_dirty_tx_backlog_threshold: 200000

2016-04-12 08:45:52.852 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env async_dirty_buffer_min_runtime: 10000

2016-04-12 08:45:52.852 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env async_dirty_buffer_drained_cutoff: 5

2016-04-12 08:45:52.852 [info] <0.3489.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Mnesia2 debug level set to debug
2016-04-12 08:45:54.878 [warning] <0.6.0> lager_error_logger_h dropped 63 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:54.878 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_monitor starting: <0.3565.0>

2016-04-12 08:45:54.878 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Version: "1.0.0"

2016-04-12 08:45:54.878 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env access_module: mnesia2

2016-04-12 08:45:54.879 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env auto_repair: true

2016-04-12 08:45:54.879 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env backup_module: mnesia2_backup

2016-04-12 08:45:54.879 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env debug: trace

2016-04-12 08:45:54.880 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test8024@testing-worker-linux-docker-f366a174-3354-linux-14.2016-04-12_08.45.13/Mnesia2.test8024@testing-worker-linux-docker-f366a174-3354-linux-14"

2016-04-12 08:45:54.880 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_disc_copies_at_startup: true

2016-04-12 08:45:54.880 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_log_load_regulation: false

2016-04-12 08:45:54.880 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_log_time_threshold: 180000

2016-04-12 08:45:54.880 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_log_update_in_place: true

2016-04-12 08:45:54.881 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_log_write_threshold: 1000

2016-04-12 08:45:54.881 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env event_module: mnesia2_event

2016-04-12 08:45:54.881 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env extra_db_nodes: []

2016-04-12 08:45:54.881 [info] <0.3569.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3569.0>
2016-04-12 08:45:54.882 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env ignore_fallback_at_startup: false

2016-04-12 08:45:54.882 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env fallback_error_function: {mnesia2,lkill}

2016-04-12 08:45:54.882 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env max_wait_for_decision: infinity

2016-04-12 08:45:54.882 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env schema_location: opt_disc

2016-04-12 08:45:54.883 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env core_dir: false

2016-04-12 08:45:54.883 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env pid_sort_order: false

2016-04-12 08:45:54.884 [info] <0.3563.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env no_table_loaders: 2

2016-04-12 08:45:56.908 [warning] <0.6.0> lager_error_logger_h dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:56.909 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): mnesia2_monitor starting: <0.3614.0>

2016-04-12 08:45:56.910 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Version: "1.0.0"

2016-04-12 08:45:56.910 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env access_module: mnesia2

2016-04-12 08:45:56.910 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env auto_repair: true

2016-04-12 08:45:56.910 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env backup_module: mnesia2_backup

2016-04-12 08:45:56.910 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env debug: debug

2016-04-12 08:45:56.910 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dir: "/home/travis/build/lrascao/mnesia2/logs/ct_run.test8024@testing-worker-linux-docker-f366a174-3354-linux-14.2016-04-12_08.45.13/Mnesia2.test8024@testing-worker-linux-docker-f366a174-3354-linux-14"

2016-04-12 08:45:56.910 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_disc_copies_at_startup: true

2016-04-12 08:45:56.910 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_log_load_regulation: false

2016-04-12 08:45:56.910 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_log_time_threshold: 180000

2016-04-12 08:45:56.911 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_log_update_in_place: true

2016-04-12 08:45:56.911 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dump_log_write_threshold: 1000

2016-04-12 08:45:56.911 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env event_module: mnesia2_event

2016-04-12 08:45:56.911 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env extra_db_nodes: []

2016-04-12 08:45:56.912 [info] <0.3618.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3618.0>
2016-04-12 08:45:56.912 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env ignore_fallback_at_startup: false

2016-04-12 08:45:56.912 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env fallback_error_function: {mnesia2,lkill}

2016-04-12 08:45:56.912 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env max_wait_for_decision: infinity

2016-04-12 08:45:56.912 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env schema_location: opt_disc

2016-04-12 08:45:56.913 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env core_dir: false

2016-04-12 08:45:56.913 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env pid_sort_order: false

2016-04-12 08:45:56.913 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env no_table_loaders: 2

2016-04-12 08:45:56.913 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env dc_dump_limit: 4

2016-04-12 08:45:56.914 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env send_compressed: 0

2016-04-12 08:45:56.914 [info] <0.3612.0> Mnesia2('test8024@testing-worker-linux-docker-f366a174-3354-linux-14'): Env send_max_packets: 20

2016-04-12 08:45:58.938 [warning] <0.6.0> lager_error_logger_h dropped 36 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:45:58.940 [info] <0.3700.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3700.0>
2016-04-12 08:45:58.942 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:45:58.943 [error] <0.3691.0> CRASH REPORT Process <0.3691.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:45:58.943 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:01.035 [info] <0.3764.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3764.0>
2016-04-12 08:46:01.037 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:01.038 [error] <0.3755.0> CRASH REPORT Process <0.3755.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:01.038 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:02.162 [info] <0.3835.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3835.0>
2016-04-12 08:46:02.163 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:02.186 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:46:02.366 [info] <0.3896.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3896.0>
2016-04-12 08:46:17.642 [error] <0.3887.0> CRASH REPORT Process <0.3887.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:17.642 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:19.757 [info] <0.4452.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.4452.0>
2016-04-12 08:46:19.759 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:25.766 [error] <0.4443.0> CRASH REPORT Process <0.4443.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:25.766 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:27.868 [info] <0.4552.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.4552.0>
2016-04-12 08:46:27.870 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:28.887 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:46:30.994 [info] <0.4668.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.4668.0>
2016-04-12 08:46:30.996 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:31.003 [error] <0.4659.0> CRASH REPORT Process <0.4659.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:31.003 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:33.055 [info] <0.4735.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.4735.0>
2016-04-12 08:46:33.058 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:33.080 [error] <0.4726.0> CRASH REPORT Process <0.4726.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:33.080 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:35.195 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:46:35.218 [info] <0.1791.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1791.0>
2016-04-12 08:46:35.233 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:35.213 [info] <0.4827.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.4827.0>
2016-04-12 08:46:35.215 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:36.233 [error] <0.1843.0> gen_server <0.1843.0> terminated with reason: killed
2016-04-12 08:46:36.233 [error] <0.1843.0> CRASH REPORT Process <0.1843.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:46:36.233 [error] <0.1782.0> CRASH REPORT Process <0.1782.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:36.233 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:38.267 [info] <0.1859.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1859.0>
2016-04-12 08:46:38.271 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:39.275 [error] <0.4890.0> gen_server <0.4890.0> terminated with reason: killed
2016-04-12 08:46:39.275 [error] <0.4890.0> CRASH REPORT Process <0.4890.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:46:39.275 [error] <0.4818.0> CRASH REPORT Process <0.4818.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:39.275 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:40.326 [error] <0.1850.0> CRASH REPORT Process <0.1850.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:40.326 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:41.424 [info] <0.1941.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1941.0>
2016-04-12 08:46:41.428 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:41.429 [error] <0.1931.0> CRASH REPORT Process <0.1931.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:41.403 [info] <0.4933.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.4933.0>
2016-04-12 08:46:41.407 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:41.430 [error] <0.4924.0> CRASH REPORT Process <0.4924.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:41.431 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:41.474 [info] <0.5008.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5008.0>
2016-04-12 08:46:41.429 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:45.390 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:46:45.459 [info] <0.5132.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5132.0>
2016-04-12 08:46:45.463 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:45.448 [info] <0.2010.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2010.0>
2016-04-12 08:46:45.449 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:55.140 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:46:55.144 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:46:56.269 [info] <0.2132.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2132.0>
2016-04-12 08:46:56.273 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:56.306 [error] <0.2184.0> gen_server <0.2184.0> terminated with reason: killed
2016-04-12 08:46:56.306 [error] <0.2184.0> CRASH REPORT Process <0.2184.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:46:56.306 [error] <0.2123.0> CRASH REPORT Process <0.2123.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:56.264 [info] <0.5263.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5263.0>
2016-04-12 08:46:56.266 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:56.329 [error] <0.5254.0> CRASH REPORT Process <0.5254.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:56.330 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:56.361 [info] <0.5351.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5351.0>
2016-04-12 08:46:56.306 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:56.557 [info] <0.2220.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2220.0>
2016-04-12 08:46:58.076 [error] <0.2211.0> CRASH REPORT Process <0.2211.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:58.076 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:59.124 [warning] <0.6.0> lager_error_logger_h dropped 4 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:46:59.129 [info] <0.5474.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5474.0>
2016-04-12 08:46:59.131 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:59.150 [error] <0.5536.0> gen_server <0.5536.0> terminated with reason: killed
2016-04-12 08:46:59.136 [info] <0.2323.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2323.0>
2016-04-12 08:46:59.141 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:46:59.152 [error] <0.2332.0> gen_server <0.2332.0> terminated with reason: killed
2016-04-12 08:46:59.150 [error] <0.5536.0> CRASH REPORT Process <0.5536.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:46:59.152 [error] <0.2332.0> CRASH REPORT Process <0.2332.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:46:59.150 [error] <0.5465.0> CRASH REPORT Process <0.5465.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:59.152 [error] <0.2314.0> CRASH REPORT Process <0.2314.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:46:59.151 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:46:59.152 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:01.262 [info] <0.2398.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2398.0>
2016-04-12 08:47:01.269 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:01.272 [error] <0.2409.0> gen_server <0.2409.0> terminated with reason: killed
2016-04-12 08:47:01.255 [info] <0.5585.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5585.0>
2016-04-12 08:47:01.257 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:01.274 [error] <0.5576.0> CRASH REPORT Process <0.5576.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:01.272 [error] <0.2409.0> CRASH REPORT Process <0.2409.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:01.273 [error] <0.2389.0> CRASH REPORT Process <0.2389.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:01.274 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:01.273 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:03.336 [info] <0.5665.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5665.0>
2016-04-12 08:47:03.354 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:03.377 [error] <0.5656.0> CRASH REPORT Process <0.5656.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:03.300 [info] <0.2457.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2457.0>
2016-04-12 08:47:03.301 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:03.377 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:04.824 [error] <0.2448.0> CRASH REPORT Process <0.2448.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:04.824 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:05.942 [info] <0.5790.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5790.0>
2016-04-12 08:47:05.946 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:06.285 [error] <0.5844.0> gen_server <0.5844.0> terminated with reason: killed
2016-04-12 08:47:05.948 [info] <0.2546.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2546.0>
2016-04-12 08:47:05.953 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:06.287 [error] <0.2558.0> gen_server <0.2558.0> terminated with reason: killed
2016-04-12 08:47:06.287 [error] <0.2558.0> CRASH REPORT Process <0.2558.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:06.285 [error] <0.5844.0> CRASH REPORT Process <0.5844.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:06.287 [error] <0.2537.0> CRASH REPORT Process <0.2537.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:06.288 [error] <0.5835.0> gen_server <0.5835.0> terminated with reason: killed
2016-04-12 08:47:06.288 [error] <0.5835.0> CRASH REPORT Process <0.5835.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:06.290 [error] <0.5781.0> CRASH REPORT Process <0.5781.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:06.290 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:06.287 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:06.191 [info] <0.7.0> Application lager started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:06.191 [info] <0.7.0> Application poolgirl started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:06.232 [info] <0.102.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.102.0>
2016-04-12 08:47:06.249 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:08.393 [info] <0.2628.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2628.0>
2016-04-12 08:47:08.399 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:08.402 [error] <0.2639.0> gen_server <0.2639.0> terminated with reason: killed
2016-04-12 08:47:08.387 [info] <0.5885.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5885.0>
2016-04-12 08:47:08.389 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:08.403 [error] <0.5949.0> gen_server <0.5949.0> terminated with reason: killed
2016-04-12 08:47:08.402 [error] <0.2639.0> CRASH REPORT Process <0.2639.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:08.403 [error] <0.5949.0> CRASH REPORT Process <0.5949.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:08.402 [error] <0.2619.0> CRASH REPORT Process <0.2619.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:08.404 [error] <0.5876.0> CRASH REPORT Process <0.5876.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:08.404 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:08.402 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:10.496 [info] <0.2698.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2698.0>
2016-04-12 08:47:10.516 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:10.521 [error] <0.2711.0> gen_server <0.2711.0> terminated with reason: killed
2016-04-12 08:47:10.492 [info] <0.5979.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5979.0>
2016-04-12 08:47:10.493 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:10.522 [error] <0.6024.0> gen_server <0.6024.0> terminated with reason: killed
2016-04-12 08:47:10.521 [error] <0.2711.0> CRASH REPORT Process <0.2711.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:10.522 [error] <0.6024.0> CRASH REPORT Process <0.6024.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:10.522 [error] <0.2689.0> CRASH REPORT Process <0.2689.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:10.523 [error] <0.5970.0> CRASH REPORT Process <0.5970.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:10.523 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:10.522 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:12.654 [info] <0.2773.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2773.0>
2016-04-12 08:47:12.657 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:12.660 [error] <0.2825.0> gen_server <0.2825.0> terminated with reason: killed
2016-04-12 08:47:12.660 [error] <0.2825.0> CRASH REPORT Process <0.2825.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:12.660 [error] <0.2764.0> CRASH REPORT Process <0.2764.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:12.631 [info] <0.6065.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.6065.0>
2016-04-12 08:47:12.633 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:12.660 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:13.723 [error] <0.6056.0> CRASH REPORT Process <0.6056.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:13.723 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:15.767 [info] <0.2843.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2843.0>
2016-04-12 08:47:15.769 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:20.814 [error] <0.2838.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2856.0> exit with reason killed in context child_terminated
2016-04-12 08:47:20.801 [info] <0.6143.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.6143.0>
2016-04-12 08:47:20.809 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:20.816 [error] <0.6188.0> gen_server <0.6188.0> terminated with reason: killed
2016-04-12 08:47:20.816 [error] <0.6188.0> CRASH REPORT Process <0.6188.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:20.814 [error] <0.2838.0> Supervisor mnesia2_kernel_sup had child undefined started with mnesia2_checkpoint_sup:start() at <0.2856.0> exit with reason reached_max_restart_intensity in context shutdown
2016-04-12 08:47:20.816 [error] <0.6134.0> CRASH REPORT Process <0.6134.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:20.814 [error] <0.2910.0> gen_server <0.2910.0> terminated with reason: killed
2016-04-12 08:47:20.814 [error] <0.2910.0> CRASH REPORT Process <0.2910.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:20.815 [error] <0.2834.0> CRASH REPORT Process <0.2834.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:20.816 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:20.815 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:22.018 [info] <0.2942.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2942.0>
2016-04-12 08:47:22.031 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:22.423 [error] <0.2933.0> CRASH REPORT Process <0.2933.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:21.993 [info] <0.6253.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.6253.0>
2016-04-12 08:47:22.321 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:22.483 [error] <0.6353.0> gen_server <0.6353.0> terminated with reason: killed
2016-04-12 08:47:22.483 [error] <0.6353.0> CRASH REPORT Process <0.6353.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:22.483 [error] <0.6340.0> gen_server <0.6340.0> terminated with reason: killed
2016-04-12 08:47:22.483 [error] <0.6340.0> CRASH REPORT Process <0.6340.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:22.483 [error] <0.6318.0> gen_server <0.6318.0> terminated with reason: killed
2016-04-12 08:47:22.483 [error] <0.6318.0> CRASH REPORT Process <0.6318.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:22.483 [error] <0.6244.0> CRASH REPORT Process <0.6244.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:21.929 [warning] <0.6.0> lager_error_logger_h dropped 8 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:22.025 [info] <0.192.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.192.0>
2016-04-12 08:47:22.039 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:22.504 [error] <0.275.0> gen_server <0.275.0> terminated with reason: killed
2016-04-12 08:47:22.504 [error] <0.275.0> CRASH REPORT Process <0.275.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:22.505 [error] <0.183.0> CRASH REPORT Process <0.183.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:22.505 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:22.606 [info] <0.296.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.296.0>
2016-04-12 08:47:22.614 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:22.483 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:22.586 [info] <0.6372.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.6372.0>
2016-04-12 08:47:22.423 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:22.449 [info] <0.3034.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3034.0>
2016-04-12 08:47:22.552 [info] <0.3129.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3129.0>
2016-04-12 08:47:23.434 [error] <0.367.0> gen_server <0.367.0> terminated with reason: killed
2016-04-12 08:47:23.434 [error] <0.367.0> CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:23.434 [error] <0.357.0> gen_server <0.357.0> terminated with reason: killed
2016-04-12 08:47:23.434 [error] <0.357.0> CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:23.434 [error] <0.287.0> CRASH REPORT Process <0.287.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:23.434 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:23.476 [info] <0.393.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.393.0>
2016-04-12 08:47:23.477 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:25.598 [warning] <0.6.0> lager_error_logger_h dropped 19 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:25.598 [error] <0.6363.0> CRASH REPORT Process <0.6363.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:25.619 [warning] <0.6.0> lager_error_logger_h dropped 9 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:25.619 [error] <0.3222.0> gen_server <0.3222.0> terminated with reason: killed
2016-04-12 08:47:25.619 [error] <0.3222.0> CRASH REPORT Process <0.3222.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:25.619 [error] <0.3120.0> CRASH REPORT Process <0.3120.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:25.643 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:25.671 [info] <0.499.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.499.0>
2016-04-12 08:47:25.673 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:26.520 [error] <0.573.0> gen_server <0.573.0> terminated with reason: killed
2016-04-12 08:47:26.520 [error] <0.573.0> CRASH REPORT Process <0.573.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:26.521 [error] <0.566.0> gen_server <0.566.0> terminated with reason: killed
2016-04-12 08:47:26.522 [error] <0.566.0> CRASH REPORT Process <0.566.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:26.525 [error] <0.490.0> CRASH REPORT Process <0.490.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:25.598 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:25.688 [info] <0.6489.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.6489.0>
2016-04-12 08:47:25.992 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:25.619 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:25.706 [info] <0.3243.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3243.0>
2016-04-12 08:47:25.735 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:26.634 [error] <0.6480.0> CRASH REPORT Process <0.6480.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:26.526 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:26.547 [info] <0.598.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.598.0>
2016-04-12 08:47:26.548 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:26.654 [error] <0.3330.0> gen_server <0.3330.0> terminated with reason: killed
2016-04-12 08:47:26.654 [error] <0.3330.0> CRASH REPORT Process <0.3330.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:26.654 [error] <0.3234.0> CRASH REPORT Process <0.3234.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:26.654 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:26.736 [info] <0.3351.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3351.0>
2016-04-12 08:47:26.750 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:27.564 [error] <0.3412.0> gen_server <0.3412.0> terminated with reason: killed
2016-04-12 08:47:27.564 [error] <0.3412.0> CRASH REPORT Process <0.3412.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:27.564 [error] <0.3421.0> gen_server <0.3421.0> terminated with reason: killed
2016-04-12 08:47:27.564 [error] <0.3421.0> CRASH REPORT Process <0.3421.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:27.565 [error] <0.3342.0> CRASH REPORT Process <0.3342.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:26.634 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:26.732 [info] <0.6602.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.6602.0>
2016-04-12 08:47:27.041 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:27.565 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:27.627 [info] <0.3447.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3447.0>
2016-04-12 08:47:27.645 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:27.653 [error] <0.3505.0> gen_server <0.3505.0> terminated with reason: killed
2016-04-12 08:47:27.653 [error] <0.3505.0> CRASH REPORT Process <0.3505.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:27.653 [error] <0.3495.0> gen_server <0.3495.0> terminated with reason: killed
2016-04-12 08:47:27.653 [error] <0.3495.0> CRASH REPORT Process <0.3495.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:26.680 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:26.705 [info] <0.699.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.699.0>
2016-04-12 08:47:28.679 [warning] <0.6.0> lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:28.690 [info] <0.3525.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3525.0>
2016-04-12 08:47:28.703 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:28.775 [error] <0.3516.0> CRASH REPORT Process <0.3516.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:28.775 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:28.775 [error] <0.824.0> gen_server <0.824.0> terminated with reason: killed
2016-04-12 08:47:28.787 [error] <0.6657.0> gen_server <0.6657.0> terminated with reason: killed
2016-04-12 08:47:28.775 [error] <0.824.0> CRASH REPORT Process <0.824.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:28.787 [error] <0.6657.0> CRASH REPORT Process <0.6657.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:28.775 [error] <0.813.0> gen_server <0.813.0> terminated with reason: killed
2016-04-12 08:47:28.789 [error] <0.6593.0> CRASH REPORT Process <0.6593.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:28.775 [error] <0.813.0> CRASH REPORT Process <0.813.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:28.775 [error] <0.772.0> gen_server <0.772.0> terminated with reason: killed
2016-04-12 08:47:28.775 [error] <0.772.0> CRASH REPORT Process <0.772.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:28.776 [error] <0.690.0> CRASH REPORT Process <0.690.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:28.775 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:28.876 [info] <0.3603.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3603.0>
2016-04-12 08:47:28.941 [info] <0.3698.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3698.0>
2016-04-12 08:47:29.237 [info] <0.3788.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3788.0>
2016-04-12 08:47:29.237 [warning] <0.6.0> lager_error_logger_h dropped 26 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:29.247 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:29.655 [error] <0.3850.0> gen_server <0.3850.0> terminated with reason: killed
2016-04-12 08:47:29.655 [error] <0.3850.0> CRASH REPORT Process <0.3850.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:29.656 [error] <0.3779.0> CRASH REPORT Process <0.3779.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:28.776 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:28.790 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:28.862 [info] <0.6747.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.6747.0>
2016-04-12 08:47:28.865 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:29.683 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:29.656 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:29.685 [info] <0.3888.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3888.0>
2016-04-12 08:47:30.250 [error] <0.3943.0> gen_server <0.3943.0> terminated with reason: killed
2016-04-12 08:47:30.250 [error] <0.3943.0> CRASH REPORT Process <0.3943.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:30.251 [error] <0.3879.0> CRASH REPORT Process <0.3879.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:30.251 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:30.810 [info] <0.3970.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.3970.0>
2016-04-12 08:47:30.824 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:30.885 [error] <0.3961.0> CRASH REPORT Process <0.3961.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:30.202 [info] <0.6860.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.6860.0>
2016-04-12 08:47:30.218 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:30.249 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:30.287 [info] <0.6943.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.6943.0>
2016-04-12 08:47:30.940 [info] <0.7044.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.7044.0>
2016-04-12 08:47:31.246 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:31.370 [error] <0.7109.0> gen_server <0.7109.0> terminated with reason: killed
2016-04-12 08:47:30.950 [info] <0.850.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.850.0>
2016-04-12 08:47:31.281 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:31.372 [error] <0.913.0> gen_server <0.913.0> terminated with reason: killed
2016-04-12 08:47:31.370 [error] <0.7109.0> CRASH REPORT Process <0.7109.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:30.885 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:30.978 [info] <0.4062.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.4062.0>
2016-04-12 08:47:31.374 [error] <0.4123.0> gen_server <0.4123.0> terminated with reason: killed
2016-04-12 08:47:31.371 [error] <0.7035.0> CRASH REPORT Process <0.7035.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:31.372 [error] <0.913.0> CRASH REPORT Process <0.913.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:31.375 [error] <0.4123.0> CRASH REPORT Process <0.4123.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:31.372 [error] <0.908.0> gen_server <0.908.0> terminated with reason: killed
2016-04-12 08:47:31.375 [error] <0.4116.0> gen_server <0.4116.0> terminated with reason: killed
2016-04-12 08:47:31.372 [error] <0.908.0> CRASH REPORT Process <0.908.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:31.376 [error] <0.4116.0> CRASH REPORT Process <0.4116.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:31.372 [error] <0.841.0> CRASH REPORT Process <0.841.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:31.376 [error] <0.4053.0> CRASH REPORT Process <0.4053.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:31.376 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:31.406 [info] <0.4153.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.4153.0>
2016-04-12 08:47:31.408 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:31.493 [info] <0.4230.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.4230.0>
2016-04-12 08:47:31.372 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:31.402 [info] <0.956.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.956.0>
2016-04-12 08:47:31.493 [info] <0.1034.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1034.0>
2016-04-12 08:47:31.371 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:31.428 [info] <0.7157.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.7157.0>
2016-04-12 08:47:31.510 [info] <0.7249.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.7249.0>
2016-04-12 08:47:41.519 [warning] <0.6.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:41.519 [error] <0.7242.0> Supervisor mnesia2_sup had child undefined started with mnesia2_kernel_sup:start() at undefined exit with reason killed in context start_error
2016-04-12 08:47:41.519 [error] <0.7245.0> gen_server mnesia2_monitor terminated with reason: killed
2016-04-12 08:47:41.519 [error] <0.7248.0> gen_server mnesia2_recover terminated with reason: killed
2016-04-12 08:47:41.519 [error] <0.7248.0> CRASH REPORT Process mnesia2_recover with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:41.519 [error] <0.7268.0> gen_server mnesia2_snmp_sup terminated with reason: killed
2016-04-12 08:47:41.519 [error] <0.7268.0> CRASH REPORT Process mnesia2_snmp_sup with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:41.519 [error] <0.7246.0> gen_server mnesia2_subscr terminated with reason: killed
2016-04-12 08:47:41.519 [error] <0.7246.0> CRASH REPORT Process mnesia2_subscr with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:41.519 [error] <0.7240.0> CRASH REPORT Process <0.7240.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}} in application_master:init/4 line 134
2016-04-12 08:47:41.520 [info] <0.7.0> Application mnesia2 exited with reason: {{shutdown,{failed_to_start_child,mnesia2_kernel_sup,killed}},{mnesia2_sup,start,[normal,[]]}}
2016-04-12 08:47:41.520 [error] <0.7245.0> CRASH REPORT Process mnesia2_monitor with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:41.605 [warning] <0.6.0> lager_error_logger_h dropped 5 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:41.605 [error] <0.1083.0> gen_server <0.1083.0> terminated with reason: killed
2016-04-12 08:47:41.604 [warning] <0.6.0> lager_error_logger_h dropped 3 messages in the last second that exceeded the limit of 50 messages/sec
2016-04-12 08:47:41.605 [error] <0.4274.0> gen_server <0.4274.0> terminated with reason: killed
2016-04-12 08:47:41.605 [error] <0.1083.0> CRASH REPORT Process <0.1083.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:41.605 [error] <0.4274.0> CRASH REPORT Process <0.4274.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:41.605 [error] <0.1078.0> gen_server <0.1078.0> terminated with reason: killed
2016-04-12 08:47:41.605 [error] <0.4221.0> CRASH REPORT Process <0.4221.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:41.605 [error] <0.1078.0> CRASH REPORT Process <0.1078.0> with 0 neighbours exited with reason: killed in gen_server:terminate/7 line 826
2016-04-12 08:47:41.605 [error] <0.1025.0> CRASH REPORT Process <0.1025.0> with 0 neighbours exited with reason: killed in application_master:terminate/2 line 228
2016-04-12 08:47:41.605 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:41.605 [info] <0.7.0> Application mnesia2 exited with reason: killed
2016-04-12 08:47:44.007 [info] <0.7358.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.7358.0>
2016-04-12 08:47:44.009 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:47.916 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:48.053 [info] <0.7494.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.7494.0>
2016-04-12 08:47:48.057 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:48.063 [info] <0.1131.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1131.0>
2016-04-12 08:47:48.085 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:48.063 [info] <0.4320.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.4320.0>
2016-04-12 08:47:48.097 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:54.208 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:54.344 [info] <0.4434.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.4434.0>
2016-04-12 08:47:54.362 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:54.214 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:54.332 [info] <0.7623.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.7623.0>
2016-04-12 08:47:54.336 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:47:54.215 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:47:54.341 [info] <0.1246.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1246.0>
2016-04-12 08:47:54.645 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:00.735 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:00.873 [info] <0.7752.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.7752.0>
2016-04-12 08:48:00.875 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:00.736 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:00.884 [info] <0.1363.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.1363.0>
2016-04-12 08:48:00.916 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:00.743 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:00.884 [info] <0.4548.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.4548.0>
2016-04-12 08:48:00.907 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:21.589 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:21.740 [info] <0.5673.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5673.0>
2016-04-12 08:48:21.754 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:21.590 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:21.735 [info] <0.8890.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.8890.0>
2016-04-12 08:48:22.042 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:21.595 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:21.741 [info] <0.2486.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2486.0>
2016-04-12 08:48:21.757 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:28.451 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:28.585 [info] <0.5797.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5797.0>
2016-04-12 08:48:28.891 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:28.452 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:28.587 [info] <0.9029.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.9029.0>
2016-04-12 08:48:29.075 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:28.479 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:28.603 [info] <0.2612.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.2612.0>
2016-04-12 08:48:28.619 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:35.410 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:35.533 [info] <0.10510.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.10510.0>
2016-04-12 08:48:35.536 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:35.411 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:35.541 [info] <0.4082.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.4082.0>
2016-04-12 08:48:35.859 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:35.422 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:35.557 [info] <0.7270.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.7270.0>
2016-04-12 08:48:35.572 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:42.132 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:42.350 [info] <0.7688.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.7688.0>
2016-04-12 08:48:42.366 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:42.134 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:42.322 [info] <0.12219.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.12219.0>
2016-04-12 08:48:42.652 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:42.162 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:42.348 [info] <0.5394.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5394.0>
2016-04-12 08:48:42.656 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:48.807 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:49.074 [info] <0.5512.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14', <0.5512.0>
2016-04-12 08:48:49.079 [info] <0.7.0> Application mnesia2 started on node 'd795486o795394n795394@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:48.812 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:49.051 [info] <0.12349.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14', <0.12349.0>
2016-04-12 08:48:49.055 [info] <0.7.0> Application mnesia2 started on node 'test8024@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:48.818 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:49.074 [info] <0.8481.0>@mnesia2_tm:init:132 starting mnesia2_tm, 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14', <0.8481.0>
2016-04-12 08:48:49.084 [info] <0.7.0> Application mnesia2 started on node 'd795492o795484n795484@testing-worker-linux-docker-f366a174-3354-linux-14'
2016-04-12 08:48:55.338 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:55.372 [info] <0.7.0> Application mnesia2 exited with reason: stopped
2016-04-12 08:48:55.344 [info] <0.7.0> Application mnesia2 exited with reason: stopped
